### ISSUE TITLE
Support for array of composite types

### ISSUE THREAD

**Issue by pascaldanek** [sfackler/rust-postgres#1002]
Composite types are supported by struct. However, when an array of composite type is used, a serialization error occurs saying that an error occured trying io convert between  types using the `_<whatever composite type name>` postgres type. 

When a composite type is created, postgres automatically supports arrays for this type by creating a new type named by prepending an underscore to the original composite type name. 

Is there any simple way to make this work for `Vec<MyType>`?

**Comment by sfackler** [comment]
Arrays of composites seem to work for me - could you provide a self contained example for the issue you're seeing?

**Comment by pascaldanek** [comment]
Sorry for the noise, I am closing this issue.
