### ISSUE TITLE
prepare statements overload the postgres server causing oom

### ISSUE THREAD

**Issue by lyang24** [sfackler/rust-postgres#1004]
We ran connection pooling with tokio postgres connections to talk to our database (cockroach db). We have experienced some sql performance impact due to cockroach db server side oom cause by too much prepared statements. 

I believe postgres/ cockroachdb (implement postgres syntax) do not clear prepared statements unless we specifically ran Deallocate sql or when our connection is closed.

all of our statements are two round trips to the backend:
1. [prepare ](https://github.com/sfackler/rust-postgres/blob/7cd7b187a5cb990ceb0ea9531cd3345b1e2799c3/tokio-postgres/src/to_statement.rs#L18)- it will generate a unique Integer for each prepare statement ([ref](https://github.com/sfackler/rust-postgres/blob/7cd7b187a5cb990ceb0ea9531cd3345b1e2799c3/tokio-postgres/src/prepare.rs#L66))
2. execute

there are two ways to prevent this problem in tokio postgres
1. cache prepared statement result from db if cache hit use the result do not send another prepare to the backend db.
3. make the process 3 round trip - remember the id generated as the name of prepare statement after query is finished send a [deallocate ](https://www.postgresql.org/docs/current/sql-deallocate.html) query.

**Comment by sfackler** [comment]
Prepared statements are deallocated by this library when they are dropped, but via the Close backend protocol message: https://www.postgresql.org/docs/current/protocol-flow.html#PROTOCOL-FLOW-EXT-QUERY

**Comment by lyang24** [comment]
> Prepared statements are deallocated by this library when they are dropped, but via the Close backend protocol message: https://www.postgresql.org/docs/current/protocol-flow.html#PROTOCOL-FLOW-EXT-QUERY

thanks that makes sense I need to digger deeper on our side will close this issue for now
