### ISSUE TITLE
Could you expose  enum `Inner` in prostgres_types?

### ISSUE THREAD

**Issue by mokeyish** [sfackler/rust-postgres#1009]
Thanks for this nice crate. 

Could you expose enum `Inner` in the prostgres_types?

Currently I can only use string type and kind.

**Comment by sfackler** [comment]
What problem are you trying to solve?

**Comment by mokeyish** [comment]
I want to convert pg data to `BlockEntry`(data structure of [databend](https://github.com/datafuselabs/databend)) for memory calculating.

![image](https://user-images.githubusercontent.com/16131917/228103838-e221a91a-711d-4228-ab86-eca605c5629a.png)

**Comment by sfackler** [comment]
```rust
match ty {
    Type::TEXT => ...,
    Type::TIMESTAMP => ...,
    ...
```

**Comment by mokeyish** [comment]
Although this also work, it is not like an Enum that VsCode will prompt to match all.
