### ISSUE TITLE
#[derive(Debug)] On DataRowBody Not Present On Version 0.7.8 Downloaded by Cargo

### ISSUE THREAD

**Issue by Daniel-A-Gutierrez** [sfackler/rust-postgres#1015]
I've gotten a compilation error and done the following to fix it now twice now on two different machines. 

This is the line importing tokio postgres in my cargo.toml
tokio-postgres = {version = "0.7.8" , features = ["with-bit-vec-0_6"]}

As far as I can tell this is the most up to date version. 
I get an error that data row body doesn't implement debug, linking me to "Row" in tokio-postgres. 
The struct in question is defined [here](https://github.com/sfackler/rust-postgres/blob/master/postgres-protocol/src/message/backend.rs) , at line 527. In my local package registry , the #[derive(Debug)] is not present, so I add it manually, and that fixes the error. After cleaning and rebuilding, I can use the library without issue. 

I'm using the most up to date version, and the fix is already present here in the github as of 4 months ago, but it isn't present in the version cargo downloads when using this crate.

**Comment by sfackler** [comment]
#1013
