### ISSUE TITLE
Allow passing `search_path` as client-side params

### ISSUE THREAD

**Issue by Weakky** [sfackler/rust-postgres#1016]
## Overview

It's currently impossible to define the `search_path` without issuing a query to the database, although it is possible to set it up as client options when connecting to PG. See https://www.postgresql.org/docs/current/runtime-config-client.html#GUC-SEARCH-PATH

Are you open to allowing this additional config?

I have a PR opened on our fork https://github.com/prisma/rust-postgres/pull/1. Let me know if you'd be ok with roughly having the content of that PR merged in your repo.

Thanks 🙏

**Comment by sfackler** [comment]
Like with libpq, you'd pass that in the `options` field: https://stackoverflow.com/a/66287119
