### ISSUE TITLE
Question: LoadBalancing

### ISSUE THREAD

**Issue by cemremengu** [sfackler/rust-postgres#1019]
Does this driver support specifying `LoadBalance` option like the JDBC driver?

```
loadBalanceHosts = boolean

In default mode (disabled) hosts are connected in the given order. If enabled hosts are chosen randomly from the set of suitable candidates.
```

**Comment by sfackler** [comment]
I don't believe something like that is currently exposed. If libpq offers similar functionality we could mirror that here.

**Comment by sfackler** [comment]
You can also shuffle the hosts list yourself depending on how your code is set up.

**Comment by cemremengu** [comment]
I think libpq does not support it yet but as far as I understand its around the corner (or already released)

https://commitfest.postgresql.org/38/3679/

**Comment by sfackler** [comment]
Ah cool. Once that API is stabilized we can reflect it here.

**Comment by fritshoogland-yugabyte** [comment]
This would be an awesome feature that can save a lot of people from having to use haproxy or pgcat just for this functionality!

**Comment by fritshoogland-yugabyte** [comment]
Load balancing is added to postgresql version 16: https://www.postgresql.org/docs/16/libpq-connect.html
