### ISSUE TITLE
the trait `postgres::types::ToSql` is not implemented for the type `rustc-serialize::json::Json`

### ISSUE THREAD

**Issue by s-panferov** [sfackler/rust-postgres#102]
Hello @sfackler. I noticed that support of `Json` suddenly stopped working. The small example to reproduce https://github.com/s-panferov/postgres-test.

```
➜  postgres-test git:(master) ✗ cargo test
   Compiling postgres-test v0.0.1 (file:///Users/panferov/Workspace/my/postgres-test)
src/main.rs:17:18: 17:23 error: the trait `postgres::types::ToSql` is not implemented for the type `rustc-serialize::json::Json` [E0277]
src/main.rs:17     stmt.query(&[&json]).unwrap()
                                ^~~~~
```

What can be wrong?

**Comment by sfackler** [comment]
The cargo.toml has a * dependency on rustc-serialize, while rust-postgres has a dependency on 0.2. It looks like cargo is pulling in both an 0.2 version and an 0.3 version at the same time. If you change the dependency from * to 0.2 it works. Seems like a bug to file on Cargo.
