### ISSUE TITLE
`postgres-types`: Can't insert oidvector

### ISSUE THREAD

**Issue by mstrydom** [sfackler/rust-postgres#1025]
`postgres-types` does not seem to have built in support for `oidvector`. I tried to do this by inserting `vec![1_u32, 2_u32]` as a `Vec<Oid>`, but doing so results in:

```
invalid oidvector data
```

Which seems to come from [this line in the Postgres codebase](https://github.com/postgres/postgres/blob/647fa500547fdf2a967412633a9f6f21ba69e144/src/backend/utils/adt/oid.c#L216). It looks to me like Postgres assumes a [lower_bound of 0](https://github.com/postgres/postgres/blob/647fa500547fdf2a967412633a9f6f21ba69e144/src/backend/utils/adt/oid.c#L213), but `ToSql` of `Vec` is always [setting it as 1](https://github.com/sfackler/rust-postgres/blob/8b9b5d0388c8961c44b7c107eaa626c24a0b3051/postgres-types/src/lib.rs#L915).

Is there another way to send in `oidvector` as a bound parameter?

**Comment by sfackler** [comment]
https://docs.rs/postgres_array/latest/postgres_array/ Provides more control over array types.

**Comment by sfackler** [comment]
Though we could (and probably should) update that ToSql impl to use a lower_bound of 0 when the target type is oidvector.

**Comment by mstrydom** [comment]
> https://docs.rs/postgres_array/latest/postgres_array/ provides more control over array types.

I will take a look at that and see if it solves the problem. Thanks!

**Comment by mstrydom** [comment]
I can confirm that `postgres_array` does solve my problem, thanks! I did have to muck around with some extra formatting/to_string conversions to get it to format the same in Rust as in Postgres, so I still think having an explicit `oidvector` type might be nice. But feel free to resolve this issue if you do not agree that more work is warranted here.
