### ISSUE TITLE
Trait FromSql not implemented for time::Timespec

### ISSUE THREAD

**Issue by debuuu** [sfackler/rust-postgres#103]
I've run into this compile error a few times whilst I've been using rust-postgres, but having updated to the latest Rust compiler (1.0.0-nightly 2015-03-22) yesterday night, which brought the problem back out, I've been unable to solve it.

Basically I'm just trying to use time::Timespec with rust-postgres, and I get a compile error whenever I try to do something that would require ToSql or FromSql to be implemented for it. I see that both do have implementations in source, and have tried including postgres::types::*, but nothing seems to work.

I also tried setting my dependencies to time 0.1.14; postgres 0.7, but on-compile it still always downloads the latest versions. 

Any idea what I might be doing wrong?

**Comment by sfackler** [comment]
`Timespec` support is optional, and can be enabled by turning on the `time` feature: https://github.com/sfackler/rust-postgres#timestamptimestamptz-types

```toml
[dependencies.postgres]
version = "0.7"
features = ["time"]
```

**Comment by debuuu** [comment]
Ah..! I was wondering on the front page when it mentions the time support being "optionally provided", if that meant there was some special Cargo flag. Thanks a lot, compiles again!
