### ISSUE TITLE
Declaring types belonging to a different schema

### ISSUE THREAD

**Issue by deven96** [sfackler/rust-postgres#1038]
Given the following mood enum 

```sql
CREATE TYPE "mood" AS ENUM (
 'sad',
 'ok',
 'happy'
);
```

```rust
use postgres_types::{ToSql, FromSql};

#[derive(Debug, ToSql, FromSql)]
 #[postgres(name = "mood")]
enum Mood {
     #[postgres(name = "sad")]
     Sad,
     #[postgres(name = "ok")]
     Ok,
     #[postgres(name = "happy")]
     Happy,
 }
```

But I wanted to declare an enum in a different schema e.g a

```sql
CREATE TYPE types.mood AS ENUM (
 'sad',
 'ok',
 'happy'
)
```
How would this be represented using the #[postgres(...)] enum, as I see the Overrides struct only allows `name` and `transparent` being set?

**Comment by sfackler** [comment]
IIRC the implementation doesn't currently check the schema name. You shouldn't need to do anything special.

**Comment by danielnehrig** [comment]
> IIRC the implementation doesn't currently check the schema name. You shouldn't need to do anything special.

i have a similar case with https://github.com/sfackler/rust-postgres/issues/1083
does that mean that it will check any schema with that type ?
