### ISSUE TITLE
`notice_callback` not available in tokio-postgres

### ISSUE THREAD

**Issue by to266** [sfackler/rust-postgres#1045]
https://github.com/sfackler/rust-postgres/pull/655 does not seem to be exposed as part of the `tokio_postgres::Config`, so it's not really configurable.

Would be nice to support that too :)

**Comment by sfackler** [comment]
In tokio-postgres you can poll the connection directly: https://docs.rs/tokio-postgres/latest/tokio_postgres/struct.Connection.html#method.poll_message

**Comment by to266** [comment]
Ah, nice! 

I see it's a bit more elaborate to use, but I have no issue with that.
For others, here's a [link to tests](https://github.com/sfackler/rust-postgres/blob/790af54a0fdd5c487e77dc9a25d82921ee31ffe6/tokio-postgres/tests/test/main.rs#L696) that do exactly this
