### ISSUE TITLE
Question: readonly connection

### ISSUE THREAD

**Issue by stevenliebregt** [sfackler/rust-postgres#1046]
Hi, is it possible to have a client connect as `read-only`? I see that there is such a functionality on `transaction` but could not find anything for the main `client`.

**Comment by sfackler** [comment]
If you want to enforce that a connection can never make any modifications you'd want to create a read-only user.

You may be able to do it for an individual connection by setting `options` to `-c default_transaction_read_only=true` in the connection configuration but I haven't personally tried that.
