### ISSUE TITLE
copy x FROM STDIN format( CSV)

### ISSUE THREAD

**Issue by jamessewell** [sfackler/rust-postgres#1050]
Is there still a way of doing the above from async code? 

I can only seem to find working examples for the binary protocol (I don't know the column defs so I can't use this).

**Comment by sfackler** [comment]
copy_in just returns a Sink of bytes - you can write a CSV into that.

**Comment by stevenliebregt** [comment]
I'm also looking to do this, I have a `Vec<u8>` that I want to send to that sink but can't find a method that accepts that, which one could I use?

**Comment by sfackler** [comment]
The sink consumes types implementing the `Buf` trait. The simplest thing to do would be to convert your Vec into Bytes: `Bytes::from(my_vec)`.

**Comment by stevenliebregt** [comment]
Through which method should I do that?

**Comment by sfackler** [comment]
https://docs.rs/futures/latest/futures/sink/trait.SinkExt.html#method.send
