### ISSUE TITLE
Breaking change in `tokio-postgres` 0.7.9.

### ISSUE THREAD

**Issue by ryzhyk** [sfackler/rust-postgres#1062]
Thanks for these great crates!

It is probably too late to do anything about this, but just want to point out that `tokio-postgres 0.7.9` introduced a breaking change, which I believe violates semantic versioning. Specifically, the `Config::user` field now defaults to the current user, which breaks any code that relies on `Config::new()` to create an empty config. For example I ran into this with the `pg-client-config` crate, namely, [this function](https://docs.rs/pg-client-config/0.1.1/pg_client_config/fn.load_config.html), which no longer initializes `Config::user` from the `PGUSER` environment variable.

**Comment by sfackler** [comment]
Hmm, we could defer the default to when the config is finalized I suppose.

**Comment by dmarteau** [comment]
Note that breaks also the database name wich is also configured by default to user name.

**Comment by sfackler** [comment]
How does this break dbname?

**Comment by dmarteau** [comment]
Never mind, documentation was misleading me: `The name of the database to connect to. Defaults to the username.`

**Comment by sfackler** [comment]
Fixed in tokio-postgres v0.7.10/postgres v0.19.7.
