### ISSUE TITLE
query logging

### ISSUE THREAD

**Issue by mikedilger** [sfackler/rust-postgres#107]
If you wanted to log all queries while in (for example) debug mode, how would you go about it?

Idea 1: I could log every time my code used `Connection`, `Transaction`, or `Statement`.  However, I could easily forget in some places, so I don't like this.

Idea 2: I could wrap `Connection`, `Transacation`, and `Statement` and have them log.  The wrapper structs would keep the real structures private, and provide wrapper functions for `prepare()`, `transaction()`, `execute()`, `query()`, and maybe a few others.   This avoids any changes in rust-postgres.  Logging parameters is difficult (`Debug`/`Display` are not required to be a `ToSql` type, nor should they be), but maybe so in any case.

Idea 3: Perhaps a couple `debug!()` statements in `raw_prepare()` and `inner_execute()` would work, and would be much less code?

**Comment by zr40** [comment]
Alternatively, you could enable server-side logging on your development database with `log_min_duration_statement = 0` in postgresql.conf.

**Comment by sfackler** [comment]
Adding `debug!` calls in the right places in rust-postgres seems reasonable, I'll do that tonight.

**Comment by sfackler** [comment]
https://github.com/sfackler/rust-postgres/commit/97ed6f02b6e77101a8de3b4011e48ed50fc4474b

It might be worth having `ToSql` extend `Debug` and logging parameters when executing queries as well.

**Comment by mikedilger** [comment]
I concur, a small price to pay for parameter logging.

**Comment by sfackler** [comment]
Done: https://github.com/sfackler/rust-postgres/commit/01862817c96a66128750e5cfa30a2a5d9e57e623

**Comment by sfackler** [comment]
I think this is resolved now? If not, feel free to reopen!
