### ISSUE TITLE
Struct/Composite Type with Schema Name Question (postgres-types)

### ISSUE THREAD

**Issue by danielnehrig** [sfackler/rust-postgres#1083]
This is a Question on how to add information to a struct (which implements ToSql) which is a composite type and exists in a schema different than public
given I have added a composite type to my database with a schema name different than public like `"myschema"."SomeCompositeType"`

```rust
#[derive(ToSql)]
struct SomCompositeType {
  value: i32,
}
```

now I wanna do a DB function call and pass the parameters to this DB function call

```rust
...
let data = SomeCompositeType::default();
client.execute("SELECT insert_some_composite_type($1);". &[&data]);
...
```

but nowhere I have given information that this struct/composite type only exists in one schema

how can I accomplish that?

maybe I've missed a section in the docs.rs but I couldn't find any information about it
if there is information about it a pointer would be appreciated and a sorry in advance is given

**Comment by sfackler** [comment]
The generated code doesn't check the schema. You shouldn't need to do anything.
