### ISSUE TITLE
error[E0277]: the trait bound `Uuid: ToSql` is not satisfied - Rust dependency issue

### ISSUE THREAD

**Issue by Chanchal1233** [sfackler/rust-postgres#1089]
getting these two errors when compiling:

error[E0277]: the trait bound `Uuid: ToSql` is not satisfied

error[E0277]: the trait bound `NaiveDateTime: ToSql` is not satisfied

my dependency setup:

[package]
name = "warehousrManagementService"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4"
tokio = { version = "1", features = ["full"] }
tokio-postgres = "0.7.2"
chrono = { version = "0.4.19", features = ["serde"] }
serde = "1.0"
serde_derive = "1.0"
uuid = { version = "0.8.2", features = ["v4", "serde"] }
serde_json = "1.0.64"

New to rust would really appreciate the help. Thanks.

**Comment by sfackler** [comment]
```toml
tokio-postgres = { version = "0.7.2", features = ["with-uuid-0_8"] }
```

**Comment by cuyler** [comment]
Just in case someone runs across this in 2024:

`tokio-postgres = { version = "0.7.2", features = ["with-uuid-1] }`
