### ISSUE TITLE
Strict openssl dependency causes version conflict

### ISSUE THREAD

**Issue by zr40** [sfackler/rust-postgres#109]
Now that version 0.6.0 of the `openssl` package has been released, and other packages now depend on this newer version, I've found that `postgres` causes a version conflict, since it requires 0.5.x. (cc #108)

`openssl` requires a matching `openssl-sys` version, but because this involves a native library (see also rust-lang/cargo#1006), cargo refuses to build both versions, resulting in the following output:

```
native library `openssl` is being linked to by more than one package, and can only be linked to by one package

  openssl-sys v0.5.5
  openssl-sys v0.6.0
```

In my project, I don't need to use SSL to connect, since I'm connecting through a unix socket. But even though I don't use SSL to connect to PostgreSQL, I do perform HTTPS requests. This combination makes me unable to update my dependencies until every dependency with an explicit version constraint for `openssl` has updated their manifest.

I see two approaches to solving this.

1. Loosen the version constraint of `openssl`. Currently, `postgres` requires 0.5.x, and with #108 this would be bumped to 0.6.x. But this will resurface again as soon as 0.7 is released. Perhaps this version constraint could be loosened to any 0.x version? After all, semver doesn't require stability while the major version is 0.

2. Make the `openssl` dependency an optional one, just like unix socket support is. Then only code that actually connects to PostgreSQL through SSL will hit this issue.

**Comment by sfackler** [comment]
I have a PR open on the semver repo to allow range dependencies that should help with this since we can say `openssl = ">= 0.5.0, < 0.7.0"` and update that as needed: https://github.com/rust-lang/semver/pull/43

**Comment by sfackler** [comment]
Cargo now supports range dependencies so we'll be able to support larger spreads of OpenSSL versions in the future.
