### ISSUE TITLE
Optional Serde support

### ISSUE THREAD

**Issue by ArtemGr** [sfackler/rust-postgres#110]
Hey!
Please consider adding Serde support.

Here's a little something I'm using, it can channel anything Serialize+Deserialize, not just the Value:

    use serde::json;
    use serde::de::Deserialize;
    use serde::ser::Serialize;
    use std;
    use std::fmt::Debug;
    use std::io::{Read, Write};

    #[derive(Debug)]
    struct PgJson<T> (T);  // Implement FromSql for any type that Serde can decode from JSON.
    impl<T: Deserialize> postgres::FromSql for PgJson<T> {
      fn from_sql<R: Read> (ty: &postgres::Type, raw: &mut R) -> postgres::Result<PgJson<T>> {
        if *ty == postgres::Type::Jsonb {
          let mut jsonb_version: [u8; 1] = [0];
          if let Err (err) = raw.read (&mut jsonb_version) {return Err (postgres::Error::IoError (err))}
          if jsonb_version[0] != 1 {return Err (postgres::Error::IoError (std::io::Error::new (std::io::ErrorKind::Other, "!jsonb v1")))}}
        let v: T = match json::de::from_reader (raw) {Ok (sj) => sj,
          Err (err) => return Err (postgres::Error::IoError (std::io::Error::new (std::io::ErrorKind::Other, &format! ("{}", err) [..])))};
        Ok (PgJson (v))}
      fn accepts (ty: &postgres::Type) -> bool {*ty == postgres::Type::Json || *ty == postgres::Type::Jsonb}}
    impl <T: Serialize + Debug> postgres::ToSql for PgJson<T> {
      fn to_sql<W: ?Sized> (&self, ty: &postgres::Type, out: &mut W) -> postgres::Result<postgres::types::IsNull> where Self: Sized, W: Write {
        // Can't use `json::ser::to_writer` because of ?Sized incompatibility.
        match json::ser::to_string (&self.0) {
          Ok (js) => {
            match write! (out, "{jsonb_version}{json}", jsonb_version = if *ty == postgres::Type::Jsonb {"\x01"} else {""}, json = js) {
              Ok(()) => Ok (postgres::types::IsNull::No),
              Err (err) => Err (postgres::Error::IoError (err))}},
          Err (err) => Err (postgres::Error::IoError (std::io::Error::new (std::io::ErrorKind::Other, &format! ("{}", err) [..])))}}
      fn accepts (ty: &postgres::Type) -> bool {*ty == postgres::Type::Json || *ty == postgres::Type::Jsonb}
      to_sql_checked!();
    }
    impl<T> std::ops::Deref for PgJson<T> {
      type Target = T;
      fn deref<'a> (&'a self) -> &'a T {&self.0}}

**Comment by sfackler** [comment]
You can now opt into `ToSql` and `FromSql` implementations for `serde::json::Value` with the `serde` feature. I'm trying to restrict the opt in implementations in rust-postgres to ones that can't be defined elsewhere (the `Value` implementation would have to live in either `serde` or `rust-postgres` for example), so I don't think a thing like `PgJson` makes sense to add here. It seems like a cool thing to put into a separate crate though!

**Comment by ArtemGr** [comment]
>  I'm trying to restrict the opt in implementations in rust-postgres to ones that can't be defined elsewhere (the Value implementation would have to live in either serde or rust-postgres for example), so I don't think a thing like PgJson makes sense to add here

`PgJson` is here exactly to overcome this limitation, I would've implemented `FromSql` for `serde::de::Deserialize` directly if I could.

Good to know Sede's supported now!

Working directly with `serde::de::Deserialize` and `serde::ser::Serialize` would have been faster though as it avoids the overhead of `Value` (and works with `Value` just fine).
