### ISSUE TITLE
Get primary key when inserting

### ISSUE THREAD

**Issue by JJaviMS** [sfackler/rust-postgres#1100]
Hi, I am trying to perform an insertion in a transaction where an insertion depends on a previously inserted primary key (with a FK constraint). As far as I can see, the execute method only returns the number of updates columns. Is there a way to get the inserted primary key?

For [example in Java](https://stackoverflow.com/questions/201887/primary-key-from-inserted-row-jdbc) this is possible by using JDBC.

**Comment by sfackler** [comment]
Use `client.query_one("INSERT INTO ... VALUES (...) RETURNING id")`

**Comment by JJaviMS** [comment]
It worked perfectly. Thank you!
