### ISSUE TITLE
`TransactionBuilder::start` Future dropped before completion

### ISSUE THREAD

**Issue by wquark** [sfackler/rust-postgres#1120]
`batch_execute` submits the creation of the transaction (https://github.com/sfackler/rust-postgres/blob/master/tokio-postgres/src/transaction_builder.rs#L109), but the `Transaction` object itself may never be constructed in case the future is dropped.

https://github.com/sfackler/rust-postgres/commit/f6189a95f24af45068ecfd6e3c4e6b71ac8e43fe fixed it for `Client::transaction`.

**Comment by sfackler** [comment]
Good find. We should probably implement `transaction` with `TransactionBuilder` to avoid having two places that need to deal with this.

**Comment by wquark** [comment]
Makes sense. Anything else you need from my end? Is this something you'd knock out quickly or would you rather have a PR?

**Comment by sfackler** [comment]
Either way!
