### ISSUE TITLE
Helper for switching on sslmode and MakeTlsConnect<Socket>

### ISSUE THREAD

**Issue by ryandotsmith** [sfackler/rust-postgres#1139]
Hello. I would like to make a function that uses the config to determine if we should build a connection using NoTls or an SslConnector but I'm having a difficult time lining up the types. Any suggestions?

```rust
fn get_tls_connector(cfg: &Config) -> postgres_openssl::MakeTlsConnector {
    match cfg.get_ssl_mode() {
        tokio_postgres::config::SslMode::Prefer | tokio_postgres::config::SslMode::Require => {
            let mut builder = SslConnector::builder(SslMethod::tls()).unwrap();
            builder.set_verify(SslVerifyMode::NONE);
            MakeTlsConnector::new(builder.build())
        }
        _ => NoTls,
    }
}
```

**Comment by sfackler** [comment]
Why do you need to do that instead of just always using the real connector?

**Comment by ryandotsmith** [comment]
I would need to do that if I was unaware that connecting to a locally running postgres over tls is a perfectly fine thing to do ;)

thank you

**Comment by sfackler** [comment]
You don't even need to connect over TLS - a connector like postgres_openssl *allows* you to connect with TLS, it doesn't *require* it.

**Comment by ryandotsmith** [comment]
I was wondering about that. Good to know. Is there ever a reason to use NoTls?

**Comment by sfackler** [comment]
If you know you're not going to use TLS it avoids some extra dependencies.
