### ISSUE TITLE
Iterating over the rows with mapping example

### ISSUE THREAD

**Issue by waynenilsen** [sfackler/rust-postgres#114]
Would it be possible to add an example to the readme? I have a similar example to the one from the readme but cannot seem to figure out how to do the same thing but get the results into a vector using iterator mapping.

So, this works 
```rust
        let conn = get_connection();
        let stmt = conn.prepare("SELECT id, firstname, lastname FROM person").unwrap();
        for row in stmt.query(&[]).unwrap() {
            let person = Person {
                firstname: row.get(1),
                lastname: row.get(2),
            };
            println!("Found person {}", person.firstname);
        }
```

But I have to specify the type of `row` during the mapping which seems like it should be [`Option<Row<'a>`](http://sfackler.github.io/rust-postgres/doc/src/postgres/lib.rs.html#1684) it seems. 

```rust
        get_connection()
            .prepare("SELECT id, firstname, lastname FROM person").unwrap()
            .query(&[]).unwrap()
            .iter().map( | row | {
                Person {
                    firstname: row.get(1),
                    lastname: row.get(2),
                }
        }).collect().to_json()
```

I feel like I'm close, any suggestions? The code above does not work but it "feels" pretty close.

**Comment by sfackler** [comment]
What specific error are you seeing? It looks like the compiler would be complaining about not knowing what the return type of `collect` is there. All it knows there is that it's something that has a `to_json` method, but that could include all kinds of things. Changing `collect()` to `collect::<Vec<_>>()` might help.

**Comment by waynenilsen** [comment]
This worked, thank you for your tip regarding the collect type hint, it turns out that is what the compiler was complaining about (at first).

```rust
        let conn = get_connection();
        let stmt = conn.prepare("SELECT id, firstname, lastname FROM person").unwrap();
        stmt
            .query(&[]).unwrap()
            .iter().map( | row | {
                Person {
                    firstname: row.get(1),
                    lastname: row.get(2),
                }
        }).collect::<Vec<_>>().to_json()
```

I wish I could have done

```rust
        get_connection()
            .prepare("SELECT id, firstname, lastname FROM person").unwrap()
            .query(&[]).unwrap()
            .iter().map( | row | {
                Person {
                    firstname: row.get(1),
                    lastname: row.get(2),
                }
        }).collect::<Vec<_>>().to_json()
```

but I get  `error: borrowed value does not live long enough`. I guess that is just the borrow checker doing what it has to do to keep everyone safe.

**Comment by sfackler** [comment]
Yeah, there's a bit of a balancing act for cases like that to both make rules in the compiler covering how long the value lasts that are both comprehensible and work in as many cases as possible.
