### ISSUE TITLE
Idea: Add RowDescription to SimpleQueryMessage

### ISSUE THREAD

**Issue by rigby-dane** [sfackler/rust-postgres#1143]
Currently when processing the `SimpleQueryMessage`, if there are no `DataRows` coming from postgres the column data is inaccessible since the data is embedded in the `SimpleQueryRow`. In particular, this makes it difficult if you're displaying user submitted or dynamic query results where being able to determine the columns from the query after it's been sent to the server would be useful. Adding an enum value of `RowDescription(Arc<[SimpleColumn]>)` would alleviate this since you could separately process the columns even without a `DataRow` being returned.

**Comment by sfackler** [comment]
Seems reasonable to me. SimpleQueryMessage is already marked non_exhaustive so this should be a backwards compatible change.
