### ISSUE TITLE
turmoil support

### ISSUE THREAD

**Issue by mcches** [sfackler/rust-postgres#1149]
I'm one of the author's from [turmoil](https://github.com/tokio-rs/turmoil) and I was wondering how you'd feel about supporting a `turmoil::net::TcpStream` socket variant (under a feature flag of course). I was able to get this working with minimal changes to `tokio-postgres` thanks to how the [`Socket`](https://github.com/sfackler/rust-postgres/blob/98f5a11bc0a8e451552d8941ffa078c7eb6cd60c/tokio-postgres/src/socket.rs#L4) type is structured.

**Comment by sfackler** [comment]
I think things should work out of the box with connect_raw: https://docs.rs/tokio-postgres/latest/tokio_postgres/config/struct.Config.html#method.connect_raw

**Comment by mcches** [comment]
Ah, I missed that option. Looks like exactly what I need. Thanks!
