### ISSUE TITLE
supplying &[f32] as params

### ISSUE THREAD

**Issue by guspower** [sfackler/rust-postgres#1167]
I am trying to provide a `&[f32]` as params to `execute` (an output from a Pearson correlation in `ndarray-stats`). 
I get the following build error:
```
expected `&[&dyn ToSql + Sync]`, found `&[f32]`
```

I considered wrapping `f32` in a custom type that implements `ToSql` but that seems like overkill.
After re-reading the docs I enabled the `array-impls` feature to see if that would get me any further.
I can see that there is a `ToSql` impl for `f32`, but I could do with some pointers about the most sensible way forward!

Thanks for your help + super useful library.

**Comment by sfackler** [comment]
What are those f32's supposed to correspond to? Are they individual parameters to the query? A single array parameter?

**Comment by guspower** [comment]
They are individual parameters to the query (not an array parameter).

**Comment by guspower** [comment]
TIL: `query_raw`

works perfectly, thank you +!
