### ISSUE TITLE
Allow sending multiple requests before response

### ISSUE THREAD

**Issue by jeff-davis** [sfackler/rust-postgres#117]
I mentioned this at the last rust meetup: I think you can send multiple requests before the response to the first one arrives, i.e. pipelined requests. This can hide network latency when sending many requests when the application doesn't immediately need the response (e.g. INSERT/UPDATE/DELETE without RETURNING).

Again, this is not a fully-formed idea, but I wanted to record it now so it's not forgotten.

**Comment by sfackler** [comment]
This seems like a neat idea. One possible API:
```rust
pub enum BatchRequest<'a> {
    Prepare(&'a str),
    Query(&'a Statement<'a>, &'a [&'a ToSql]),
    Execute(&'a Statement<'a>, &'a [&'a ToSql]),
}

pub enum BatchResponse<'a> {
    Prepare(Statement<'a>),
    Query(Rows<'a>),
    Execute(u32),
    Error(Error),
}

impl Connection {
    pub fn batch_request<'a>(&self, requests: &[BatchRequest<'a>]) -> Vec<BatchResponse<'a>> { ... }
}
```

Everything within a single batch would execute within one transaction, which does mean that if Postgres runs into an error at request *n* statements *n+1* etc won't be processed. So, the result `Vec` would either be the same length as the requests or it would terminate early and the last entry would be a `BatchResponse::Error`.

**Comment by jeff-davis** [comment]
Is there a reason they need to be done as a batch? Why not just single statements, but without waiting for a response?

**Comment by sfackler** [comment]
I was working on an implementation of this but realized that there are some issues that I think will keep it from working for now, unfortunately. Specifically, I'm worried about TCP deadlocks.

Imagine we're making a batched request consisting of a query that will return many rows followed by something else, say some other query. The client sends off the request to execute the first query, and then tries to send the second query immediately afterwards. Let's say that there are some enough parameters in the second query that the whole thing is larger than the sum of the client's outbound TCP buffer and the server's inbound buffer combined. So, it's going to block on write until the server starts reading again. But, the server's going to handle the first query and start returning the rows to the client. If there's enough data to fill the client's inbound TCP buffer and the server's outbound buffer, the server's going to block waiting for the client to read, so we deadlock.

I think it can be worked around by the client running the batch with nonblocking IO so it can handle the case where the socket's not ready for writes but is ready for reads. I'm not totally sure of the state of cross-platform wrappers around `select`/IOCP right now, but something may exit. The messaging logic will have to be pretty significantly rewritten to handle this case, though.

**Comment by jeff-davis** [comment]
Good point. I think it can be done, but it requires more thought.

**Comment by ArtemGr** [comment]
For the record: http://blog.2ndquadrant.com/postgresql-latency-pipelining-batching/

**Comment by bfrog** [comment]
I for one like the batch_query api idea and think it would work pretty well

**Comment by malthe** [comment]
I implemented an asynchronous PostgreSQL driver in TypeScript that supports pipelining:

https://www.npmjs.com/package/ts-postgres

Handling errors is the difficult part, allowing already sent queries to (attempt to) succeed despite an earlier error. I added a fuzzing test to weed out the various failure modes.

**Comment by kosta** [comment]
What is the state of this issue? I'm not 100% sure, but from reading the code in master branch, it seems that in `tokio-postgres`, calling execute simply enqueues a Future to be processed, which is already 50% of what this issue wants :)

I understand this piece of code well enough to figure out whether pipelining is already being used. If not, is it a local change in this function?
https://github.com/sfackler/rust-postgres/blob/a4bdcb11e4929ba21599cdfcce47fea052f413ad/tokio-postgres/src/proto/connection.rs#L82

As a side note, I see huge differences between the last publications on crates.io and master branch. Is a new release scheduled? Is there something holding it back?

**Comment by sfackler** [comment]
The version of tokio-postgres on master fully supports pipelining. All of the tests that `join` multiple queries together are taking advantage of that, for example: https://github.com/sfackler/rust-postgres/blob/master/tokio-postgres/tests/test.rs

The main thing holding back a release is finishing the big rewrite that's pending. I'll try to work on it a bit more this week.

**Comment by sfackler** [comment]
I'd say it's in a usable-but-undocumented-and-subject-to-change state :)

In particular, having having people try out the current APIs and provide feedback would be great!
