### ISSUE TITLE
A way to retrieve a more structure query plan from EXPLAIN

### ISSUE THREAD

**Issue by hirenhpatel** [sfackler/rust-postgres#1176]
I am able to get the query plan by prepending EXPLAIN to the query string I send through `postgres::Client`.

But the result comes back as rows of unstructured `&str` that I must parse.

Is this a limitation of the Postgres front end? or is there a way to get this in a more structured form through rust-postgres?

**Comment by sfackler** [comment]
I am not aware of any way to get more structured query planning information than what the `EXPLAIN` verb will do.

**Comment by hirenhpatel** [comment]
Thank you.
