### ISSUE TITLE
BUG: Fetch 2D arrays from Postgres

### ISSUE THREAD

**Issue by doper1** [sfackler/rust-postgres#1186]
### Library and version
tokio-postgres 0.7.12

### What's my goal

My goal is a column from a table which holds 2D arrays - VARCHAR[][]. That column can also contain null values.

### What's the bug

There is seemingly no way of doing so without getting an error. There are two possibilities for fetching the data:
```rust
let vars: Vec<Vec<String>> = row.get(0);
let vars: Vec<String>> = row.get(0);
```

The first one returns the error: error retrieving column 0: error deserializing column 0: cannot convert between the Rust type `alloc::vec::Vec<alloc::vec::Vec<alloc::string::String>>` and the Postgres type `_varchar

And the second one is in the 'correct' type, but then errors: Error: error deserializing column 0: array contains too many dimensions

### What I tried to do

I tried to rows using the second form until I get the 'too many dimensions error' and then use the first method, but the first method always errors regardless if the underlying value is null or a 2D array

### The full code
```rust
use dotenv::dotenv;
use tokio_postgres::{NoTls};
use std::env;

#[tokio::main]
async fn main() -> Result<(), Box<dyn std::error::Error>> {
    dotenv().ok();
    let postgres_host = env::var("POSTGRES_HOST").map_err(|_| "POSTGRES_HOST not found")?;
    let postgres_user = env::var("POSTGRES_USER").map_err(|_| "POSTGRES_HOST not found")?;
    let postgres_password =
        env::var("POSTGRES_PASSWORD").map_err(|_| "POSTGRES_PASSWORD not found")?;
    let postgres_db = env::var("POSTGRES_DB").map_err(|_| "POSTGRES_DB not found")?;

    let (client, connection) = tokio_postgres::connect(
        &format!(
            "postgres://{}:{}@{}:5432/{}",
            postgres_user, postgres_password, postgres_host, postgres_db
        ),
        NoTls,
    ).await?;

    tokio::spawn(async move {
        if let Err(e) = connection.await {
            eprintln!("connection error: {}", e);
        }
    });

    let rows = client.query("SELECT some_val FROM 2d_table", &[]).await?;

    for row in rows {
        match &row.try_get::<_, Option<Vec<String>>>(0) {
            Ok(Some(_)) => {
                print!("");
            }
            Ok(None) => {
                println!("");
            }
            Err(error) => {
                println!("Error: {}\n------------------", error);
                let vars: Vec<Vec<String>> = row.get(0);
                println!("VALUES: {:?}", vars);
            }
        }
    }

    Ok(())
}
```

**Comment by sfackler** [comment]
You should use the postgres-array crate to interact with multidimensional arrays: https://docs.rs/postgres_array/latest/postgres_array/

**Comment by doper1** [comment]
Thanks! it worked!

The fix:
```rust
use postgres_array::Array;

let vars: Array<String> = row.get(0);
```
