### ISSUE TITLE
commit after RowStream is consumed

### ISSUE THREAD

**Issue by docteurklein** [sfackler/rust-postgres#1191]
Hi!

I'm trying to commit a transaction after all rows of `query_typed_raw` have been streamed.
Maybe this is a bad idea because I should close the transaction as soon as possible (to help vacuum), and use `query_typed` instead?

Maybe wrapping the stream in a newtype implementing `Drop` could call `commit`?
Another option would be to allow `TransactionBuilder` (or `Transaction`) to be configurable regarding its own `Drop` impl?

something like:

```rust
conn.build_transaction().commit_on_drop().start().await?;
```

Do you have a better idea?
Thanks!

Regardless, below is a snippet of my code, it's an axum handler that streams http2 frames for each postgres row.

```rust
    let tx = conn.build_transaction().isolation_level(IsolationLevel::Serializable).start().await.map_err(internal_error)?;

    let rows = tx.query_typed_raw(&query.sql, sql_params).await.map_err(internal_error)?
        .map(|row| row.unwrap().get::<usize, String>(0))
    ;

    // this line blocks any progress, I should wait for the stream to be consumed before calling commit
    tx.commit().await.map_err(internal_error)?;


    match headers.get(ACCEPT).unwrap().to_str() { // @TODO real negotation parsing
        Ok("application/jsonl") => {
            Ok((
                [("content-type", "application/jsonl")],
                Html(Body::from_stream(
                    rows.map(|row| Bytes::from(row))
                    .map(Ok::<_, axum::Error>),
                ))
            ).into_response())
        }

```

**Comment by sfackler** [comment]
Wouldn't you want to ensure the transaction is committed before returning data to the caller? I am assuming there are some writes happening in the real code that aren't included in that snippet or there would be no need for any transaction at all.

**Comment by docteurklein** [comment]
>  why can't you just put the commit snippet at the end?

I thought about it but my handler needs to return the `IntoResponse` of the stream early so that it can be streamed to the browser. The final `commit()` statement would be dead code (unless I miss something).

> I'd stream the data into memory—I'd still use query_typed_raw/query_raw to avoid the intermediate Vec<Row>

I'd say that "stream in memory then commit then send" is the same as `collect()`ing in a Vec, no?

But I agree that in any case, it's surely better to ensure the transaction is commited before sending anything to the client, it totally passed over my head.

I think I'll write a separate write path, so that I can still setup my transaction and commit as wanted. I just won't be able to stream progress, but that's OK for the write path I guess.
