### ISSUE TITLE
Cannot get Timespec 

### ISSUE THREAD

**Issue by veer66** [sfackler/rust-postgres#121]
I try to read TIMESTAMP WITH TIME ZONE. I defined t as Timespec. I have already extern crate time; and use time::Timespec;

but I still get this error message:

the trait `postgres::types::FromSql` is not implemented for the type `time::Timespec` [E0277]
                             updated_time:row.get("created_time"),

**Comment by sfackler** [comment]
You need to enable the `time` feature to activate the `FromSql` and `ToSql` implementations for `Timespec`: https://github.com/sfackler/rust-postgres#timestamptimestamptz-types

**Comment by veer66** [comment]
Thank you. I just notice how to enable feature in Cargo.toml.
