### ISSUE TITLE
How to use CopyInStatement?

### ISSUE THREAD

**Issue by amosbird** [sfackler/rust-postgres#122]
I cannot find any docs to help me understand this usage. Is there any simple examples I can mimic? I think there should be an example that use a bunch of string rows as input.

**Comment by sfackler** [comment]
There are some example uses of it in the tests: https://github.com/sfackler/rust-postgres/blob/master/tests/test.rs#L756-L772

It is not a particularly ergonomic API at the moment.

**Comment by amosbird** [comment]
Thanks. I think it will be useful to directly pass an Iterator that yields `char` delimited string to CopyInStmt.

**Comment by sfackler** [comment]
Version 0.9 changes the COPY support pretty significantly. `CopyInStatement` is gone, and there's now a `copy_in` method on `Statement` that just takes a `Read`er that it pipes to the postgres server: http://sfackler.github.io/rust-postgres/doc/v0.9.1/postgres/struct.Statement.html#method.copy_in
