### ISSUE TITLE
upstream out-of-std bufstream adds 40ms

### ISSUE THREAD

**Issue by mikedilger** [sfackler/rust-postgres#123]
I believe the bug I want to report is upstream, but I'm opening this issue to track it.  So far I haven't looked further upstream just yet.

Using rust-postgres 0.8.7, my webserver pages typically get served in 1ms.   Using rust-postgres 0.8.8, that changes to 41ms.

I tried reverting a6c5d3014d50bd6ee075f774ff6a4878a9e02e56 and the performance returned.

So something about out-of-std bufstream has slowed it down considerably.

**Comment by mikedilger** [comment]
upstream bug report: https://github.com/alexcrichton/bufstream/issues/1

**Comment by sfackler** [comment]
I believe this should be resolved now, but please reopen if you're still seeing problems.

**Comment by mikedilger** [comment]
Yep fixed.  Thanks.
