### ISSUE TITLE
insert returning id

### ISSUE THREAD

**Issue by vrcod** [sfackler/rust-postgres#128]
Postgres has the "insert returning id" (http://www.postgresql.org/docs/9.4/static/sql-insert.html) functionality, is it possible to use this with existing functionality or is this something not yet implemented?

**Comment by sfackler** [comment]
Yep, it'll act like a normal query that returns a row set

```rust
let stmt = try!(conn.prepare("INSERT INTO foo (bar) VALUES ('baz') RETURNING id"));
let id: i32 = try!(stmt.query(&[])).iter().next().unwrap().get(0);
```

**Comment by vrcod** [comment]
Thanks. I'm trying to do this with a transaction, is it possible? I'm currently getting an error
```
error: no method named `query` found for type `core::result::Result<postgres::Statement<'_>, postgres::error::Error>` in the current scope
```
```
let query = "INSERT INTO foo (bar) VALUES ('baz') RETURNING id";
let stmt = trans.prepare(query);
let result = stmt.query(&[]);
let id: i32 = result.iter().next().unwrap().get(0);
```

**Comment by sfackler** [comment]
`query` returns a `Result` as well, so you'll need to get the `Rows` out of it. Right now it's calling `iter` on the `Result`, not the `Rows`.

**Comment by vrcod** [comment]
Got it, thanks, it's working.

**Comment by tylerhjones** [comment]
@sfackler could you help with an updated version of this?
Using version `0.17.0-alpha.1`
I do not see  a query method available on a `Statement` object

Would the following be a correct example?
```rust
    let stmt: Statement = conn.prepare(
        "INSERT INTO users \
        (usr_name, email, organization_id, role) \
        VALUES ($1, $2, $3, $4) \
        RETURNING id")?;

    let rows = conn.query(&stmt, &[&name, &usr_email, &org_id, &usr_role.role])?;
```

**Comment by sfackler** [comment]
Yes.
