### ISSUE TITLE
Please add support for using `?` as alternative to numbered parameters

### ISSUE THREAD

**Issue by ivanceras** [sfackler/rust-postgres#132]
The query
```sql
 conn.execute("INSERT INTO person (name, data) VALUES ($1, $2)",
                 &[&me.name, &me.data]).unwrap();
```
would be much more easier to generate in an ORM as
```sql
 conn.execute("INSERT INTO person (name, data) VALUES (?, ?)",
                 &[&me.name, &me.data]).unwrap();

```

**Comment by zr40** [comment]
Why would `?, ?` be easier to generate than `$1, $2`? If you're generating statements, I would think numbered parameters are easier, because that allows you to construct the parameter list as you go without needing to match the same `?` order in your statements.

**Comment by ivanceras** [comment]
I'm building an ORM which requires dynamic generation of sql statements at run time. A certain query can contain queries in it i.e(column subquery) and multiple filters and can also contain queries with indefinite number of parameters i.e. (WHERE pid NOT IN (SELECT pid FROM product ...)).  Keeping track of the numbering of the parameter will be complicated as Query is passed to builders recursively as needed.

**Comment by zr40** [comment]
You still need to keep track of parameter index, because the order in the parameter list depends on where the builders end up placing the `?`s. If you need to keep track of the index anyway, you can just use `$1`.

**Comment by sfackler** [comment]
This would require a rather nontrivial parser to understand enough of the Postgres query grammar to be able to determine which `?`s are parameters and which are not. It seems somewhat out of scope for the database driver itself, but you could definitely make a separate crate that could do the translation.

**Comment by ivanceras** [comment]
jdbc driver uses `?` instead of the numbered parameters. I though that is the standard way of doing sql prepared statements.

**Comment by sfackler** [comment]
There isn't really a standard syntax for prepared statements across databases. Postgres uses `$1`. SQLite supports all of `?`, `?1`, `:foobar`, `@foobar`, `$foobar`. MySQL and MSSQL use `@foobar`.

JDBC standardized on `?` as a "least common denominator" at the cost of forcing every driver to include the logic to parse queries and adjust parameter syntax as necessary.

**Comment by sfackler** [comment]
The Postgres JDBC driver's parser for reference: 
http://grepcode.com/file/repo1.maven.org/maven2/org.postgresql/postgresql/9.4-1201-jdbc41/org/postgresql/core/v2/V2Query.java#30
http://grepcode.com/file/repo1.maven.org/maven2/org.postgresql/postgresql/9.4-1201-jdbc41/org/postgresql/core/Parser.java
