### ISSUE TITLE
Detailed errors in error::Error::description

### ISSUE THREAD

**Issue by ArtemGr** [sfackler/rust-postgres#134]
Currently `error::Error` just prints "An error reported by the Postgres server" most of the time, omitting all the details. Could it be changed to include the description from the cause or is it intentional?

**Comment by sfackler** [comment]
There's not much that can be done about `description` since it returns a `&str`, but I've updated the `Display` implementations to inline the error messages from the inner errors.

**Comment by ArtemGr** [comment]
Right, `Display`'s what I needed. Thanks!
