### ISSUE TITLE
postgres::Connection does not implement Send

### ISSUE THREAD

**Issue by marcusklaas** [sfackler/rust-postgres#135]
Is there a reason why it shouldn't? Implementing it could be useful for wrapping operations in a `Future`, for example.

**Comment by sfackler** [comment]
It appears to implement `Send` to me - what issues are you having specifically? https://github.com/sfackler/rust-postgres/blob/master/src/lib.rs#L867-L870

**Comment by marcusklaas** [comment]
Ah, apologies. I didn't know it could be implemented implicitly. I hadn't actually tried. Sorry!

**Comment by sfackler** [comment]
Yep, `Send` is one of the few traits (`Sync` is another) that is automatically implemented by a type if all of its fields implement it.
