### ISSUE TITLE
Executing a query with results, without preparing it

### ISSUE THREAD

**Issue by RustyRails** [sfackler/rust-postgres#141]
Is it possible to execute a one-off query, without first preparing it? And getting the results? Looking through the docs, I'm unable to find a way. Is this intentional?

**Comment by sfackler** [comment]
There isn't right now. I have been thinking about adding a `query` method on `Connection`/`Transaction` along side `execute` for this kind of use case but it requires some internal refactoring that I haven't gotten around to doing yet.

**Comment by sfackler** [comment]
I believe that this is unfortunately incompatible with http://sfackler.github.io/rust-postgres/doc/v0.10.0/postgres/rows/struct.IntoIter.html. Not sure how to deal with that in a way that doesn't break backwards compatibility.

**Comment by sfackler** [comment]
I've implemented this on a separate branch that i'll merge in when we're ready to cut an `0.11` release: https://github.com/sfackler/rust-postgres/commit/c3fc8f953947f75a227156a09c99d1c0cc94013e#diff-b4aea3e418ccdb71239b96952d9cddb6R1041

**Comment by barosl** [comment]
This is very nice to hear! Having to use `.prepare()` even though I don't particularly reuse the constructed `Statement` has been a bit tedious.
