### ISSUE TITLE
Limit/Offset with a parameter

### ISSUE THREAD

**Issue by antoyo** [sfackler/rust-postgres#142]
It seems impossible to send a parameter for a `LIMIT` or an `OFFSET`.

The following code executes correctly:

```rust
let result = connection.prepare("SELECT field1 FROM Person WHERE field2 = 42 OFFSET 24").unwrap();
result.query(&[]);
```

while this one generates an error:

```rust
let result = connection.prepare("SELECT field1 FROM Person WHERE field2 = 42 OFFSET $1").unwrap();
result.query(&[&24]);
```

The error is `WrongType(Int8)`.

Thanks to fix this issue.

**Comment by sfackler** [comment]
The error message is saying that postgres is expecting that parameter type to be an `INT8` aka a Rust `i64`, while the raw `24` you pass into query will end up being an `i32`.

**Comment by antoyo** [comment]
Ah, I see.
Thanks.
