### ISSUE TITLE
Implement Index for Rows

### ISSUE THREAD

**Issue by Pyriphlegethon** [sfackler/rust-postgres#143]
The ```Rows``` struct implements a [get method](https://github.com/sfackler/rust-postgres/blob/master/src/rows.rs#L63) that ```panic```s if the index is out of bounds. You should probably implement the [Index trait](https://doc.rust-lang.org/std/ops/trait.Index.html) which does exactly what you want. If a ```get``` function exists for a type it usually returns an ```Option<T>``` instead of calling ```panic```. See [get for Vec](https://doc.rust-lang.org/std/vec/struct.Vec.html#method.get).
The same goes for ```Row``` which currently has a ```get``` and a ```get_opt``` function.

**Comment by sfackler** [comment]
`Rows` cannot implement `Index` since it must return a value by reference. If `IndexGet` is ever added to Rust, `Rows` would be able to implement that.
