### ISSUE TITLE
Release 0.10.2 or 0.11 with updated openssl

### ISSUE THREAD

**Issue by sorccu** [sfackler/rust-postgres#146]
Looks like the change has already been made in the repo, but a new version hasn't been published.

This makes it very, very difficult to build an app that uses both postgres and openssl 0.7.x.

**Comment by sfackler** [comment]
Ah yeah, will do

**Comment by sfackler** [comment]
Released 0.10.2

**Comment by sorccu** [comment]
Thanks!
