### ISSUE TITLE
How to I receive `NOTIFY` from other processes?

### ISSUE THREAD

**Issue by letharion** [sfackler/rust-postgres#149]
I have this simple test program:

    let conn = Connection::connect("postgres://test:test@localhost", &SslMode::None).unwrap();
    conn.execute("LISTEN chan", &[]);
    let notifications = conn.notifications();

    conn.execute("NOTIFY chan, 'rust'", &[]);
    let mut it = notifications.iter();
    for i in 0..99999999 {
        let a = it.next();
        match a {
           Some(b) => {
               println!("{:?}", b);
           }
           _ => {}
        }
    }

The notification that I send with 'rust' as payload gets printed, and everything looks fine. However, if I then go into psql, and send `NOTIFY chan, 'psql';` while the loop is running, that notification never seems to show up.

I also did a long sleep while I sent notifications from psql, instead of long loop, but that didn't have any other effect. (Not that I really know why it would)

The other way works fine however. If I `LISTEN chan;` from psql, then I receive the 'rust' payload.

I'm probably doing something wrong that has an easy fix, but I can't work out what it is, any help would be appreciated. :)

    $ rustc --version
    rustc 1.5.0-beta.2 (b0f440163 2015-10-28)
    $ psql --version
    psql (PostgreSQL) 9.4.5

**Comment by letharion** [comment]
Just found `HandleNotice` http://sfackler.github.io/rust-postgres/doc/v0.10.2/postgres/trait.HandleNotice.html which looks relevant. :)

**Comment by sfackler** [comment]
The iterator returned by `notifications.iter()` will only return notifications that the driver's already received and processed. Any notification that has been sent after the last operation on the connection that touched the network (e.g. `query`) will not be found. `notifications.blocking_iter()` and `notifications.timeout_iter()` will return iterators that will check the network for incoming notifications.

With `notifications.iter()`, you can "touch the network" to get it to pick up pending notifications:

```rust
let mut notifications = conn.notifications();

for i in 0..99999999 {
    let a = it.next();
    match a {
       Some(b) => {
           println!("{:?}", b);
       }
       _ => conn.query("", &[]), // execute a noop query to pick up new messages
    }
}
```

Or just use `blocking_iter()`.

`HandleNotice` is actually separate from the `LISTEN` and `NOTIFY` system. It handles messages the server sends about things like the server shutting down.

**Comment by letharion** [comment]
Thank you very much, blocking_iter looks like just what I need.
Want me to submit something back as a documentation update around this? :)

**Comment by sfackler** [comment]
Please do! The documentation on `iter` right now is not great about explaining how this stuff works.
