### ISSUE TITLE
Cursor Support

### ISSUE THREAD

**Issue by bfrog** [sfackler/rust-postgres#154]
I have a scenario where I get an absolutely huge number of rows I'd like to work with in Rust from Postgres, what I don't want is to just load up my rust process with millions of rows though.

Cursors seem like the ideal solution to this sort of thing, it would be awesome if the client lib here supported them.

**Comment by sfackler** [comment]
I haven't tried, but you can probably handle cursors directly in postgres with normal queries: http://www.postgresql.org/docs/9.2/static/plpgsql-cursors.html

There's also [`lazy_query`](http://sfackler.github.io/rust-postgres/doc/v0.11.0/postgres/stmt/struct.Statement.html#method.lazy_query) which should handle the "I have tons of rows" use case.

**Comment by sfackler** [comment]
Hopefully the previous comment answered your question, but feel free to reopen this if not!

**Comment by flip111** [comment]
Try `query_raw` this drastically reduces memory usage. Though for working with more than one query at the same time probably the client has to be cloned first (not sure what the best solution is in this case, will run into borrow issues with multiple `&mut`)
