### ISSUE TITLE
Streaming select query result

### ISSUE THREAD

**Issue by calebmer** [sfackler/rust-postgres#155]
Is there a way to stream the results of a select query? I'm building an HTTP API and I'd like to use a stream (with a map) from database rows to the HTTP response for high performance. How can I do this?

I'm aware of `lazy_query` but it's only for a prepared statement. As an API I'm generating new queries for each request.

**Comment by sfackler** [comment]
Preparing a statement and then using `lazy_query` is probably what you want here. The docs for `prepare` are maybe a bit misleading - you'll usually only be using it for repeatedly executed queries but this is another case where you'd want to.

All queries that you execute are actually prepared internally - the `Connection::query` and `Connection::execute` methods are just conveniences. `conn.execute(query, args)` is roughly equivalent to `conn.prepare(query).and_then(|stmt| stmt.execute(args)`.

**Comment by calebmer** [comment]
Thanks! My main question has been answered so I'll close, but are there any negative impacts of using postgres's prepare mechanism for every query?

**Comment by sfackler** [comment]
The main cost is an extra round trip to the server.
