### ISSUE TITLE
Add mapping between `u32` and SERIAL

### ISSUE THREAD

**Issue by aochagavia** [sfackler/rust-postgres#159]
Since `SERIAL` is unsigned, it makes sense to read it and write it as `u32` without having to cast it explicitly (from and to i32). @sfackler does this seem useful to you? I don't have much experience with PostgreSQL or with your library, so maybe I am missing something.

**Comment by sfackler** [comment]
`SERIAL` is a bit of a weird thing in Postgres - it's not really a type, but rather closer to a macro almost.

```
postgres=# CREATE TEMPORARY TABLE foo (id SERIAL PRIMARY KEY);
CREATE TABLE
postgres=# \d foo
                        Table "pg_temp_2.foo"
 Column |  Type   |                    Modifiers
--------+---------+--------------------------------------------------
 id     | integer | not null default nextval('foo_id_seq'::regclass)
Indexes:
    "foo_pkey" PRIMARY KEY, btree (id)
```

Using serial is exactly equivalent to manually creating a sequence, creating the row with a `INTEGER` type, setting its default to `nextval('the_sequence')`, and then adjusting the sequence to be owned by the column. I don't believe the database even records the fact that the column was created with `SERIAL`.

Notably, while the sequence will start at 0 and go up from there, you can manually insert negative values in the column just fine:

```
postgres=# INSERT INTO foo (id) VALUES (-1);
INSERT 0 1
postgres=# SELECT * FROM foo;
 id
----
 -1
(1 row)
```

**Comment by aochagavia** [comment]
Wow... I didn't expect that. Then I'll just close the issue.

Thanks for the explanation!
