### ISSUE TITLE
Feature request: Non-blocking connections and asynchronous queries

### ISSUE THREAD

**Issue by Koka** [sfackler/rust-postgres#160]
I wonder if it's possible to implement non-blocking connections and asynchronous query support in this driver. AFAIK postgres protocol itself support this feature not only for notifications, but also for SQL queries (sending non-blocking SQL queries and asynchronous fetching of results, in particular). It's even [implemented](http://www.postgresql.org/docs/current/static/libpq-async.html) in postgresql C client library libpq. Rust appears to be a great language for concurrency and parallel processing and non-blocking database access can be quite valuable for concurrent applications.

**Comment by sfackler** [comment]
This is definitely something that seems like it would make sense to add.

There are a couple of "levels" of async-ness that libpq provides. In one use case, your socket is still a normal blocking socket, but you want to start a query and then do some work before waiting on the result. This is doable now without much effort, but it will require some thought as to what the API will look like.

In the stronger case, your socket is fully nonblocking. This case will require significant internal changes, and a lot of thought about how the APIs here should actually behave.

**Comment by bfrog** [comment]
Perhaps a Promise<T,E> like return for something like an async_query method could be worthwhile for at least the first kind of async situation that libpq provides now

**Comment by jwilm** [comment]
@bfrog Although Promises are nice in a lot of situations, they're not one-size-fits-all. A generic API would be more flexible, and a promise-like implementor of it could be provided. For example, the core of such an API might be:

```rust
/// Something that can process and async response
trait ProcessResponse {
    /// Called once a query finishes or errors
    fn process_response(PgResponse);
}

/// Async query API
pub fn async_query<P: ProcessResponse>(sql: &str /* or whatever */,
                                       params: &[&ToSql],
                                       processor: P)
{
    // builds query and sends to event loop
    // ...
    // event loop eventually calls processor.process_response
}
```

and a promise implementation could take this form:

```rust
/// Promise type for async queries
pub struct QueryPromise(rx: mpsc::Receiver<PgResponse>);

impl QueryPromise {
    /// Create a new promise and the handler
    pub fn new() -> (QueryPromise, QueryPromiseHandler) { /* ... */ }

    /// Run some code after the query has been handled (or errored)
    pub fn then<F: FnOnce(PgResponse)>(func: F) {
        func(self.0.recv().unwrap())
    }
}

/// Type that gets passed to async_query
pub struct QueryPromiseHandler(tx: mpsc::Sender<PgResponse>);

impl ProcessResponse for QueryPromiseHandler {
    #[inline]
    fn process_response(res: PgResponse) {
        let _ = self.0.send(res);
    }
}

// Example usage omitting crucial details such as esablishing a connection and all that
fn main() {
    let (promise, handler) = QueryPromise::new();
    query_async("SELECT * FROM users LIMIT 1", &[], handler);
    promise.then(|res| println!("Got a response: {:?}", res);
}
```

Reasons for such an API:
1. Promise forces you to block somewhere
2. Promises are 1:1. Maybe you want a queue of responses instead of a promise.
3. Maybe a user wants to do something completely different like send the response to another event loop.
4. In a common use case like an Iron handler, the HTTP handler thread shouldn't be blocked waiting for a DB call. Generic API here would allow integrating with an arbitrary async framework.

**Comment by bfrog** [comment]
It seems like tokio-rs would be a great basis for doing non-blocking postgres

**Comment by sfackler** [comment]
This is implemented in the tokio-postgres crate.
