### ISSUE TITLE
Add support for std::net::{Ipv4Addr, Ipv6Addr, IpAddr} <-> INET

### ISSUE THREAD

**Issue by ivan** [sfackler/rust-postgres#161]
Would you take a PR that does this?  (I am working on one.)

**Comment by sfackler** [comment]
Postgres stores a netmask in addition to the IP address, which is why these implementations don't exist already.

**Comment by ivan** [comment]
Indeed, that is a bit of a troublesome mismatch.  What I'm doing is: always writing 32 bits / 128 bits in `ToSql`, and doing something like

```rust
        if bits != 32 {
            let err: Box<error::Error + Sync + Send> = "INET must have all 32 bits for Ipv4Addr".into();
            return Err(Error::Conversion(err));
        }
```

in `FromSql`.

Do you think that is workable?

**Comment by sfackler** [comment]
I would prefer that the implementations in this library be "lossless" in general.

**Comment by ivan** [comment]
I take your point.  I guess I might want to make a new crate with types that wrap `Ipv4Addr` and `Ipv6Addr` to add a netmask.

**Comment by ivan** [comment]
I just figured out that there *is* a way to insert `Ipv4Addr`/`Ipv6Addr` using strings:

```rust
let ipv4_s = format!("{}", Ipv4Addr::new(127, 0, 0, 1));
let ipv6_s = format!("{}", Ipv6Addr::new(1, 2, 3, 4, 5, 6, 7, 8));
conn.execute("INSERT INTO sessions (last_seen_ipv4, last_seen_ipv6) VALUES (cast($1::text as inet), cast($2::text as inet))", &[&ipv4_s, &ipv6_s]).unwrap();
```

**Comment by zr40** [comment]
@ivan note that you can do just `$1::text::inet`. Both cast syntaxes have the same meaning, you don't need to use both together.

**Comment by ivan** [comment]
Thanks!  That does look a lot better.

**Comment by newpavlov** [comment]
@sfackler 
How about just using a simple aliased tuple `type MaskIpAddr = (IpAddr, u8);` for lossless operations with `inet` and `cidr`?
