### ISSUE TITLE
WrongType error with Enums

### ISSUE THREAD

**Issue by mikedilger** [sfackler/rust-postgres#162]
Something has broken Enums (perhaps changes related to #153 ?).  My ToSql implementation, which used to work, now errors out with:

````
Conversion(WrongType(Other { name: "realm_relationship_t", oid: 43842, kind: Enum(["Default"]), schema: "public" }))
````

I very hopefully tried using postgres-derive-macros, but it does the same thing.

**Comment by mikedilger** [comment]
I'm using the latest crates.io releases.

RealmRelationship currently only has 1 enum variant.  `Default` is a reserved word in SQL, but I don't think that should matter in this context.

````rust
/// Relationship between a parent realm and a child realm
#[derive(Debug,Clone,Copy,PartialEq,Eq, ToSql, FromSql)]
pub enum RealmRelationship {
    /// The default relationship
    Default
}
````

**Comment by sfackler** [comment]
The implementation that postgres-derive-macros generates checks that the variant names match (which they appear to here), as well as that the type name itself matches, which generates the error (`RealmRelationship` vs `realm_relationship_t`). You can rename the enum to match, or use the `#[postgres]` attribute to adjust what the `ToSql` and `FromSql` implementations will look for:

```rust
/// Relationship between a parent realm and a child realm
#[derive(Debug,Clone,Copy,PartialEq,Eq, ToSql, FromSql)]
#[postgres(name = "realm_relationship_t")]
pub enum RealmRelationship {
    /// The default relationship
    Default
}
```

**Comment by mikedilger** [comment]
Ah, I was using it wrong. Not sure why it failed prior to using postgres-derive-macros but I no longer care because it works. Thanks.
