### ISSUE TITLE
Support SSL automatically depending on the URL ?

### ISSUE THREAD

**Issue by Keats** [sfackler/rust-postgres#166]
Hello,

I have a PR to add SSL support to my database migration tool to add SSL support (https://github.com/Keats/dbmigrate/pull/7).

Would it be possible to have the Connection handle sslmode automatically? It's a bit tricky right now.

Here's what I mean by automatic handling:

- I have openssl feature for rust-postgres and no sslmode in url -> non ssl
- I have openssl feature for rust-postgres and  sslmode in url -> I get back a SSL connection with the correct sslmode
- I don't have openssl feature for rust-postgres -> always get non ssl, maybe error if ssl is in the url ?

**Comment by sfackler** [comment]
It's not totally clear to me how this would be implemented, unfortunately.

* This library is agnostic of the actual SSL backend - it could be OpenSSL, it could be Secure Transport, it sould be SChannel, it could be GnuTLS, etc.
* There is a fair amount of configuration that people need in various cases over their SSL provider - additional trusted root certificates, protocol selection, cipher selection, control over hostname validation, etc.
* I'm also a bit leery of having the query parameters be a mix of things that the client cares about and that the Postgres server cares about.

**Comment by Keats** [comment]
Good points, didn't think about all of that.

Closing
