### ISSUE TITLE
Error querying Redshift

### ISSUE THREAD

**Issue by alienfluid** [sfackler/rust-postgres#167]
Was trying to query a table on Amazon Redshift (modified, stripped down Postgres) and keep getting this error --

`thread '<main>' panicked at 'called `Result::unwrap()` on an `Err` value: Db(DbError { severity: "ERROR", code: UndefinedTable, message: "relation \"pg_catalog.pg_enum\" does not exist", detail: None, hint: None, position: None, where_: None, schema: None, table: None, column: None, datatype: None, constraint: None, file: "/home/awsrsqa/padb/src/pg/src/backend/catalog/namespace.c", line: 217, routine: "RangeVarGetRelid" })', ../src/libcore/result.rs:688`

Looks like the library tries to query the pg_catalog.pg_enum table, which does not exist on Redshift. Any workaround for this? Doesn't look like there are any Rust libraries that support Redshift directly.

**Comment by sfackler** [comment]
Looks like Redshift doesn't support enumerated or composite types - should just be a matter of allowing the creation of the `TYPEINFO_ENUM_QUERY` and `TYPEINFO_COMPOSITE_QUERY` to fail if the error code is `UndefinedTable`. We do something similar for range types already: https://github.com/sfackler/rust-postgres/blob/master/src/lib.rs#L502

**Comment by alienfluid** [comment]
Perfect, I can submit a pull request for it later today or tomorrow. Thanks for looking into it so quickly.

**Comment by sfackler** [comment]
Just pushed what I think is a fix to master, but I don't have easy access to a Redshift instance. Could you try it out and report back? I'll publish a new release once we're sure things are working.

**Comment by alienfluid** [comment]
The query seems to be working now, thanks! I'll report if something else breaks down the road with my usage of your library against Redshift.

**Comment by sfackler** [comment]
Great! Released v0.11.6 with this fix.
