### ISSUE TITLE
Bug in dynamic ORDER BY

### ISSUE THREAD

**Issue by ccjr** [sfackler/rust-postgres#168]
I'm not sure if this is intended behaviour, or if I'm doing something wrong; however, when I dynamically assign `ORDER BY`, I'm not getting expected results, see https://gist.github.com/ccjr/fc47ea0c855b325b3d21b06dcfe9bff3

**Comment by sfackler** [comment]
Query parameters can't be used that way - they fill in for values, not arbitrary portions of query syntax.

**Comment by ccjr** [comment]
Fair enough, is there a recommended way of building a query that way?

**Comment by ccjr** [comment]
I got this working using `format!`. I was mostly just wondering if there was a "blessed" way of doing this, but I guess it doesn't really make sense to have stuff like that in the driver. Thanks for your prompt reply!

**Comment by sfackler** [comment]
Yep, building up the string manually is what I have done in the past for
this kind of thing.
