### ISSUE TITLE
return null column value will poison the connection 

### ISSUE THREAD

**Issue by limitee** [sfackler/rust-postgres#170]
thread '<main>' panicked at 'error retrieving column "sum": Conversion(WasNull)', /Users/mingli/.cargo/registry/src/github.com-88ac128001ac3a9a/postgres-0.11.6/src/rows.rs:204

Retun null or Result::Err is ok....but poison the connection is so bad.

**Comment by sfackler** [comment]
What do you mean by poisoning the connection? If you have nullable types, use an `Option<T>` instead of just a `T`.

**Comment by sfackler** [comment]
The [get_opt](http://sfackler.github.io/rust-postgres/doc/v0.11.6/postgres/rows/struct.Row.html#method.get_opt) method will not panic on conversion errors.

**Comment by limitee** [comment]
I have no chance to do that.
select case sum(amount)::integer=null then 0 from order_food where forder_id=100;
if no set matches forder_id=100, it will throws a err, not returns a err. That is the problem.
    let out_rst = {
            let rst = conn.query(sql, &[]);//here, should return a Result, not throws a err
            rst.and_then(|rows| {
                Result::Ok(self.get_back_json(rows))
            })
        };

**Comment by sfackler** [comment]
Are you sure that's the case? That error message refers to an error retrieving a column from a `Row`. I would expect that to be happening in `get_back_json` judging from that.

**Comment by limitee** [comment]
It's my fault...It truely comes from get_back_json....Thanks.
