### ISSUE TITLE
Change `ToSql` for `&[T]` be 1-indexed

### ISSUE THREAD

**Issue by jonhoo** [sfackler/rust-postgres#176]
Making the values produced by `&[T].to_sql()` be 0-indexed means that they are no longer compatible with `ARRAY` literals. From the PostgreSQL [manual](http://www.postgresql.org/docs/9.5/static/sql-expressions.html#SQL-SYNTAX-ARRAY-CONSTRUCTORS):

> The subscripts of an array value built with ARRAY always begin with one.

Is there a good reason why 0-indexed arrays were chosen for serialization?

**Comment by sfackler** [comment]
They're zero indexed because Rust arrays are - it was pretty arbitrary.

What issues are caused by this behavior?

**Comment by jonhoo** [comment]
For what it's worth, the fix is to use casting to array from the textual array format:
```sql
WHERE COALESCE(maybe.arr, CAST('[0:0]={1}' AS integer[])) = $1::integer[]
```
That's not particularly icky in this simple case, but if you want the array to contain values from another table for example, you end up with ugly workarounds like:
```sql
WHERE COALESCE(maybe.arr, CAST('[0:0]={' || other.x || '}' AS integer[])) = $1::integer[]
```
If you want multiple elements, you need to start doing string concatenation with `,` too. It gets ugly fast.

**Comment by sfackler** [comment]
Ok, fair enough. We can't make this change until the next major release, but it seems reasonable to make then. Could you open a PR against the "breaks" branch with the change? That's where I'm collecting these kinds of things.

**Comment by sfackler** [comment]
I fixed this in the breaks branch.

Also worth noting that the [postgres-array](https://github.com/sfackler/rust-postgres-array) crate has more complete support for Postgres arrays.
