### ISSUE TITLE
Error converting between Postgres and Rust types

### ISSUE THREAD

**Issue by inxi-pc** [sfackler/rust-postgres#177]
Error converting between Postgres and Rust types: cannot convert to or from a Postgres value of type `myschema.item_type`

The item_type is enum in postgres.  When i use stmt to do a query, and assign a string param to query, i got this error.  Before i use 0.8.6 library, it is fine. Could you guide me to solve this issue? 

Thanks @sfackler

**Comment by inxi-pc** [comment]
I use debug to get the error place. 

```rust
let sql = format!("SELECT {} FROM {} WHERE {} = $1 ORDER BY {}", columns, Self::table(), column, Self::primary_key());
        let stmt = try!(conn.prepare(&sql));
        debug!("error beofe query: {:?}", key);
        let rows = try!(stmt.query(&[key]));
        debug!("error beofe from_row");
```

got this 

```rust
DEBUG:cm_api::model: error beofe query: "TODAY_SHOCKER"
DEBUG:postgres: executing statement s1 with parameters: ["TODAY_SHOCKER"]
DEBUG:hyper::server::response: writing head: Http11 InternalServerError
```

**Comment by inxi-pc** [comment]
one more thing, i test other enum type operation. like insert, i got this same error.

**Comment by inxi-pc** [comment]
sorry, i just check , find other thing...

**Comment by inxi-pc** [comment]
Old library version is working fine..i just test

**Comment by sfackler** [comment]
Enum types are distinct from strings in Postgres. You can cast the enum column to and from a varchar to get it to work with a string, or use something like rust-postgres-derive to implement `FromSql` and `ToSql for your enum: https://github.com/sfackler/rust-postgres-derive

**Comment by inxi-pc** [comment]
Got it, thanks very much
