### ISSUE TITLE
Join query issue

### ISSUE THREAD

**Issue by inxi-pc** [sfackler/rust-postgres#180]
Hi Mr Sfackler

I meet a issue when i got data from join query, like inner join.

I have table Item {a_id, quantity ... } , table Sku {b_id, a_id, quantity }. 
And when i do inner join query, like below:

```Rust
let rows = try!(conn.query(format!(
        SELECT a.*, b.* FROM test.item AS a
        INNER JOIN test.sku AS b
        ON a.item_id = b.item_id 
        WHERE item_id = 10022319
        ).as_ref()
)));
```

I got a row data which include Item field and sku field. But when i got field data from row by using 
get_opt(field_name), i got exception data at field named quantity, it's data is Item table quantity data,
not sku.

```Rust
Row { statement: Statement { name: "s18", parameter_types: [], 
columns: [
Column { name: "item_id", type_: Int4 }, 
Column { name: "quantity", type_: Int4 },  
Column { name: "sku_id", type_: Int4 }, 
Column { name: "item_id", type_: Int4 }, 
Column { name: "quantity", type_: Int4 }, 
Column { name: "price", type_: Float8 }] } }
```
We can find, the field result column name is same, although i use AS in query, i cant got the correct
field data by a.field_name also. i am confused on this. Kindly guide me how to solve same field issue in join query if you are free. 

Best regard

**Comment by sfackler** [comment]
You will probably need to use numeric indices to access `b`'s `quantity` if you want to continue using `a.*, b.*` rather than something like `a.item_id, a.quantity as a_quantity, ...`. If Postgres names both columns `quantity`, that's all we have.
