### ISSUE TITLE
Failed to connect to postgres

### ISSUE THREAD

**Issue by cirfi** [sfackler/rust-postgres#181]
```rust
let conn = Connection::connect("postgres://postgres:passwd@localhost/postgres", SslMode::None).unwarp();
```
which result to be:
Err(Io(Error { repr: Custom(Custom { kind: UnexpectedEof, error: StringError("failed to fill whole buffer") }) }))

PostgreSQL version: 9.5.2
Rust version: both stable 1.8.0 and nightly 1.10.0 failed.

I've tried node.js's pg as well. It succeeded.

**Comment by sfackler** [comment]
Do you by any chance have an environment that I can access which reproduces this? I don't believe anyone's run into issues of this kind before.

**Comment by cirfi** [comment]
Sorry but I'm under campus network.
I'll purchase a vps and try again.

**Comment by cirfi** [comment]
I successfully connect to PostgreSQL on Ubuntu 16.04, GCE.
But still failed on my Arch Linux.
Maybe it's an Arch related issue.

**Comment by sfackler** [comment]
I test locally on Arch so I don't think it's that. Maybe something weird with Postgres's locale?

**Comment by cirfi** [comment]
I just followed Arch wiki's "initdb --locale $LANG -E UTF8 -D '/var/lib/postgres/data'".

**Comment by sfackler** [comment]
What is your `$LANG`?

**Comment by cirfi** [comment]
--- ~ » echo $LANG
en_US.UTF-8

**Comment by sfackler** [comment]
Weird - all I can think of is using Wireshark to look at the messages coming out of Postgres. Have you worked with it before?

**Comment by cirfi** [comment]
Which interface should I use?
I have no idea which interface will internal connections use.

**Comment by cirfi** [comment]
No connections for filter tcp.port == 5432 on interface Loopback.

**Comment by sfackler** [comment]
Try filtering on `pgsql` rather than `tcp.port` - this is what things should look like when successfully connecting:

![capture](https://cloud.githubusercontent.com/assets/1455697/15349020/362f2e02-1c84-11e6-988d-f2aa8381cd78.PNG)

**Comment by cirfi** [comment]
I'm sorry. 
It's quite slow to access crate.io in China. So I aliased cargo to proxychains cargo. And I forgot it.
Connections are under proxy. So wireshark can't capture them on fiter pgsql.
I'm sorry.
I solve this by excluding 127.0.0.0/255.0.0.0 in proxychains config file.

**Comment by sfackler** [comment]
Ah, that'd do it! Glad things are working now.
