### ISSUE TITLE
Error converting empty array to Vec<T>

### ISSUE THREAD

**Issue by programble** [sfackler/rust-postgres#189]
For example,

```rust
fn empty_array(conn: &Connection) {
    for row in &conn.query("SELECT '{}'::varchar[]", &[]).unwrap() {
        let _: Vec<String> = row.get(0);
    }
}
```

results in this error:

```
thread '<main>' panicked at 'error retrieving column 0: Conversion(StringError("array contains too many dimensions"))', /Users/curtis/.cargo/registry/src/github.com-88ac128001ac3a9a/postgres-0.11.9/src/rows.rs:204
```

which comes from [this check](https://github.com/sfackler/rust-postgres/blob/5938db205b7d7721acdcbd18541c779c6f4e6540/src/types/mod.rs#L361).

Based on the following, it seems likely that Postgres encodes empty arrays as having zero dimensions.

```
curtis=# SELECT array_ndims('{}'::varchar[]);
 array_ndims
─────────────
           ¤
(1 row)
```

**Comment by sfackler** [comment]
Ah, that's weird. Seems reasonable to just tweak that check to allow 0 and 1 dimensional arrays. Do you want to make the PR or should I?

**Comment by programble** [comment]
I can do it.
