### ISSUE TITLE
transaction issues (probably MIR related)

### ISSUE THREAD

**Issue by mikedilger** [sfackler/rust-postgres#195]
I've gotten a number of new behaviours since the MIR switch, and yes, perhaps this should be filed  under `rust-lang/rust`.  But I wanted to discuss with you briefly first.

This (out of context) block:
````rust
{
        let conn = try!(pool.get());
        let trans = try!(conn.transaction());

       // do multiple things with &trans ...

        trans.set_commit();
    }
````

now breaks the assert in transaction.rs:199  (with rust-nightly >= 2016-08-03)
````rust
debug_assert!(self.depth == conn.trans_depth);
````

 I think if I create a sub-block with the transaction inside, it might work, but I'll get to testing later, e.g.
````rust
{
        let conn = try!(pool.get());
        {
                let trans = try!(conn.transaction());

               // do multiple things with &trans ...

                trans.set_commit();
        }
}
````

The other possibly related behavior is that if a transaction fails, and I get a new connection from the pool, sometimes that new connection fails every SQL command with "current transaction is aborted, commands ignored until end of transaction block" ... meaning the trans is not dropping and the connection is still wrapped in the failed trans.

I may not be able to attend to getting better examples/details right away as I've got client work keeping me busy, but I thought I should say something sooner rather than later.

**Comment by sfackler** [comment]
Ouch.

Until MIR gets fixed, you can use `trans.commit()` to explicitly consume the transaction when you want to commit it. That won't fix the rollback case though, obviously.

**Comment by sfackler** [comment]
I believe the upstream miscompilation issue has been fixed?
