### ISSUE TITLE
serde_json::Value: postgres::types::FromSql not satisfied

### ISSUE THREAD

**Issue by millerjs** [sfackler/rust-postgres#196]
I'm not sure what I've changed, but I had JSONB deserializing to `serde_json::Value` before.  Should the below example compile? If not, can you tell me what am I doing wrong here:

```rust
extern crate serde_json;
extern crate postgres;

use serde_json::Value;
use postgres::{Connection, SslMode};

fn main() {
    let con_str = "postgres://postgres@localhost/test";
    let connection = Connection::connect(con_str,  SslMode::None).unwrap();
    for row in &connection.query("SELECT values FROM table1", &[]).unwrap() {
        let values: Value = row.get(0);
    }
}
```

error:
```
src/main.rs:11:33: 11:36 error: the trait bound `serde_json::Value: postgres::types::FromSql` is not satisfied [E0277]
src/main.rs:11         let values: Value = row.get(1);
                                               ^~~
```

Cargo.toml
```ini
...
[dependencies]
serde = "*"
serde_json = "*"

[dependencies.postgres]
version = "*"
features = ["serde_json"]
```

Thanks!

**Comment by sfackler** [comment]
The postgres library currently supports serde_json 0.7 while 0.8 is the newest version. Because you're using wildcard dependencies, you're ending up with 0.8 rather than 0.7.

**Comment by millerjs** [comment]
Thanks! I'm curious why `rust-postgres` compiles with the feature without error, does it pull `serde_json = { version = ">= 0.6, < 0.8", optional = true }` and bind the implementation to a different version such that when I pull `.8` it's not implemented?  Sorry, I'm not sure what cargo does with conflicting versions.

**Comment by sfackler** [comment]
You will end up with both serde_json 0.7 and serde_json 0.8 at the same time.

**Comment by millerjs** [comment]
Thanks, will have to read up on that.
