### ISSUE TITLE
Cant .get(0) integer row?

### ISSUE THREAD

**Issue by Meai1** [sfackler/rust-postgres#197]
![bug](https://cloud.githubusercontent.com/assets/1112157/17830682/0d0a9090-66d3-11e6-83c3-28162d946ca6.PNG)

I'm on rust 1.13 nightly

**Comment by sfackler** [comment]
It appears that the database is sending back a 64 bit integer (see `Int8` in the error message). Try converting to an `i64` rather than an `i32`.
