### ISSUE TITLE
Statement expecting a bigint (i64) returns a `Conversion(WrongType(Int8))` incorrectly

### ISSUE THREAD

**Issue by norcalli** [sfackler/rust-postgres#198]
Minimal test case:
```rust
let conn = Connection::connect("...").unwrap();
conn.query("SELECT $1::bigint", &[&10i64]).unwrap(); // fine
conn.query("SELECT $1::bigint", &[&10i32]).unwrap(); // Conversion(WrongType(Int8))
```

This, I presume should be returning Int64 instead. Seems to be the same issue as here: https://github.com/sfackler/rust-postgres/issues/197

**Comment by sfackler** [comment]
The postgres backend tells us what types parameters are expected to have. We don't have any control over it on this end.

The "8" in `Int8` refers to a byte count, not a bit count, by the way.

**Comment by norcalli** [comment]
Ohhhhhhh, well knowing it's the byte count makes way more sense, since that would have to be `i64`. I feel like that should be documented more clearly (although imo calling it `Int8` is confusing). Even a note on the README would be nice explaining some of the errors.

**Comment by sfackler** [comment]
Type names are extracted directly from Postgres, so its naming conventions are what we go with.

**Comment by norcalli** [comment]
Alright. Fair enough
