### ISSUE TITLE
Panick when trying to get Varchar column

### ISSUE THREAD

**Issue by hypercat** [sfackler/rust-postgres#202]
Hi,

I'm trying to get a varchar value from my postgres database and end up with a panicking thread. My affected code is:
```rust
let rows = stmt_prep.query(&[&i]);
if rows.is_err() {
	println!("Failed to execute prepared SQL statement: {}", rows.unwrap_err());
	return;
}
let rows = rows.unwrap();
let row = rows.get(0); 
let stmp: String = row.get(1);
```
Based on my understanding, Varchar should convert perfectly to the Rust type String but maybe I misunderstood something? The error message I get is the following:
`thread '<main>' panicked at 'error retrieving column 1: WrongType(Varchar)', C:\Users\xx\.cargo\registry\src\github.com-88ac128001ac3a9a\postgres-0.10.2\src\rows.rs:241`

I'm using postgres 10.2 (10.11.11 does not compile, that's why I do not use it) together with rust 1.8.

I took a look at /types/mod.rs and saw that fromSql for String should accept Type::Varchar but somehow it fails for me. Does anybody have an idea what might go wrong with my code?

**Comment by sfackler** [comment]
Hmm, that does seem like something that should work. Could you make a little self contained example that I can build and debug?

**Comment by hypercat** [comment]
Ok, strangely, if I create a sole file just for that it works like a charm. Cannot reproduce it. I'll take a closer look at it.
