### ISSUE TITLE
Idiomatic way to store a transaction inside a struct?

### ISSUE THREAD

**Issue by ysimonson** [sfackler/rust-postgres#205]
I have a struct like so:

```rust
#[derive(Debug)]
pub struct PostgresTransaction<'a> {
	account_id: i32,
	pool: Pool<PostgresConnectionManager>,
	trans: postgres::Transaction<'a>
}

impl<'a> PostgresTransaction<'a> {
	fn new(pool: Pool<PostgresConnectionManager>, account_id: i32) -> Result<Self, SimpleError> {
		let conn = try!(pool.get());
		let trans = try!(conn.transaction());

		Ok(PostgresTransaction {
			pool: pool,
			account_id: account_id,
			trans: trans,
		})
	}
}
```

This gives me the error that `conn` does not live long enough. 

I thought I could add `conn` to the struct, so that it would own both `conn` and `trans`, but I get the same error. My understanding from asking around on #rust-beginners is that this is because `conn` cannot be moved after `trans` has been created.

If this understanding is correct, how can I allow a struct to own a transaction?

**Comment by sfackler** [comment]
You can set this up, but it'll require some amount of unsafe code: https://play.rust-lang.org/?gist=4b48994e39966fa94c3aa819beed9b5e&version=stable&backtrace=1

**Comment by ysimonson** [comment]
Great, that worked - thank you! This is the end result with r2d2 for posterity:

```rust
#[derive(Debug)]
pub struct PostgresTransaction {
	account_id: i32,
	trans: postgres::Transaction<'static>,
	conn: Box<PooledConnection<PostgresConnectionManager>>,
}

impl PostgresTransaction {
	fn new(conn: PooledConnection<PostgresConnectionManager>, account_id: i32) -> Result<Self, Error> {
		let conn = Box::new(conn);
		let trans = unsafe { mem::transmute(try!(conn.transaction())) };

		Ok(PostgresTransaction {
			account_id: account_id,
			conn: conn,
			trans: trans,
		})
	}
}
```
