### ISSUE TITLE
Serialize directly to a struct or a list of structs from a table.

### ISSUE THREAD

**Issue by cetra3** [sfackler/rust-postgres#216]
Not sure if this is implementable or not but like we can serialize/deserialize structs into json with serde and rustc_serialize, it should be possible to do this the other way.

At the moment, all examples show manually building a struct:

```rust
for row in &conn.query("SELECT id, name, data FROM person", &[]).unwrap() {
        let person = Person {
            id: row.get(0),
            name: row.get(1),
            data: row.get(2),
        };
        println!("Found person {}", person.name);
    }
```

It should be possible to cast the response directly to the struct:

i.e,
```rust
for person in &conn.query("SELECT id, name, data FROM person", &[]).decode().unwrap() {
    println!("Found person {}", person.name);
}
```

Once again not sure if this is currently possible.

**Comment by sfackler** [comment]
This is not currently supported in rust-postgres but would be relatively easy to add externally via an extension trait:

```rust
pub trait FromRow {
    fn from_row(row: &Row) -> Result<Self, Error>;
}

pub fn RowExt {
    fn decode<T: FromRow>(&self) -> Result<T, Error>;
}

impl<'a> RowExt for Row<'a> {
    fn decode<T: FromRow>(&self) -> Result<T, Error> {
        T::from_row(self)
    }
}
```

**Comment by cetra3** [comment]
Fair enough.  This sort of feature bordering on an ORM.  Would that involve implementing for each different struct you have?

**Comment by sfackler** [comment]
Yep! Each struct that you want to decode should implement `FromRow`.
