### ISSUE TITLE
How to Execute Counts

### ISSUE THREAD

**Issue by esatterwhite** [sfackler/rust-postgres#220]
I'm trying to run a single count query, but getting the value out of the result has been problematic.
I've tried `rows.get(0).get(0)` and `rows.get(0).get(<column name>)` and I usually get errors about not having enough type information in the context.

the only way I can get the value, is by iterating over the Rows struct and over ridding a variable. 
Is there a better way to do this?
```sql
   SELECT count(id)::integer as total
   FROM table
   where fk = $1
```

```rust
  let counts = conn.query(SQL, &[&FK]).unwrap();
  let mut count: i32 = 0;
  for c in counts.iter() {
    count = c.get(0);
  }
```

**Comment by sfackler** [comment]
The compiler needs to know the type of value you want it to deserialize. Something like

```rust
let count: i32 = counts.get(0).get(0);
```

**Comment by esatterwhite** [comment]
Ok, that makes sense.  Sometimes I run into a similar problem when assigning values to structs when calling `row.get()` on an integer column
```
panicked at 'error retrieving column "year": Conversion(WrongType(Int4))', /home/esatterwhite/.cargo/registry/src/github.com-1ecc6299db9ec823/postgres-0.13.1/src/rows.rs:206
```

It looks like it should convert just fine

**Comment by sfackler** [comment]
Are you trying to convert to something other than an `i32`?

**Comment by esatterwhite** [comment]
Ah, you are right. I Thought I tried most of the number types. `i32` does work. Sorry about that
