### ISSUE TITLE
Feature Request: rows_instance.iter() could retrieve data lazily?

### ISSUE THREAD

**Issue by hicqu** [sfackler/rust-postgres#221]
I'm a new-comer for rust-postgres. Does postgres::rows::Iter retrieve data from server lazily? If not, I think we need that feature. What do you think, @sfackler ?
Thanks a lot!

**Comment by sfackler** [comment]
I believe this is what you're looking for? http://sfackler.github.io/rust-postgres/doc/v0.13.2/postgres/stmt/struct.Statement.html#method.lazy_query

**Comment by hicqu** [comment]
@sfackler that's so amazing! Thank you very much!
