### ISSUE TITLE
Error compiling with-uuid

### ISSUE THREAD

**Issue by mentalbrew** [sfackler/rust-postgres#225]
Rust: rustc 1.14.0 (e8a012324 2016-12-16)
Cargo: cargo 0.15.0-nightly (298a012 2016-12-20)

A basic Cargo.toml with the following:

```
postgres = {version = "0.13.4", features=["with-uuid"]}
```

Generates the following error:
```
   Compiling postgres v0.13.4
error[E0308]: mismatched types
  --> /Users/mentalbrew/.cargo/registry/src/github.com-1ecc6299db9ec823/postgres-0.13.4/src/types/uuid.rs:24:28
   |
24 |         types::uuid_to_sql(*self.as_bytes(), w);
   |                            ^^^^^^^^^^^^^^^^ expected array of 16 elements, found slice
   |
   = note: expected type `[u8; 16]`
   = note:    found type `[u8]`

error: aborting due to previous error

error: Could not compile `postgres`.
```

Am I doing something wrong here? Any ideas?

**Comment by mentalbrew** [comment]
This may be related to a Cargo.lock issue. I blew away my Cargo.lock and ran the build again and everything worked as advertised. My apologies.

**Comment by sfackler** [comment]
Hmm, that might imply that uuid broke back compat at some point?

**Comment by mentalbrew** [comment]
I just started the project but I'm still learning Rust so I probably installed/uninstalled things randomly while I was testing things. That may have contributed to it.
