### ISSUE TITLE
tokio_postgres hides useful types

### ISSUE THREAD

**Issue by tqoitc** [sfackler/rust-postgres#226]
There are certain types such as `ToSql` which are not reexported and are difficult to create wrappers around as a result. Relevant examples in the doc are [here][1].

Similarly, the `BoxFuture` returned from `Connection::connect`'s error type is `ConnectError` which cannot be accessed to be able to tell what went wrong.

[1]: https://docs.rs/tokio-postgres/0.1.0/tokio_postgres/struct.Connection.html

**Comment by tqoitc** [comment]
Fixed by reading through `postgres-shared`'s docs. It's still not very ergonomic but it's usable.

**Comment by sfackler** [comment]
ToSql is reexported as tokio_postgres::types::ToSql
