### ISSUE TITLE
Implement Sync on Connection

### ISSUE THREAD

**Issue by giovanniberti** [sfackler/rust-postgres#229]
Would it be possible to implement Send in order to use the same Connection between different threads?

**Comment by sfackler** [comment]
Connection is already Send, but it can't be Sync - it's inherently stateful and if you have multiple threads reading/writing on the socket at the same time, it'll totally break.

You may want to use https://crates.io/crates/r2d2_postgres

**Comment by giovanniberti** [comment]
Thanks!
