### ISSUE TITLE
phf=0.7.21 not available

### ISSUE THREAD

**Issue by stianjensen** [sfackler/rust-postgres#230]
https://github.com/sfackler/rust-postgres/commit/17c53c967c4e6bc99301a53d74a556e235f60834 bumped the phf dependency to 0.7.21, but this version doesn't seem to be available. I can't currently install the master branch of rust-postgres locally now because of this.

**Comment by aleksanb** [comment]
After resolving this blocker, a new version of rust-postgres can be published!

**Comment by sfackler** [comment]
It definitely exists? https://crates.io/crates/phf

**Comment by stianjensen** [comment]
Oh, sorry. I just looked at the releases page on GitHub, my bad.

But the reason I discovered it is I tried installing the master of this repo locally, but a few rounds of `cargo update` seem to have magically fixed that.
