### ISSUE TITLE
Incompatible with Chrono 0.3

### ISSUE THREAD

**Issue by mmstick** [sfackler/rust-postgres#232]
Just a heads up that the new version of **chrono** is incompatible with this.

**Comment by sfackler** [comment]
Fixed! This will force an 0.14 so I'm going to try to fold some other cleanup into the release. It may take a couple of days.

**Comment by hammerandtongs** [comment]
@sfackler 

Building against https://github.com/sfackler/rust-postgres.git#79644f92 I'm getting 

"""the trait `postgres::types::ToSql` is not implemented for `chrono::DateTime<chrono::UTC>`"""

and

"""the trait `postgres::types::FromSql` is not implemented for `chrono::DateTime<chrono::UTC>`"""

**Comment by sfackler** [comment]
Did you enable the `with-chrono` feature? You're sure you aren't pulling in two versions of chrono?

**Comment by hammerandtongs** [comment]
:)

Thank you, it was a second version of chrono (git and crates.io). I switched to crates only and I'm good to go.

Thank you so much for this postgresql library it seems very well done and great postgresql is important for my work.

**Comment by sfackler** [comment]
Glad it's useful for you!
