### ISSUE TITLE
New cargo release

### ISSUE THREAD

**Issue by ysimonson** [sfackler/rust-postgres#235]
Hello! Could you release a new version on crates.io? I'm asking because:

* There's a [commit](https://github.com/sfackler/rust-postgres/commit/79644f9279694ca9a953b2c1825c8c54114b70eb) to add support for chrono 0.3 that's not on crates.io. Chrono 0.3 is necessary for the latest versions of serde.
* I was trying to reference `rust-postgres`'s master branch to get around this, but that caused some errors with `r2d2`/`r2d2-postgres` which wanted to reference postgres 0.13.6.

In combination, I think that means that, barring some sort of cargo.toml voodoo I'm not aware of, it's not currently possible to run postgres + serde + chrono + r2d2 on rust 1.15.1.

**Comment by sfackler** [comment]
You should be able to use the `[replace]` section of a Cargo.toml, to globally swap out the master branch for all dependencies:

```toml
[replace]
"postgres:0.13.6" = { git = "https://github.com/sfackler/rust-postgres" }
```

I was making some last cleanups and changes before an 0.14 release, but I think that's basically ready to go. I should be able to finalize it tonight.

**Comment by ysimonson** [comment]
That did it. Thanks as always @sfackler! I'll just close this out.
