### ISSUE TITLE
Inserting enum type

### ISSUE THREAD

**Issue by glennpierce** [sfackler/rust-postgres#238]
Hi I am trying to insert an enum type defined as

// CREATE TYPE tridium_status AS ENUM ('ok', 'null', 'down', 'unackedAlarm', 'fault', 'unknown');

My code is like

#[macro_use]
extern crate postgres;

use postgres::types::{Type, SessionInfo, IsNull, ToSql, FromSql};

enum Status {
    Ok,
    Null,
    Down,
    UnackedAlarm,
    Fault,
    Unknown
}

impl ToSql for Status {
     fn to_sql<W: Write+?Sized>(&self, _: &Type, mut w: &mut W, _: &SessionInfo) -> Result<IsNull> {
         let name = match *self {
             Status::Ok => b"ok",
             Status::Null => b"null",
             Status::Down => b"down",
             Status::UnackedAlarm => b"unackedAlarm",
             Status::Fault => b"fault",
             Status::Unknown => b"unknown",
         };
         try!(w.write_all(name));
         try!(w.write([0])); // I think the strings are null terminated but can't remember for sure
         Ok(IsNull::No)
    }

    to_sql_checked!();
 
}

But I get the following errors I can't seem to solve ?

use postgres::types::{Type, SessionInfo, IsNull, ToSql, FromSql};                                                                                                                  
   |                             ^^^^^^^^^^^ no `SessionInfo` in `postgres::types`

fn to_sql<W: Write+?Sized>(&self, _: &Type, mut w: &mut W, _: &SessionInfo) -> Result<IsNull> {                                                                              
    |                                                                                     ^^^^^^^^^^^^^^ expected 2 type arguments, found 1 

What am I doing wrong ?

Thanks

**Comment by glennpierce** [comment]
Things seem to have changes .

What I have so far

#[derive(Debug)]
pub enum Status {
    Ok,
    Null,
    Down,
    UnackedAlarm,
    Fault,
    Unknown
}


//fn to_sql<W: Write+?Sized>(&self, _: &Type, mut w: &mut W, _: &SessionInfo) -> Result<IsNull> {

impl ToSql for Status {
    fn to_sql(&self,
              _: &Type,
              w: &mut Vec<u8>)
              -> Result<IsNull, Box<Error + Sync + Send>> {

            let name = match *self {
                Status::Ok => b"ok",
                Status::Null => b"null",
                Status::Down => b"down",
                Status::UnackedAlarm => b"unackedAlarm",
                Status::Fault => b"fault",
                Status::Unknown => b"unknown",
            };
            try!(w.write_all(name));
            try!(w.write([0])); // I think the strings are null terminated but can't remember for sure
            Ok(IsNull::No)
    }

    accepts!(Status);

    to_sql_checked!();
}


160 |             let name = match *self {                                                                                                                                              
    |                        ^ expected an array with a fixed size of 2 elements, found one with 4 elements

match arm with an incompatible type                                                                                                                                               
   --> src/tridium_proxy.rs:162:33                                                                                                                                                      
    |                                                                                                                                                                                   
162 |                 Status::Null => b"null",                                                                                                                                          
    |                                 ^^^^^^^                                                                                                                                           
                                                                                                                                                                                        
error: no method named `write_all` found for type `&mut std::vec::Vec<u8>` in the current scope                                                                                         
   --> src/tridium_proxy.rs:168:20                                                                                                                                                      
    |                                                                                                                                                                                   
168 |             try!(w.write_all(name));

**Comment by sfackler** [comment]
I'd recommend using https://github.com/sfackler/rust-postgres-derive to generate this code for you!

**Comment by glennpierce** [comment]
Hmm in the end I used

#[macro_use]
extern crate postgres_derive;

#[derive(Debug, ToSql, FromSql)]
pub enum tridium_status {
    ok,
    null,
    down,
    unackedAlarm,
    fault,
    unknown
}

Easy!

**Comment by glennpierce** [comment]
Just saw your comment
