### ISSUE TITLE
Store chrono datetime with milliseconds

### ISSUE THREAD

**Issue by glennpierce** [sfackler/rust-postgres#239]
Hi
I'm not sure if this is an issue with rust-postgres but how can I store a dateTime or NaiveDateTime into a
timestamp with timezone column so the milliseconds  or microseconds are stored ?

Thanks

**Comment by sfackler** [comment]
Postgres stores timstamps at microsecond resolution. If you enable the `with-chrono` Cargo feature, you can use `NaiveDateTime` with `TIMESTAMP` columns and `DateTime` with `TIMESTAMPTZ` columns.

**Comment by glennpierce** [comment]
OK thanks. I thought so but I have been getting errors like

 { severity: "ERROR", parsed_severity: None, code: UniqueViolation, message: "duplicate key value violates unique constraint \"sensor_values_2017q1_ts_sensor_unq\"", detail: Some("Key (ts, sensor_id)=(2017-02-24 20:12:02+00, 598245) already exists.")

when the milliseconds are changing.

This seems like the microseconds were not being saved.

My table is defined as

Column   |           Type           |                 Modifiers                  | Storage | Stats target | Description 
-----------+--------------------------+--------------------------------------------+---------+--------------+-------------
 ts        | timestamp with time zone | not null                                   | plain   |              | 
 value     | double precision         | not null default 'NaN'::real               | plain   |              | 
 sensor_id | integer                  | not null                                   | plain   |              | 
 status    | tridium_status           | not null default 'unknown'::tridium_status | plain   |              | 


i am inserting like

let timestamp_milli = timestamp_in_milli % 1000;
let timestamp_secs = timestamp_in_milli / 1000;
let ts = NaiveDateTime::from_timestamp(timestamp_secs, timestamp_milli as u32);
let dt = DateTime::<UTC>::from_utc(ts, UTC);

let insert_values_statement = trans.prepare_cached(
                                                "INSERT INTO sensor_values(
                                                ts,
                                                value,
                                                sensor_id,
                                                status)
                                                VALUES ($1,$2,$3,$4) ON CONFLICT(ts, sensor_id) DO NOTHING").unwrap();
 insert_values_statement.execute(&[&dt, &value, &bmos_id, &tridium_status::ok]).unwrap();


I know i am constructing NaiveDateTime with milliseconds but they don't make it through to postgres.

Doing 

SELECT to_char(ts, 'YYYY-MM-DD HH:MI:SS:MS') FROM sensor_values WhERE sensor_id=598245;

always show 000 for the milliseconds.

Odd.


Thanks

**Comment by sfackler** [comment]
Ah yeah, I'm seeing the same thing - looks like a bug in the serialization logic. Will look into it.

**Comment by sfackler** [comment]
Oh, no, the serialization is correct. `NaiveDateTime::from_timestamp`'s second argument is a number of nanoseconds, not a number of milliseconds: https://docs.rs/chrono/0.3.0/chrono/naive/datetime/struct.NaiveDateTime.html#method.from_timestamp

**Comment by glennpierce** [comment]
Ah yes that did it. I shouldn't have missed that. Thanks.

**Comment by sfackler** [comment]
No problem!
