### ISSUE TITLE
keep a transaction object in a struct ?

### ISSUE THREAD

**Issue by glennpierce** [sfackler/rust-postgres#240]
Hi

Is there someway to get the same transaction object back from a connection until I commit ?
I am trying to store a transaction object in a struct to keep in in scope to achieve this.

Some background

I have a service running where I am intercepting a few mysql calls (Don't ask, It is either this or pay many thousands for a commercial developer kit). Basically calls like
 

SET autocommit=0
commit
insert .....

Are continuously sent and I process them in a loop.

After SET autocommit=0 I want to get a transaction after which a load of inserts occur. this is finally
followed by the commit where I will translate to a postgres transaction.commit;

The mysql requests are handled by implementing a PacketHandler trait as below.  

struct MySqlHandler<'a> {
    postgres_conn : Connection,
    trans : Transaction<'a>,
}

impl<'a> PacketHandler for MySqlHandler<'a> {

    fn handle_request(&mut self, p: &Packet) -> Action {

        match p.packet_type() {
            Ok(PacketType::ComQuery) => {

               // handle mysql queries
	       if sql.to_lowercase().contains("SET autocommit=0") {
                        // setup transaction
                        self.trans = self.postgres_conn.transaction().unwrap();
                        Action::Ok
                }
                else if sql.to_lowercase().contains("commit") {
                        self.trans.commit();
                        Action::Ok
                }
		else {
                       // insert with transaction
                      self.trans.execute( ...
                }

            }
    }
}

The trouble I am having is declaring the Transaction in the same struct as the connection as i am getting 
lifetime errors. 

"
 cannot infer an appropriate lifetime for autoref due to conflicting requirements
 self.trans = self.postgres_conn.transaction().unwrap();
"

Is there some way I can start a transaction and get the same transaction back from a connection on each following query until i commit ?

This maybe just my inexperience with Rust and the is a better way to organise this code.

Thanks

**Comment by sfackler** [comment]
The `Transaction` object isn't actually doing anything particularly special - just `conn.batch_execute("BEGIN")` when you construct it and `conn.batch_execute("COMMIT")` or `conn.batch_execute("ROLLBACK")` when you drop it. Your best bet is probably to just store the connection and manage the transaction yourself in the same way.

**Comment by glennpierce** [comment]
Thanks. That is useful. 
I will go that route.
