### ISSUE TITLE
When inserting a NaiveDatetime the insertion is 12 hours out

### ISSUE THREAD

**Issue by glennpierce** [sfackler/rust-postgres#241]
When inserting a NaiveDatetime the insertion is 12 hours out

Eg 

let d = NaiveDate::from_ymd(2017, 2, 25);
let t = NaiveTime::from_hms_milli(21, 45, 01, 020);

let ts = NaiveDateTime::new(d, t);
let dt = DateTime::<UTC>::from_utc(ts, UTC);

 let insert_values_statement = postgres_conn.prepare_cached(
                                                "INSERT INTO sensor_values(
                                                ts,
                                                value,
                                                sensor_id)
                                                VALUES ($1,2.0,598245) ON CONFLICT(ts, sensor_id) DO NOTHING").unwrap();
println!("inserting {}", dt);
insert_values_statement.execute(&[&dt]).unwrap();

The program prints

inserting 2017-02-25 21:45:01.020 UTC

but then looking in the db shows

SELECT to_char(MAX(ts), 'YYYY-MM-DD HH:MI:SS:MS') FROM sensor_values WHERE sensor_id=598245;
         to_char         
-------------------------
 2017-02-25 09:45:01:020

Updating seems to work

insert must past the hour in 12 hour format

**Comment by sfackler** [comment]
`TIMESTAMPTZ` values are converted into the timezone specified by the [`timezone` parameter](https://www.postgresql.org/docs/9.2/static/runtime-config-client.html#GUC-TIMEZONE). If you include the timezone in your select statement, you'll see that it is shifted off of UTC by the difference you're seeing.

**Comment by glennpierce** [comment]
ah yes sorry. not sure why I was using to_char to select in psql in the first place. Sorry
