### ISSUE TITLE
Asynchronous notification support for tokio-postgres

### ISSUE THREAD

**Issue by shanegibbs** [sfackler/rust-postgres#242]
Title says it all :wink: I couldn't see anything in the docs. Is this a planned feature? Any chance of an eta?

Thanks

**Comment by sfackler** [comment]
It'll be easy to add support - I only haven't done anything with it because I'm not sure what the API should look like.

**Comment by sfackler** [comment]
Here's a possible approach: https://github.com/sfackler/rust-postgres/pull/243

**Comment by shanegibbs** [comment]
Makes sense to me. Did you have any reservations?
