### ISSUE TITLE
Difficulty Binding Values When Updating Multiple Fields In A jsonb Column 

### ISSUE THREAD

**Issue by TheServerAsterisk** [sfackler/rust-postgres#249]
Consider the following snippet: 
```rust
pub fn update_something(field1: i64) {
  let query =  "UPDATE myschema.something
                SET
                    settings = settings || '{
                        \"field1\" : $1,
                        \"field2\" : 2,
                        \"field3\" : 3,
                    }'
                WHERE
                    uuid = 1";
  conn.execute(query, &[&field1]).unwrap();
  
}
```

I am having some difficulty figure out how to bind a value in this case. More specifically I will get the error

```
Err(Db(
     DbError{  
         severity:"ERROR",
         parsed_severity:None,
         code:SyntaxError,
         message:"syntax error at or near \"$1\"",
        detail:None,
        hint:None,
        position:Some(Normal(178)),
        where_:None,
        schema:None,
        table:None,
        column:None,
        datatype:None,
        constraint:None,
        file:Some("scan.l"),
        line:Some(1082),
        routine:Some("scanner_yyerror")
    }
))
```
I have also tried going `\"layout_id\" : '$1' to ensure it wasn't an issue of the value being caught in between two single quotes. Any suggests on how to resolve this issue?

**Comment by sfackler** [comment]
Query parameters can't be inserted into the middle of a string - it might be easiest to construct the JSON value on the client side. You can also probably string-concatenate the JSON structure together if you want to keep it in the query.

**Comment by TheServerAsterisk** [comment]
Hmm, unfortunately, the first option won't for me since this updates a subset of fields, then again I could pull the whole column down and do a diff. I will look into the string concatenate solution you suggested. I am guessing you meant something like 
```
UPDATE myschema.something
                SET
                    settings = settings || '{
                        \"field1\" :' || $1 || ',
                        \"field2\" : 2,
                        \"field3\" : 3,
                    }'
                WHERE
                    uuid = 1";
```

Then again maybe sane solution is just to refactor the table.
