### ISSUE TITLE
Support libpq defined ssl parameters

### ISSUE THREAD

**Issue by kkartaltepe** [sfackler/rust-postgres#254]
Recently took to trying to implement a simple certificate authentication with this library and it was a little troublesome to get off the ground, although I am still rather new to rust.

I know this is a rust native driver but for the sake of consistency and increased usability with people moving from other languages it should comply with parameters offered in the ODBC and JDBC postgres drivers.
https://www.postgresql.org/docs/current/static/libpq-connect.html#LIBPQ-PARAMKEYWORDS
Namely:
```
sslmode
requiressl
sslcert
sslkey
sslrootcert
sslcrl
```
~~and optionally~~

~~`sslcompression`~~

With the current feature options, `with-openssl` et al, an end user can only implement the features of `sslmode`/`requiressl` without explicitly depending on their own ssl crate. This could lead to version mismatching and multiple linkages of the chosen ssl crate. The modules to implement these should be re-exported by the `with-*` feature modules to start with and hopefully later on driver parameters would be implemented seamlessly when you chose an ssl feature.

**Comment by sfackler** [comment]
You should not be using SSL compression, ever: https://en.wikipedia.org/wiki/CRIME

libpq does its configuration that way because it forces the use of OpenSSL on all platforms. However, other SSL libraries like Security Framework or SChannel do not work in the same way. Parsing separate certificate and key files into the form you need requires some hackiness with Security Framework and is apparently theoretically possible with SChannel though I have never been able to actually make it work. They like to work with keys pulled from a system keystore.

**Comment by kkartaltepe** [comment]
I defer to your experience with non openssl interfaces, and I as much as I would like them all to be standardized to a platform agnostic format even among official drivers the acceptable format for files specified by these parameters is platform dependent (libpq vs JDBC private key format). Just providing the common options even if they require platform specific file formats would be sufficient to be consistent with the rest of the postgresql environment. If a specific platform doesnt support CA certificates outside of the system keystore then that would be a limitation on that platform that could be documented. Similarly for client certs and keys.

The smaller more accessible change i would also like to see from this issue is the rexport of the TLS module/crate for use by users. Even in the tests for this crate there is use of additional non-exported modules that are required to implement the common postgresql parameters.
```rust
fn test_require_ssl_conn() {
    use openssl::ssl::{SslMethod, SslConnectorBuilder};
    use postgres::tls::openssl::OpenSsl;
```
I imagine it's similar for the other TLS modules available. These are commonly used by everyone using self-signed certs or cert auth in postgres so it makes sense to re-export these in `postgres::tls::xxx` to support configuring these common options without introducing an explicit dependency on an TLS library that you only use for configuring `rust-postgres`.

**Comment by sfackler** [comment]
Reexporting the TLS crates in their module totally makes sense - I just pushed a commit doing that.

Check out the native-tls crate if you're interested in a platform agnostic TLS layer. A thing to note there is just how limited it is. The lowest common denominator of universally supported functionality is very small.

**Comment by kkartaltepe** [comment]
I did take a peek but didn't notice any examples of client certificates which was my requirement for identification in the first place when looking through postgres drivers. Thanks for the quick update on the module re-export.

**Comment by GreenReaper** [comment]
CRIME isn't necessarily applicable to the PostgreSQL use-case, and can be very beneficial. In any case, SSL compression is currently on by default - [the sslcompression option is only ever used to disable it](https://doxygen.postgresql.org/fe-secure-openssl_8c_source.html#l01278).

Of course if you use OpenSSL 1.1.0 it is disabled by default and won't currently work (although I'm trying to get PostgreSQL developers to address that); it also won't work if you don't compile zlib in to start with (this is the default on Debian jessie/stretch, Ubuntu 12.04+, and probably other distributions).

**Comment by sfackler** [comment]
If compression is sufficiently beneficial, I would suggest that you advocate for compression support at the Postgres protocol level - why wouldn't you want to compress unencrypted sessions as well?

More generally, TLS compression is on its way out. It's disabled by default in OpenSSL 1.1.0 as you've noted, it's been disabled in Linux distros's packages including Ubuntu, and it has been explicitly removed from TLS 1.3.
