### ISSUE TITLE
Upgrade uuid to 0.5

### ISSUE THREAD

**Issue by mentalbrew** [sfackler/rust-postgres#255]
Because UUID 0.5 now supports serde 1.0

Thanks!

**Comment by mentalbrew** [comment]
That's some wicked response time sfackler!

**Comment by mentalbrew** [comment]
Do you plan on doing a release in the near future? The r2d2_postgres is now my hold up in regards to UUID support for serde 1.0.

**Comment by sfackler** [comment]
Done!
