### ISSUE TITLE
Support the 'unknown' type

### ISSUE THREAD

**Issue by kkartaltepe** [sfackler/rust-postgres#256]
From this mail thread https://www.postgresql.org/message-id/1179.1302203983%40sss.pgh.pa.us
and some documentation on type conversion https://www.postgresql.org/docs/9.5/static/typeconv-oper.html

Unknown types can only arise from string literals or NULL literals. So it should be possible to implement conversion of these types to `Option<String>`. If it is a NULL literal instead of a string literal it is safe to represent it as a `None<T>`. Because the only unknown type literals allowable in postgres are String and NULL combined with the fact that only string types can be cast to 'unknown' this kind of conversion should be safe on the rust side.

This just a nice to have when working with queries involving literal strings or NULLs as 'unknown' type can propagate up selects, although it is unlikely to be encountered in normal database objects.

**Comment by sfackler** [comment]
Could you give an example of a query that exposes an value with an unknown type?

**Comment by kkartaltepe** [comment]
`select 'hello world'` and then try to `row.get(0)`

**Comment by kkartaltepe** [comment]
a more concrete example now that I am at a computer
```rust
for row in &conn.query("select 'hello world'", &[]).unwrap() {
	let s: String = row.get(0);
	println!("{}", s);
}
```

**Comment by sfackler** [comment]
Interestingly , the column type in `select 'hello world'` is now `text` rather than `unknown` in PostgreSQL 10.

**Comment by kkartaltepe** [comment]
Its probably better that way, I think it was mostly used for type conversion fudging.
