### ISSUE TITLE
postgres-shared v0.2.0 -> v0.2.1 has a semver breaking serde upgrade

### ISSUE THREAD

**Issue by daboross** [sfackler/rust-postgres#257]
Correct me if I've missed something, but it seems that `postgres-shared` updated serde from `0.9` to `1.0` in between v0.2.0 and v0.2.1. Any crate which depends on `postgres-shared = "^0.2"` and depends on the `ToSql` impl on serde v0.9 `serde_json::Value` will now break when `cargo update` is used (or when next downloaded, if it's a library?)

Could this possibly be corrected by yanking v0.2.1 and re-publishing as v0.3.0?

I don't personally use `postgres`, but I found this through https://www.reddit.com/r/rust/comments/698ok3/how_can_i_specify_the_version_of_an_external/ and thought it would be best to report it here. The user in question seems to have had a broken build by updating v0.2.0 to v0.2.1.

**Comment by daboross** [comment]
I can see that the commit was especially made to allow for still using `v0.9`, but as far as I'm aware cargo will make no attempt to "version match" serde to keep compatibility. As far as I can tell libraries depending on `^0.2` will break, with the only fix being to release a new version depending on `=0.2.0` if they are still bound to serde 0.9 by other packages.

**Comment by sfackler** [comment]
It's a bit of an unfortunate situation, but the large version range approach is less painful overall than taking a major version bump any time any of `bit-vec`, `chrono`, `eui48`, `geo`, `rustc-serialize`, `serde_json`, `time`, `uuid`, `openssl`, `native-tls`, `schannel`, or `security-framework` release a new major version.

**Comment by daboross** [comment]
Ah, OK.
