### ISSUE TITLE
How Can I Leverage Multiple In Clause With Unknown Length And Different Types?

### ISSUE THREAD

**Issue by TheServerAsterisk** [sfackler/rust-postgres#259]
Sorry about the awkward title. However, consider the following "query" 

```sql
SELECT
    *
FROM 
    schema.table
WHERE 
    col1 IN ($1, $2, ... $p) 
AND 
    col2 IN ($p+1, $p+2, ... $n) 
```
Where `p` is the length of  vector `a`  and `n` is the length of vector `b`. Furthermore, vector `b` has a different datatype than vector `a`. 

While I can generate the required string I am having some difficulty figuring out how to pass the vectors as `&[&ToSql]`. The only solution I can think of is to mesh the vecs as a single `Vec<Box<ToSql>>` . However, it is not clear, to me at least, whether this is the best/correct method to use. 

Any help would be appreciated.

**Comment by sfackler** [comment]
You can use the [`ANY`](https://www.postgresql.org/docs/9.6/static/functions-comparisons.html) function and store your two sets of parameters in separate slices. For example, if `col1` is an `INTEGER` and `col2` is a `VARCHAR`, you can do something like:

```rust
let col1 = &[0, 1, 2];
let col2 = &["foobar", "fizzbuzz"];

let rows = conn.query("SELECT * FROM schema.table WHERE col1 = ANY($1) AND col2 = ANY($2)", &[col1, col2])?;
```

**Comment by TheServerAsterisk** [comment]
I see, thanks.
