### ISSUE TITLE
Query doesn't return

### ISSUE THREAD

**Issue by Thomspoon** [sfackler/rust-postgres#260]
Hello, sorry if this is a simple answer. I have a connection to my local PostgreSQL db, and I'm just making simple queries:

```rust
println!("Sending query...");
let stmt = &conn.query("SELECT * FROM users", &[])?;
println!("Got response!...");
```

However, stmt never seems to return from the query. Is there something else that needs to be done?

**Comment by sfackler** [comment]
How large is the users table? You can look at Postgres itself to see if the query is still running.

**Comment by Thomspoon** [comment]
The users table is one entry... According to pg_stat_activity, the query is in idle.

**Comment by sfackler** [comment]
If you hook a debugger up, where is the thread waiting?

**Comment by Thomspoon** [comment]
Forgive me, I misread the response from pg_stat_activity. My query doesn't
seem to be making it through. How can I debug the connection?

**Comment by sfackler** [comment]
I find https://www.wireshark.org/ super helpful for that kind of thing.

**Comment by Thomspoon** [comment]
Here was the culprit, an error message.
<img width="408" alt="screen shot 2017-05-30 at 7 32 43 pm" src="https://cloud.githubusercontent.com/assets/7809144/26609636/3c41a53e-4570-11e7-8bfb-ace2ef85e58e.png">

I'm using r2d2 to manage a connection pool, and it seems that the pool didn't handle this case. I created a minimal example without r2d2, and I get a stack trace:
Running `target/debug/postgres-test`
```
thread 'main' panicked at 'called `Result::unwrap()`
 on an `Err` value: Db(DbError { severity: "ERROR",
parsed_severity: Some(Error), code: InsufficientPriv
ilege, message: "permission denied for relation user
s", detail: None, hint: None, position: None, where_
: None, schema: None, table: None, column: None, dat
atype: None, constraint: None, file: Some("aclchk.c"
), line: Some(3411), routine: Some("aclcheck_error")
 })', src/libcore/result.rs:859
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```

Does r2d2 not support error handling?

**Comment by sfackler** [comment]
What do you mean by "doesn't support error handling"? If an error is encountered in the pool, it'll get sent to the handler (the default one logs it), and the message is attached to errors coming out of `Pool::get`.

**Comment by Thomspoon** [comment]
Maybe I'm out of scope... I have the example here: https://tokio.rs/docs/getting-started/db/ up and running, but the InsufficientPrivilege error doesn't make its way to the user.

**Comment by sfackler** [comment]
Do you not see the error coming from this line?

```rust
            let conn = db.get().map_err(|e| {
                io::Error::new(io::ErrorKind::Other, format!("timeout: {}", e))
            })?;
```

**Comment by Thomspoon** [comment]
I do not see an error from that. I am testing with two users, one that has admin privileges, and one that doesn't. Both get to

`let stmt = &conn.query("SELECT * FROM users", &[])?;`

just fine, only the one with privilege actually completes.

**Comment by sfackler** [comment]
So does the server block inside of `query` forever? Can you get a stack trace of that with gdb or something like that?

**Comment by sfackler** [comment]
That doesn't look like the right thread. You can use `info threads` to list all threads and `thread N` to jump to thread `N`.

**Comment by Thomspoon** [comment]
That is the only thread currently running, the others are in a mutex lock.

**Comment by sfackler** [comment]
If nothing is inside of code in the postgres crate, then `query` has returned. If you're not hitting the line after the query, it's presumably returning that error. I would look at what's doing the error handling upstream.

**Comment by Thomspoon** [comment]
Eh, I must've not have let the thread run to completion?

```rust
Process 34899 stopped
* thread #2, stop reason = step over
    frame #0: 0x000000010001ac99 proto-backend-pg`std::panic::catch_unwind<closure,(core::result::Result<futures::poll::Async<proto_backend_
pg::Message>, std::io::error::Error>, std::panic::AssertUnwindSafe<futures::future::lazy::Lazy<closure, core::result::Result<proto_backend_p
g::Message, std::io::error::Error>>>)>(f=closure(AssertUnwindSafe<futures::future::lazy::Lazy<closure, core::result::Result<proto_backend_pg
::Message, std::io::error::Error>>>(Lazy<closure, core::result::Result<proto_backend_pg::Message, std::io::error::Error>> {
inner: First(closure(Pool<r2d2_postgres::PostgresConnectionManager>(Arc<r2d2::SharedPool<r2d2_postgres::PostgresConnectionManager>> {
ptr: Shared<alloc::arc::ArcInner<r2d2::SharedPool<r2d2_postgres::PostgresConnectionManager>>> {
pointer: NonZero<*const alloc::arc::ArcInner<r2d2::SharedPool<r2d2_postgres::PostgresConnectionManager>>>(&0x101439000),
_marker: PhantomData<alloc::arc::ArcInner<r2d2::SharedPool<r2d2_postgres::PostgresConnectionManager>>> {

}
}
})))
}))) at panic.rs:363
```

I've tested Postgres by itself, r2d2-postgres by itself, and Tokyo by itself. The only problem comes with merging the three.

**Comment by sfackler** [comment]
If you replace the Postgres code with returning an explicit error, do you see it pop up somewhere?

**Comment by Thomspoon** [comment]
No I don't... Should I post on Tokio and see if they have any ideas? I don't have this problem with just r2d2/rust-postgres itself.

**Comment by sfackler** [comment]
Yep, seems like a question for tokio/futures.
