### ISSUE TITLE
How to update MONEY value?

### ISSUE THREAD

**Issue by pgkos** [sfackler/rust-postgres#261]
Is there any way to perform an update on a column value with MONEY (or NUMERIC) type?

**Comment by sfackler** [comment]
You could define Rust types that correspond to them and implement `ToSql` and `FromSql`, or cast to and from strings - e.g. `conn.execute("UPDATE items SET price = $1::VARCHAR", &["120.99"])`.

**Comment by pgkos** [comment]
Thank you, casting works beautifully.
(I use `"UPDATE items SET price = $1::varchar::float8::numeric::money"`)
