### ISSUE TITLE
Rationale for mapping u32 to OID?

### ISSUE THREAD

**Issue by xpe** [sfackler/rust-postgres#262]
What's the rationale for mapping Rust's `u32` to PostgreSQL's [OID][oid] type?

[oid]: https://www.postgresql.org/docs/current/static/datatype-oid.html

Here are the first opening paragraphs from the PostgreSQL documentation:

> Object identifiers (OIDs) are used internally by PostgreSQL as primary keys for various system tables. OIDs are not added to user-created tables, unless WITH OIDS is specified when the table is created, or the default_with_oids configuration variable is enabled. Type oid represents an object identifier. There are also several alias types for oid: regproc, regprocedure, regoper, regoperator, regclass, regtype, regrole, regnamespace, regconfig, and regdictionary. Table 8-24 shows an overview.

> The oid type is currently implemented as an unsigned four-byte integer. Therefore, it is not large enough to provide database-wide uniqueness in large databases, or even in large individual tables. So, using a user-created table's OID column as a primary key is discouraged. OIDs are best used only for references to system tables.

> The oid type itself has few operations beyond comparison. It can be cast to integer, however, and then manipulated using the standard integer operators. (Beware of possible signed-versus-unsigned confusion if you do this.)

To me, this gives the impression that mapping `u32` to `OID` is a stretch, and possibly an unwise one that will create many follow-up problems. They seem quite different semantically. In particular, note that "The oid type is **currently implemented** as an unsigned four-byte integer" which suggests that oid is not intended to simply substitute for unsigned 32-bit integers.

Have you considered the pros and cons of:
* mapping `u32` in Rust to a signed 32-bit integer, e.g. `INT`?
* not mapping `u32` at all?

**Comment by sfackler** [comment]
Mapping to an `i32` is certainly wrong - you'd get the wrong number for anything larger than 2^31!

Changing the binary format representation of OID would break wire format compatibility, in which case there would almost certainly be larger changes folded in. If that happens, we'll deal with it when it comes.

However, that warning has been around for at least a decade, so I'm not holding my breath.
