### ISSUE TITLE
Enable Rows to be owned and sent to 'static threads

### ISSUE THREAD

**Issue by jwilm** [sfackler/rust-postgres#263]
Currently `Rows` is tied to the lifetime of `Statement` which has a borrowed `Connection`. This prevents `Rows` from being owned and sent to a `'static` thread.

The only data used by `Rows` from the `Statement` is already wrapped in an `Arc`. Solution here is to remove `Statement` and give it a clone of the `Arc<StatementInfo>`. This will remove the lifetime from `Rows` and allow it to be owned and sent to 'static thread.

`Row` should remain as a borrowed type to prevent unnecessary reference count bumps to `Arc<StatementInfo>`.

**Comment by sfackler** [comment]
I believe this can be done backwards compatibly as long as we leave the lifetime parameter (and just always use `'static`.
