### ISSUE TITLE
Add a row get_opt method that returns a result instead of an option?

### ISSUE THREAD

**Issue by TheServerAsterisk** [sfackler/rust-postgres#266]
While I certainly agree that any error returned will be unrecoverable but I would prefer the ability fail the program/task in a different manner than a panic. In my specific case, the error will be logged with slog but the iron/graphql instance will "fail" with an appropriate body alongside a 500 status code.

**Comment by jwilm** [comment]
`get_opt` returns an `Option<Result<T>>`. The optional part indicates whether the requested column is actually present. The wrapped `Result` indicates whether the column can be converted to the requested type `T`.

What part about this forces you to panic? Can't you just handle all 3 situations? Eg.

```rust
match row.get_opt(0) {
    None => /* column not present */,
    Some(Err(err)) => /* column can't be made a `T`, here's an error */,
    Some(Ok(val)) => /* success */
}
```

**Comment by TheServerAsterisk** [comment]
Oh... I totally overlooked the get_opt method the docs. My apologies.
