### ISSUE TITLE
Using prepared statements in transactions

### ISSUE THREAD

**Issue by FauxFaux** [sfackler/rust-postgres#268]
I see in #27 that it was decided not to add a way to use a prepared statement inside a transaction.

I have ended up with code that looks like the following, for which parsing might be relevantly slow:

```
let conn = connection();
for foo in long_list {
   let tran = conn.transaction();
   tran.execute("something $1;" &[&foo.a]));
   tran.execute("something else $2;" &[&foo.b]));
   tran.commit();
}
```

Is the recommendation here to use `prepare_cached` inside the loop? Or to use the `lazy_query` api? Neither seems very nice.

**Comment by sfackler** [comment]
The most straightforward option is to use https://docs.rs/postgres/0.14.2/postgres/stmt/struct.Statement.html#method.lazy_query. It might make sense to add other methods to `Transaction` to execute or make a normal query with a statement prepared outside of the transaction.

You can also use https://docs.rs/postgres/0.14.2/postgres/transaction/struct.Transaction.html#method.prepare_cached potentially.

**Comment by raine** [comment]
What happened to `prepare_cached`?

There's no trail of it being removed in repo search but it exists in earlier version on docs.rs.

**Comment by FauxFaux** [comment]
It was removed when the old synchronous crate was removed (cd2f57a), and not added when the synchronous wrapper for the tokio crate was re-created, apparently. I don't know why and don't remember this rather old issue.
