### ISSUE TITLE
In clause ?

### ISSUE THREAD

**Issue by glennpierce** [sfackler/rust-postgres#270]
I have a vector on i32 values.

How can I do a select on a table where one field is in theis vector of values.

Ie

&conn.query("SELECT id, name FROM table WHERE id in $", &ids)?

currently I just get 

for row in &conn.query(query_string, &ids)? {
    |                                              ^^^^ expected slice, found struct `std::vec::Vec`
    |
    = note: expected type `&[&postgres::types::ToSql]`
               found type `&std::vec::Vec<i32>`
    = help: here are some functions which might fulfill your needs:
            - .as_slice()

Thanks

**Comment by glennpierce** [comment]
Ok have this now

let ids_borrowed = ids.iter().map(|i| &*i as &ToSql).collect::<Vec<_>>();

 for row in &conn.query("SELECT sensor_id, ts, value FROM sensor_values WHERE sensor_id IN $1 LIMIT 10", &ids_borrowed.as_slice())? {
        println!("row: {:?}", row);
}


$1 not getting replaced though.

**Comment by sfackler** [comment]
The list after `IN` isn't part of a query that can be replaced with a parameter. You can instead use the `ANY` function:

```rust
for row in &conn.query("SELECT sensor_id, ts, value FROM sensor_values WHERE sensor_id = ANY($1) LIMIT 10", &ids_borrowed.as_slice())? {
    println!("row: {:?}", row);
}
```

**Comment by glennpierce** [comment]
Thanks. Although I get

panicked at 'expected 1 parameters but got 527  (The length of the vector)

**Comment by sfackler** [comment]
Oh right, you'll need an input slice of one array of all of the data:

```rust
for row in &conn.query("SELECT sensor_id, ts, value FROM sensor_values WHERE sensor_id = ANY($1) LIMIT 10", &[ids])? {
    println!("row: {:?}", row);
}
```

**Comment by glennpierce** [comment]
Yeah Thanks.

Final code was

for row in &conn.query("SELECT sensor_id, ts, value FROM sensor_values WHERE sensor_id = ANY($1) LIMIT 10", &[&ids])? {

}
