### ISSUE TITLE
Bumped chrono 0.4 not released

### ISSUE THREAD

**Issue by krl** [sfackler/rust-postgres#276]
Will there soon be a cargo release with the bumped 0.4? I'm stuck between dependencies at the moment.

**Comment by sfackler** [comment]
Since it's a breaking change, there are some other tweaks I want to fold in. Should be good to go sometime this weekend.

**Comment by lancecarlson** [comment]
@sfackler any update on this? :)

**Comment by sfackler** [comment]
Sorry for the long delay here - I'm working through some other API overhauls, but I think we're nearly there :)

**Comment by sfackler** [comment]
Done!
