### ISSUE TITLE
Impossible to return query-based future in tokio-postgres

### ISSUE THREAD

**Issue by djc** [sfackler/rust-postgres#277]
I'm trying to use `tokio-postgres` in my `mailsync` crate, where I want to query the database for a list of labels and then execute one future-returning function per-label (which will need to do more database work).

This is what I got so far:

```rust
fn sync_folders(ctx: Context) -> Box<Future<Item = (Context, Vec<Result<Label, ()>>), Error = io::Error>> {
    let Context { client, conn } = ctx;
    Box::new(conn.prepare("SELECT id, name, mod_seq FROM labels")
        .and_then(|(stmt, conn)| {
            let mut labels = Vec::new();
            conn.query(&stmt, &[]).for_each(|row| {
                let label = Label {
                    id: row.get(0),
                    name: row.get(1),
                    mod_seq: row.get(2),
                };
                println!("Found label {} (id = {}, mod_seq = {}", label.name, label.id, label.mod_seq);
                labels.push(Ok(label));
                Ok(())
            });
            ok((Context { client, conn }, labels))
        })
        .map_err(|e| io::Error::new(io::ErrorKind::Other, "FAIL")))
}
```

However, this fails with:

```rust
error[E0277]: the trait bound `futures_state_stream::StateStream<Error=tokio_postgres::error::Error, Item=tokio_postgres::rows::Row, State=tokio_postgres::Connection> + std::marker::Send + 'static: std::marker::Sized` is not satisfied
  --> src/main.rs:74:36
   |
74 |             conn.query(&stmt, &[]).for_each(|row| {
   |                                    ^^^^^^^^ the trait `std::marker::Sized` is not implemented for `futures_state_stream::StateStream<Error=tokio_postgres::error::Error, Item=tokio_postgres::rows::Row, State=tokio_postgres::Connection> + std::marker::Send + 'static`
   |
   = note: `futures_state_stream::StateStream<Error=tokio_postgres::error::Error, Item=tokio_postgres::rows::Row, State=tokio_postgres::Connection> + std::marker::Send + 'static` does not have a constant size known at compile-time
```

Is this expected? As you see, I am already returning a `Box` to allow returning unsized stuff, so why does it seem impossible to return query results? This also seems to be lacking in the example and there seem to be no tests at all that show anything composing across functions, so I'm wondering if there are known issues with this.

Some support would be much appreciated.

**Comment by sfackler** [comment]
This is a bad diagnostic coming from the compiler - it gets confused if there are multiple traits which provide a `for_each` method, but you haven't implemented the one that's actually applicable. It's trying to apply the implementation of `Stream` for `Box<T> where T: ?Sized + Stream`, but the return type from `query` is `Box<StateStream>`, and `StateStream` doesn't implement `Stream`.

You should be able to just add a dependency on the `futures_state_stream` crate and add a `use futures_state_stream::StateStream`.

Also remember that `for_each` is asynchronous and returns a future - the code as written won't work. `labels` is moved into the `for_each` closure and won't be accessible when you try to return it (and the work won't have been done). Instead, you may want to try `.map` to turn each row into a `Label` and then `.collect` to turn the stream of `Label`s into a future returning a `Vec<Label>`.

**Comment by djc** [comment]
Thanks a lot, that did the trick!

BTW, `StateStream` looks extremely useful from my experiments, have you discussed putting it in the `futures` crate. It could use some example code though, to show some idiomatic ways of processing the stream and getting out the `State`. Have you discussed merging it into the `futures` crate?

**Comment by sfackler** [comment]
There's an issue here: https://github.com/alexcrichton/futures-rs/issues/301
