### ISSUE TITLE
Info whether a column is nullable?

### ISSUE THREAD

**Issue by golddranks** [sfackler/rust-postgres#279]
Hi, thanks for this library! I have a question about the nullability of columns. I can inspect the types and names of columns of the returned rows. This is super helpful if I don't know the schema beforehand. However, I'm unable to find a way to check if a column is nullable or not, which is an important guarantee for converting the data to Rust types. Shouldn't the nullability be a part of the type or a feature of the column? (I guess that with DB's it's considered more of a feature of the column?) It would be helpful if the `Column` type would allow inspecting that.

**Comment by sfackler** [comment]
That information is unfortunately not sent back when you prepare a statement, but you can track it down in the `information_schema.columns` table: https://www.postgresql.org/docs/9.5/static/infoschema-columns.html.

**Comment by golddranks** [comment]
Ah, never mind about it, then. It would've been neat if that were possible. So, the protocol doesn't differentiate between nullable and and nonnullable types, meaning it's more like a constrain checked only in the end of the DBMS, right?

**Comment by sfackler** [comment]
Right - `NOT NULL` is just a constraint checked when you insert into the table.
