### ISSUE TITLE
[question] Rows to JSON

### ISSUE THREAD

**Issue by marioidival** [sfackler/rust-postgres#284]
Do I can convert a result rows to JSON?

**Comment by marioidival** [comment]
I've tried impl Serialize from serde_json, but got this error:
![2017-08-05-235757_1007x261_scrot](https://user-images.githubusercontent.com/1129263/29000162-f16fcce4-7a39-11e7-8993-667c2022a8b4.png)

**Comment by sfackler** [comment]
You can make a wrapper type around the Row and implement Serialize for that.

```rust
struct ToJson<'a>(Row<'a>);

impl<'a> Serialize for ToJson<'a> {
    ...
}
```

**Comment by marioidival** [comment]
@sfackler The wrapper work to solve this bug, but others appears... Do you can tell me how I do this? (serialize rows or row to JSON)?

**Comment by sfackler** [comment]
What do the rows look like? What do you want the JSON to look like?

**Comment by marioidival** [comment]
Basically, I want serialize results comming from Postgres. I work on [this](https://www.github.com/marioidival/goga) and I need return results as JSON.

In fast example, I want make a query on some table and return it as JSON. I could do some hardcode and run across all rows and build it, but if rust-postgres have support to serde_json, I should use it.

**Comment by marioidival** [comment]
[An example](https://github.com/marioidival/goga/blob/master/src/api/databases.rs#L5)

**Comment by sfackler** [comment]
The general way to go would be to iterate through the columns, check the type of it, deserialize to a Rust type, and then serialize that through Serde.

**Comment by marioidival** [comment]
@sfackler Oh... I didn’t want do this :thinking:

**Comment by marioidival** [comment]
But, thanks for explanation!

**Comment by marioidival** [comment]
@sfackler ID serial should be `int4` ?

**Comment by sfackler** [comment]
Yep.

**Comment by marioidival** [comment]
type conversion error: cannot convert to or from a Postgres value of type `int4` =(  I try use format!() to parse int to String, but got errors... How to this?

**Comment by sfackler** [comment]
I'm not sure I understand what you're doing exactly. An `int4` maps to `i32`, which you can then turn into a string.

**Comment by marioidival** [comment]
Basically, 4 days ago I try serialize Rows to JSON and you saw:
 `"The general way to go would be to iterate through the columns, check the type of it, deserialize to a Rust type, and then serialize that through Serde."`

Then, I iterate through rows and try do put name column and value column in a `HashMap<String, String>`. 
The weird it's, `int4` maps to `i32`, which can turn into String, but that error occurs.
`"type conversion error: cannot convert to or from a Postgres value of type int4"`

**Comment by sfackler** [comment]
```rust
let mut map = HashMap::new();
for (idx, column) in row.columns().enumerate() {
    let value = match column.type_() {
        INT4 => row.get::<_, i32>(idx).to_string(),
        INT8 => row.get::<_, i64>(idx).to_string(),
        TEXT | VARCHAR => row.get::<_, String>(idx),
        // ...
    };
    map.insert(column.name().to_string(), value);
}
```

**Comment by jwdeitch** [comment]
I hate to point out an obvious, but have you considered `json_agg()` in your statement?

**Comment by marioidival** [comment]
@jwdeitch I dont try this yet. I have plan to use json_agg in future as result.

**Comment by brandonros** [comment]
Would it be considered bad practice to prefer to use json_agg and doing the conversion to JSON in the database instead of the client Rust app?

**Comment by andre1sk** [comment]
@brandonros  in general yes since it's not trivial to scale Postgres horizontally but the answer obviously depends on your particular workload

**Comment by JeanMertz** [comment]
I came across this thread while looking into why this library doesn't implement more deserialization options to go from a `postgres::types::Type` to a `serde_json::Value`?

Right now, only `JSON` and `JSONB` are supported, but `Value` [can represent any type that's supported by JSON](https://docs.serde.rs/serde_json/value/enum.Value.html). So basically anything for which [`Into<Value>`](https://docs.serde.rs/serde_json/value/enum.Value.html#implementations) is implemented, including all the `Option<Value>`, `Vec<Value>` and `Map<String, Value>` combinations.

As you mentioned @sfackler I can do the conversions myself, but it makes it more error prone and more verbose.

**Comment by Paxa** [comment]
We can solve this by generating json in postgres:
```rust
let res = conn.query("SELECT COALESCE(json_agg(requests), '[]'::json)::text as json_rows \
                      FROM my_table where col1 = $1",
                      &[&aaa]).unwrap();

let json_rows: String = res.get(0).get("json_rows");
```

Also can make custom serializer for rustc_serialize, but postgres has too many types https://docs.rs/postgres/0.15.2/postgres/types/index.html

**Comment by Venryx** [comment]
This doesn't cover all the types, but this is what I use:
```rust
pub fn postgres_row_to_json_value(row: Row) -> Result<JSONValue, anyhow::Error> {
    let row_data = postgres_row_to_row_data(row)?;
    Ok(JSONValue::Object(row_data))
}

// some type-aliases I use in my project
pub type JSONValue = serde_json::Value;
pub type RowData = Map<String, JSONValue>;

pub fn postgres_row_to_row_data(row: Row) -> Result<RowData, anyhow::Error> {
    let mut result: Map<String, JSONValue> = Map::new();
    for (i, column) in row.columns().iter().enumerate() {
        let name = column.name();
        let json_value = pg_cell_to_json_value(&row, column, i)?;
        result.insert(name.to_string(), json_value);
    }
    Ok(result)
}

pub fn pg_cell_to_json_value(row: &Row, column: &Column, column_i: usize) -> Result<JSONValue, anyhow::Error> {
    let column_type = column.type_();
    Ok(match *column.type_() {
        Type::BOOL =>
            row.get::<_, Option<bool>>(column_i).map_or(JSONValue::Null, |a| JSONValue::Bool(a)),
        Type::INT8 =>
            row.get::<_, Option<i64>>(column_i).map_or(JSONValue::Null, |a| JSONValue::Number(serde_json::Number::from(a))),
        Type::FLOAT8 => match row.get::<_, Option<f64>>(column_i) {
            Some(val) => JSONValue::Number(serde_json::Number::from_str(&val.to_string())?),
            None => JSONValue::Null,
        },
        Type::TEXT =>
            row.get::<_, Option<String>>(column_i).map_or(JSONValue::Null, |a| JSONValue::String(a)),
        Type::JSON | Type::JSONB =>
            row.get::<_, Option<JSONValue>>(column_i).unwrap_or(JSONValue::Null),
        _ => anyhow::bail!("Cannot convert pg-cell \"{}\" of type \"{}\" to a JSONValue.", column.name(), column_type.name()),
    })
}
```

**Comment by Venryx** [comment]
This doesn't cover all the types, but this is what I use:
```rust
pub fn postgres_row_to_json_value(row: Row) -> Result<JSONValue, anyhow::Error> {
    let row_data = postgres_row_to_row_data(row)?;
    Ok(JSONValue::Object(row_data))
}

// some type-aliases I use in my project
pub type JSONValue = serde_json::Value;
pub type RowData = Map<String, JSONValue>;

pub fn postgres_row_to_row_data(row: Row) -> Result<RowData, anyhow::Error> {
    let mut result: Map<String, JSONValue> = Map::new();
    for (i, column) in row.columns().iter().enumerate() {
        let name = column.name();
        let json_value = pg_cell_to_json_value(&row, column, i)?;
        result.insert(name.to_string(), json_value);
    }
    Ok(result)
}

pub fn pg_cell_to_json_value(row: &Row, column: &Column, column_i: usize) -> Result<JSONValue, Error> {
    let f64_to_json_number = |raw_val: f64| -> Result<JSONValue, Error> {
        let temp = serde_json::Number::from_f64(raw_val.into()).ok_or(anyhow!("invalid json-float"))?;
        Ok(JSONValue::Number(temp))
    };
    Ok(match *column.type_() {
        // for rust-postgres <> postgres type-mappings: https://docs.rs/postgres/latest/postgres/types/trait.FromSql.html#types
        // for postgres types: https://www.postgresql.org/docs/7.4/datatype.html#DATATYPE-TABLE

        // basics
        Type::BOOL => get_basic(row, column, column_i, |a: bool| Ok(JSONValue::Bool(a)))?,
        Type::INT2 => get_basic(row, column, column_i, |a: i16| Ok(JSONValue::Number(serde_json::Number::from(a))))?,
        Type::INT4 => get_basic(row, column, column_i, |a: i32| Ok(JSONValue::Number(serde_json::Number::from(a))))?,
        Type::INT8 => get_basic(row, column, column_i, |a: i64| Ok(JSONValue::Number(serde_json::Number::from(a))))?,
        Type::TEXT | Type::VARCHAR => get_basic(row, column, column_i, |a: String| Ok(JSONValue::String(a)))?,
        Type::JSON | Type::JSONB => get_basic(row, column, column_i, |a: JSONValue| Ok(a))?,
        Type::FLOAT4 => get_basic(row, column, column_i, |a: f32| Ok(f64_to_json_number(a.into())?))?,
        Type::FLOAT8 => get_basic(row, column, column_i, |a: f64| Ok(f64_to_json_number(a)?))?,

        // array types
        Type::BOOL_ARRAY => get_array(row, column, column_i, |a: bool| Ok(JSONValue::Bool(a)))?,
        Type::INT2_ARRAY => get_array(row, column, column_i, |a: i16| Ok(JSONValue::Number(serde_json::Number::from(a))))?,
        Type::INT4_ARRAY => get_array(row, column, column_i, |a: i32| Ok(JSONValue::Number(serde_json::Number::from(a))))?,
        Type::INT8_ARRAY => get_array(row, column, column_i, |a: i64| Ok(JSONValue::Number(serde_json::Number::from(a))))?,
        Type::TEXT_ARRAY => get_array(row, column, column_i, |a: String| Ok(JSONValue::String(a)))?,
        Type::JSON_ARRAY | Type::JSONB_ARRAY => get_array(row, column, column_i, |a: JSONValue| Ok(a))?,
        Type::FLOAT4_ARRAY => get_array(row, column, column_i, |a: f32| Ok(f64_to_json_number(a.into())?))?,
        Type::FLOAT8_ARRAY => get_array(row, column, column_i, |a: f64| Ok(f64_to_json_number(a)?))?,

        _ => bail!("Cannot convert pg-cell \"{}\" of type \"{}\" to a JSONValue.", column.name(), column.type_().name()),
    })
}

fn get_basic<'a, T: FromSql<'a>>(row: &'a Row, column: &Column, column_i: usize, val_to_json_val: impl Fn(T) -> Result<JSONValue, Error>) -> Result<JSONValue, Error> {
    let raw_val = row.try_get::<_, Option<T>>(column_i).with_context(|| format!("column_name:{}", column.name()))?;
    raw_val.map_or(Ok(JSONValue::Null), val_to_json_val)
}
fn get_array<'a, T: FromSql<'a>>(row: &'a Row, column: &Column, column_i: usize, val_to_json_val: impl Fn(T) -> Result<JSONValue, Error>) -> Result<JSONValue, Error> {
    let raw_val_array = row.try_get::<_, Option<Vec<T>>>(column_i).with_context(|| format!("column_name:{}", column.name()))?;
    Ok(match raw_val_array {
        Some(val_array) => {
            let mut result = vec![];
            for val in val_array {
                result.push(val_to_json_val(val)?);
            }
            JSONValue::Array(result)
        },
        None => JSONValue::Null,
    })
}
```

I'm currently using the above in my project, and it's working well. (though I haven't tried all of the types yet)

@sfackler Would you be interested in a pull-request to add something like the above to `tokio-postgres`? (it could be behind a feature gate perhaps)

**Comment by Venryx** [comment]
> @Venryx any idea to parse ENUM to Json?

Sorry no, I'm not using enums at the moment.

A quick search suggests hard-coding the translation for enum values: https://www.antoniodiaz.me/en/blog/7

That's not ideal of course, so if someone knows a better way, please mention. (eg. getting the name of the enum from the query results somehow, mapping that to a list of enum types, then automatically finding the matching enum value)
