### ISSUE TITLE
example of error handling ? (for example "duplicate key")

### ISSUE THREAD

**Issue by allan-simon** [sfackler/rust-postgres#285]
Hello big thanks for the library, especially a full-rust client, it's not an easy task :)

What I'm currently missing is an example showing me how to do deal cleanly (without just a "unwrap" or "expect)  with erros , more specifically the "duplicate key" error.

it seems like i need to deal with  this https://docs.rs/postgres/0.15.1/postgres/error/struct.SqlState.html  but as I'm not really proficient yet in rust I have some trouble making it works.

would it possible to have some example in the documentation on how to deal with it ?

**Comment by sfackler** [comment]
Sure - there's some code internal to postgres itself that should be a good example of doing that kind of thing: https://github.com/sfackler/rust-postgres/blob/master/postgres/src/lib.rs#L754. You can call `.code()` on a Postgres Error and it'll return an `Option<&SqlState>` which you can compare against.

**Comment by allan-simon** [comment]
wow that's some fast answer here ^^ is it because it's rust so it's faster ? :P i'm looking into it right now, thanks

**Comment by sfackler** [comment]
No problem! There are constants defined in the error module for all of the defined SqlStates, btw: https://docs.rs/postgres/0.15.1/postgres/error/index.html#constants

**Comment by allan-simon** [comment]
yep exactly what i needed

```rust
      let rows = match result {                                                                                                                                                    
          Ok(rows) => rows,                                                                                                                                                        
          Err(ref e) => {                                                                                                                                                          
              if e.code() == Some(&UNIQUE_VIOLATION) {                                                                                                                             
                  panic!("sentence already exists");                                                                                                                               
              }                                                                                                                                                                    
              panic!(format!("{}", e));                                                                                                                                            
          }           
     };    
```

**Comment by allan-simon** [comment]
thanks
