### ISSUE TITLE
How to get serial id?

### ISSUE THREAD

**Issue by krircc** [sfackler/rust-postgres#288]
when i insert data to a table I want get the table's serial id. the sql is : 
```sql
INSERT INTO comment (id, aid, uid, content, createtime) VALUES (20, 1, 1, 'ok, good', '2017-07-23 23:41:45.672805609 +08:00') RETURNING id;
```
i get the serial id is 20.
when code is : 
```rust
conn.execute("INSERT INTO comment (aid, uid, content, createtime) VALUES ($1, $2, $3, $4) RETURNING id", &[&aid, &uid, &content, &createtime]).unwrap();
```
can't get serial id, so how How to get serial id use postgres crate? 
sorroy i'm now not very Familiar with this crate , but i want to learn more.

**Comment by sfackler** [comment]
Use query instead. A single row with the ID will be returned.

**Comment by krircc** [comment]
@sfackler ok that's a idea, so the query Statement is more power . :+1:
