### ISSUE TITLE
Do parameter bindings work in Connection::query?

### ISSUE THREAD

**Issue by bluejekyll** [sfackler/rust-postgres#291]
The docs show parameter bindings in `query` and `execute` methods. I've been getting an error when doing that:

```rust
stmt.query("SELECT 1 FROM pg_database WHERE datname=$1", &[&db_name])
```

Produces an error:

```console
Error(
    Db(
        DbError {
            severity: "ERROR",
            parsed_severity: Some(
                Error
            ),
            code: SqlState(
                "26000"
            ),
            message: "unnamed prepared statement does not exist",
            detail: None,
            hint: None,
            position: None,
            where_: None,
            schema: None,
            table: None,
            column: None,
            datatype: None,
            constraint: None,
            file: Some(
                "postgres.c"
            ),
            line: Some(
                1626
            ),
            routine: Some(
                "exec_bind_message"
            )
        }
    )
)
```

whereas a prepared stmt is fine:

```rust
let stmt = conn.prepare_cached("SELECT 1 FROM pg_database WHERE datname=$1")?;
stmt.query(&[&db_name])
```

Working around this with prepared statements, just wondering why I'm getting the error in the unprepared `query`.

**Comment by sfackler** [comment]
That definitely shouldn't be happening! Do you have a self contained example that runs into this?

**Comment by bluejekyll** [comment]
I can try to put one together, in a little bit. I'm willing to believe this is my setup as this seems like something others would have reported. I'm using default conn parameters, nothing crazy. (though we are using a customized version of postgres, so that throws a variable into the mix).

I'll try and repro on a vanilla postgres install in a little bit.

**Comment by sfackler** [comment]
Cool. The non-prepared query and execute methods use the special Postgres "unnamed prepared statement": https://www.postgresql.org/docs/10/static/protocol-flow.html to avoid having to spend an extra round trip closing the statement. It could be that your custom stuff is messing with that?

**Comment by bluejekyll** [comment]
Totally. I'll ping our team on that...

**Comment by bluejekyll** [comment]
I'm closing this, it's an internal problem. Thanks for the pointer @sfackler !
