### ISSUE TITLE
postgresql:// instead of postgres:// in connection URI

### ISSUE THREAD

**Issue by pka** [sfackler/rust-postgres#293]
According to https://www.postgresql.org/docs/current/static/libpq-connect.html#AEN45575, connection URI start with `postgresql://`. rust-postgres mostly uses `postgres://`, but both seem to work. Shouldn't rust-postgres also use `postgresql://`, at least in the documentation?

**Comment by sfackler** [comment]
Sure - we don't check what scheme the URL contains in the library itself - you could use `http://` and it's still work :)

**Comment by pka** [comment]
Ups, just read "The URI scheme designator can be either postgresql:// or postgres://". So using `postgres://` is correct. But the PostgreSQL docu seems to prefer `postgresql://`
