### ISSUE TITLE
Release tokio-postgres version with same -shared version as rust-postgres

### ISSUE THREAD

**Issue by djc** [sfackler/rust-postgres#294]
I have a crate where I'm using both tokio-postgres and rust-postgres for various reasons. However, I've run into problems when using the `ToSql` impl for `chrono`. I can't find the rust issue for this now, but with the currently releases rust-postgres pulling in a different version of postgres-shared than tokio-postgres, rustc ends up finding multiple ToSql implementations for chrono types, and is then unable to select any.

An easy fix would appear to be to just release a new version of tokio-postgres with the bumped dependency (which has been there for a while). Is that feasible/easy?

**Comment by sfackler** [comment]
Yeah, sorry, the tokio-postgres update fell way behind the postgres update. I just need to update it to take the new version of futures-state-stream and then we should be good to go I think.

**Comment by sfackler** [comment]
Published 0.3.0
