### ISSUE TITLE
lazy_query example

### ISSUE THREAD

**Issue by stepankuzmin** [sfackler/rust-postgres#298]
Hi there! I want to stream a large set of rows from a database. I didn't find any examples of `lazy_query` and tried to do it like this:

```rust
let query = format!("select row_to_json({1}) from {0}.{1}", schema, table);

let trans = conn.transaction().unwrap();
let stmt = trans.prepare(&query).unwrap();
let result = stmt.lazy_query(&trans, &[], 2);

for rows in result {
    println!("row: {:?}", rows);
}
```

I'm getting `LazyRows { name: "s0p0", row_limit: 2, remaining_rows: 2, more_rows: true }` as result. So how can I get rows from `LazyRows`?

**Comment by sfackler** [comment]
You're missing an `.unwrap()` on the `lazy_query` call. Rather than iterating over the rows, you're iterating over the `Ok` value of the `Result<LazyRows, Error>`.

**Comment by stepankuzmin** [comment]
Thanks for reply, @sfackler! I've tried 

```rust
let result = stmt.lazy_query(&trans, &[], 2).unwrap();

for rows in result {
    println!("row: {:?}", rows);
}
```

But the compiler says, that the trait `Iterator` is not implemented for `LazyRows`:

```shell
41 | /     for rows in result {
42 | |         println!("row: {:?}", rows);
43 | |     }
   | |_____^ `postgres::rows::LazyRows<'_, '_>` is not an iterator; maybe try calling `.iter()` or a similar method
   |
   = help: the trait `std::iter::Iterator` is not implemented for `postgres::rows::LazyRows<'_, '_>`
   = note: required by `std::iter::IntoIterator::into_iter`
```

**Comment by sfackler** [comment]
Ah right - the other bit here is that `LazyRows` implements the [`FallibleIterator`](https://docs.rs/fallible-iterator/0.1.3/fallible_iterator/trait.FallibleIterator.html) rather than the normal `Iterator` trait.

This should do what you want:

```rust
extern crate fallible_iterator;

use fallible_iterator::FallibleIterator;

let trans = conn.transaction().unwrap();
let stmt = trans.prepare(&query).unwrap();
let mut result = stmt.lazy_query(&trans, &[], 2).unwrap();

while let Some(row) = result.next().unwrap() {
    println!("row: {:?}", row);
}
```

**Comment by sfackler** [comment]
I've added an example to the documentation to make this less confusing: https://github.com/sfackler/rust-postgres/commit/89d39cc5abe4d5d269d6bcbe54886320d54c9d89.

**Comment by stepankuzmin** [comment]
Great! Thanks!

**Comment by stepankuzmin** [comment]
One more question: In the example above I'm querying 4k rows, but the body of while loop is only called once. It seems, that `row_limit` does not affect query.

**Comment by sfackler** [comment]
The row limit doesn't affect the user-visible access to the rows, it just controls the batch size that those rows are loaded from the database. Loading rows in batches of 1 or batches of 4K will behave the same way when looping (other than 1 row per batch probably being a lost slower!).

**Comment by stepankuzmin** [comment]
Wow, thanks! That's clear for me now.
