### ISSUE TITLE
Example to print every notification in separate task

### ISSUE THREAD

**Issue by grotsev** [sfackler/rust-postgres#301]
I try to spawn Task for every notification, for instance, to concurrently println them.

In your example test only first notification is consumed.
https://github.com/sfackler/rust-postgres/blob/89d39cc5abe4d5d269d6bcbe54886320d54c9d89/tokio-postgres/src/test.rs#L476

I'm quite new in tokio and its documention has not example for https://docs.rs/futures/0.1/futures/stream/trait.Stream.html#method.into_future
Can your add test case to asynchronously consume all notifications? Or say some thoughts how to spawn and pass Notifications.into_inner() Connection through the Future?

My try is
```rust
extern crate tokio_postgres;
extern crate tokio_core;
extern crate futures;

use tokio_postgres::{Connection, TlsMode};
use tokio_core::reactor::Core;
use futures::{Future, Stream};

fn main() {
    let mut l = Core::new().unwrap();
    let handle = &l.handle();

    let done = Connection::connect(
        "postgres://postgres:111@172.17.0.2:5432",
        TlsMode::None,
        &handle,
    ).then(|c| c.unwrap().batch_execute("LISTEN test_notifications"))
        .and_then(|c| {
            c.notifications().for_each(|n| {
                let serve_one = futures::future::ok(println!("{:?}", n.channel));
                handle.spawn(serve_one);
                Ok(())
            })
        });

    l.run(done).unwrap();
}
```

but it gives error
```
error[E0271]: type mismatch resolving `<futures::stream::ForEach<tokio_postgres::Notifications, [closure@main.rs:19:40: 23:14 handle:_], std::result::Result<(), tokio_postgres::Error>> as futures::IntoFuture>::Error == (tokio_postgres::Error, tokio_postgres::Connection)`
  --> main.rs:18:10
   |
18 |         .and_then(|c| {
   |          ^^^^^^^^ expected struct `tokio_postgres::Error`, found tuple
   |
   = note: expected type `tokio_postgres::Error`
              found type `(tokio_postgres::Error, tokio_postgres::Connection)`
```

**Comment by sfackler** [comment]
Oops - I forgot to update the `Error` type of `Notifications` from `Error` to `(Error, Connection)` to match with everything else. It should compile if you instead do `c.unwrap().batch_execute("LISTEN test_notifications").map_err(|(e, _)| e)`.

Unrelated to that, but your `serve_one` future does nothing.

**Comment by grotsev** [comment]
Thanks @sfackler it's work. Moreover `serve_one` prints notifications sended from psql! What do you mean it does nothing?

**Comment by sfackler** [comment]
The body of the for_each is printing the channel, and then creating and spawning a task that immediately returns `()`.
