### ISSUE TITLE
Notifications and statements through the same connection

### ISSUE THREAD

**Issue by grotsev** [sfackler/rust-postgres#302]
```rust
connection.notifications().for_each(|n| ... )
```
consumes connection.

Is there any way to get notifications and execute statements on the same connection? Or I have to open second one.

**Comment by sfackler** [comment]
You can turn the Notifications stream back into a Connection with [into_inner](https://docs.rs/tokio-postgres/0.3.0/tokio_postgres/struct.Notifications.html#method.into_inner), but that's probably not all that easy to work with.

Not sure what a better API would be - it seems like it'd be nice if `notifications()` took `&self` so you could work with it and the main connection at the same time, but that'd require a SPMC channel.
