### ISSUE TITLE
Tokio-postgres general question

### ISSUE THREAD

**Issue by madmaxio** [sfackler/rust-postgres#308]
Hello, can you please give an overview when should rust-postgres be used and when tokio-postgres? What fit which use-case, and what are use-cases for tokio-postgres and maybe some common pitfalls with it?

**Comment by sfackler** [comment]
I think it's generally going to be dictated by the rest of the thing you're building. If it operates in a normal blocking mode then use rust-postgres, if it uses tokio, then use tokio-postgres. In general, rust-postgres is probably going to be a bit simpler to use, and is also a bit more featureful.

**Comment by madmaxio** [comment]
Thx.
