### ISSUE TITLE
query and execute function. First parameter as variable

### ISSUE THREAD

**Issue by loothood** [sfackler/rust-postgres#314]
Hi. The code:
`let query = "SELECT datname FROM pg_database WHERE datname = '$1'";`
`let database_name = "myDataBase";`
`conn.query(query, &[&database_name]);`

But there is a panic:
`thread main panicked at 'expected 0 parameters but got 1'`
I know that I can use:
`conn.query("SELECT datname FROM pg_database WHERE datname = '$1'", &[&database_name])`
But this format does not suit me.
Also I can use:
`let database_name = "myDataBase"`
`let query = format!("SELECT datname FROM pg_database WHERE datname = '{}'", database_name)`
`conn.query(query, &[])`
But I can't understand why I can't use &[&parameter] format if this format exists.
 Is any ways to store queries to database with variables in separate variables?

**Comment by sfackler** [comment]
This library has no way of knowing if the query string passed to it was bound to a variable or not.

`'$1'` is a string that happens to contain the characters `$` and `1`. You want `SELECT datname FROM pg_database WHERE datname = $1`.

**Comment by loothood** [comment]
I get it. thank you!
