### ISSUE TITLE
After adding the `with-geo` feature `ToSql` is still not implemented for `geo::Point<f64>`

### ISSUE THREAD

**Issue by chinedufn** [sfackler/rust-postgres#317]
Hey!

Trying to work with `Point`s in postgres via the `with-geo` feature but running into a bit of trouble. Apologies if I'm missing anything obvious.

Here's how to reproduce this - https://github.com/chinedufn/rust-postgres-geo-failed-build

I've tried to include all relevant information below but please do let me know if I'm missing any useful info!

Thanks!

---

Error:

```sh
   Compiling point v0.1.0 (file:///Users/chinedufn/Development/learning/rust/point)
error[E0277]: the trait bound `geo::Point<f64>: postgres::types::ToSql` is not satisfied
  --> src/main.rs:21:11
   |
21 |         &[&location, &1]
   |           ^^^^^^^^^ the trait `postgres::types::ToSql` is not implemented for `geo::Point<f64>`
   |
   = note: required for the cast to the object type `postgres::types::ToSql`

error: aborting due to previous error
```

To reproduce:

```sh
git clone https://github.com/chinedufn/rust-postgres-geo-failed-build
cd rust-postgres-geo-failed-build
cargo build
```

Version info:

```sh
$ rustc --version
rustc 1.24.0-nightly (edbd7d232 2017-12-20)
$ cargo --version
cargo 0.25.0-nightly (930f9d949 2017-12-05)
```

**Comment by sfackler** [comment]
You're using geo 0.6, but postgres uses geo 0.4.

**Comment by chinedufn** [comment]
Thank you so much - I'll give that a try.

Mind if I update the docs to call out that `geo 0.4` is required?

**Comment by sfackler** [comment]
Sure - we should probably do the same for the other similar crates as well.

**Comment by chinedufn** [comment]
Rust noob here - how can I figure out which versions of the other optional crates are required?

Once I know that I'm happy to update the others.

**Comment by sfackler** [comment]
They're listed over here: https://github.com/sfackler/rust-postgres/blob/master/postgres-shared/Cargo.toml#L25-L32

**Comment by chinedufn** [comment]
Thanks again - closing this and opened a PR - https://github.com/sfackler/rust-postgres/pull/318
