### ISSUE TITLE
select with hstore column.

### ISSUE THREAD

**Issue by glennpierce** [sfackler/rust-postgres#323]
How can I get a hstore value ?

I can see the type mapping is HashMap<String, Option<String>>

When I do something like

"SELECT id, name, namespace, description, additional_info FROM sensors

Where additional_info is a hstore. I get the error

no binary output function available for type hstore

I can't find any samples with a google search.

Thanks

**Comment by sfackler** [comment]
That's strange. What version of Postgres are you using? We have a test for hstore parameters, so it should work minimally on Postgres 9 and 10: https://github.com/sfackler/rust-postgres/blob/792d7bf374b5b12ae58a43074c51c7f1d5b39ace/postgres/tests/types/mod.rs#L256.

**Comment by glennpierce** [comment]
9.5.5

**Comment by sfackler** [comment]
What does this query return for you? You may have an out of date version of the hstore extension or something?

```
postgres=# select typsend from pg_type where typname = 'hstore';
   typsend
-------------
 hstore_send
(1 row)
```

**Comment by glennpierce** [comment]
It returns 
typsend
-------------
-
(1 row)

**Comment by glennpierce** [comment]
select * from pg_available_extensions WHERE name like '%hstore%' returns

"hstore_plperlu";"1.0";"";"transform between hstore and plperlu"
"hstore_plpython2u";"1.0";"";"transform between hstore and plpython2u"
"hstore_plpython3u";"1.0";"";"transform between hstore and plpython3u"
"hstore";"1.3";"";"data type for storing sets of (key, value) pairs"
"hstore_plpythonu";"1.0";"";"transform between hstore and plpythonu"
"hstore_plperl";"1.0";"";"transform between hstore and plperl"

**Comment by sfackler** [comment]
Does `ALTER EXTENSION hstore UPDATE` do anything? Not sure I can help much more beyond that. Something's weird with your database's hstore configuration.

**Comment by glennpierce** [comment]
Weird it gives

ALTER EXTENSION hstore UPDATE

ERROR:  extension "hstore" does not exist

********** Error **********

ERROR: extension "hstore" does not exist
SQL state: 42704


However if I do

CREATE EXTENSION hstore;

I get

ERROR:  type "hstore" already exists

********** Error **********

ERROR: type "hstore" already exists
SQL state: 42710

**Comment by glennpierce** [comment]
I will play around with the config later. Like you said must be my config. Its not an important db so I can start over, with a new db.

Thanks
