### ISSUE TITLE
Implement accepts for a (rust) enum type

### ISSUE THREAD

**Issue by mleduque** [sfackler/rust-postgres#328]
I have a rust type that looks like
```
enum MyType {
  MyString(String),
  MyNumber(u32),
  MyVec(Vec<f64>),  
  MyVecVec(Vec<Vec<f64>>),
}
```
I had implemented accept like this because I couldn't find any documentation on what it does or what the Type and Kind types do :
```
    fn accepts(_ty: &Type) -> bool {
        true
    }
```
It worked until I added the double vec. Then I got some panics
```
thread 'main' panicked at 'expected array type'
```

I suspect I should return different values for accept based on the actual enum instance, but how do I do that ?

**Comment by sfackler** [comment]
Is this in ToSql? You can call `to_sql_checked` on your underlying type to make sure the types are compatible:

```rust
fn to_sql(&self, ty: &Type, out: &mut Vec<u8>) -> Result<IsNull, Box<Error + Sync + Send>> {
    match *self {
        MyType::MyString(ref s) => s.to_sql_checked(ty, out),
        ...
    }
}
```

**Comment by mleduque** [comment]
Yes it's ToSql.
I hadn't thought of that, thanks.

2018-03-09 18:29 GMT+01:00 Steven Fackler <notifications@github.com>:
