### ISSUE TITLE
Query fails in redshift.

### ISSUE THREAD

**Issue by glennpierce** [sfackler/rust-postgres#330]
Hi

I have some code of a simple query

`let results : postgres::Result<Rows> = self.conn.query("SELECT id, name FROM sensors WHERE id = ANY($1)", &[&sensor_ids]);
`

where 

`sensor_ids is sensor_ids : Vec<i32>`

This works fine against my local postgres db (9.5)

I am now trying to move to redshift but I get the error

`Err(Error(Db(DbError { severity: "ERROR", parsed_severity: None, code: SqlState("22P03"), message: "invalid array flags", detail: None, hint: None, position: None, where_: None, schema: None, table: None, column: None, datatype: None, constraint: None, file: Some("/home/ec2-user/padb/src/pg/src/backend/utils/adt/arrayfuncs.c"), line: Some(1174), routine: Some("array_recv") })))
`
Any idea what this could be ?

PS.

If I query through my ide
SELECT id, name FROM sensors WHERE id = ANY(ARRAY[596304,597992,610978,597998])

It works

Thanks

**Comment by sfackler** [comment]
It looks like Redshift is looking for a `Vec<i64>` instead of a `Vec<i32>` for the parameter.

**Comment by glennpierce** [comment]
Even though the column in a integer which according to the docs is
INTEGER, INT, or INT4  ?

**Comment by sfackler** [comment]
Oh wait, I was responding to the initial error of `Err(Error(Conversion(WrongType(Type(Int8Array)))))`. What changed to go from that error to the "invalid array flags" one?

**Comment by glennpierce** [comment]
I had the column as biginteger so I changed it to integer which it should have been. Sorry I should have maybe created another issue.

**Comment by sfackler** [comment]
The Redshift docs claim that arrays aren't supported at all, but I'm not sure why a query using them would fail in that way: https://docs.aws.amazon.com/redshift/latest/dg/c_unsupported-postgresql-datatypes.html.

**Comment by glennpierce** [comment]
That's weird as I can issue
SELECT id, name FROM sensors WHERE id = ANY(ARRAY[596304,597992,610978,597998]) from my database ide and it works fine.

Also I am using ANY here as I don't think the IN clause works with rust-postgres ?

**Comment by sfackler** [comment]
It works just fine - it just takes a sequence of separate values rather than an array of values.

One possibility is that Redshift is forked off of Postgres 8.1 or older, where they didn't support null array elements (support was added in 2005!). We should be able to make this work by only setting the null flag if there are actually null values.

**Comment by glennpierce** [comment]
I have tried the IN clause now as well. (hacked as a single str)

ie
`let results : postgres::Result<Rows> = conn.query("SELECT id, name FROM sensors WHERE id IN (596304,597992,610978,597998)", &[]);`

From rust-postgres I get the same error of invalid array flags

**Comment by sfackler** [comment]
If that exact query generates that error, then that seems like a bug on the Redshift side of things. We're not producing any arrays in that case, we're just sending a string to Redshift.

**Comment by glennpierce** [comment]
Odd. If I copy and paste that query into my ide (datagrip) it works fine.
I must be doing something silly in the code then.

**Comment by glennpierce** [comment]
Out of curiosity is there away to pass an array to a sequence so I can do something like

`conn.query("SELECT id, name FROM sensors WHERE id IN ($1)", &[596304,597992,610978,597998]);`

**Comment by sfackler** [comment]
Nope - https://github.com/sfackler/rust-postgres/issues/326#issuecomment-368078120

**Comment by glennpierce** [comment]
Ok I got the In clause working.

So to recap in redshift

`SELECT id, name FROM sensors WHERE id = ANY(ARRAY[596304,597992,610978,597998]) 
`
fails
but

`let results : postgres::Result<Rows> = conn.query("SELECT id, name FROM sensors WHERE id IN (596304,597992,610978,597998)", &[]);`

works.


Thanks

**Comment by sfackler** [comment]
Wait, so even `ARRAY[...]` literals in the query string are broken with Redshift? I though it was just transferring array values as parameters that didn't work.
