### ISSUE TITLE
Consuming into_iter for Rows

### ISSUE THREAD

**Issue by MaikKlein** [sfackler/rust-postgres#333]
IntoIterator is only implemented for &Rows. Unless I miss something obvious, this means that I can't map the iterator and move it out of scope.

```
fn foo(&self) -> impl Iterator<item = Bar> {
    self.conn.query(...).unwrap().into_iter().map(Bar::from_row)
}
```

Would this be possible to implement?

**Comment by sfackler** [comment]
This should be pretty easy to make.

**Comment by MaikKlein** [comment]
Does query hold all the results memory? For example if my query is very large, I should make sure that I have enough memory? 

I think what I actually want is the `lazy_query` on a statement. I think API wise a consuming IntoIterator might be harder to implement because LazyRows borrows the Statement. I think I could always just scope the iterator, so it is not really a problem.

**Comment by sfackler** [comment]
Yeah, `Rows` holds all of the row data in memory at once. Use `lazy_query` if you want to stream the rows from the database over time.

**Comment by sfackler** [comment]
We now return a simple Vec<Row> on the master branch.
