### ISSUE TITLE
Update to Tokio 0.1

### ISSUE THREAD

**Issue by asonix** [sfackler/rust-postgres#334]
This should be as simple as doing the following:
 - using `tokio_tcp::TcpStream` instead of `tokio_core::tcp::TcpStream`
 - using `tokio_timer::Interval` instead of `tokio_core::reactor::Interval`
 - dropping explicit references to `Handle`

**Comment by sfackler** [comment]
It looks like tokio-uds still needs to be updated.

**Comment by jbg** [comment]
That PR is merged now

**Comment by carllerche** [comment]
And it has been released :)

**Comment by adam0z** [comment]
This would be great!

**Comment by adam0z** [comment]
How is the work going?
We are looking forward to the solution due to lack of compatibility with `tokio-threadpool` as it is described in the referenced issue below.

**Comment by sfackler** [comment]
The work lives on this branch: https://github.com/sfackler/rust-postgres/tree/tokio-rewrite

It's going to be a bigger rewrite to enable pipelining and a cleaner API.

**Comment by vorot93** [comment]
@sfackler Could you please release one last `tokio-core`-based version? I fear it will be quite some time before production end-users will be able to leverage the rewrite for microservices. New *Tokio*, *Hyper*, *tokio-postgres* and [bb8](https://github.com/khuey/bb8) might be too much to chew.

**Comment by asonix** [comment]
So I realize the development isn't done for updating to Tokio yet, but I'm trying to use the master branch and I've run into some issues. Since the `Client` needs to be borrowed to create some of the futures like `Preapare` and `Query`, but it also needs to be borrowed to create a `Transaction`, so you end up writing something like

```rust
client.prepare(...)
    .and_then(move |statement| {
        client.query(statement)
    })
```
Which means you can't actually pass it to `client.transaction()` since `client` has been moved into the `AndThen`.

In your tests, you frequently use `Runtime::block_on` to get around this, but that defeats the purpose of async code. Do you have any tips on how to use this better, or are you planning on redesigning the API further from where it is now?

A second point of confusion, the `Handshake` future yields a `Client` and a `Connection`, but I can't tell what the purpose of the `Connection` future is.

**Comment by sfackler** [comment]
Thanks for trying it out! I've noticed the same issue with the current transaction approach as well - it's not really usable in its current state. The Client's methods currently take &mut self, but we don't actually need mutability in the implementation so that could just change to &self which would avoid this issue.

The `Connection` is the thing that has the network socket and actually does the IO - you'd typically spawn that off onto a Tokio Runtime and then use the Client for your actual query work.

**Comment by rolftimmermans** [comment]
Thanks for your hard work so far @sfackler. Please, if you don't mind, let me know if there's anything I can contribute to get a Tokio 0.1 based version working and released.

**Comment by NotSqrt** [comment]
@sfackler I see a lot of work has been done !
How far is it from a release ?
Thanks !

**Comment by dvic** [comment]
@NotSqrt I believe a release is coming soon(see https://github.com/sfackler/rust-postgres/issues/411#issuecomment-453799792)

@sfackler this issue can be closed, right?

**Comment by sfackler** [comment]
The 0.4.0-rc.2 release uses tokio 0.1.
