### ISSUE TITLE
RefCell<T> already borrowed

### ISSUE THREAD

**Issue by radford** [sfackler/rust-postgres#34]
I'm seeing `pool.get_connection()` return connections where the `RefCell` is `WRITING` (as opposed to `UNUSED` like it should be), so that the first use of the connection fails with `RefCell<T> already borrowed`.  If I `sleep(1)` after getting the connection, then it becomes `UNUSED`, so it seems like a race condition.

This only happens when the client is `cond.wait()`ing in `get_connection()`, so that it gets a connection that was just previously used.

**Comment by sfackler** [comment]
I believe this should be fixed by rust-lang/rust#21972.
