### ISSUE TITLE
Support for verify-ca authentication method?

### ISSUE THREAD

**Issue by Choestelus** [sfackler/rust-postgres#347]
Hi, I'm stuck at problem on database connection.

Currently I'm trying to connect to postgresql server with following entry in `pg_hba.conf` file

```
hostssl    all    all    some.ip.addr.ess/32    cert
```

this would be connected using psql with following command:
`psql "postgresql://user@some.ip.addr.ess/db_name?sslmode=verify-ca"`

From #217 I know how to manually specify root CA but not with a client certificate

Is there a way to connect to database using `cert` authentication method?
Thanks

**Comment by sfackler** [comment]
This is something you'd configure in whatever TLS implementation you're using.

**Comment by Choestelus** [comment]
Thanks for replying

I'm still not sure about how to specify private key though (not sure if about pkcs#8 or something), postgres cert authentication needs both client certificate and *certificate private key*, but will look further into this.
