### ISSUE TITLE
DbError while trying to prepare stmt

### ISSUE THREAD

**Issue by fafhrd91** [sfackler/rust-postgres#352]
i am trying to use prepare_cached with 

```sql  
UPDATE world SET randomnumber = temp.randomnumber FROM (VALUES ($1, $2)) AS temp(id, randomnumber) WHERE temp.id = world.id
```

**Comment by fafhrd91** [comment]
"No operator matches the given name and argument type(s). You might need to add explicit type casts."

**Comment by sfackler** [comment]
That doesn't seem like it's related to this library, but rather a query that Postgres doesn't understand I think.

**Comment by fafhrd91** [comment]
i can execute this query in pgsql
```sql
UPDATE world SET randomnumber = temp.randomnumber FROM (VALUES (1, 2)) AS temp(id, randomnumber) WHERE temp.id = world.id
```

also similar query work in java

**Comment by sfackler** [comment]
Can you execute this query in pgsql?

```sql
PREPARE foo AS UPDATE world SET randomnumber = temp.randomnumber FROM (VALUES ($1, $2)) AS temp(id, randomnumber) WHERE temp.id = world.id;
```

**Comment by sfackler** [comment]
We pass the query string directly to Postgres, there is no processing done on our end. The JDBC driver may be string-interpolating the query on its end rather than actually making a prepared statement.

**Comment by fafhrd91** [comment]
ok, I can not execute prepare. 
Thanks

**Comment by fafhrd91** [comment]
i modified query, now i can prepare it without error and i can "PREPARE" it pgsql
```sql
UPDATE world SET randomnumber = temp.randomnumber::integer FROM (VALUES ($1, $2)) AS temp(id, randomnumber) WHERE temp.id::integer = world.id
```

but now i get `Error(Conversion(WrongType(Type(Text))))` while trying to execute stmt `prep_stmt.execute(&[&1, &2])`
