### ISSUE TITLE
README should show a working SSL example

### ISSUE THREAD

**Issue by ciofeca** [sfackler/rust-postgres#355]
My problem: I can't get *TlsMode::Require* working for a remote PostgreSQL database. Someone using this crate just disabled certificate verification; this does not make much sense to me. I'm on Ubuntu with stock OpenSSL.

How to reproduce:

step 1: configure your remote PostgreSQL server to only accept SSL connections. Example:

* server-side configuration to require encryption (without fallback to unencrypted) for your specific external users (in *pg_hba.conf* add something like *"hostssl mydatabase user 11.22.33.0/24 md5");*
* server-side keys ([at least server.crt/server.key](https://www.postgresql.org/docs/9.1/static/ssl-tcp.html)) in PostgreSQL's data directory; note that [letsencrypt](https://letsencrypt.org)-generated keys will work as expected;
* note: PostgreSQL server has to be restarted every time you change SSL parameters/files;
* now you will get a message like *"SSL connection (protocol: TLSv1.2..."* when you connect with *psql --host example.org --username user ...);*

step 2: try this:

    extern crate postgres;
    use postgres::tls::openssl::OpenSsl;
    use postgres::tls::openssl::openssl::ssl::{SslConnectorBuilder, SslMethod};
    use postgres::{Connection, TlsMode};
    
    extern crate chrono;
    use chrono::prelude::*;
    
    const CREDENTIALS: &str = "postgres://user:password@example.org/mydatabase";
    
    fn main() {
        let connector = SslConnectorBuilder::new(SslMethod::tls()).unwrap().build();
        let openssl = OpenSsl::from(connector);
        let db = Connection::connect(CREDENTIALS, TlsMode::Require(&openssl)).expect("dbconnect");
    
        println!("connection OK");
    
        for row in &db.query("select current_timestamp", &[]).expect("errquery") {
            let ts: DateTime<Local> = row.get(0);
            println!("OK: current_timestamp is {}", ts);
        }
    }

Note that you will need in *Cargo.toml* these:

    [dependencies]
    postgres = { version = "*", features = ["with-chrono", "with-openssl"] }
    chrono = "*"
    openssl = "*"

Result: fail.

While the command-line client *psql* will be able to log in using Tls, the above *rust-postgres* example will never show "connection OK" and will always complain about *verify_result: X509VerifyError { code: 20, error: "unable to get local issuer certificate" }... library: "SSL routines", function: "tls_process_server_certificate", reason: "certificate verify failed", file: "../ssl/statem/statem_clnt.c"....*

Note: I would use the *clientcert=1* parameter in that *hostssl* description in order to get *psql* client complaining with a similar *"connection requires a valid client certificate"* fatal error.

That X509 error code 20 also happens if adding:

    openssl.danger_disable_hostname_verification(true);

It also happens if using *SSL_CERT_FILE=/tmp/cacert.pem* on a freshly downloaded bundle as of [rust-openssl issue #534](https://github.com/sfackler/rust-openssl/issues/534).

Also happens if adding proper *root.crt/root.crl* to the PostgreSQL server.

My guess is that something must be configured in the client before doing the *connect* (specifying a CApath? telling OpenSSL to not to send any local certificate?), but the *rust-postgres* crate currently only allows the *danger_disable_hostname_verification* thing.

**Comment by ciofeca** [comment]
After some diving in the OpenSSL documentation, I found in a not very brilliant [man page](https://linux.die.net/man/3/ssl_set_verify) that the client has to use *SSL_VERIFY_NONE* (so that the client verifies the server certificate, but the PostgreSQL server will only rely on the user/password supplied by the client). No need to specify a local PEM bundle file.

Thus, having configured PostgreSQL server with *hostssl* and *server.key/server.crt* (self-signed or issued by *letsencrypt)* as above, this is a working *rust-postgres* example (Ubuntu 18.04 local, Postgres 9.1 remote only accepting SSL connections):

    extern crate postgres;
    use postgres::tls::openssl::openssl::ssl::{SslConnectorBuilder, SslMethod};
    use postgres::{Connection, TlsMode};

    extern crate chrono;
    use chrono::prelude::*;

    const CREDENTIALS: &str = "postgres://user:password@example.org/mydatabase";

    fn main() {
        // unencrypted version shall get "DbError FATAL no pg_hba.conf for user... SSL off...":
        // let db = Connection::connect(CREDENTIALS, TlsMode::None).expect("dbconnect-nossl");

        let mut connbuilder = SslConnectorBuilder::new(SslMethod::tls()).unwrap();
        connbuilder.set_verify(postgres::tls::openssl::openssl::ssl::SSL_VERIFY_NONE);
        let openssl = postgres::tls::openssl::OpenSsl::from(connbuilder.build());
        let db = Connection::connect(CREDENTIALS, TlsMode::Require(&openssl)).expect("dbconnect");

        println!("connection OK");

        for row in &db.query("select current_timestamp", &[]).expect("errquery") {
            let ts: DateTime<Local> = row.get(0);
            println!("OK: database current_timestamp is {}", ts);
        }
    }

**Comment by sfackler** [comment]
> so that the client verifies the server certificate, but the PostgreSQL server will only rely on the user/password supplied by the client

No, if SSL_VERIFY_NONE is passed, the client completely ignores the certificate provided by the server.

**Comment by matthewkmayer** [comment]
I want to chime in saying the most recent code snippet ( https://github.com/sfackler/rust-postgres/issues/355#issuecomment-392248211 ) helped me a lot. I've some services in other languages that use `sslmode=require` which doesn't verify certs by default, so this behavior was needed to get parity with those. And now we know we should change it to be more secure by verifying the cert we get! 👍

**Comment by andrewbanchich** [comment]
@sfackler Would you be able to provide an example for the README?

**Comment by sfackler** [comment]
The contents of the README have been moved to crate documentation. The postgres-openssl and postgres-native-tls crates have examples: https://docs.rs/postgres-openssl/0.3.0-alpha.2/postgres_openssl/#examples
