### ISSUE TITLE
postgres:///bananas URL parsed as TCP

### ISSUE THREAD

**Issue by sqwishy** [sfackler/rust-postgres#361]
The URL string "postgres:///bananas" when parsed as connection params has a TCP host instead of unix-domain socket thingy.

```
    #[test]
    fn parse_unix_url() {
        let params = "postgres:///bananas";
        let params = params.into_connect_params().unwrap();
        assert_eq!(params.host(), &Host::Unix(PathBuf::new()));
        assert_eq!(params.database(), Some("bananas"));
    }
```
```
thread 'params::test::parse_unix_url' panicked at 'assertion failed: `(left == right)`
  left: `Tcp("")`,
 right: `Unix("")`', postgres-shared/src/params/mod.rs:290:9
```

Is this wrong or am I doing something dumb?

**Comment by sfackler** [comment]
> To connect to the server via Unix sockets, host should be set to the absolute path of the directory containing the socket file. Since / is a reserved character in URLs, the path should be URL encoded.

https://docs.rs/postgres/0.15.2/postgres/struct.Connection.html#method.connect

**Comment by sqwishy** [comment]
OK, that's easy enough I guess. I didn't see that bit in the documentation, thanks for pointing it out. Some documentation for [libpq](https://www.postgresql.org/docs/current/static/libpq-connect.html#LIBPQ-CONNSTRING) say "In particular, a Unix-domain socket connection is chosen if the host part is either empty or starts with a slash..." so this was surprising to me. But I guess there's no rule that says everything else has to work that way.

**Comment by jbg** [comment]
> OK, that's easy enough I guess. I didn't see that bit in the documentation, thanks for pointing it out. Some documentation for [libpq](https://www.postgresql.org/docs/current/static/libpq-connect.html#LIBPQ-CONNSTRING) say "In particular, a Unix-domain socket connection is chosen if the host part is either empty or starts with a slash..." so this was surprising to me. But I guess there's no rule that says everything else has to work that way.

In case anyone arriving here via Google is also mislead by the last comment: in order to make the host part of a URL start with a slash, you need to percent-encode the slash. Otherwise the slash terminates the host part. (This is just URL syntax and has nothing specific to do with postgres or rust-postgres.)

The libpq docs are accurate, though maybe not as user-friendly as they could be since they don't mention the need for encoding, and the rust-postgres behaviour is consistent with libpq's.

**Comment by sqwishy** [comment]
>The libpq docs are accurate, though maybe not as user-friendly as they could be since they don't mention the need for encoding, and the rust-postgres behaviour is consistent with libpq's.

The libpq docs do mention that socket directories do need to be encoded if included in the host part of a URI and include an example of a connection string using percent encoding:

>The host component is interpreted as described for the parameter host. In particular, **a Unix-domain socket connection is chosen if the host part is either empty** or starts with a slash, otherwise a TCP/IP connection is initiated. Note, however, that the slash is a reserved character in the hierarchical part of the URI. So, to specify a non-standard Unix-domain socket directory, either omit the host specification in the URI and specify the host as a parameter, or **percent-encode** the path in the host component of the URI:

https://www.postgresql.org/docs/9.2/libpq-connect.html#LIBPQ-CONNSTRING

My understanding from the above is that omitting the host (such as in "postgres:///database") should mean that a unix socket is used. Instead, this library treats it as a host for a TCP/IP socket. That's what this issue was about when I opened it. Sorry if this was somehow confusing; I did not intend to make any claims about URI encoding.

**Comment by jbg** [comment]
Thanks for the clarification! The misunderstanding was mine :) I arrived here while looking into whether this library supports UNIX socket connections and then read everything through that "lens". Sorry for the noise.
