### ISSUE TITLE
Support auto-detecting the unix domain socket

### ISSUE THREAD

**Issue by RalfJung** [sfackler/rust-postgres#362]
When using `diesel::pg::PgConnection`, I can set the database URL to something like `postgres://r@/my-db`, and it will figure out which domain socket to use.

With this crate, I instead have to actually give the path to the socket. So I tried to find out where that socket lives, but all I found so far is `/var/run/postgresql/.s.PGSQL.5432` -- the PID of the postgres server is encoded in that name, so it is not stable. Seems like I have to adapt my application configuration after every reboot if I want this crate to connect to postgres via a unix domain socket.

It'd be great if whatever magic happens in `diesel::pg::PgConnection` could also be implemented here. Actually, [looking at the source](https://github.com/diesel-rs/diesel/blob/master/diesel/src/pg/connection/raw.rs#L19), I can't even see any magic so maybe this is just a matter of exposing a feature of the underlying C library.

**Comment by RalfJung** [comment]
Hm, even with `postgres://r@%2Fvar%2Frun%2Fpostgresql%2F.s.PGSQL.5432/my-db` I get errors -- so far I'm just unable to connect to the DB, while connecting to the same DB on the same machine with diesel works fine.

**Comment by sfackler** [comment]
Diesel uses libpq, the C library that is part of PostgreSQL itself. Since it's compiled alongside the server, it knows what the default unix socket directory was. rust-postgres isn't built in that way so it doesn't know what the default would be.

5432 is the port, not the process ID. The URL should contain the path to the directory containing the socket file, not the path to the file: `postgres://r@%2Fvar%2Frun%2Fpostgresql/my-db`.

**Comment by RalfJung** [comment]
> Diesel uses libpq, the C library that is part of PostgreSQL itself. Since it's compiled alongside the server, it knows what the default unix socket directory was. rust-postgres isn't built in that way so it doesn't know what the default would be.

I see. I guess that makes this request not realizable then?

> 5432 is the port, not the process ID. The URL should contain the path to the directory containing the socket file, not the path to the file:

That was my bad, sorry again -- I didn't read the docs carefully enough, just expecting it to be the file because what else would it be.

**Comment by sfackler** [comment]
> I see. I guess that makes this request not realizable then?

Yeah, I don't think we can really implement it unfortunately.

> That was my bad, sorry again -- I didn't read the docs carefully enough, just expecting it to be the file because what else would it be.

Ah yeah, I didn't see you'd updated your post :)
