### ISSUE TITLE
[Notifications] BlockingIter pending forever

### ISSUE THREAD

**Issue by kamek-pf** [sfackler/rust-postgres#365]
Hey !

I keep running into an issue but I can't figure out what's  causing it.
I have a service listening for notifications, it simply reads the content of the notification and pushes it through a channel, it looks like this :

```rust
pub fn listen_radius_events(sender: Sender<Events>) {
    let conn = get_pg_connection();
    conn.execute("LISTEN radius_events", &[])
        .expect("PG Listen failed");

    let notifications = conn.notifications();
    let mut it = notifications.blocking_iter();

    loop {
        let r = it.next()
            .map(|opt_value| opt_value.unwrap().payload)
            .map_err(|e| Error::Notification(e))
            .and_then(|payload| build_event(payload))
            .and_then(|event| {
                let sync = sender.send(Events::Radius(event))?;
                Ok(sync)
            });

        if r.is_err() {
            error!("Radius event processing failed : {:?}", r);
        }
    }
}
```

Now what happens is, after some time, usually a week or two, I stop receiving notifications.
I don't get any error, and it doesn't look like the `Connection` fails, I simply stop receiving anything.

One thing I noticed, when the system gets into this state, if I look at `pg_stat_activity`, I don't see a `LISTEN radius_events` in the `query` column like I'm supposed to.

Maybe there's a limitation I'm not aware of. 
Any idea what could be causing this ? Do you think using a different type of iterator might help ?

**Comment by sfackler** [comment]
There wouldn't be an active LISTEN query - that just registers the connection for notifications and returns. I'm not sure why you'd stop receiving responses as long as the connection is still alive.

**Comment by kamek-pf** [comment]
Probably not an active one, but I should at least see an idle one, right ? Notifications are coming in correctly since yesterday :
```sql
select
    query_start,
    state_change,
    state,
    query
from pg_stat_activity;
2018-06-30 13:57:44.042590	2018-06-30 13:57:44.042637	idle	LISTEN radius_events
```

When the problem occurs I don't even see the idle query, which seems to indicate that the connection is dead, but since I'm not getting errors I'm not sure what to think.

**Comment by kamek-pf** [comment]
I just tried to kill the connection, and then I do get errors : `communication with the server has desynchronized due to an earlier IO error`.
This probably has nothing to do with `rust-postgres`, I'll close the issue and report back if I find out what;s going on.
