### ISSUE TITLE
Feature request: `format` or `quote_ident` support

### ISSUE THREAD

**Issue by dahlbaek** [sfackler/rust-postgres#367]
As far as I know, `EXECUTE format(...) USING ...` is the suggested idiom when composing dynamic SQL commands in postgres, [example](https://www.postgresql.org/docs/10/static/plpgsql-statements.html#PLPGSQL-QUOTE-LITERAL-EXAMPLE). Looking over the `rust-postgres` README, it looks like `rust-postgres` currently only supports something like `EXECUTE ... USING ...`. Did I miss something? Is there any plan for `rust-postgres` to support a full `EXECUTE format(...) USING ...` type command?

Currently, I have a toy project with some databse io written in python using `psycopg2`, where the [`psycopg2.sql`](http://initd.org/psycopg/docs/sql.html) module enables this type of dynamic SQL command composition. I want to rewrite the toy project in rust, and `rust-postgres` seems like the natural substitute for `psycopg2` to me.

**Comment by sfackler** [comment]
I don't think that'd be something we'd add to the postgres crate itself, but it seems like a reasonable thing for someone to build a separate crate around!

**Comment by dahlbaek** [comment]
I see. Out of curiosity, is it correct that building such a crate would either require some type of `libpq` interaction, or writing the quoting logic from scratch?

**Comment by sfackler** [comment]
I mean, the two options would be to pull the escaping functionality from somewhere that already exists, or implement it from scratch, yes.
