### ISSUE TITLE
Is it possible to control which OID gets written for a given parameter?

### ISSUE THREAD

**Issue by mavilein** [sfackler/rust-postgres#377]
First of all thank you for this amazing crate! We are writing our first Rust application now and were delighted to find such a well maintained library in order to connect to Postgres. 🙏 

However we currently struggle a bit with type conversions. The application we are writing is very dynamic in nature and therefore we do not know the schema of the underlying database at implementation time (think of it as an ORM). For example our application might just receive a floating point number and we do not know whether it is represented by a numeric, real or double precision in Postgres. This causes us trouble defining the implementation of `ToSql` for our types.

This is our current understanding of the flow in the driver:
1. A query is prepared by sending it to the Postgres server. This returns the types (OIDs) of the columns used in the query, e.g. `numeric`.
2. Those types are then passed to the various `ToSql` instances provided by the application code. If an instance is not able to handle a given type an error is returned (this is determined through `accepts`).
3. If no error is returned, the OID from step 1 is written to the message stream along with the actual value that is returned from the `ToSql` instance for a parameter.

Therefore the `ToSql` instance has to write the value in exactly the format that is expected by the type returned in step 1. This is causing a problem for us since we do not know which type an underlying column has at implementation time. If our application receives a floating point number, it might be represented by a numeric or double precision. Therefore we would like to be able ourselves to control which OID gets written to the message stream. 
In our example we would like to always write the OID for `Float8` no matter what type the underlying column has and then rely on the conversion capabilities of Postgres itself to do the right thing.

Is this possible with this crate? So far we were not able to find a solution by reading through the source code of this crate.

**Comment by sfackler** [comment]
It's not possible to do this with the API exposed by this crate currently. I'm not sure if Postgres itself is willing to do automatic conversions for parameters that don't match the types its expecting, so that'd probably be something to check for.

If it does work on the Postgres level, it seems like it'd be reasonable to change the API to support this kind of thing.

The alternative would probably be to have your `ToSql` implementation look at the expected type provided and support all of the conversions internally.

**Comment by sfackler** [comment]
Er, wait, no. The client doesn't include the OID of each parameter in the bind message. It just has to match what the Postgres server specified when the statement was prepared.

**Comment by mavilein** [comment]
I think what we want is `prepare_typed` that i found in [here](https://github.com/sfackler/rust-postgres/issues/377). We are using this crate in version `0.15.2`. However the function `prepare_typed` has been added after that version. Is ther a reason that there has not been a release since February although there have been plenty of commits since then?

**Comment by sfackler** [comment]
The 0.16.0-rc.1 release has prepare_typed (along with a ton of other changes!)
