### ISSUE TITLE
Suboptimal API design wrt. transactions

### ISSUE THREAD

**Issue by rustonaut** [sfackler/rust-postgres#378]
The current transaction API is suboptimal designed making it easy to accidentally cause panics in a way which is normally prevented by rust.

## Current API design

- connections are passed on and used by `&self`
- starting a transaction returns a transaction instance and takes `&self`
- now thinks need to be done on that transaction instance
- `GenericConnection` abstracts over wether or not something is `Connection` or `Transaction`
- we have nested transactions (or at last something similar to it)
- using a connection instance while a transaction is active panics

## Problem

As everything is done by `&self` there is nothing in place to prevent you
from using a connection object instead of a transaction object causing a
panic, even worse if your function works with both by being abstract over
`GenericConnection` it is easy to accidentally pass in the wrong connection
object especially in context of refactoring thinks.

The think is that this normally should be prevented by rust as starting a
transaction is a change of state (here internal and world state) and should
normally require `&mut`. (Except starting/stopping a transaction it's should
be fine to ignore that executing any INSERT,UPDATE,DROP, LOCK etc. also
changes world state).

## Solutions

The most rust-like solution would be to use `&mut self` and let the borrow
checker do the rest. But given the current API design and the rest of the
API design this might cause a headache for people to refactor, so it's 
probably not an option.

Another approach would be to upgrade the `Connection` itself. 
Which would require a slightly different handling of (named) savepoints 
but this is easy to impl. as it already contains internal mutability so instead
of using the call stack for "stacking" the names there could be a vec of
savepoint names (better a small vec). Problem here is the parts where
`Transaction` provides functionality "exceeding" what `Connection` 
provides mainly the savepoint method and the handling of ending
(sub)transactions based on RAII. Anyway to to connection
increasing it's transaction depth count this is already halfway done
this way.

My guess is that the best solution probably lies somewhere in between,
like upgrading the connection itself but also providing a Transaction
object to make the `savepoint` method available and auto ending
transactions on drop if not done explicitly before. But this needs 
a bit more consideration.

As a side note transactions often are already writing in a `{}` block
to make sure the transaction object is dropped at the right place,
so going from this to a signature accepting a FnOnce closure should be
simple for most use cases (you still would need inner upgrading due to
connection still using `&self` to start a transaction, but now could pass in
something providing a savepoint method and you now can handle the end
of the (sub)transaction better).

**Comment by sfackler** [comment]
Yeah, the current use of `&self` everywhere is not the best. There's a larger proposed refactor in #346 that resolves this that might be worth taking a look at.

**Comment by sfackler** [comment]
This is now implemented on master.
