### ISSUE TITLE
Please upgrade phf to 0.7.23

### ISSUE THREAD

**Issue by 11nk** [sfackler/rust-postgres#381]
=0.7.22 cause version conflict with actix-web

**Comment by 11nk** [comment]
@sfackler `tokio-postgres` still =0.7.22

**Comment by sfackler** [comment]
tokio-postgres 0.3 depends on postgres-shared 0.4 which should work fine.

**Comment by 11nk** [comment]
what i said before was in the master branch  code, i'm sorry for that.

**Comment by sfackler** [comment]
Fixed
