### ISSUE TITLE
Postgres Error 42P10 blocks connection indefinitely

### ISSUE THREAD

**Issue by kosta** [sfackler/rust-postgres#383]
I noticed my programm hanging in Connection.execute() reliably.

`pg_stat_activity()` shows the query was submitted, state is now idle in ClientRead, so as far as postgres is concerned, it waits for the client to submit a new query.

Checking with Wireshark shows the server responded immediately with

    E....SERROR.VERROR.C42P10.Mthere is no unique or exclusion constraint matching the ON CONFLICT specification.Fplancat.c.L824.Rinfer_arbiter_indexes..Z....I

and the connection hangs since.

Peeking through this repos issues, it seems this is not the first time error are being swallowed. Error handling is something rust is supposed to be good at. Is this caused by https://github.com/tokio-rs/tokio-proto/issues/176 ? (I'm not using r2d2 atm)

Thanks in advance for your time and efforts! :)

**Comment by sfackler** [comment]
That certainly seems bad! Can you make a little program that reproduces the issue?

**Comment by kosta** [comment]
Nevermind, it was the following combination:

* start a crossbeam scope
* start a scoped thread that prints some stats until it receives a stop signal on a crossbeam channel
* execute a postgres query that returns an error
* use operator `?` to return early _without ever sending the stop signal_
* have the crossbeam thread pool wait forever for the scoped thread that never receives a stop signal
* all debug output points to the line with the `?`

Fix was to move the channel construction _inside_ the scoped thread scope so that the channel is closed automatically when the error makes the program return early.

Sorry about the noise!
