### ISSUE TITLE
Update openssl version

### ISSUE THREAD

**Issue by simonsilvalauinger** [sfackler/rust-postgres#386]
Hello there,
arch linux is already using openssl 1.1.1, so arch linux users can't use this crate, because the openssl crate is not up to date. Is it possible to use the latest version of the openssl crate?

Thanks
Simon

**Comment by sfackler** [comment]
I think the right thing to do here is to deprecate the built-in features and publish a separate postgres-openssl crate that'll use the 0.11 release. This has already been done on master, but I'll backport that over to the current stable release tonight.

**Comment by sfackler** [comment]
This is now released as the `postgres-openssl` crate.

**Comment by simonsilvalauinger** [comment]
You're great, thank you very much!
