### ISSUE TITLE
Submit release with native-tls ^0.2

### ISSUE THREAD

**Issue by jnicholls** [sfackler/rust-postgres#387]
Now that native-tls 0.2 has been out for about 5 months now, and I already see that postgres-native-tls has been updated for 0.2, it would be amazing if you put out a release with this new dependency. I have other code that relies on native-tls 0.2 and I wish not to have a wrapper crate for establishing my TLS connections to postgres just because of this.

I'll fork in the meantime. Thank you!

**Comment by jnicholls** [comment]
What I actually did was create a [patch.crates-io] section for `postgres` and `postges-native-tls` that pointed to your repo. Of course then r2d2_postgres had a build error since `From<postgres_shared::error::Error>` is not implemented for `postgres::Error` in this latest version. Odd times indeed.

**Comment by jnicholls** [comment]
I forked the repo and edited `postgres-shared` to be `v0.4.2` to match what is published on crates.io, and then`r2d2_postgres` and `native-tls` 0.2 built happily.

**Comment by jnicholls** [comment]
Of course now I'm getting `FromSql<'a>` updates. This is no longer fun. And now that I realized postgres::tls::native_tls was publicly exported the entire time, I suppose I could have avoided this altogether :D But, the issue still stands. It would be nice to put out a new release at some point. Thanks.

**Comment by sfackler** [comment]
Yeah, the master branch is in the middle of a bunch of breaking changes.

I think the right thing to do here is to deprecate the built-in features and publish a separate `postgres-native-tls` crate that'll use the 0.2 release. This has already been done on master, but I'll backport that over to the current stable release tonight.

**Comment by jnicholls** [comment]
@sfackler You are the man. For what it's worth, I did work around my personal issues. And additionally, I like the incoming changes on master for sure. If you need a hand with anything big or small let me know. I could perhaps update `postgres-derive` for the new `FromSql<'a>` implementation.

**Comment by sfackler** [comment]
This is now released as the `postgres-native-tls` crate.
