### ISSUE TITLE
Hyper with  tokio_postgres

### ISSUE THREAD

**Issue by goriunov** [sfackler/rust-postgres#391]
Is there any way to use  tokio_postgres with hyper, is there any examples ? I am still new to the Rust and trying to make simple rest API with db connection.

**Comment by sfackler** [comment]
There aren't any examples I'm aware of, but if you take some code using Hyper and some code using tokio-postgres, they should compose together just fine.

**Comment by jwilm** [comment]
@goriunov, you can try out the [`l3-37` connection pooler](https://github.com/onesignal/l3-37) we wrote and use at OneSignal. The pool can be cloned indefinitely, and you can ask it for a connection via a method like `get_conn() -> Future<Conn>`.

**Comment by o01eg** [comment]
It looks like published tokio_postgres version still depends on tokio-core while hyper uses tokio.

**Comment by tyranron** [comment]
@jwilm wow, I think that should be mentioned in #233 too.
