### ISSUE TITLE
postgres-native-tls 0.1.0 out of sync between github and crates.io

### ISSUE THREAD

**Issue by swfsql** [sfackler/rust-postgres#397]
I'm not sure if this is expected (for being an initial version), but I'd like to point out that those two are out of sync:
- https://github.com/sfackler/rust-postgres/blob/master/postgres-native-tls/src/lib.rs ( [fixed commit](https://github.com/sfackler/rust-postgres/blob/08df4b330f5cdf251c373c1c705bc87a06bc67cd/postgres-native-tls/src/lib.rs) )
- https://docs.rs/crate/postgres-native-tls/0.1.0/source/src/lib.rs

Best regards,

**Comment by sfackler** [comment]
The released version is off of this branch: https://github.com/sfackler/rust-postgres/tree/postgres-shared-0.4.x
