### ISSUE TITLE
Support futures 0.3 alpha

### ISSUE THREAD

**Issue by andreytkachenko** [sfackler/rust-postgres#406]
Consider creating a branch for futures 0.3 (aka `futures-preview` crate) support. It is possible now to try it with [romio](https://github.com/withoutboats/romio) crate.

**Comment by sfackler** [comment]
You should be able to use it as-is with one of the futures-0.1-to-futures-0.3 compatibility libraries I think. I don't really want to be maintaining a forked branch indefinitely.

**Comment by sfackler** [comment]
You're welcome to maintain this on your own fork, but I'll be sticking with futures 0.1 until 0.3 finalizes.
