### ISSUE TITLE
Support row-returning queries via the simple protocol

### ISSUE THREAD

**Issue by sfackler** [sfackler/rust-postgres#413]
The only API we currently expose via the simple query protocol returns `()` to encourage use of prepared statements for "real" work. However, there are some use cases that require use of the simple query protocol. For example, the replication protocol only supports simple queries, as do some load balancers.

The simple approach would be to simply return `Stream<Item = StringRow>`, where `StringRow` is like `Row`, but returns `Option<&str>` since the simple query protocol doesn't use binary encoded values. However, simple queries can contain multiple statements, and this approach loses framing of where the rows from one query end and the next begin. Additionally, we lose information about e.g. how many rows were added by an insert statement.

Another approach could be something that's a bit closer to the messages we get back from the backend:

```rust
pub enum SimpleQueryResult {
    RowDescription(RowDescription),
    Row(StringRow),
    CommandComplete(u64),
}

impl Client {
    fn simple_query(&mut self, query: &str) -> impl Stream<Item = SimpleQueryResult, Error = Error> { ... }
}
```

cc @jwilm

**Comment by jwilm** [comment]
Took me a few minutes to catch up on what's been happening in rust-postgres land; I was surprised by `14571ab0292f5fa11302b39fded69d98ee99b660`, but it sounds like the plan is to have core implementation async and then provide sync wrappers later on?

Anyways, this sounds like a great proposal for a futures API for the simple/string protocol.

**Comment by sfackler** [comment]
The sync API's been rebuilt on top of the async one: https://github.com/sfackler/rust-postgres/tree/master/postgres.
