### ISSUE TITLE
Timeline for new release ?

### ISSUE THREAD

**Issue by goriunov** [sfackler/rust-postgres#422]
Hi, 

I have notices that there have been done a lot of work on rust-postgres especially for async but no new releases in a while. Just wondering if you have any timeline for next release ?

Thanks :)

**Comment by sfackler** [comment]
I think tokio-postgres is just about ready, at least for an RC release. I'll make a final pass and cut one tomorrow night.

**Comment by sfackler** [comment]
Update: tokio-postgres itself is basically ready to go, but tokio-postgres-native-tls and tokio-postgres-openssl need documentation, etc. Should actually be tomorrow.

**Comment by sfackler** [comment]
Published tokio-postgres 0.4.0-rc.1!
