### ISSUE TITLE
postgres vs tokio_postgres

### ISSUE THREAD

**Issue by nevi-me** [sfackler/rust-postgres#425]
I've previously depended on `postgres = "0.15"` on my Cargo.toml, but when I change it to point to the git repo, it seems like everything breaks. For example, types seem to now be in `tokio_postgres::types`, and `Connection` no longer exist (I see `Client`).

Should I still be using postgres, or should I rather move to tokio_postgres? I perform simple tasks that read and write data to Postgres, so I was fine with doing that synchronously.

**Comment by sfackler** [comment]
If you want to use a synchronous Postgres client, you should probably continue to use `postgres`.

**Comment by nevi-me** [comment]
Does it have the same API as the async one? The thing that made me point cargo to github was that reading a value from `Row` seemed to consume the `Row`.
I'm creating a Postgres table reader that reads data into an Apache Arrow `RecordBatch`, so I was struggling with reading more than one column at a time.
Maybe I was doing something wrong, so I'll try again when I get a chance.

**Comment by sfackler** [comment]
> The thing that made me point cargo to github was that reading a value from `Row` seemed to consume the `Row`.

Nope, it does not consume the row: https://docs.rs/postgres/0.15.2/postgres/rows/struct.Row.html#method.get

**Comment by nevi-me** [comment]
I'll try it out. I got tokio_postgres working, but I'd rather use the sync version. If I can't get it working, I'll stick with the async one.

Thanks Steven
