### ISSUE TITLE
Using enum derive with tokio_postgres

### ISSUE THREAD

**Issue by blainehansen** [sfackler/rust-postgres#428]
Hello! I'm trying to use the wonderful [derive macros for postgres enums](https://github.com/sfackler/rust-postgres-derive) along with the newest version of tokio-postgres, but it seems the `0.4.0-rc.2` release doesn't line up with the traits.

Is there something I'm doing wrong in this following example? Is there a way to use the derive crate with tokio-postgres, or should I just use `0.3`? (which I was able to get working with this example).

```toml
tokio-postgres = "0.4.0-rc.2"
postgres = "0.15"
postgres-derive = "0.3"
```

```rust
#[macro_use] extern crate postgres;
#[macro_use] extern crate postgres_derive;
extern crate tokio_postgres;
use tokio_postgres::types::ToSql;

#[derive(Debug, ToSql)]
enum Name {
	Variant1,
	Variant2,
}

fn main() {
	println!("{:?}", <Name as ToSql>::accepts(&tokio_postgres::types::Type::TEXT));
}
```

The only compile error I get:

```
error[E0277]: the trait bound `Name: tokio_postgres::types::ToSql` is not satisfied
   --> src/main.rs:430:19
    |
430 |     println!("{:?}", <Name as ToSql>::accepts(&tokio_postgres::types::Type::TEXT));
    |                      ^^^^^^^^^^^^^^^^^^^^^^^^ the trait `tokio_postgres::types::ToSql` is not implemented for `Name`
    |
    = note: required by `tokio_postgres::types::ToSql::accepts`
```

**Comment by sfackler** [comment]
postgres and postgres_derive are a bit behind tokio_postgres currently.

**Comment by blainehansen** [comment]
Gotcha. I'll be happy to wait. Keep up the good work :smile:

**Comment by sfackler** [comment]
This is now supported by enabling the `derive` Cargo feature in the `postgres-types` crate: https://docs.rs/postgres-types/0.1.0-alpha.2/postgres_types/#derive
