### ISSUE TITLE
Add Tokio Postgres (docs) and version to readme

### ISSUE THREAD

**Issue by goriunov** [sfackler/rust-postgres#429]
Hi, it is a bit hard to find tokio postgres docs without going to crates.io and directly searching for tokio-postgres and then selecting latest version and going to corresponding docs. Could you may be add section to README like (Under development) and link to crates for each project ?

Thank you very much :)

**Comment by sfackler** [comment]
https://docs.rs/ is the standard place to find documentation for the vast majority of Rust crates, fyi.

Seems reasonable to add links to the README though.
