### ISSUE TITLE
ToSql impl for IpAddr

### ISSUE THREAD

**Issue by cholcombe973** [sfackler/rust-postgres#430]
postgres has support for the inet type that can handle ipv4 and ipv6.  It would be nice if the postgres crate suported a ToSql for IpAddr.  It's likely more efficient than using varchar

**Comment by sfackler** [comment]
I assume `ToSql` would set /32 as the netmask? Should `FromSql` ignore it or assert that it's /32?

**Comment by cholcombe973** [comment]
That's a good question.  IpAddr's variants don't seem to have that information.  I think assuming /32 is fine

**Comment by cholcombe973** [comment]
Awesome!
