### ISSUE TITLE
tokio_postgres: Transaction should support Drop

### ISSUE THREAD

**Issue by tyranron** [sfackler/rust-postgres#431]
The current implementation of `Transaction` only rolls back on `Err` result on inner `Future`. However, this is not enough when some panic in inner future occurs and is caught somewhere else up the stack.

In my case the `Connection` is returned back to the pool being poisoned with unfinished `Transaction`. I've tried to implement simple wrapper but had troubles with implementing async operation in `drop()`.

Another work-around I see here is verifying connection for being poisoned when retrieving from the pool and rolling back the transaction there.

**Comment by sfackler** [comment]
You cannot perform async work in `Drop`.

One option could be to wrap your inner future with https://docs.rs/futures/0.1.26/futures/future/trait.Future.html#method.catch_unwind

**Comment by tyranron** [comment]
Maybe we can schedule rollback somehow onto executor in `Drop` without waiting its completion?

Using catch_unwind inside inner future is OK, but may require additional infra for errors handling up the application layers. It would be more convenient to `.catch_unwind()` panics only on the higher layers (like controllers, etc).

**Comment by sfackler** [comment]
Ah yeah, we should be able to schedule a rollback in drop like we handle statement closure. It'll need to be careful to only do that if the future has started the transaction but not already completed it.

**Comment by sfackler** [comment]
The async/await-based Transaction implementation on the `std-futures` branch is way more ergonomic and handles this properly.
