### ISSUE TITLE
Reuse connection in a stream

### ISSUE THREAD

**Issue by nevi-me** [sfackler/rust-postgres#435]
I'm implementing a service that connects to a kafka/[nats](http://nats.io) stream, and saves all incoming messages from the `futures::Stream` to the database.

After connecting to the streaming server of my choice, I get a `impl Future<Item= impl Stream<Item=Message, Error=()>, Error=()>`.

I'm trying to create a connection once for the stream, and then write each message to the database. I seem to be unable to "share" the connection, because something like:

```rust
fn connect_to_pg() -> impl Future<Client>;
fn write_to_db(client: Client, message: Message) -> impl Future<WriteResult>;

let snippet: Future<Stream<Message>> = some_fn();
some_fn.and_then(|subscriptions| {
  // establish pg connection
  connect_to_pg().map(|pg_client| (pg_client, subscriptions))
})
.and_then(|(pg_client, subscription)| {
  // try to write each message to database
  subscription.for_each(|message| write_to_db(pg_client, message)
});
```

doesn't work because I `cannot move out of captured variable in an 'FnMut' closure`.

___

As it appears that I can't clone the connection, are there any workarounds that I could follow? I don't know if an `Arc` could work, as it seems that I can't use `&Client` instead of `Client` when trying to execute my DB statements.

**Comment by sfackler** [comment]
Depending on how things are structured, you may be able to pass a &mut Client into write_to_db rather than passing it by value.

It'll unfortunately be a bit awkward until async await become stable.

**Comment by kaibyao** [comment]
Have you tried
```rust
.and_then(|(mut pg_client, subscription)| {
// ...
});
```
? (note the `mut` keyword in front of `pg_client`)

**Comment by nevi-me** [comment]
Hey @kaibyao, that doesn't solve the problem. Just checked now, and I still get the same error.

**Comment by kaibyao** [comment]
Sorry, I misunderstood the original problem. I actually ran into something similar (was running batch inserts in a loop) and had to use [loop_fn](https://docs.rs/futures/0.1.27/futures/future/fn.loop_fn.html) and pass in the connection to the loop. The inner function (`write_to_db` in your case) would have to return the `client` after it was done using it. It's ugly and you have to pass the client around, but it works.

**Comment by sfackler** [comment]
The async/await-based implementation on the `std-futures` branch should be way easier to work with.
