### ISSUE TITLE
Best function return type for gracefully handling database errors?

### ISSUE THREAD

**Issue by fearofcode** [sfackler/rust-postgres#437]
In my application, I have database query functions that can error out for application-level reasons, and also the database could error out. I'd like to at minimum print out the error message.

What return type should I have for a function that inserts into the database but could error out for other reasons?

A highly simplified example of such logic would be something like this:

```
struct Foo {
  id: Option<i32>,
  ...
}

fn create_foo(foo: &Foo) -> ??? {
  if foo.id.is_some() {
    return an error indicating that this struct has already been created
  }

  execute an INSERT query with foo's values
  if it succeeded, return the number of rows affected
  if not, return the error so it can be printed
}
```

The examples only show calling `.unwrap()`, which is fine, except I'd like to gracefully handle foreseeable errors rather than just panicking. So I'd like to return some kind of `Result<T>`.

The error I'll return and the errors this library uses will differ in type.

So, is there a better option than `Result<u64, Box<dyn Error>>` (in the case of a call to `.execute()` which returns a `postgres::Result<u64>`)? That's what I currently have now.

If this is a reasonable thing to do, would it help to add a brief note to the README to demonstrate how to work with rust-postgres's errors in this way? I'm happy to write up a small documentation pull request. I feel this may be helpful to newer Rust users, such as myself. Personally, I often try out database libraries for projects shortly after learning the basics of that language, and this problem was confusing for me.

Thanks!

**Comment by sfackler** [comment]
This is something of a broader question than specifically Postgres clients, so you may want to try asking on users.rust.lang.org or reddit.com/r/rust.

Generally, you'd have some error type that can store the error information you need. `Box<Error>` is one simple approach, as is a custom enum with variants for Postgres errors, other errors, etc.
