### ISSUE TITLE
Trying to understand how to send in dynamic variables to a execute function. (Raw pointers?)

### ISSUE THREAD

**Issue by veniamin-ilmer** [sfackler/rust-postgres#438]
Using the `postgres` crate (version 0.15.2), I can do something like this:

    let a = true;
    let b = "yes";
    let c = 1;

    conn.execute("INSERT INTO abc (a, b, c) VALUES ($1, $2, $3)", &[&a, &b, &c]);

Notice a, b, and c are different type, and the execute function can work regardless of the type.

I see that this array of types is declared as this: `&[&dyn postgres_shared::types::ToSql]`

So now, I would like do insert a dynamic set of values, like this:

    let mut dollar_str_array = vec![];
    for j in 0 .. LIMIT {
        dollar_str_array.push(format!("${}", j+1));
    }
    let dollar_str = dollar_str_array.join(",");

    let a = true;
    let b = "yes";
    let c = 1;

    let mut values_arr = vec![];
    for j in 0 .. LIMIT {
        values_arr.push(&a);
        values_arr.push(&b);
        values_arr.push(&c);
    }

    conn.execute(format!("INSERT INTO abc (a, b, c) VALUES ({})", dollar_str, &values_arr);

If I build, the compiler complains to me that the vec![...] has differing types going into vec!.

I tried casting the pointers to raw pointers that I looked up by writing `as *const` in each push, but it tells me that's invalid.

It sounds to me like the postgres crate has some kind of simple [to_sql](https://docs.rs/postgres/0.15.2/postgres/types/trait.ToSql.html#tymethod.to_sql) function to do this, but I'm having trouble figuring out how to use this to allow multiple different types in the array.

Can you please help? Thank you!

**Comment by sfackler** [comment]
You don't need to cast to raw pointers, you just need to hint the types a bit so the compiler's type inference understands what's going on. This should do it:

```rust
let mut values_arr: Vec<&dyn ToSql> = vec![];
```
