### ISSUE TITLE
How to insert DEFAULT values?

### ISSUE THREAD

**Issue by kaibyao** [sfackler/rust-postgres#439]
Hi,

I'm trying to run the following query:
`INSERT INTO foo (test_bigint, test_text) VALUES ($1, $2);`
with
```
parameters:
$1 = DEFAULT
$2 = DEFAULT
```

The following params arrays don't work:
```rust
&[&"DEFAULT", &"DEFAULT"] // it's sending "DEFAULT" strings, which throws an error (failure to convert to int8)
&[&None::<i64>, &None::<String>] // it's sending NULL instead of DEFAULT
```

**What's the correct way to execute/prepare the query so that they send `DEFAULT` parameter values?**

**Comment by sfackler** [comment]
The elements of the `VALUES` tuple are either expressions that can be query parameters or the literal token `DEFAULT`. You'd need to change your query to `INSERT INTO foo (test_biging, test_text) VALUES (DEFAULT, DEFAULT)`.

https://www.postgresql.org/docs/11/sql-insert.html

**Comment by kaibyao** [comment]
Thanks for the quick response! I guess this was my misunderstanding of Postgres’ prepared statements, as I thought that it was possible to use `DEFAULT` as a query parameter. I will use `DEFAULT` in the actual query itself then.
