### ISSUE TITLE
Type conversion error

### ISSUE THREAD

**Issue by esn01** [sfackler/rust-postgres#440]
I can not find a reason why my code does not work.
It would be helpful to know which parameter can not be converted.

Trace:

2019-05-19T22:54:15.962257733+02:00 - postgres:489 => preparing query with name ``: SELECT nextval('pd01_activity_id_seq')
2019-05-19T22:54:15.971840110+02:00 - postgres:608 => executing statement  with parameters: []
2019-05-19T22:54:16.588457760+02:00 - persorg::db:91 => create_activity -> pd01_id: 48
2019-05-19T22:54:16.588632202+02:00 - postgres:901 => executing query: BEGIN
2019-05-19T22:54:16.595343969+02:00 - postgres:489 => preparing query with name ``:  INSERT INTO pd01_activity
	(
	  pd01_activity_id,
	  pd01_persid,
	  pd01_task_type_id,
	  pd01_code,
	  pd01_number,
	  pd01_descr,
	  pd01_customer,
	  pd01_start,
	  pd01_end,
	  pd01_duration,
	  pd01_insert_id,
	  pd01_update_id
	)
	VALUES	($1, $2, $3, $4, $5, $6, $7, $8, $9,  $10, $11, $12 )
2019-05-19T22:54:16.600572062+02:00 - postgres:608 => executing statement  with parameters: [48, 2, 2, "FSN-110011", 112223, "First created over API", "K-005", 2019-04-24T15:41:42, 2019-04-24T15:43:12, 120, 2, 2]
2019-05-19T22:54:16.600863678+02:00 - postgres:901 => executing query: ROLLBACK
2019-05-19T22:54:16.606257370+02:00 - persorg::app:73 => handle_create_activity; => Error creating activity: "type conversion error: cannot convert to or from a Postgres value of type `int4`"

My code:

	let trans = connection.transaction().unwrap();

	let s_sql = " \
	INSERT INTO pd01_activity
	(
	  pd01_activity_id,
	  pd01_persid,
	  pd01_task_type_id,
	  pd01_code,
	  pd01_number,
	  pd01_descr,
	  pd01_customer,
	  pd01_start,
	  pd01_end,
	  pd01_duration,
	  pd01_insert_id,
	  pd01_update_id
	)
	VALUES	($1, $2, $3, $4, $5, $6, $7, $8, $9,  $10, $11, $12 )";

	trans.execute(
		s_sql,
		&[
			&activity.pd01_id,
			&activity.pd01_persid,
			&activity.pd01_task_type_id,
			&activity.pd01_code,
			&activity.pd01_number,
			&activity.pd01_descr,
			&activity.pd01_customer,
			&activity.pd01_start,
			&activity.pd01_end,
			&activity.pd01_duration,
			&user.persid,
			&user.persid,
		],
	)?;
	trans.commit().unwrap();

Variable activity is of type:

#[derive(Serialize, Deserialize, Clone)]
pub struct Activity {
	pub pd01_id: i32,
	pub pd01_persid: i32,
	pub pd01_task_type_id: i32,
	pub pd01_code: String,
	pub pd01_number: i32,
	pub pd01_descr: String,
	pub pd01_customer: String,
	#[serde(with = "serial")]
	pub pd01_start: NaiveDateTime,
	#[serde(with = "serial")]
	pub pd01_end: NaiveDateTime,
	pub pd01_duration: i32,
	pub pd01_insert_id: i32,
	pub pd01_update_id: i32,
}

Table definition :

CREATE TABLE pd01_activity
(
   pd01_activity_id   integer       DEFAULT nextval('pd01_activity_id_seq'::regclass) NOT NULL,
   pd01_persid        integer       NOT NULL,
   pd01_task_type_id  integer       NOT NULL,
   pd01_code          varchar(20)   NOT NULL,
   pd01_number        integer       NOT NULL,
   pd01_descr         varchar(80),
   pd01_customer      varchar(80),
   pd01_start         timestamp     NOT NULL,
   pd01_end           timestamp     NOT NULL,
   pd01_duration      integer,
   pd01_insert_date   timestamp,
   pd01_insert_id     integer       NOT NULL,
   pd01_update_date   timestamp,
   pd01_update_id     integer       NOT NULL
);

ALTER TABLE pd01_activity
   ADD CONSTRAINT pd01_activity_id_pk
   PRIMARY KEY (pd01_activity_id);

Cargo.toml

[dependencies]
tide = "0.1.1"
http = "0.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
log = "*"
log4rs = { version = "0.8", features = ["toml_format"] }
chrono = { version = "0.4", features = ["serde"] }
postgres = { version = "0.15", features = ["with-time","with-chrono"] }

**Comment by sfackler** [comment]
It sounds like you're using something other than an `i32` for one of the `integer` parameters.

**Comment by esn01** [comment]
Thank you very much - you are right - one parameter was not of i32, Solved.
