### ISSUE TITLE
tokio-posgres: statement error

### ISSUE THREAD

**Issue by ntrippar** [sfackler/rust-postgres#444]
using tokio-postgres = "0.4.0-rc.2" im having a error with the statements, im doing a single query with a single paramenter, and the second time i execute the program im having this issue.

error: db error: ERROR: prepared statement "s0" already exists

**Comment by sfackler** [comment]
That's very weird. Do you have some code that reproduces the issue?

**Comment by sfackler** [comment]
Are you connecting directly to the database or is there something in the middle? This sounds like it could be that you're connecting to a pool or something that isn't closing connections when tokio-postgres does.

**Comment by ntrippar** [comment]
Yes, the database im connecting is a public one, this is for downloading the 
certificate transparency data, maybe they use a proxy and that proxy is not closing the connections.

https://gist.github.com/ntrippar/c507ffbeda45e008543b4fab71567aaa

**Comment by sfackler** [comment]
You may need to use simple_query rather than the prepared statement APIs in that case: https://docs.rs/tokio-postgres/0.4.0-rc.2/tokio_postgres/struct.Client.html#method.simple_query
