### ISSUE TITLE
tokio-postgres does not compile on Windows

### ISSUE THREAD

**Issue by IsaacLeeWebDev** [sfackler/rust-postgres#449]
I'm getting a compile-time error that I only get on a Windows machine. I get this error with a fresh `cargo new` project run with the nightly version of rust, and the stable version of rust run with `rustup run stable cargo build`. 

The error/version of Rust I'm using:
![image](https://user-images.githubusercontent.com/20074921/60126086-0d66fe00-9742-11e9-9660-d29192cb3bcc.png)

My Cargo.toml:
![image](https://user-images.githubusercontent.com/20074921/60126281-7cdced80-9742-11e9-9ce3-4154c07a912c.png)

The place the error is thrown: (in `src/stream.rs:50:30`) 
![image](https://user-images.githubusercontent.com/20074921/60126775-992d5a00-9743-11e9-8797-308c458aea78.png)

It appears as though there's just no place ConnectError is defined, here.

**Comment by sfackler** [comment]
Have you tried using 0.4.0-rc.2?

**Comment by IsaacLeeWebDev** [comment]
@sfackler That fixes it! 🎉
