### ISSUE TITLE
 URI character handling issue/error.

### ISSUE THREAD

**Issue by MrSpock** [sfackler/rust-postgres#453]
Hi,

I have a DB where password contain "$" characters let say "$Pa$ssword".
I'm unable to get connection in any way:
`let dburi = "postgres://spock:$Pa$ssword@172.28.25.50/saturn";`

`let another_dburi = &format!("postgres://{}:{}@172.28.25.50/saturn", "spock", "$Pa$ssword");
`
I also tried 
`
let third_uri = "hostaddr=172.28.25.50 dbname=saturn user=spock password='$Pa$ssword';
`
And I'm getting:
`invalid connection parameters: Illegal character in authority`
How to handle special characters in db password ?

**Comment by sfackler** [comment]
You can percent-encode them.

**Comment by MrSpock** [comment]
Is there other way ? Credentials are provided by another system that I can’t change :-/ It would require some hack with pipes etc..

**Comment by sfackler** [comment]
You don't need to change the password - you just need to percent-encode it if you're manually assembling the URL. Alternatively you can just use the `ConnectParams` type and avoid having to make a string: https://docs.rs/postgres/0.15.2/postgres/params/struct.ConnectParams.html.

**Comment by MrSpock** [comment]
Thanks. This solved problem.
