### ISSUE TITLE
`CREATE DATABASE` inside `batch_execute` fails

### ISSUE THREAD

**Issue by norcalli** [sfackler/rust-postgres#454]
Error is `"CREATE DATABASE cannot run inside a transaction block"` on postgres 11, which leads me to believe that the statement is being executed inside a transaction, and that makes it seem like `autocommit` is to blame here, but I don't know how to modify that with `postgres:0.15.2`.

**Comment by sfackler** [comment]
A transaction is only running if you explicitly execute a `BEGIN`, or use the `Connection::transaction` method.

This test program succeeds for me:

```rust
use postgres::{Connection, TlsMode};

fn main() {
    let conn = Connection::connect("postgres://postgres@localhost:5433", TlsMode::None).unwrap();

    conn.batch_execute("CREATE DATABASE test").unwrap();
    conn.execute("CREATE DATABASE test2", &[]).unwrap();
}
```

**Comment by norcalli** [comment]
@sfackler hmm. Mine is extremely similar, and yet I'm getting that error. I actually use docker to allocate a new service, and the code lives here https://github.com/norcalli/kpostgres_fixture/blob/be850ebaf6df2022d9a6f01a1dffdf5e3f8eaed9/src/lib.rs#L130 if you were interested in the full testcase.

`temp_pg` allocates an anonymous docker instance and tries to run the code. `temp_db` runs against postgresql I have installed running with systemd, and both fail.

**Comment by sfackler** [comment]
I don't know why it would be doing that, but it seems like it has to be something on the Postgres server configuration rather than in the client.

**Comment by norcalli** [comment]
@sfackler what version of postgres were you using?

**Comment by sfackler** [comment]
I was using the ETE test container, which is based off of Postgres 11: https://github.com/sfackler/rust-postgres/blob/master/docker/Dockerfile

**Comment by vitaly-burovoy** [comment]
@norcalli, error in your code is not because it has "CREATE DATABASE", but because you have multiple DBMS-related (not just DB-related) statements in one request.

The PostgreSQL wraps multiple statements in a query into a transaction:
https://www.postgresql.org/docs/current/protocol-flow.html#PROTOCOL-FLOW-MULTI-STATEMENT
That's why you get "... cannot run inside a transaction block".

Try to split all multistatement queries (lines 130..132, 140..141) into separate "conn.batch_execute" calls.

**Comment by norcalli** [comment]
@vitaly-burovoy you are absolutely correct. Thank you, I never realized that could be a problem.
