### ISSUE TITLE
Neither with-native-tls nor with-openssl compiles on Ubuntu with OpenSSL 1.1.1

### ISSUE THREAD

**Issue by provtimofei** [sfackler/rust-postgres#455]
Compiling openssl v0.9.24
error: failed to run custom build command for `openssl v0.9.24`
process didn't exit successfully: `postgres-test/target/debug/build/openssl-f03754764cc4a5c5/build-script-build` (exit code: 101)
--- stderr
thread 'main' panicked at 'Unable to detect OpenSSL version', ~/.cargo/registry/src/github.com-1ecc6299db9ec823/openssl-0.9.24/build.rs:16:14
note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.

**Comment by sfackler** [comment]
`openssl v0.9` does not support OpenSSL 1.1.1. Use 0.10.

**Comment by tbolsh** [comment]
Can you, please, provide a working example of Postgres code with TLS?

**Comment by sfackler** [comment]
Use https://docs.rs/postgres-openssl/0.1.0/postgres_openssl/
