### ISSUE TITLE
Question about listening for notification in 0.4.0-rc.3

### ISSUE THREAD

**Issue by rolftimmermans** [sfackler/rust-postgres#456]
In 0.3.0 there was a `notifications()` method on the connection that returned a stream of notifications. I notice that the API has been overhauled a bit for 0.4 (mostly in a very good way).

However I can't seem to find any way to listen for notifications anymore. Is this intentional? Is there a recommended alternative or is it just not possible anymore? Thanks!

**Comment by sfackler** [comment]
You set up a future that wraps the `Connection` and calls `poll_message`: https://github.com/sfackler/rust-postgres/blob/master/tokio-postgres/tests/test/main.rs#L447.
