### ISSUE TITLE
Docs for postgres-native-tls 0.2.0-rc.1

### ISSUE THREAD

**Issue by suhabe** [sfackler/rust-postgres#457]
Where are the docs for the new postgres-native-tls 0.2.0-rc.1 release?
The link https://docs.rs/postgres-native-tls/0.2.0-rc.1 doesn't seem to work.

**Comment by sfackler** [comment]
Oh oops, looks like I accidentally published it as 0.1.0-rc.1: https://docs.rs/postgres-native-tls/0.1.0-rc.1/postgres_native_tls/

I just pushed up a fixed version.
