### ISSUE TITLE
Remove rustc-serialize

### ISSUE THREAD

**Issue by est31** [sfackler/rust-postgres#459]
serde 1.0 has been around [since over two years](https://github.com/serde-rs/serde/releases/tag/v1.0.0) now, so I think one could think about removing rustc-serialize. I see two tasks:

* Removal of the optional dependency (for 0.16?)
* Removal of the dev-dependency

**Comment by sfackler** [comment]
This has already been done in the 0.16 release candidates.

**Comment by est31** [comment]
Oh sorry for that, I was only checking crates.io which seems to ignore release candidates (makes sense in general to do that but I haven't thought about it).

**Comment by sfackler** [comment]
No worries!
