### ISSUE TITLE
Synchronous client without the tokio dependencies

### ISSUE THREAD

**Issue by fbernier** [sfackler/rust-postgres#461]
Hi,

I just took a quick glance at `0.16.0-rc.2` and correct me if I'm wrong but it seems like this whole lib has been rewritten to use `tokio`, even the synchronous client.

One of the downsides of this is upgrading from `0.15.0` means adding `95` new dependencies to projects which don't need `tokio` at all, increasing build times by a lot and most likely binary size.

Is this the way forward? Did I miss anything? Is there anything I can do to help avoid this?

Thanks for you work

**Comment by sfackler** [comment]
This is my plan of the way forward. It's much easier to have one backend rather than two, and running connections asynchronously gives us the ability to have much nicer handling of notifications, for example.

**Comment by fbernier** [comment]
I see, do you think it could be possible to have a feature which would reduce the number of tokio-related dependencies with a feature when all one need is a synchronous client ?

**Comment by sfackler** [comment]
I mean sure, we definitely don't want to have dependencies on things that we don't need. I don't really know what that would concretely look like though.

**Comment by kika** [comment]
Uh-oh and now, 4 years later, that decision prevents us from using this crate on Cloudflare Workers platform (wasm-unknown-unknown target)

**Comment by GeeWee** [comment]
Also for us using Fastly's Compute@Edge

**Comment by kika** [comment]
I believe that would be the case on many upcoming platforms like Golem.
