### ISSUE TITLE
Implementing ToSql

### ISSUE THREAD

**Issue by jplatte** [sfackler/rust-postgres#463]
Currently, it is necessary to read the source to understand how to implement `ToSql`. Even then, one has to access `#[doc(hidden)]` code to keep with the style of the other implementations (is there a reason the `to_sql_checked` method can't have a default impl, or be part of an extension trait?).

Is it actually discouraged to implement `ToSql` for types local to ones crate, or is this just something that should be allowed, but nobody has bothered to make it a nice experience?

**Comment by sfackler** [comment]
What doc(hidden) code do you need access to? The trait is definitely intended to be implemented outside of the crate, but if there are things missing from its documentation we can add them.

To the best of my knowledge, it is not possible to avoid having to manually write a to_sql_checked implementation, but as the documentation notes, all of those should be generated by the `to_sql_checked!()` macro.

**Comment by jplatte** [comment]
> What doc(hidden) code do you need access to?

I was referring to `fn __to_sql_checked` that I found in the code, but actually the issue is that in the 0.16.0 release candidate, `to_sql_checked!` is no longer exported from the crate.

> To the best of my knowledge, it is not possible to avoid having to manually write a to_sql_checked implementation

This is not at all obvious from the code. The `to_sql_checked` macro looks like it doesn't do anything a default implementation couldn't do. I guess I could just try it changing it and see what breaks though.

**Comment by sfackler** [comment]
> I was referring to `fn __to_sql_checked` that I found in the code, but actually the issue is that in the 0.16.0 release candidate, `to_sql_checked!` is no longer exported from the crate.

Ah yeah, that should be exported down through tokio-postgres into postgres as well.

**Comment by jplatte** [comment]
Thanks :)
