### ISSUE TITLE
Support for higher precision numbers

### ISSUE THREAD

**Issue by ffimnsr** [sfackler/rust-postgres#464]
Would like to ask whether high precision numbers would be supported e.g. [u128](https://doc.rust-lang.org/std/u128/index.html) and [i128](https://doc.rust-lang.org/std/primitive.i128.html)?

**Comment by sfackler** [comment]
To the best of my knowledge, Postgres does not have 128 bit integer types.

**Comment by TEFEdotCC** [comment]
With domain it is possible to create data types of 128 bit and more.
```SQL
CREATE DOMAIN uint_128 AS INTEGER NOT NULL
CHECK (VALUE >= 0 AND VALUE < 2^128)
CHECK (SCALE(VALUE) = 0)
```
