### ISSUE TITLE
Support for agensgraph

### ISSUE THREAD

**Issue by tbolsh** [sfackler/rust-postgres#466]
[Agensgraph](https://bitnine.net/agensgraph/) is a Graph DB based on Postgres DB. It is a multu-model database, supporting [OpenCypher](https://www.opencypher.org/) and Ansi-SQL. SQL queries and Cypher queries can be integrated into a single query in AgensGraph. 

I am currently playing with rust (I am a novice) and Agensgraph. As part of it I am trying to adopt rust-postgres to work with Agensgraph. So far an extremely small amount of changes was necessary to support all what I currently want to do (one line added to types). I think it might be useful for others if I will share my changes - in a separate branch.

**Comment by afidegnum** [comment]
Hi, I'm also interested in this. is there a way to contribute? The little contribution could help

**Comment by sfackler** [comment]
What changes would be required to support it? We did lang some code changes to support Redshift and CockroachDB historically.
