### ISSUE TITLE
Possible to collect a resulting row list into a Vector of said struct?

### ISSUE THREAD

**Issue by redditaccount624** [sfackler/rust-postgres#468]
I'm using `tokio-postgres` with `postgres` and `postgres-derive`.

I have a table in my database that contains cards. I'd like to query that table with a simple `SELECT` statement and store the result into a Vector of structs.

Here's my current attempt:

```rust
#[derive(Debug, ToSql, FromSql, PartialEq, Clone)]
#[postgres(name = "card")]
struct CardQuery {
    id: i32,
    title: String
}

let stmt = client.prepare("SELECT id, title FROM card").await?;

let rows = client
    .query(&stmt, &[])
    .try_collect::<Vec<CardQuery>>()
    .await?;
```

Unfortunately, this gives [the following error](https://i.imgur.com/m2WntzM.png)

Is this possible to do? I'd like to avoid the boilerplate of having to manually reconstruct the struct by calling get on each of the columns, because some of my tables have many columns and this would be quite cumbersome.

Thanks.

**Comment by sfackler** [comment]
That kind of ORM-style workflow is out of scope for this crate. There might be external crates that do that kind of thing though?

**Comment by redditaccount624** [comment]
Oh, then I think I'm confused about what the `ToSql` and `FromSql` macros are supposed to do then. I thought their purpose was so that you could serialize and deserialize structs to and from rows.

**Comment by sfackler** [comment]
`#[derive(ToSql, FromSql)]` converts Rust structs to and from Postgres [composite types](https://www.postgresql.org/docs/11/rowtypes.html).

**Comment by redditaccount624** [comment]
I think I need an example to understand this. A composite type seems to just be a row? And you say these features can convert this to a struct? That sounds exactly what I'm trying to do here? I'm missing something..

**Comment by sfackler** [comment]
There is a composite type corresponding to every Postgres table, but you can also treat composites like normal values and have them as columns in another table or whatever. If you always want to select every column from a table, you can definitely pull the rows out as their composite values.

**Comment by redditaccount624** [comment]
This is somewhat solved with the introduction of [this](https://github.com/dcchut/serde_postgres)
