### ISSUE TITLE
Is there support for chrono?

### ISSUE THREAD

**Issue by redditaccount624** [sfackler/rust-postgres#470]
I'm using the async tokio-postgres branch with [serde-postgres](https://github.com/dcchut/serde_postgres). It's all working great! I can deserialize postgres rows into structs with this.

The only problem is that it seems that I'm getting errors about chrono not being supported. When I was previously using Diesel this worked (deserializing Postgres `timestamptz` columns into `chrono::NaiveDateTime`), so I think it should be possible?

I tried changing my TOML to include this:

```
tokio-postgres = { git = "https://github.com/sfackler/rust-postgres", branch = "std-futures", features = ["with-chrono-0_4"] }
serde_tokio_postgres = { git = "https://github.com/dcchut/serde_postgres" }
chrono = { version = "0.4.7", features = ["serde"] }
```

And I'm not getting any compile errors, but now I'm getting a runtime error:

```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: UnsupportedType', src\libcore\result.rs:1084:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
error: process didn't exit successfully: `C:\Users\Admin\Desktop\testing tokio postgres crate\target\debug\test-async.exe` (exit code: 101)
```

For deserializing into a struct that looks like this:

```rust
#[derive(Debug, Deserialize)]
pub struct ResponseGetMessages {
    pub body: String,
    pub created_at: chrono::NaiveDateTime,
    pub receiver: i32
}
```

If I comment out the `created_at` field, it works perfectly and deserializes into a Rust struct, but for some reason if I include it then it crashes at runtime. Any ideas?

I also tried changing `created_at` to be of type `chrono::DateTime<Utc>`, `chrono::DateTime<Local>`, and `chrono::DateTime<FixedOffset>` as well (even though `NaiveDateTime` worked for Diesel), and I got the same error.

**Comment by sfackler** [comment]
The `UnsupportedType` error seems like it probably came from serde_postgres - that error doesn't exist in this crate itself.

**Comment by redditaccount624** [comment]
Ah, I think you're right. Well, do you have any advice for resolution regardless? Not sure how to modify their code to introduce support for chrono. If you're not sure then I'll just close this I guess.

**Comment by sfackler** [comment]
You'd have to ask them, but serde's interface isn't really built to pass arbitrary types around.
