### ISSUE TITLE
Possible to use results of SELECT as values for INSERT? 

### ISSUE THREAD

**Issue by kirhgoff** [sfackler/rust-postgres#471]
I am trying to write an application that will be syncing similar tables between databases. I hope to make code as generic as possible so the user does not need to recompile the app to apply sync to different tables, just change the configuration describing the table and field names.

The simplest code to illustrate will be the selecting rows from a table and inserting them back in one database (lets disregard key constraints for now):
```rust
use postgres::types::{ToSql, FromSql};
use postgres::rows::Row;
use postgres::{Connection, TlsMode};

fn main() {
    let database_url = "postgres://something";

    let connection = Connection::connect(database_url, TlsMode::None).unwrap();
    let rows = connection.query("SELECT a,b,c FROM table", &[]).unwrap();
    for row in &rows {
        // Just one of the attempts to solve it dynamically, did not work
        let values:Vec<Box<dyn ToSql>> = vec![
            Box::new(row.get(0)),
            Box::new(row.get(1)),
            Box::new(row.get(2))
        ];
        let new_values = ... // What should be here?
        connection.execute("INSERT INTO table(a,b,c) VALUES($1, $2, $3)", new_values.as_slice());
    }
}
```
I see a possible way to resolve it as to have the information about types, have a code that would convert each element types from FromSql to ToSql for the same column type but still not sure how to write that and it smells with unsafe.

Is there a simpler way to achieve that? For primitive types, is there a way to write generic code that passes results of SELECT as parameters of INSERT? Would appreciate any suggestion.

**Comment by o01eg** [comment]
Maybe `FromSql` should implements `ToSql`.

**Comment by sfackler** [comment]
If you're trying to do bulk transfers between identical tables, `COPY` queries should perform significantly better and avoid having to do any type conversion in between.

**Comment by kirhgoff** [comment]
Thanks for a suggestion, I tried to use COPY, but the connection related code 
```
    let database_url = "postgres://postgres:postgres@localhost:5433/bbbb";
    let connection = Connection::connect(database_url, TlsMode::None).unwrap();
    let rows = connection.query("COPY source_table TO STDOUT", &[]).unwrap();
    println!("{:?}", &rows);
```
crashes with an error
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error(Io(Custom { kind: InvalidInput, error: StringError("COPY queries cannot be directly executed") }))', src/libcore/result.rs:999:5
note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
```

I found examples where you are using COPY in tests https://github.com/sfackler/rust-postgres/blob/master/postgres/src/test.rs, but you are using it in master, which is yet to be released.

**Comment by kirhgoff** [comment]
I think my main problem is not with the library (which is awesome, thank you for working on it), but with Rust (I am still learning it) and its trait object concept, I am trying to write very simple code with known types and still struggle to create at least dynamic structure. For example, this does not compile:
```rust
use postgres::{Connection, TlsMode};
use postgres::types::ToSql;

fn main() {
    let source_url = "postgres://postgres:postgres@localhost:5433/source_db";
    let source_connection = Connection::connect(source_url, TlsMode::None).unwrap();

    let target_url = "postgres://postgres:postgres@localhost:5434/target_db";
    let target_connection = Connection::connect(target_url, TlsMode::None).unwrap();

    let rows = source_connection.query("SELECT * FROM source_table", &[]).unwrap();
    for row in &rows {
        let id: i32 = row.get(0);
        let some_string: String = row.get(1);
        let some_value: f32 = row.get(2);

        println!("values: {:} {:} {:}", id, some_string, some_value);

        let new_values:Vec<Box<dyn ToSql>> = vec![Box::new(id), Box::new(some_string), Box::new(some_value)];

        let _ = target_connection.execute(
            "INSERT INTO target_table(id, some_string, some_value) VALUES($1, $2, $3)",
            new_values.as_slice() // this works - &[&id, &some_string, &some_value];
        );
    }
}
```

**Comment by sfackler** [comment]
You need to use the copy_in and copy_out methods: https://docs.rs/postgres/0.15.2/postgres/stmt/struct.Statement.html#method.copy_in
