### ISSUE TITLE
Is Connection#query safe against SQL injections?

### ISSUE THREAD

**Issue by Kinrany** [sfackler/rust-postgres#473]
Is it safe to pass strings to [`Connection#query`][1], or should I escape them first?

[1]: https://docs.rs/postgres/0.15.0/postgres/struct.Connection.html#method.query

**Comment by sfackler** [comment]
Parameters are processed in a way that is safe against SQL injection, but if you are dynamically generating the query string itself, you still need to be aware of whatever escaping you need to do:

```rust
// safe
fn do_an_insert(text: &str) {
    client.execute("INSERT INTO foo (text) VALUES ($1)", &[&s]).unwrap();
}

// not safe
fn do_an_insert(text: &str) {
    let query = format!("INSERT INTO foo (text) VALUES ('{}')", text);
    client.execute(&query, &[]).unwrap();
}
```

**Comment by Kinrany** [comment]
Couldn't find the escaping in the source. Thanks!
