### ISSUE TITLE
Required to cast an integer to an integer for the query to execute without failing

### ISSUE THREAD

**Issue by githubaccount624** [sfackler/rust-postgres#479]
Just spent a couple hours figuring out why a query was failing.

My code was basically this:

    let id: i32 = 5;

    let query = "SELECT id, title FROM item WHERE id = $1";

    let statement = client.prepare(&query).await?;

    let rows = client.query(&statement, &[&id])
                           .map_ok(|r| from_row::<TableItem>(r).unwrap())
                           .try_collect::<Vec<TableItem>>().await?;

And it was erroring out at runtime with the following error:

    `Err`: Error { kind: ToSql(0), cause: Some(WrongType(Type(Text))) }.

I solved it by casting `$1` to an `int4`, basically by changing the `query` line to this:

    let query = "SELECT id, title FROM item WHERE id = $1::int4";

This caused the query to succeed. Except I'm not sure why this is necessary, as `id` is already an `i32` and the column in postgres is an `int4`. I didn't have this problem in diesel.

Is this a bug?

**Comment by sfackler** [comment]
Could you create a self-contained example that reproduces this? I don't really see how the database would become confused as to what type a parameter should be.

**Comment by githubaccount624** [comment]
Sure, I'll try to get a minimum working example working in a bit.

**Comment by githubaccount624** [comment]
Okay, I've made a self-contained reproducible example. Assuming you have a postgres table named person with an `int4` id column:

    let x: i32 = 5;
    let query = "SELECT id FROM person WHERE $1 = $1;";
    let statement = client.prepare(&query).await?;
    let mut rows = client.query(&statement, &[&x]).try_collect::<Vec<_>>().await?;
    let result: i32 = rows.pop().unwrap().get(0);
    println!("hey {}", result);

At runtime the following error is outputted the console:

    `Err`: Error { kind: ToSql(0), cause: Some(WrongType { postgres: Type(Text), rust: "i32" }) }.

However, if you change the `query` line to the following:

    let query = "SELECT id FROM person WHERE $1::int4 = $1::int4;";

Then there is no error and it works fine.

Perhaps there is a reason for this and I'm just doing something stupid. If that is the case then please let me know :p

**Comment by sfackler** [comment]
Why are you comparing a query parameter to itself? I guess Postgres just picks the `TEXT` type arbitrarily since there's nothing else constraining it.

**Comment by sfackler** [comment]
You can use the `prepare_typed` method to explicitly specify the types of the parameters you want rather than adding casts in the query.

**Comment by githubaccount624** [comment]
Ah okay neat thanks!
