### ISSUE TITLE
Checking if postgres::Connection is valid

### ISSUE THREAD

**Issue by glennpierce** [sfackler/rust-postgres#486]
I have a long running process what constantly performs queries on my db.
I wanted to reused a postgres::Connection for these queries but the connection over time would eventually fail
Is it possible to determine if a postgres::Connection is in a failed state and then re perform the connection if necessary or does one have to perform  a query and check for a error ?

I would like to abstract this into a global Conn that reconnects in necessary.

Thanks

**Comment by sfackler** [comment]
https://docs.rs/postgres/0.15.2/postgres/struct.Connection.html#method.is_desynchronized

**Comment by glennpierce** [comment]
Ah Thanks. I must have read past that when scanning down the page. Perhaps I was not expecting in to be named so. Was expecting something like is_valid to match is_active.

Thanks for the pointer.
