### ISSUE TITLE
Queries with NULL guard for optional parameters fail

### ISSUE THREAD

**Issue by liquidscorpio** [sfackler/rust-postgres#490]
Thanks for the fine driver! Really appreciate your work in developing and maintaining this one. :+1: 

Executing queries which are designed to make certain WHERE clauses optional like:
```sql
SELECT * FROM test_table t
WHERE ($1 IS NULL OR t.age > $1);  -- Notice the clause
                                   -- if $1 is NULL it will return all records
                                   -- otherwise only those greater than 1
```
 are failing with a message:
```shell
Query execute: database error: ERROR: could not determine data type of parameter $1
```

The Rust code:
```rust
let query = "SELECT * FROM test_table t WHERE ($1 IS NULL OR t.age > $1);";
let conn = get_connection(); // A wrapper around Connection::connect() 
                             // with some standardized error handling/logging
let filter_age = None::<i32>;
match conn.query(query,  &[&filter_age]) {
    Ok(rows) => rows,
    Err(e) => panic!("Query execution error: {}", e.to_string()),
}
```

Cargo.toml entry
```
postgres = { version = "0.15.2", features = ["with-chrono", "with-uuid"] }
```

Table schema with very basic test data available in this [SQLFiddle](http://sqlfiddle.com/#!17/333348/2).

**Notes**
The message itself is coming from the database and I inspected syslog output in verbose logging mode. The postgres server is not receiving the param it seems. When params are received the output usually contains a statement detailing the params along with the query itself like:
```
machine-abc postgres[24605]: ... user@host DETAIL:  parameters: $1 = '1'
```
But, in this case, only query is output so my hunch is the driver is unable to send such params to the server.

Not really proficient with Rust as yet but let me know if I can help in someway.

**Comment by sfackler** [comment]
We transmit that exact string literal to the server.

**Comment by liquidscorpio** [comment]
In that case, somewhat strange that it is not working. On the other hand, the query works fine through clients like `psql`.

**Comment by sfackler** [comment]
It fails in psql for me:

```
postgres=# create temporary table test_table (age int);
CREATE TABLE
postgres=# prepare foo as select * from test_table t where ($1 is null or t.age > $1);
ERROR:  could not determine data type of parameter $1
LINE 1: prepare foo as select * from test_table t where ($1 is null ...
```

**Comment by liquidscorpio** [comment]
Whoops! I did not use prepared statements in my `psql` tests (was passing the param directly). Investigating further now and will close the issue or post updates if I can derive further information.

Thanks!

**Comment by sfackler** [comment]
It infers correctly if you reverse the order of the two checks. You can also type-hint explicitly in the query.

**Comment by liquidscorpio** [comment]
@sfackler You're correct! Changing to the following works.
```
WHERE ($1::int IS NULL OR t.age > $1)
```

When looking further, landed on this one which was helpful:
 - https://github.com/jackc/pgx/issues/281#issuecomment-307247685.

Thanks! Closing this one.
