### ISSUE TITLE
Missing logging after upgrading

### ISSUE THREAD

**Issue by rlabrecque** [sfackler/rust-postgres#492]
Hey there, I updated from `postgres = "0.15"` and `r2d2_postgres = "0.14"` to 
`postgres = "0.16.0-rc.1"` / `r2d2_postgres = "0.15.0-rc.1"`, and I'm noticing that the logging was removed.

Any chance we could get some of that back? (Preferably via https://github.com/tokio-rs/tracing !)

Specifically log lines like these: https://github.com/sfackler/rust-postgres/blob/postgres-shared-0.4.x/postgres/src/lib.rs#L608

https://github.com/sfackler/rust-postgres/blob/master/tokio-postgres/src/query.rs#L33

**Comment by sfackler** [comment]
This will require a change to the parameter interface, since right now we take a single-pass iterator.

**Comment by bikeshedder** [comment]
No change of the interface required. See #524 

I just wonder if logging should be brought back to `Client::prepare`, too?
