### ISSUE TITLE
Why does a prepared statement bind to a client?

### ISSUE THREAD

**Issue by enzious** [sfackler/rust-postgres#494]
This is more of a question, but why does a statement bind to a client?

Will this cause issues with a pool?

EDIT: This seems to be a postgres issue... can we do anything to solve this from the rust-postgres side or is it best-practice to not save prepared statements with a pool?

If that's the case, would it be a good idea to have a simple_query_params(..., [ToSql...]) method?

**Comment by fakeshadow** [comment]
You can treat a client and it's prepared statements as one connection in pool. It's a easy implementation with existing tokio-postgres pools unless you specifically want different statements for different connections in pool.

**Comment by enzious** [comment]
@fakeshadow Can you link me to some example or doc page?

**Comment by fakeshadow** [comment]
I wrote a pool based on `L3_37` and `bb8` with this feature.
https://github.com/fakeshadow/tang_rs/blob/master/src/postgres_tang.rs
Basically a small change to `PostgresConnectionManager` when impl `ManageConnection` trait in `L3_37` will do the trick. prepare your statements in connect method and return your client and statements in a tuple.

**Comment by sfackler** [comment]
l337/bb8 may want to do something like this, allowing values to be attached to a pooled connection: https://github.com/sfackler/r2d2/pull/84.

I have some in-progress changes that will allow you to call `.query("SELECT ...", &[...])` directly.
