### ISSUE TITLE
Any example how to use tokio-postgres with async/await?

### ISSUE THREAD

**Issue by kingluo** [sfackler/rust-postgres#496]
I need to use tokio-postgres with async/await, directly as tokio program.
But I failed to configure Cargo.toml and write a simple hello world program.

Any example provided? It seems that tokio-postgres does not have any doc and served as the internal and private crate of the sync version rust-postgres, which get me really frustrated...

**Comment by sfackler** [comment]
The docs are right here: https://docs.rs/tokio-postgres/0.4.0-rc.3/tokio_postgres/

**Comment by kingluo** [comment]
> The docs are right here: https://docs.rs/tokio-postgres/0.4.0-rc.3/tokio_postgres/

But that's not async/await version.
Is there any full example including Cargo.toml so that I could use tokio-postgres directly?

**Comment by kingluo** [comment]
I use git version of tokio-postgres, then it success to compile the example shown in the comment of the `lib.rs`.

https://gist.github.com/kingluo/999dd1ec1c2e39291428dd3f7719c334
