### ISSUE TITLE
Transaction `commit()` hangs

### ISSUE THREAD

**Issue by murtyjones** [sfackler/rust-postgres#497]
**postgres =** `{ version = "0.15", features = ["with-chrono"] }`
**r2d2_postgres =** `"0.14.0"`
**r2d2 =** `"^0.8"`

I have some threaded work being done that makes use of postgres connections from a pool:
```
let manager = PostgresConnectionManager::new(host, R2d2TlsMode::None).unwrap();
let pool: Pool<PostgresConnectionManager> = r2d2::Pool::builder()
        .max_size((num_threads as u32) + 1)
        .build(manager)
        .unwrap();

// later on...
let pool = pool.clone();
let conn = pool.get().unwrap();
let trans: Transaction = conn.transaction().expect("Couldn't begin transaction");
// Some simple inserts
trans.commit().expect("Couldn't insert into split_filing")
```

My threaded work seems to perform fine and executes the code above repeatedly as it churns through a series of work.

But after a minute or two of running it hangs on the commit:
```
[2019-10-14T01:25:33Z DEBUG postgres] executing query: BEGIN
[2019-10-14T01:25:33Z DEBUG postgres] preparing query with name `s12`: 
             INSERT INTO (redacted);
             
[2019-10-14T01:25:33Z DEBUG postgres] executing statement s12 with parameters: [ redacted ]
[2019-10-14T01:25:33Z DEBUG postgres] executing statement s12 with parameters: [ redacted ]
// ~90 more inserts
[2019-10-14T01:25:35Z DEBUG postgres] executing statement s12 with parameters: [ redacted ]
[2019-10-14T01:25:35Z DEBUG postgres] executing query: COMMIT
```

**Comment by sfackler** [comment]
What is the database doing at that time?

**Comment by murtyjones** [comment]
My SSH tunnel connection isn't showing any errors and neither is RDS. I'm also able to make manual queries against the DB while the hang occurs. Not sure what else to look at DB-related

**Comment by sfackler** [comment]
You can look at the `pg_stat_activity` table to see what the state of the connection is: https://www.postgresql.org/docs/12/monitoring-stats.html

**Comment by murtyjones** [comment]
Nice, thank you.

The state of for each connections `idle` and the query is `COMMIT` at the hang time.

**Comment by sfackler** [comment]
If the connection is idle, it should have finished running. Are you absolutely sure that the commit call hasn't returned?

**Comment by murtyjones** [comment]
Does appear that it's hanging after the commit. Sorry for the false issue!
