### ISSUE TITLE
How to handle timestamp data?

### ISSUE THREAD

**Issue by xudesheng** [sfackler/rust-postgres#498]
I saw a change from release note:"* The `with-rustc_serialize` and `with-time` Cargo features have been removed. Use `serde` and `SystemTime` or `chrono` instead."

How can I make timetamp conversion successfully?
```
let timestamp = row.get::<usize,DateTime<Utc>>(1);
```

**Comment by sfackler** [comment]
The documentation for FromSql covers what conversions are allowed: https://docs.rs/postgres/0.16.0-rc.2/postgres/types/trait.FromSql.html.

**Comment by xudesheng** [comment]
> The documentation for FromSql covers what conversions are allowed: https://docs.rs/postgres/0.16.0-rc.2/postgres/types/trait.FromSql.html.

Thank you for your quick response.
yes, I can get this works:
```
let timestamp = row.get::<usize,SystemTime>(1);
```

But, how can I get it into a chrono::DateTime<Utc> type? I really don't want to convert a "SystemTime" type to chrono::DateTime<Utc> type.

**Comment by sfackler** [comment]
Enable the `"with-chrono-0_4"` Cargo feature.

**Comment by toplinuxsir** [comment]
@sfackler 
I enabled "with-chrono-0_4", but the error is  
```
Error { kind: ToSql(2), cause: Some(WrongType { postgres: Timestamp, rust: "chrono::datetime::DateTime<chrono::offset::utc::Utc>" }) }
```

**Comment by mozkeeler** [comment]
> @sfackler
> I enabled "with-chrono-0_4", but the error is
> 
> ```
> Error { kind: ToSql(2), cause: Some(WrongType { postgres: Timestamp, rust: "chrono::datetime::DateTime<chrono::offset::utc::Utc>" }) }
> ```

I encountered this when trying to insert a value into a table with type `TIMESTAMP`. I fixed it by changing the type in the table to `TIMESTAMP WITH TIME ZONE`.

**Comment by sweihub** [comment]
How can I insert a chrono datetime to postgresql `timestamptz`?

1. I enabled the feature "with-chrono_0_4"
2. Construct a timestamp ``` let ts = chrono::Utc.timestamp_nanos(time);```
3. Execute the insert
```
let n = client.execute(sql, &[&ts, ...]);
```
4.  Always error
```
error serializing parameter 1: cannot convert between the Rust type `i64` and the Postgres type `timestamptz`
```

**Comment by sfackler** [comment]
That error indicates you're trying to convert an i64, not a chrono timestamp.

**Comment by sweihub** [comment]
Thanks for reply, however, I am constructing a DateTime<Utc>, it's not an i64

```
let ts: chrono::DateTime<chrono::Utc> = chrono::Utc.timestamp_nanos(1234567890);
let n = client.execute(sql, &[&ts, ...]);

```

which is identical to 
```
let ts = chrono::Utc.timestamp_nanos(1234567890);
let n = client.execute(sql, &[&ts, ...]);

```

**Comment by sfackler** [comment]
It is complaining about the parameter at index 1, not index 0.

**Comment by sweihub** [comment]
Aha, many thanks!  
I have 3 consecutive `timestamptz` fields, I am focusing on the first field only, thanks for pointing it out, problem solved.
