### ISSUE TITLE
[Question] How can I derive FromSql and ToSql using 0.16.0-rc.2

### ISSUE THREAD

**Issue by herzrasen** [sfackler/rust-postgres#499]
Hi,

I'm quite new to Rust so please excuse if I'm just not seeing something obvious. 

I try to derive `FromSql` and `ToSql` implementations on an enum using `rust-postgres-0.16.0-rc.2`
```
#[macro_use]
extern crate postgres;

use postgres::types::{FromSql, ToSql};

#[derive(FromSql, ToSql, Debug)]
enum Foo {
    Bar,
    Baz,
}
```
Compiler output:
```
error: cannot find derive macro `FromSql` in this scope
error: cannot find derive macro `ToSql` in this scope
```

In `0.15` I had to use `rust-postgres-derive` and enable macro usage from this crate. But the github page states that it's functionality has been moved here. 

Could you point me to what I'm doing wrong?

**Comment by dutchmartin** [comment]
As far I can see, they are [removed here](https://github.com/sfackler/rust-postgres/commit/4b5bcbb6020d70f3fcd32de4a7a5c5d075e54426#diff-fd22e6a8220788eed1e9c3defb8144ce) and moved into the [postgres-derive crate](https://github.com/sfackler/rust-postgres/releases/tag/postgres-derive-v0.4.0-alpha.1)

**Comment by herzrasen** [comment]
Ah, thanks. Still kind of confusing to me...

**Comment by sfackler** [comment]
It has been moved to the postgres-types crate: https://docs.rs/postgres-types/0.1.0-alpha.1/postgres_types/#derive

Note that it works with postgres 0.17, not 0.16.
