### ISSUE TITLE
decode of serde_json Value type  fail in module postgres-shared "with-serde_json",please check your code !

### ISSUE THREAD

**Issue by zhuxiujia** [sfackler/rust-postgres#502]
## Cardgo.toml:
postgres-shared = {version = "*", features = ["with-serde_json"] }

## Rust Code:
fn decodeRow(row: &Row) -> Value {
 let cs = row.columns();
 for c in cs.as_ref() {
     let id:serde_json::Value= row.get(index);
     println("{:?}",id);
 }
}

##  it will  painc :
 
`
thread 'core::SqlBuilder::TestLinkPostgres' panicked at 'error retrieving column 0: Error(Conversion(WrongType(Type(Varchar))))', C:\Users\mayn\.cargo\registry\src\github.com-1ecc6299db9ec823\postgres-0.15.2\src\rows.rs:201:31
stack backtrace:
   0: backtrace::backtrace::dbghelp::trace
             at C:\Users\VssAdministrator\.cargo\registry\src\github.com-1ecc6299db9ec823\backtrace-0.3.37\src\backtrace/dbghelp.rs:88
   1: backtrace::backtrace::trace_unsynchronized
             at C:\Users\VssAdministrator\.cargo\registry\src\github.com-1ecc6299db9ec823\backtrace-0.3.37\src\backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src\libstd\sys_common/backtrace.rs:77
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src\libstd\sys_common/backtrace.rs:61
   4: core::fmt::write
             at src\libcore\fmt/mod.rs:1028
   5: std::io::Write::write_fmt
             at src\libstd\io/mod.rs:1412
   6: std::sys_common::backtrace::_print
             at src\libstd\sys_common/backtrace.rs:65
   7: std::sys_common::backtrace::print
             at src\libstd\sys_common/backtrace.rs:50
   8: std::panicking::default_hook::{{closure}}
             at src\libstd/panicking.rs:189
   9: std::panicking::default_hook
             at src\libstd/panicking.rs:206
  10: std::panicking::rust_panic_with_hook
             at src\libstd/panicking.rs:469
  11: std::panicking::continue_panic_fmt
             at src\libstd/panicking.rs:376
  12: std::panicking::begin_panic_fmt
             at src\libstd/panicking.rs:331
  13: postgres::rows::Row::get
             at <::std::macros::/panic macros>:9
  14: Rbatis::decode::PostgresJsonDecoder::decodeRow
             at src\decode/PostgresJsonDecoder.rs:60
  15: Rbatis::decode::PostgresJsonDecoder::<impl Rbatis::decode::Decoder::Decoder for postgres::rows::Rows>::decode
             at src\decode/PostgresJsonDecoder.rs:34
  16: Rbatis::core::SqlBuilder::TestLinkPostgres
             at src\core/SqlBuilder.rs:126
  17: Rbatis::core::SqlBuilder::TestLinkPostgres::{{closure}}
             at src\core/SqlBuilder.rs:107
  18: core::ops::function::FnOnce::call_once
             at /rustc/7979016aff545f7b41cc517031026020b340989d\src\libcore\ops/function.rs:227
  19: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
             at /rustc/7979016aff545f7b41cc517031026020b340989d\src\liballoc/boxed.rs:942
  20: __rust_maybe_catch_panic
             at src\libpanic_unwind/lib.rs:80
  21: std::panicking::try
             at /rustc/7979016aff545f7b41cc517031026020b340989d\src\libstd/panicking.rs:267
  22: std::panic::catch_unwind
             at /rustc/7979016aff545f7b41cc517031026020b340989d\src\libstd/panic.rs:396
  23: test::run_test_in_process
             at src\libtest/lib.rs:1936
  24: test::run_test::run_test_inner::{{closure}}
             at src\libtest/lib.rs:1766
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
test core::SqlBuilder::TestLinkPostgres ... FAILED

failures:

failures:
    core::SqlBuilder::TestLinkPostgres

test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 50 filtered out

error: test failed, to rerun pass '-p Rbatis --bin Rbatis'
`

**Comment by sfackler** [comment]
Postgres is returning a value of `VARCHAR`, not `JSON`/`JSONB`.

**Comment by zhuxiujia** [comment]
> Postgres is returning a value of `VARCHAR`, not `JSON`/`JSONB`.

but i  find  it  have a  module  crate  named   "postgres-shared",i find it  support serde_json:Value,but have some bugs..........

**Comment by sfackler** [comment]
You can convert a `JSONB` or `JSON` Postgres value into a `serde_json::Value`.
