### ISSUE TITLE
Unable to detect OpenSSL version when building rust-postgres v0.15

### ISSUE THREAD

**Issue by Melvillian** [sfackler/rust-postgres#509]
I am trying to build a rust bin app which uses rust-postgres to persist a `struct` to a Heroku postgres database. I need to use an SSL/TLS connection (or else I get a an error something like "...no pg_hba.conf...") so I am following the guidance here: https://docs.rs/postgres/0.15.2/postgres/#examples. But I am getting a build error from the `build.rs` not being able to detect the openssl version.

I have the newest versions of openssl and libssl on Ubuntu 18.04:

```
$> sudo apt-get install pkg-config libssl-dev openssl
Reading package lists... Done
Building dependency tree       
Reading state information... Done
pkg-config is already the newest version (0.29.1-0ubuntu2).
libssl-dev is already the newest version (1.1.1-1ubuntu2.1~18.04.4).
openssl is already the newest version (1.1.1-1ubuntu2.1~18.04.4).
0 upgraded, 0 newly installed, 0 to remove and 11 not upgraded.
```

yet when I try to build my crate which uses `rust-postgres` as a dependency I get the following error:

```
$> cargo build
   Compiling openssl v0.9.24
   Compiling num-integer v0.1.41
   Compiling regex v1.3.1
   Compiling rand v0.6.5
   Compiling darling_core v0.9.0
   Compiling synstructure v0.12.1
   Compiling serde_derive v1.0.102
   Compiling sha2 v0.7.1
error: failed to run custom build command for `openssl v0.9.24`

Caused by:
  process didn't exit successfully: `/home/melvillian/Desktop/code/after_market_trading_scraper/target/debug/build/openssl-fa018ab47555f4ee/build-script-build` (exit code: 101)
--- stderr
thread 'main' panicked at 'Unable to detect OpenSSL version', /home/melvillian/.cargo/registry/src/github.com-1ecc6299db9ec823/openssl-0.9.24/build.rs:16:14
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.

warning: build failed, waiting for other jobs to finish...
error: build failed
```

I've seen this somewhat related ticket: https://github.com/sfackler/rust-openssl/issues/987 but the suggestion seems to be to get `reqwest` to update their `openssl` version, however I'm pretty confused by this because it seems like a big ask of a user, and in this case the crate that uses `openssl` is a package by the same maintainer `sfackler`! I am a noob in dealing with openssl build errors so I would appreciate some guidance for myself and future beginners who stumble on this error.

**Comment by sfackler** [comment]
Rather than enabling the `openssl` feature on the `postgres` crate, use the `postgres-openssl` crate v0.1 instead: https://docs.rs/postgres-openssl/0.1.0/postgres_openssl/.

**Comment by Melvillian** [comment]
That did it! Closing this ticket...
