### ISSUE TITLE
tokio_postgress example not working

### ISSUE THREAD

**Issue by dbischof90** [sfackler/rust-postgres#511]
Hey @sfackler ,
trying out your crate right now, I noticed that `bb8_postgres::PostgresConnectionManager` requires the config to implement `ToStr` which is implemented for all structs which implement `std::fmt::Display`. That is not the case for `tokio_postgres::config::Config`.

Since the connection manager calls the tokio_postgres connect logic internally and that also works with a raw string, your example does work with the URL format as specified in the docs of tokio_postgress

```rust
let config = "postgresql://postgres@localhost:5432"; 
```

That seemed easier for this example for the moment than implementing `Display` for the Config struct.

**Comment by sfackler** [comment]
This sounds like an issue that should be filed on the bb8_postgres repo, right?

**Comment by dbischof90** [comment]
Oh I am sorry, I was juggling between these GitHubs and accidentally posted in the wrong one. Will correct!
