### ISSUE TITLE
Improved notifications handling for tokio-postgres. 

### ISSUE THREAD

**Issue by thedodd** [sfackler/rust-postgres#516]
Currently in tokio-postgres, one is not able to access the notifications mechanism via the client. An abstract pattern needs to be used on the connection and the way it is spawned in order to gain access to notifications. 

A simple improvement could be to just allocate a https://docs.rs/tokio/0.2.0-alpha.6/tokio/sync/watch/index.html channel on connection startup, pass the receiving end to the client, and then have the connection object ALWAYS use the poll pattern which handles notifications. When notifications are received, pipe them over the channel, done. Nice ergonomic design.

**Comment by sfackler** [comment]
It does not seem sufficient for all use cases to only provide the last notification received, so I don't think this makes sense as the interface for notifications. However, if only knowing whatever the most recent notification was suffices for your use case, you can set up a watch around the current interface with like 5 lines of code.

**Comment by thedodd** [comment]
Notifications are transient by nature, and as long as the user is actually consuming them, then it’s no big. 

The other approach, which is not really an option, would be to use an unbounded chan. But that will leak a lot of memory. 

Perhaps a bounded queue would be sufficient, and then we just purge the queue if it is at capacity (in the case that the user is not consuming notifications). 

Honestly though, given the transient nature of notifications, the watch interface seems to fit perfectly. If a user wants to actually store/buffer all notifications, then they could very simply map / clone the notification into an unbounded channel or the like.

You are definitely correct that any of the above can be managed in a few lines of code, which is what I did, and why I wanted to open the issue.

Anyway, thoughts on an alternative if you’re still not convinced?

**Comment by thedodd** [comment]
Oh, I should clarify as well, that in my case, I actually used an unbounded queue, but I didn’t suggest that as part of the initial design for obvious reasons :)

**Comment by sfackler** [comment]
I think the current setup is fine for now.
