### ISSUE TITLE
`Row::get` and performance

### ISSUE THREAD

**Issue by pimeys** [sfackler/rust-postgres#517]
I'm trying to understand how `Row::get` works and do we copy or move the data from the row? If we copy, would it make sense to introduce `Row::take` with `&mut self` for better performance?

At least `mysql_async` has the `take` versions, but I'm not sure are they needed with tokio-postgres.

**Comment by sfackler** [comment]
The Row object contains a buffer of serialized values. Row::get deserializes those into the type you want e.g. `i32`.

Are you specifically seeing performance issues?

**Comment by pimeys** [comment]
Just thinking ahead :)

We're basing all our postgres operations on the latest alphas of tokio-postgres and I'd like to understand a bit better how do we handle the data in cases where the user queries gigabytes of data. How many times we copy until the data is in format we want?

**Comment by sfackler** [comment]
If you're loading gigabytes of stuff from a database, it seems like your limiting factor is going to be the server's disk or network rather than memory bandwidth on the client side.
