### ISSUE TITLE
tokio-postgres with futures=0.3 instead of futures-preview ?

### ISSUE THREAD

**Issue by NotSqrt** [sfackler/rust-postgres#519]
Hello !

I'm using tokio-postgres 0.5.0-alpha.1, with `query_raw` and `TryStreamExt` to avoid collecting all the rows in a `Vec`.

```rust
let stream: RowStream = client.query_raw(&statement, slice_iter(params)).await?;
futures::pin_mut!(stream);

use futures::stream::TryStreamExt;
while let Some(row) = stream.try_next().await? {
    // ...
}
```

It compiles with `futures-preview = { version = "=0.3.0-alpha.19", features = ["async-await"] }` (same version used by tokio-postgres), but not with `futures = "0.3.0"` or `futures = "0.3.1"`
The error is:
```
309 |         while let Some(row) = stream.try_next().await? {
    |                                      ^^^^^^^^ method not found in `std::pin::Pin<&mut tokio_postgres::query::RowStream>`
    |
    = note: the method `try_next` exists but the following trait bounds were not satisfied:
            `std::pin::Pin<&mut tokio_postgres::query::RowStream> : futures_util::stream::try_stream::TryStreamExt`
            `tokio_postgres::query::RowStream : futures_util::stream::try_stream::TryStreamExt`
```

Is it logical that it fails when using a different version of `futures` ?

Thanks !

**Comment by sfackler** [comment]
> Is it logical that it fails when using a different version of futures ?

Yes, different crates are different crates.

Once tokio cuts a new release (soonish I think), we'll switch to futures 0.3

**Comment by NotSqrt** [comment]
Ok, so I'll wait for the next tokio release (https://github.com/tokio-rs/tokio/issues/1708), then the next tokio-postgres release.

Before using `query_raw`, I was using `query` + `futures=0.3`, and it seemed a little faster than `query` + `futures-preview=0.3.0-alpha.19`, so I hope to see a boost in performance !

Thanks a lot !

**Comment by djc** [comment]
Do you plan to release a new alpha (or even a final release) based on tokio-0.2 soon?

**Comment by sfackler** [comment]
Yep, I'll cut a new alpha today to unblock people. A stable release should be coming relatively quickly after that, but there's still some cleanup I need to do in the `postgres` crate in particular.

**Comment by sfackler** [comment]
Published!
