### ISSUE TITLE
Cannot share a transaction/connection between threads

### ISSUE THREAD

**Issue by jakedeichert** [sfackler/rust-postgres#521]
First off, thanks for making this and the r2d2 crates! 

So I'm running into a wall trying to pass a transaction to another thread. I saw this issue https://github.com/sfackler/r2d2/issues/95 but decided I should post here instead. I'm using `postgres=0.15.2` and `r2d2-postgres=0.14.0`.

So I've got a test server that starts a hyper service on a background thread. I'm trying to pass a `txn` into that thread so `App` can have a reference to it... this allows my route handlers to use the same transaction and would allow my test server to rollback after all my requests are complete in a test case.

~~~rust
impl TestServer {
    pub fn new(start_server: fn(App)) -> Self {
        let pool = create_pool("postgres://root:root@localhost:5432/db_name".into());
        let conn = pool.get().unwrap(); // PooledConnection<PostgresConnectionManager>
        let txn = conn.transaction().unwrap(); // Transaction

        let tcp = TcpListener::bind("127.0.0.1:0").unwrap();
        let address = tcp.local_addr().unwrap();
        let app = App::from_tcp(tcp);

        thread::spawn(|| {
            // This is just a test... but it won't compile.
            dbg!(txn.execute("SELECT 1", &[]).unwrap());
            start_server(app)
        });

        Self {
            address: address.to_string(),
            headers: HeaderMap::new(),
        }
    }
}
~~~

But I get 2 errors and I'm pretty sure I can't workaround them.

~~~
error[E0277]: `std::cell::Cell<bool>` cannot be shared between threads safely
  --> crates/http-utils/src/test_utils/server.rs:25:9
   |
25 |         thread::spawn(|| {
   |         ^^^^^^^^^^^^^ `std::cell::Cell<bool>` cannot be shared between threads safely
   |
   = help: within `postgres::transaction::Transaction<'_>`, the trait `std::marker::Sync` is not implemented for `std::cell::Cell<bool>`
   = note: required because it appears within the type `postgres::transaction::Transaction<'_>`
   = note: required because of the requirements on the impl of `std::marker::Send` for `&postgres::transaction::Transaction<'_>`
   = note: required because it appears within the type `[closure@crates/http-utils/src/test_utils/server.rs:25:23: 28:10 txn:&postgres::transaction::Transaction<'_>, start_server:&fn(app::App), app:app::App]`
   = note: required by `std::thread::spawn`

error[E0277]: `std::cell::RefCell<postgres::InnerConnection>` cannot be shared between threads safely
  --> crates/http-utils/src/test_utils/server.rs:25:9
   |
25 |         thread::spawn(|| {
   |         ^^^^^^^^^^^^^ `std::cell::RefCell<postgres::InnerConnection>` cannot be shared between threads safely
   |
   = help: within `postgres::transaction::Transaction<'_>`, the trait `std::marker::Sync` is not implemented for `std::cell::RefCell<postgres::InnerConnection>`
   = note: required because it appears within the type `postgres::Connection`
   = note: required because it appears within the type `&postgres::Connection`
   = note: required because it appears within the type `postgres::transaction::Transaction<'_>`
   = note: required because of the requirements on the impl of `std::marker::Send` for `&postgres::transaction::Transaction<'_>`
   = note: required because it appears within the type `[closure@crates/http-utils/src/test_utils/server.rs:25:23: 28:10 txn:&postgres::transaction::Transaction<'_>, start_server:&fn(app::App), app:app::App]`
   = note: required by `std::thread::spawn`
~~~

I'm not sure how to proceed. I think I've reached the limits with this crate and it seems impossible for me to share a transaction reference between threads. 

Is there any workaround you would suggest? 

Or should I give up on trying to share a transaction for multiple api requests inside a single test case?

**Comment by sfackler** [comment]
I'm not sure I fully understand. What's using the connection pool? Is the code just checking out one connection and opening a transaction on that? If so, you can just connect directly on your background thread and not worry about shipping the transaction across thread boundaries.

**Comment by jakedeichert** [comment]
> If so, you can just connect directly on your background thread and not worry about shipping the transaction across thread boundaries.

What I'm trying to do just isn't possible I think. Here's an example... i start the test server on another thread, create an account and then delete an account. My goal here is for both requests to share a single transaction that the `TestServer` manages and then rolls back when this test case completes. This is ideal because it allows test cases to be completely isolated from one another.

```rust
// account_controller_test.rs
#[test]
fn account_deletion() {
    let mut srv = TestServer::new(start_server);
    srv.request(Method::POST, "/account");
    let resp = srv.request(Method::DEL, "/account");
    assert_eq!(resp.status(), StatusCode::OK);
}
```

I've created this exact setup in a node typescript service recently (though single threaded) and i'm trying to recreate it with hyper but it's starting to seem impossible 😅 

I'm completely fine with this not being possible. I'll have to look into alternative test setups unfortunately... like creating + migrating a separate DB per test case or something.

With that said, I really hope there's a future where we can get this to work some how. Please feel free to close this 👍

**Comment by jakedeichert** [comment]
I just found out that hyper has a [single threaded option](https://github.com/hyperium/hyper/blob/master/examples/single_threaded.rs)... I could spin this up when the app is in test mode perhaps to avoid passing a txn/conn between threads. I'll give this a try.

**Comment by jakedeichert** [comment]
Wow... i actually got it working. One transaction shared for the lifetime of a single-threaded hyper server.

So for production I'll run hyper in multi-threaded mode and for the test server it'll run in single-threaded mode so I can rollback all requests made in a single test case 👍

**Comment by sfackler** [comment]
Great, sounds like you're good to go.
