### ISSUE TITLE
copy_out params

### ISSUE THREAD

**Issue by nhphu** [sfackler/rust-postgres#523]
Hi,
When I call method copy_out with this statement
```sql
COPY (SELECT * FROM eurusd
WHERE time >= to_timestamp($1) AND time <= to_timestamp($2)
LIMIT 200000) TO STDOUT BINARY;
```
thread panicked with message "expected 0 parameters but got 2". Why is that? Is there anything wrong in my statement?

**Comment by sfackler** [comment]
That's pretty weird, but it appears to just be the behavior of the Postgres server. You might want to ask in a PostgreSQL-specific support channel?

**Comment by sfackler** [comment]
This seems like a bug in PostgreSQL - if you run the query without passing the parameters in, the database returns an error that it's expecting them:

```
DbError { severity: "ERROR", parsed_severity: Some(Error), code: SqlState("42P02"), message: "there is no parameter $1", detail: None, hint: None, position: Some(Original(80)), where_: None, schema: None, table: None, column: None, datatype: None, constraint: None, file: Some("parse_expr.c"), line: Some(828), routine: Some("transformParamRef") }
```

**Comment by sfackler** [comment]
I filed this upstream: https://www.postgresql.org/message-id/16149-531659f1ce965744%40postgresql.org.

It probably makes sense to remove the parameter list argument from the copy_in and copy_out methods if they can't actually be used though!

**Comment by sfackler** [comment]
The reply to that message says that COPY queries don't support parameters, so I'll remove that argument from the methods.
