### ISSUE TITLE
Best way to write something that requires multiple statements?

### ISSUE THREAD

**Issue by GSGerritsen** [sfackler/rust-postgres#528]
If I have a query that involves, for example, something like `CREATE TEMP TABLE table (...) ON COMMIT DROP;`, which would be followed by a separate insert statement, is the way to go about this by starting a transaction and running a `prepare` + `query` for each component statement? 

Would this result in a separate network request to Postgres for each `query` call inside the transaction? If so, is there a way to have multiple statements run via a single request? I imagine `simple_query` could work for this purpose but then I think I lose the ability to check against SQL injection.

**Comment by sfackler** [comment]
If you need to inject user-provided values into your query, then you should probably use the prepared statement interface. If you don't, you can use simple_query if you'd like.

**Comment by GSGerritsen** [comment]
Yeah, in this case there will be user-provided values, so it looks like I should stick with the prepare interface. Just out of curiosity, why is `query` limited to a single statement? Would it be difficult to extend to multiple statements? 

I imagine it would be beneficial in a few cases (such as mine) to issue multiple statements that have been checked against SQL injection in a single network request.

**Comment by sfackler** [comment]
The protocol does not support multi-statement prepared queries. You would have to ask the PostgreSQL developers about extending that.
