### ISSUE TITLE
Simplest way to implement ToSql for this kind of enum?

### ISSUE THREAD

**Issue by GSGerritsen** [sfackler/rust-postgres#532]
I've searched through the issues / documentation but haven't quite found the right way to go about this yet. I have an enum that looks like this:

    enum Value {
        Int(i32),
        Float(f64),
        StringVal(String),
        Null,
        ListValue(Vec<Value>),
        Object(HashMap<String, Value>)
    }

Implementing `to_sql` would be simple enough for the contained values, as I'd just call the `to_sql` implementation that exists, but what I'm stuck on is how to handle the `ListValue` case. 

Is there a simple way to accomplish this? I know I can't simply derive `ToSql` because this isn't a C-like enum, so it seems that implementing `ToSql` myself is the only way to go.

**Comment by sfackler** [comment]
What Postgres value do you want the ListValue and Object variants to turn into?

**Comment by GSGerritsen** [comment]
For `Object` I want to map this to a JSON value, and for `ListValue` I basically want it to be an array of whatever the inner type is, so `integer[], text[]` etc.

Having said that, there's clearly a little bit of a mismatch between how the Rust enum is defined and how I want `ListValue` to work as a Postgres value, because the `ListValue` could actually contain different types inside. 

I could potentially refactor to make `Value` a trait, which `ListValue` could implement and thus enforce that the inner type implementing `Value` is the same, but if I can avoid that for now that'd be nice.

**Comment by sfackler** [comment]
Yeah, you're not going to be able to use the current definition of ListValue if you want to map down to postgres arrays.

**Comment by GSGerritsen** [comment]
I was eventually able to get around the ListValue issue by converting it to a Postgres array literal as a string, which works for my use-case at least for now.

One final question I have that came out of this is, I now have a `Vec<Value>`, and `Value` now implements `ToSql`. If I want to pass a `Vec<Value>` to `query`, how can I transform it so that it type-checks?

**Comment by sfackler** [comment]
What type(s) do you want to encode a list of Values to? `&Value::Vec(my_list)` is one option.

**Comment by GSGerritsen** [comment]
There isn't really a specific set of types I want to encode the list of Values to, rather I just want to be able to pass it as the `params` argument in `query`. So if the SQL was `select * from user where age = $1 and name = $2`, I'd have a Vec like `[IntValue(28), StringValue("Jack")]`. I assumed simply passing this Vec in as a slice would work in the same way that passing `&[&28, &"Jack"]` would work.

The type error looks like this:
    expected type `&[&dyn postgres_types::ToSql + std::marker::Sync]`
    found type `&[Value]`

Well, as I was writing this I may have figured it out? But maybe you can let me know if this is the right way to do it. I ended up writing:
  
    let params =  vals.iter().map(|v| v as &(dyn ToSql + Sync)).collect::<Vec<&(dyn ToSql + Sync)>>();

Which I can pass to `query`. `vals` is just a `Vec<Value>`. This seems a bit unwieldy but if it works it works. Is there a better way to do it? Thanks for the continued assistance by the way, very much appreciated.

**Comment by sfackler** [comment]
You could also use query_raw to avoid having to collect the references into a Vec: https://docs.rs/postgres/0.17.0/postgres/struct.Client.html#method.query_raw
