### ISSUE TITLE
Feature request:  feature-flagged compile-time-validation

### ISSUE THREAD

**Issue by Dowwie** [sfackler/rust-postgres#533]
The [SQLx project](https://github.com/launchbadge/sqlx) enables compile-time validation of SQL *and* parameter binding.  This is a killer feature worth considering adopting for rust-postgres.

Currently, a developer using rust-postgres has to rely on postgresql server logs, recorded by running tests, to resolve run-time exceptions, such as those related to bound parameters.  This workflow is essentially automated with compile-time validation, bringing errors to the developer rather than requiring a developer to go to postgresql server logs and tracing suspect sql.

**Comment by sfackler** [comment]
I built something sort of like that out a while back: https://github.com/sfackler/rust-postgres-macros. I'm not really super enthused about talking to a database as part of the build process though.

**Comment by Dowwie** [comment]
I remember that one!  It doesn't validate parameter binding, though, does it?

I understand your gut feeling about talking with the database during compiling.  I mulled over this for a while since the SQLx announcement.  My thinking is that this is analogous to the compiler downloading dependencies from crates.io, installing them within a namespace access by the compiler, and then interpreting them in the context of compilation.

**Comment by sfackler** [comment]
It validates the number of parameters, but not their types.

Yeah, I am more of a fan of generating code from a schema as a separate step. That also allows you to integrate it with your migrations or whatever to make sure the database is in the right state before generating.
