### ISSUE TITLE
Adding a generic connection trait to tokio-postgres

### ISSUE THREAD

**Issue by nolanderc** [sfackler/rust-postgres#537]
PR #525 adds a synchronous trait into rust-postgres for synchronous connections, I believe adding a corresponding trait into tokio-postgres would be benefitial. However, since async methods are not yet supported in traits we have to work around it using dynamic dispatch, such as is made possible by https://github.com/dtolnay/async-trait.

I have implemented a limited version in my own project, and would be happy to add a more full-featured version into the main library, if you'd be fine with such a workaround.

**Comment by enzious** [comment]
+1 The old `build_transaction()` was useable.

I just wrote service functions like `insert_upload(db_client, ...) -> (db_client, ...)` with the `build_transaction()` method. This allowed me to organize code that was useable in and outside a transaction.

This new method, a separate Transaction object with no Trait, is pretty cumbersome. Do I really need to write a method for both Client AND Transaction? Or use some kind of strange enum?

**Comment by sfackler** [comment]
Yeah, I think implementing it via async_trait is the way to go here.
