### ISSUE TITLE
restoring meaningful README.md files to the repos

### ISSUE THREAD

**Issue by Dowwie** [sfackler/rust-postgres#540]
If I were new to rust-postgres, I wouldn't know much about it through the front page of github other than it is a workspace of crates.  The README.md was the first thing I found when I discovered rust-postgres 2 years ago.  The README helped me get started, not the api docs.

**Comment by sfackler** [comment]
rust-postgres is just a workspace of crates. The details of the individual crates themselves are in their documentation, which is linked in the README. I don't think it's necessary to maintain docs in both places at once.
