### ISSUE TITLE
No more transaction_with or no Client::bind

### ISSUE THREAD

**Issue by njaard** [sfackler/rust-postgres#543]
I need to create a `Portal`, but I also need to set transaction properties ("`start transaction read only deferrable`"). The only way to create a transaction like that is with `client.execute("start transaction ...")`, but then I don't get a `Transaction` object, which means I can't do anything with a `Portal`.

**Comment by sfackler** [comment]
Ah yeah, we need to add an interface for custom transaction configuration.
