### ISSUE TITLE
no feature flag docs?

### ISSUE THREAD

**Issue by Dowwie** [sfackler/rust-postgres#544]
I can't find any docs on feature flags.  I am familiar with where to look (Cargo.toml) but [others aren't](https://github.com/bikeshedder/deadpool/issues/23)

**Comment by sfackler** [comment]
They are documented in the docs for ToSql and FromSql: https://docs.rs/postgres/0.17.0/postgres/types/trait.ToSql.html#types, but they could probably be made more obvious somehow.

**Comment by bikeshedder** [comment]
I'd like to propose the following style for documenting the features:

https://github.com/bikeshedder/deadpool#features

Actually it would be great if it was possible to document the feature flags in `Cargo.toml` and let `crates.io` generate the documentation for us. There doesn't seam to be an RFC for that, yet. In the mean time a table in the `README.md` does the trick.

**Comment by richlowe** [comment]
It would also be good to mention that the flags now include version numbers, which is hinted at in the `serde_json` example, but not made explicit.  What version numbers are accepted doesn't seem to be in the documentation at all.

**Comment by stepankuzmin** [comment]
Hi everyone! I'm using the latest version of `postgres` crate with `with-serde_json-1` feature enabled, but I still cannot convert column to`serde_json::Value`. Am I missing something?

```
let json_value: serde_json::Value = row.get("properties");
                                            ^^^ the trait `postgres_shared::types::FromSql` is not implemented for `serde_json::value::Value`
```

`Cargo.toml`

```toml
postgres = { version = "0.17.2", features = ["with-serde_json-1"] }
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
```

**Comment by sfackler** [comment]
It looks like you're mixing two versions of postgres - `postgres_shared` is only used in versions older than 0.17.
