### ISSUE TITLE
tokio-postgres is missing derive feature of postgres-types

### ISSUE THREAD

**Issue by qoh** [sfackler/rust-postgres#547]
Additionally, when adding it as per https://github.com/qoh/rust-postgres/commit/20fa4866ab6c1cb5ca0625d519d4fa1405de507e, it seems that postgres-derive assumes that postgres-types is a root visible crate:

```rust
use tokio_postgres::types::FromSql;
```

```
error[E0433]: failed to resolve: use of undeclared type or module `postgres_types`
  --> example/src/lib.rs:78:30
   |
78 | #[derive(Debug, Clone, FromSql)]
   |                        ^^^^^^^ use of undeclared type or module `postgres_types
`
```

**Comment by sfackler** [comment]
> Additionally, when adding it as per [qoh@20fa486](https://github.com/qoh/rust-postgres/commit/20fa4866ab6c1cb5ca0625d519d4fa1405de507e), it seems that postgres-derive assumes that postgres-types is a root visible crate

Yes, that's why tokio-postgres doesn't have that feature.

**Comment by realaltffour** [comment]
> > Additionally, when adding it as per [qoh@20fa486](https://github.com/qoh/rust-postgres/commit/20fa4866ab6c1cb5ca0625d519d4fa1405de507e), it seems that postgres-derive assumes that postgres-types is a root visible crate
> 
> Yes, that's why tokio-postgres doesn't have that feature.

Is there a way to use the derive features then?

**Comment by sfackler** [comment]
You can depend on the postgres_types crate.
