### ISSUE TITLE
Error compiling postgres-0.17.0 on rust 1.39.0

### ISSUE THREAD

**Issue by AnubhabB** [sfackler/rust-postgres#548]
`rustc 1.39.0 (4560ea788 2019-11-04)`
`cargo 1.39.0 (1c6ec66d5 2019-09-30)`
`postgres = "0.17.0"`

System: MacOS Catalina (v10.15.2) on a Intel Core i7

Error:
```
error[E0658]: the `#[non_exhaustive]` attribute is an experimental feature
  --> /Users/anubhab/.cargo/registry/src/github.com-1ecc6299db9ec823/postgres-protocol-0.5.0/src/message/backend.rs:75:1
   |
75 | #[non_exhaustive]
   | ^^^^^^^^^^^^^^^^^
   |
   = note: for more information, see https://github.com/rust-lang/rust/issues/44109

error: aborting due to previous error
```

Looks like the `postgres-protocol = "0.5.0"` used by `postgres = "0.17.0"` is the issue.

Am I missing something obvious?

**Comment by sfackler** [comment]
You need to upgrade your compiler to 1.40.
