### ISSUE TITLE
ERROR: prepared statement "s0" already exists.

### ISSUE THREAD

**Issue by Edu4rdSHL** [sfackler/rust-postgres#550]
Hello, I have been using rust-postgres since months ago and with the latest release I have started getting the following message error when doing a simple query:

`Error: db error: ERROR: prepared statement "s0" already exists.`

The code is:

https://github.com/Edu4rdSHL/findomain/blob/8d5c921a0666b5bd181ad9dab02da4b1cb5d0a3f/src/lib.rs#L409-L441 and the query I'm doing: https://github.com/Edu4rdSHL/findomain/blob/8d5c921a0666b5bd181ad9dab02da4b1cb5d0a3f/src/lib.rs#L196

I have also tried preparing the transaction and the same error happens. Using the `psql` command in my linux machine works fine. Thanks in advance.

**Comment by sfackler** [comment]
That's very strange, and I'm not sure how that would be happening from looking at the code. Could you put together a minimal bit of code that reproduces the problem?

**Comment by sfackler** [comment]
Oh, I actually think this has happened before: https://github.com/sfackler/rust-postgres/issues/444.

You'll probably need to use the simple_query API rather than query if the crt.sh database doesn't handle prepared statements properly.

**Comment by Edu4rdSHL** [comment]
I saw that issue before, still seeing the documentation and examples I didn't see how to use it to return a proper DB query. According to docs, it returns a [SimpleQueryRow](https://docs.rs/postgres/0.17.0/postgres/row/struct.SimpleQueryRow.html) that may have `get()` method for example but when I try `get()` method it says:

```
└─ ▶ cargo build
   Compiling findomain v0.9.5 (/home/sechacklabs/Projects/Rust/Development/findomain)
error[E0599]: no method named `get` found for type `&tokio_postgres::SimpleQueryMessage` in the current scope
   --> src/lib.rs:415:45
    |
415 | ...                   NAME_VALUE: row.get("NAME_VALUE"),
    |                                       ^^^ method not found in `&tokio_postgres::SimpleQueryMessage`

error: aborting due to previous error

For more information about this error, try `rustc --explain E0599`.
error: could not compile `findomain`.

To learn more, run the command again with --verbose.
```

**Comment by sfackler** [comment]
Simple rows can only be accessed by index, not by column name.

**Comment by sfackler** [comment]
Also, SimpleQueryMessage is an enum, so you'll need to match on that to get the row out: https://docs.rs/postgres/0.17.0/postgres/enum.SimpleQueryMessage.html

**Comment by Edu4rdSHL** [comment]
Thanks, it have been fixed in https://github.com/Edu4rdSHL/findomain/commit/7cd35210d4a8da39688354d565d9768afe117e50, anyways I though it's too long to access a row value compared with `query()`.
