### ISSUE TITLE
filtering for spesific column not null is not working

### ISSUE THREAD

**Issue by julienJean99** [sfackler/rust-postgres#554]
hi, I have this code which within the parameter the name of a column.

this request is supposed to return the first rows with the column name of the request is not null

``` 
let rows = match client
	.query("SELECT * FROM planet_osm_point WHERE $1::text IS NOT NULL LIMIT 1",
		   &[&request.request])
	.await {
		Ok(row) => row,
		Err(e)  => {
			match request.sender.send(Some(format!("base: {}", e).to_string())) {
				Ok(_) => {},
				Err(e) => println!("oops could not send response {:?}", e)
			};
			continue
		}
	};
println!("request is {:?}", &rows[0].try_get::<&str, String>(&request.request));
```

but in the try_get return :

`Err(Error { kind: FromSql(40), cause: Some(WasNull) })`

here is my tmol

```
tokio-postgres = "0.5.1"
tokio = {version = "0.2.6", features = ["full"]}
```

what should I do to ensure the column is not null (as a side note I tried this exact request on a PostgreSQL client and it works fine).

**Comment by sfackler** [comment]
Query parameters don’t work that way. That query is checking if the parameter string itself is not null, not if the column with that name is not null.

**Comment by julienJean99** [comment]
thank you for the answer. how can I get the behavior I want?

**Comment by sfackler** [comment]
You would have to create the query string yourself.
