### ISSUE TITLE
Can I pass the returned rows from one query as params to another?

### ISSUE THREAD

**Issue by GSGerritsen** [sfackler/rust-postgres#555]
It might look like this:

    let rows = client.query(statement_one, supplied_params).await.unwrap();
    let next_rows = client.query(statement_two, rows).await.unwrap();

Is there a transformation I can apply to `rows` so that the contents are `dyn ToSql + Sync` without knowing the types that those row values would deserialize to? So far I have tried something like this:

    let next_params = rows.iter().enumerate().map(|(i, r)| r.get(i) as &(dyn ToSql + Sync)).collect::<Vec<&(dyn ToSql + Sync)>>();

This doesn't work because `get` cannot infer a type for `T`. I suspect this might not be possible but just wanted to check.

**Comment by sfackler** [comment]
You should be able to do this with a little custom type: https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=35c8475ebf9ad516d34349452b6261e1.

**Comment by GSGerritsen** [comment]
If I'm understanding correctly, I would need to know the `Type`  of `row.get(i)`, then wrap it in a`RawValue` to be able to cast it to `dyn ToSql + Sync`? 

So I would grab the `Type` from `row.columns[i]`, and is the output type `T` for `row.get(i)` the `Option<&'a [u8]>`?

Something like: 

    for r in rows {
        let type = rows.columns[i];
        let raw = rows.get::<usize, Option<& [u8]>>(i);
        let raw_value = RawValue{ type, raw };
        next_params.push(raw_value as &(dyn ToSql + Sync);
    }

**Comment by sfackler** [comment]
No, you'd just use the FromSql implementation:

```rust
let raw_value = row.get(i).unwrap();
```

**Comment by GSGerritsen** [comment]
Ah, should have finished my coffee I guess. Thanks a ton, this is working now.
