### ISSUE TITLE
Eager requests with pipelining

### ISSUE THREAD

**Issue by namibj** [sfackler/rust-postgres#556]
It would be great to attempt sending (and queuing when network would block) the request when `Client::query` is called, instead of deferring this until the future is polled. The benefit would be that results could already be waiting if enough compute or unrelated future waiting happens before the future is `await`ed.

Note that the claim

> In both cases, the PostgreSQL server is executing the queries sequentially - pipelining just allows both sides of the connection to work concurrently when possible.

[explicitly](https://www.cockroachlabs.com/docs/v19.2/architecture/transaction-layer.html#transaction-pipelining) does not apply to CockroachDB.

Also, for various reasons, one is strongly incentivized to send early. It would be great if tokio-postgres would (at least optionally) support this. There are certainly ways around it, but I don't see any clean workaround.

**Comment by sfackler** [comment]
Can you show me some code where you need to perform significant amounts of logic after creation of a future but before running it?
