### ISSUE TITLE
Having trouble inserting a timestamp column

### ISSUE THREAD

**Issue by toadzky** [sfackler/rust-postgres#569]
I've got a table with a timestamp column and I've tried using `chrono`'s `DateTime` as well as just a string value that is cast in my sql query but it always comes back with a wrong type error.
```
Error { kind: ToSql(8), cause: Some(WrongType { postgres: Type(Timestamp), rust: "chrono::datetime::DateTime<chrono::offset::utc::Utc>" }) }
```
Is there an example somewhere of how to insert timestamps?

**Comment by sfackler** [comment]
You need to use the Postgres `TIMESTAMP WITH TIME ZONE` type to interact with `DateTime<Utc>`. The chrono `NaiveDateTime` type interacts with `TIMESTAMP`.

**Comment by toadzky** [comment]
Thank you.
