### ISSUE TITLE
Error kind is private

### ISSUE THREAD

**Issue by m-lima** [sfackler/rust-postgres#571]
On `tokio-postgres::error`, `Kind` is a private `enum` as well as a private field inside `ErrorInner`.
There is no way of asserting the error except for parsing the string that comes out of the `Display` implementation for `Error`

For example:
In both line 455: `pub(crate) fn column(column: String)`
and line 479: `pub(crate) fn row_count()`
the errors are created with no cause, only kind. And the only way to extract that information and discern between the two is by comparing the output of the `Display` implementation.

Am I missing something or not seeing a way to assess the error kind and take action accordingly?

**Comment by sfackler** [comment]
Could you be more specific about what actions you want to take in response to errors?

**Comment by m-lima** [comment]
The application is a warp server. When I do `query_one` and no items are found I get an error back (`Kind::RowCount`) signaling that no entries were found.
I cannot, however, differentiate this error easily (without parsing the String representation) and giving a sensible response to the client (in this case I wish to return a 404 Not Found)

**Comment by sfackler** [comment]
I'd just use query_opt instead and avoid having to deal with figuring out which kind of error it is in the first place.

**Comment by the-anonymous009** [comment]
Why is this issue is closed?  This is issue is not just about query_opt method. There are many cases that clients need to take different action on different kind of error but there is no easy way to do it when cause is None.
