### ISSUE TITLE
Consider exposing the `slice_iter` utility function in the public interface

### ISSUE THREAD

**Issue by aloucks** [sfackler/rust-postgres#573]
I struggled for quite a while with `Client::query_raw`. I wasn't able to get usage of it to compile until I found the `slice_iter` helper function in the `tokio-postgres` code. As far as I can tell, you pretty much have to re-implement that function in order to use `query_raw`.

**Comment by sfackler** [comment]
slice_iter is just an internal function to adjust the codegen a bit. The master branch has an example of using query_raw: https://github.com/sfackler/rust-postgres/blob/master/tokio-postgres/src/client.rs#L333
