### ISSUE TITLE
Named parameters not supported?

### ISSUE THREAD

**Issue by mamcx** [sfackler/rust-postgres#579]
Is my impression or named parameters are not supported? Is much more ergonomic to use them than positional (names are more relational).

In sqlite: https://github.com/jgallagher/rusqlite/blob/master/src/lib.rs is supported the style `:name`, so could be a good idea to reuse it.

**Comment by sfackler** [comment]
The syntax of query parameters is designed by the PostgreSQL and SQLite developers, not me. If you want Postgres to add support for `:name`, you'd need to make a request upstream with them.

**Comment by mamcx** [comment]
In other languages that I have used (.net, delphi, python, go, obj-c, swift) I could use named params in Postgres and other rdbms.

**Comment by sfackler** [comment]
Those drivers may be rewriting the query or something, I'm not sure.

**Comment by sfackler** [comment]
This crate is focused on providing an interface to what Postgres provides, so any extra query interpolation would best be handled externally.
