### ISSUE TITLE
Allow deriving Type for custom Enums

### ISSUE THREAD

**Issue by oberien** [sfackler/rust-postgres#585]
I'm using COPY IN with FORMAT binary with custom enums. The `BinaryCopyInWriter::new` function requires a list of Types for serialization. However, getting the type of a custom enum on which `ToSql` is derived seems to be non-trivial.

Assume the following enum:
```rust
#[derive(Debug, ToSql)]
pub enum Foo {
    VariantA,
    VariantB,
    VariantC,
}
```
Currently, I need to manually write out the type (and keep it synchronized by hand) like this:
```rust
Type::new(
    "Foo".to_string(),
    0, // Oid, not relevant
    Kind::Enum(vec![
        "VariantA".to_string(),
        "VariantB".to_string(),
        "VariantC".to_string(),
    ]),
    "".to_string(), // schema, not relevant
)
```

I see 3 possible solutions:
1. Allow `Type::TEXT` as Type for enums, because that's what they are serialized as anyways.
2. Create a new derivable trait `GetType` (or some other name):
    ```rust
    impl GetType for Foo {
        fn type() -> Type {
            Type::new(...)
        }
    }
    ```
    * Another idea was to create an associated constant. However `Type::new` would need to be a const-fn and `vec![]` would need to be const as well, which isn't the case. So that option is not possible (yet).
3. Add another associated constant to `Type`, which can be used as a placeholder for custom enums, similar to what `anyenum` is for binary functions. I don't know enough about the postgres ABI, but maybe just using `anyenum` here would already be possible?

Solutions (1) and (3) are only focusing on enums. However, the same should probably also be possible for custom struct types.

**Comment by sfackler** [comment]
A better solution IMO would be to just prepare a one-off query to get the real Type from the server:

```rust
client.prepare("SELECT $1::myenum")?.params()[0].clone()
```

**Comment by sfackler** [comment]
The OID of custom types is set by the database backend when they are defined. There is no way to determine it at compile time.

**Comment by seanlinsley** [comment]
Is the OID actually needed? It seems to work from my and the OP's testing.

**Comment by sfackler** [comment]
Oh sorry I misremembered. It just relies on the `Type`s to handle the data conversions.

If you don't care about that, you can just pass in an arbitrary type and have your `ToSql` implementation ignore that argument.

Alternatively you can always write your own binary copy stream.

**Comment by sfackler** [comment]
Or, you can just instantiate the Tuype with a bogus OID yourself: https://docs.rs/postgres-types/latest/postgres_types/struct.Type.html#method.new. I don't think I'd want to add a feature to make that any easier though, since the lack of a correct OID will break usage of the type in other contexts.
