### ISSUE TITLE
New release of postgres-protocol

### ISSUE THREAD

**Issue by benesch** [sfackler/rust-postgres#586]
When you have a minute, it would be great to get https://github.com/sfackler/rust-postgres/commit/0fb9ede350f0346f7e1a45af92aa53193da7437b into a release. (Apologies—I know how exhausting this is!)

**Comment by sfackler** [comment]
Done! No worries about bugging me about releases - I generally don't release all that often, so feel free to ping if you want to pick up a change.

**Comment by benesch** [comment]
Good to know—and thanks!
