### ISSUE TITLE
Listen / Notify Async Example

### ISSUE THREAD

**Issue by riendegris** [sfackler/rust-postgres#591]
Hello,

This is kind of a follow up on my trials and tribulations to get notifications working. Since I'm struggling, I can only assume that others may be having difficulties getting it to work, and having an example may help them get on track faster. So I have this sample [project](https://github.com/riendegris/test-listen), which should just connect to a db configured to emit notifications, and print them...

I would not presume to author the mechanism for connecting and listening to notifications: it has been mostly extracted from tests in `tokio_postgres`. Yet I can't get it to work, so I'm not sure what's missing, and I welcome suggestions. Thanks.

Here is the `main.rs`

```
use futures::future;
use futures::{stream, FutureExt, Stream, StreamExt, TryStreamExt};
use snafu::{Backtrace, ResultExt, Snafu};
use std::io;
use tokio::net::TcpStream;
use tokio_postgres::tls::{NoTls, NoTlsStream};
use tokio_postgres::{config::Host, AsyncMessage, Client, Config, Connection};

#[derive(Debug, Snafu)]
pub enum Error {
    #[snafu(display("User Error: {}", details))]
    #[snafu(visibility(pub))]
    UserError { details: String },

    #[snafu(display("IO Error: {}", source))]
    #[snafu(visibility(pub))]
    IOError {
        source: io::Error,
        backtrace: Backtrace,
    },

    #[snafu(display("DB Connection Error: {}", source))]
    #[snafu(visibility(pub))]
    DBError {
        source: tokio_postgres::Error,
        backtrace: Backtrace,
    },
}

#[tokio::main]
async fn main() -> Result<(), Error> {
    let connstr = String::from("postgresql://user:pwd@postgres/journal");
    let mut stream = get_stream(&connstr).await?;

    while let Ok(n) = stream.try_next().await {
        if let Some(msg) = n {
            println!("Received notification: {}", msg);
        }
    }

    Ok(())
}

async fn get_stream(
    connstr: &str,
) -> Result<impl Stream<Item = Result<String, Error>> + Send + 'static, Error> {
    let (client, mut connection) = connect_raw(connstr).await?;

    let (tx, rx) = futures::channel::mpsc::unbounded();
    let stream = stream::poll_fn(move |cx| connection.poll_message(cx)).map_err(|e| panic!(e));
    let connection = stream.forward(tx).map(|r| r.expect("stream forward"));
    tokio::spawn(connection);
    println!("Spawned dedicated connection for postgres notifications");

    client
        .batch_execute("LISTEN documents;")
        .await
        .context(DBError)?;

    Ok(rx.filter_map(|m| match m {
        AsyncMessage::Notification(n) => {
            println!("Received notification on channel: {}", n.channel());
            future::ready(Some(Ok(format!("{} : {}", n.channel(), n.payload()))))
        }
        _ => {
            println!("Received something on channel that is not a notification.");
            future::ready(None)
        }
    }))
}

async fn connect_raw(s: &str) -> Result<(Client, Connection<TcpStream, NoTlsStream>), Error> {
    let config = s.parse::<Config>().context(DBError)?;
    let host = config
        .get_hosts()
        .first()
        .ok_or(Error::UserError {
            details: String::from("Missing host"),
        })
        .and_then(|h| match h {
            Host::Tcp(remote) => Ok(remote),
            Host::Unix(_) => Err(Error::UserError {
                details: String::from("No local socket"),
            }),
        })?;
    let port = config.get_ports().first().ok_or(Error::UserError {
        details: String::from("Missing port"),
    })?;

    let conn = format!("{}:{}", host, port);
    println!("Connecting to {}", conn);
    let socket = TcpStream::connect(conn).await.context(IOError)?;
    config.connect_raw(socket, NoTls).await.context(DBError)
}
```

**Comment by sfackler** [comment]
A fully self contained example that exhibits unexpected behavior would be helpful.

**Comment by riendegris** [comment]
> exhibits unexpected behavior would be helpful

I'm not sure I follow you

**Comment by sfackler** [comment]
If I compile and run this code, what should happen, and what will happen? Do I need to have some other process sending notifications? etc.

**Comment by riendegris** [comment]
Hello, I've updated the example [here](https://github.com/riendegris/test-listen)

It's easier to setup and run the example (I think). I'm not sure what a proper example would look like, I tried to balance ease of use (all in the rust file, multiple tasks) against a more realistic setup (remote db, separate process, ...)

I would expect the program to connect to the specified database, subscribe to a channel, and prints the notifications to stdout. But I have an error:

```
thread 'main' panicked at 'Receiver::next_message called after `None`', 
```

 I think this example looks fairly close to what's in the `tokio-postgres` test.

Thank you for your time and effort on this

**Comment by sfackler** [comment]
The connection closes when the client associated with it drops when get_stream returns.

**Comment by riendegris** [comment]
Thank you Steven. Your comment enabled me to fix the example, which now seem to work correctly.

That was the good news....

Now... I mapped this modification to my original code, where I stream notifications to a warp sse channel. When I connect a client (eg curl) to that endpoint, it gets immediately disconnected (without error).

I wonder if the `stream.forward(tx)` is not the issue:

> This future will drive the stream to keep producing items until it is exhausted,

The following is from the `Forward`: If when polling the stream we get `None`, then we do close the sink (`tx`):

```
Poll::Ready(None) => {
                    ready!(self.as_mut().sink().as_pin_mut().expect(INVALID_POLL).poll_close(cx))?;
                    self.as_mut().sink().set(None);
                    return Poll::Ready(Ok(()))
```

I'm researching if another stream combinator may just keep the stream opened if no notification is available.

**Comment by sfackler** [comment]
If no notification is available, the stream should inddicate that via Poll::Pending, not Poll::REady(None).

**Comment by riendegris** [comment]
Right now I have 2 versions, neither of which is working:

## version 1

1. Create (tx, rx) pair because we need 'Sync'
2. Create (client, conn)
3. Create a stream by polling the connection
4. Connect the stream to sink, sending AsyncMessages to the channel.
5. Spawn that (what ever _that_ is)
6. Send a request for notifications with the client.
7. Connect whatever rx to sse.

=> What happens in that case is the 'LISTEN' statement gets received by the database, but the request to a sse stream gets immediately disconnected. I'm not sure why. Probably the connection spawned gets immediately shutdown?

## version 2

Here, most of the code is spawned:

1. Create (tx, rx) pair
2. Spawn a task which
   2.1 Create (client, connection)
   2.2 Create stream by polling the connection
   2.3 Subscribe to notifications (send statement LISTEN)
   2.4 Create a sink by looping over with `stream.next().await`
3 Connect the rx, just like in the first case

=> What happens in that case, 'LISTEN' is never received by the database, BUT the sse client is not disconnected.

So I'm really at a loss, I've thrown almost all my brain at it (almost, because I keep on having ideas from time to time, but its always a fustrating experience) and I'm wondering if there is a solution. 

Below are the relevant parts of both solutions:

__solution 1__

```
    let feed = warp::path("feed").and(warp::get()).and_then(|| async move {
        let (tx, rx) = futures::channel::mpsc::unbounded();
        let (client, mut connection) = connect_raw("postgresql://journaladmin:secret@postgres/journal").await.unwrap();
        let mut stream = stream::poll_fn(move |cx| connection.poll_message(cx)).map_err(|e| panic!(e));
        let connection = stream.forward(tx).map(|r| r.expect("stream forward"));
        tokio::spawn(connection);
        client.execute("LISTEN documents;", &[]).awai..context(error::DBError).unwrap();
        debug!("Spawned dedicated connection for postgres notifications");
        let stream = make_stream(rx).unwrap();
        make_infallible(sse::reply(sse::keep_alive().stream(stream)))
});
```

__solution_2__

```
   let feed = warp::path("feed").and(warp::get()).and_then(|| async move {
        let (mut tx, mut rx) = mpsc::channel(1024);
        tokio::spawn(async move {
            let (client, mut connection) =j
                connect_raw("postgresql://journaladmin:secret@postgres/journal").await.unwrap();

            let mut stream =
                stream::poll_fn(move |cx| connection.poll_message(cx)).map_err(|e| panic!(e));
            client.execute("LISTEN documents;", &[]) .await .context(error::DBError).unwrap();

            while let Some(item) = stream.next().await {
                let n = item.unwrap();
                match n {
                    AsyncMessage::Notification(notif) => {
                        tx.send(AsyncMessage::Notification(notif)).await;
                    }
                    _ => {
                        debug!("Not Sending ??? to tx");
                    }
                }
            }
        });
        debug!("Spawned dedicated connection for postgres notifications");
        let stream = make_stream(rx).unwrap();
        make_infallible(sse::reply(sse::keep_alive().stream(stream)))
    });
```

**Comment by asonix** [comment]
what I've done in one of my projects, is a
```rust
loop {
  (client, conn) = // connect... wait & continue loop on failure
  let client = Arc::new(client);
  let client2 = client.clone();
  spawn(async move { /* listen command with client2 */ })
  let stream = poll_fn(move |cx| conn.poll_message(cx));
  loop {
    match stream.next().await {
      Some(Ok(_)) => // do something with message
      Some(Err(_)) => break // inner loop
      None => break // inner loop
  }
  // the client must live as long as the stream
  // on client drop, the stream is closed
  // by explicitly dropping the client after the stream loop is broken,
  // we ensure the lifetimes are correct.
  drop(client);
}
```

**Comment by sfackler** [comment]
As I already mentioned before, in solution 1 the connection closes as soon as the client drops, which happens as soon as that function returns.

In solution 2, you're leaving the future wrapping the connection just sitting when you try to make the query. The connection is the thing that communicates over the network with the database. If it isn't running, your query isn't going to complete.

**Comment by riendegris** [comment]
I got the solution to work, by inserting 

```
tokio::spawn(async move {
  loop { }
  drop (client)
})
```
after the client sends its LISTEN command. The purpose of this thread is to take ownership of the client, and don't let it die...

There are probably better ways of achieving this...

Thanks @asonix for your suggestion as well.
