### ISSUE TITLE
rust-postgres connection pool

### ISSUE THREAD

**Issue by yonathanYPP** [sfackler/rust-postgres#593]
I need to clone a client and parsing it to some of my function, but it seems not working, because client not implement copy trait, i have tried to use r2d2_postgres but it seems doesn't work for me (because the example is minimalize). What am i looking for is... i want to declare a connection only once and parsing the client across some of my functions. Any suggestion? i really love this native rust-postgres, but i have to declare the connection every time i run a query, and this is affect my api performa. please help me

**Comment by sfackler** [comment]
You cannot clone a client; it is a stateful connection to the database. r2d2_postgres is a connection pool you can use.

**Comment by yonathanYPP** [comment]
is r2d2_postgres also implement prepare function?

**Comment by sfackler** [comment]
r2d2_postgres just gives you postgres::Clients.
