### ISSUE TITLE
How to save or fetch data with AsyncWrite/AsyncRead?

### ISSUE THREAD

**Issue by ufoscout** [sfackler/rust-postgres#595]
I found [here](https://github.com/sfackler/rust-postgres/blob/master/tokio-postgres/tests/test/binary_copy.rs) some good examples on how to select and insert BYTEA data with tokio-postgres; anyway, I cannot figure out how to achieve the same with async data sources.

For example, I have this table:
```sql
create table SAMPLE_BINARY_STORE (
    filename    TEXT NOT NULL,
    data  BYTEA
);
```

I need to:
- insert a new row in the table filling the `data` directly from an AsyncRead
- select by filename and stream the `data` directly into an AsyncWrite

Is there a way to achieve it? Is there an example somewhere that uses the AsyncRead/AsyncWrite of the `futures` crate or `tokio`?

**Comment by sfackler** [comment]
You may want to use the large object API: https://www.postgresql.org/docs/12/largeobjects.html

**Comment by ufoscout** [comment]
@sfackler  
Can't I do it with tokio-postgres? Do I need to use the libpq instead?

**Comment by sfackler** [comment]
Oops, wrong bit of documentation: https://www.postgresql.org/docs/12/lo-funcs.html

**Comment by ufoscout** [comment]
@sfackler 
from the documetation you linked:
> These two functions read and write files in the server's file system, using the permissions of the database's owning user. Therefore, by default, their use is restricted to superusers. In contrast, the client-side import and export functions read and write files in the client's file system, using the permissions of the client program.

If I correctly understood, those functions are explicitly for files on the files system, but I need something more abstract, for example, I need to stream the binary data from the DB directly to an HttpResponse without loading the whole file content in memory.

For example, in JAVA I would achieve it with:
```java
ResultSet rset = stmt.executeQuery 
                 ("select GIFDATA from streamexample where NAME='LESLIE'");

// get first row
if (rset.next())
{
      // Get the GIF data as a stream from the DB
      InputStream gif_data = rset.getBinaryStream (1);
      // write it to a file, but it could be whatever output stream
      FileOutputStream file = new FileOutputStream ("leslie.gif");
      int chunk;
      while ((chunk = gif_data.read()) != -1) {
         file.write(chunk);
      }
   }
```

**Comment by sfackler** [comment]
Postgres fully buffers rows that it sends and receives. That input stream is actually backed by a byte array internally. If you want to store files that are too large to fully buffer, than you would want to use the large object API.

That page talks about more than 2 functions. You create a large object with `lo_creat`, open it with `lo_open`, write to it with `lo_put`, etc.

**Comment by ufoscout** [comment]
Ok, thanks, now I understood how it works under the hood. 
I'll use https://github.com/sfackler/rust-postgres-large-object as an example of how to use the `lo_*` functions 
Hopefully, it will be ported to tokio-postgres one day.

Regarding the `BYTEA` column type, I have a question at this point, if the content is anyway fully loaded into memory, would you see any difference between using a `BYTEA` column to save binary data and using a `JSONB` column to save objects with this structure
```rust
struct {
   filename: String,
   data: Vec<u8>
}
```
where the binary content is saved as a `Vec<u8>` in the JSON itself?

**Comment by sfackler** [comment]
The bytea data will be more efficiently encoded when sent to and from the server. Not sure about how it would behave otherwise.

**Comment by ufoscout** [comment]
@sfackler 
I discussed this with some colleagues and, after performing some tests, I confirm that this Java code does not load the entire BYTEA data into the client memory but it effectively streams it:

```Java
ResultSet rset = stmt.executeQuery 
                 ("select GIFDATA from streamexample where NAME='LESLIE'");

// get first row
if (rset.next())
{
      // Get the GIF data as a stream from the DB
      InputStream gif_data = rset.getBinaryStream (1);
      // write it to a file, but it could be whatever output stream
      FileOutputStream file = new FileOutputStream ("leslie.gif");
      int chunk;
      while ((chunk = gif_data.read()) != -1) {
         file.write(chunk);
      }
   }
```
this allows us to insert and fetch many big files in parallel with no memory issues.

**Comment by sfackler** [comment]
That does not appear to be the case: https://github.com/pgjdbc/pgjdbc/blob/b80ebcef33f9c3801f01e28994746bc36abb2d21/pgjdbc/src/main/java/org/postgresql/jdbc/PgResultSet.java#L2457

**Comment by ufoscout** [comment]
@sfackler you are right. The Java code was using Large Object and the `getBlob()` method.
