### ISSUE TITLE
Accept String in FromSql for all postgres types

### ISSUE THREAD

**Issue by maresc-g** [sfackler/rust-postgres#597]
Hi,

I am trying to write a small psql-like program and so I need to execute user queries and display the result.

I managed to kinda do what I wanted with simple_query like so :
``` rust
for message in client.simple_query(buffer.as_str()).unwrap() {
    match message {
        SimpleQueryMessage::Row(row) => {
            for i in 0..row.len() {
                println!("{:?}", row.get(i));
            }
        }
         _ => {},
    }
}
```

But I can't get the column names since it is private, plus I would have still liked to know the type of the row so I could display the value differently depending on the type.

My first attempt was to do something like this :
``` rust
for row in client.query(buffer.as_str(), &[]).unwrap() {
    let mut i = 0;
    for c in row.columns() {
        let s : String = row.get(i);
        println!("c({}, {}) = {}", c.name(), c.type_(), s);
        i += 1;
    }
}
```

But this raises a WrongType error if the column is not a string.
Hence my question : wouldn't it be useful to allow all types to be converted to String ?

Sorry if I missed something obvious, I am quite new to rust.

**Comment by sfackler** [comment]
If you want to handle different types in different ways anyway, why do you need all the values as strings?

**Comment by maresc-g** [comment]
I am not planning to do something very specific for each type, maybe displaying strings, integers, numerics in a different colors, things like that.

Plus, if I need to know every type it wouldn't work for custom types.

**Comment by sfackler** [comment]
You could pass the same query to `prepare` and then `simple_query` to get both column names and types and the values as strings.

**Comment by maresc-g** [comment]
Ok this works well enough, thanks !
