### ISSUE TITLE
Switching database inside an open connection

### ISSUE THREAD

**Issue by xrl** [sfackler/rust-postgres#599]
Is it possible to switch databases similar to how psql has `\c $dbname`? I tried by control character but it didn't work. Is psql doing a reconnection under the hood or sending some kind of control message over the socket?

My use case, I'm instantiating new app databases as the RDS master user, then I need to switch from the `postgres` database to the new app database so I can install some extensions in its schema. Right now I'm writing code to open a second tokio-postgres connection and that's working but it seems sub-optimal.

**Comment by sfackler** [comment]
`\c` just makes a new connection: https://www.postgresql.org/docs/current/app-psql.html#APP-PSQL-META-COMMANDS

**Comment by xrl** [comment]
Thought that might be the case! I'm going to close this.
