### ISSUE TITLE
Can BinaryCopyInWriter be reused?

### ISSUE THREAD

**Issue by mcamou** [sfackler/rust-postgres#602]
I have an application where we're using the `BinaryCopyInWriter` to copy data into Postgres. I would like to know whether the `BinaryCopyInWriter` can be created just once, and then reused after calling `.finish()` (similar to a normal Prepared Statement), or do we need to create a new one each time? Same thing regarding the sink created by `client.copy_in()`.

**Comment by sfackler** [comment]
No. finish takes self by value: https://docs.rs/postgres/0.17.3/postgres/struct.CopyInWriter.html#method.finish
