### ISSUE TITLE
Lack of 'ToSql' and 'FromSql' tutorial/example. 

### ISSUE THREAD

**Issue by tomus85** [sfackler/rust-postgres#607]
Hey, I've come across this package and so far I'm liking it. However, I am stuck on custom-defined types. Where is an example in PostgreSQL
```
CREATE TYPE prize AS ENUM('gold', 'silver', 'bronze');

CREATE TABLE Package(
 id SERIAL NOT NULL,
name VARCHAR NOT NULL,
prize PRIZE
)
```

As shown that `prize` is a user-defined type and also nullable.
Here is my struct example in rust
```
use postgres::types::{ToSql, FromSql, Type, IsNull, to_sql_checked};
use bytes::BytesMut;
use std::error::Error;

#[derive(Debug)]
struct Package {
  id: u32,
 name: String,
prize: Option<Prize>,
}

impl Package {
  fn new(name: String) -> Package {
      Package {
           id: -1,
          name: name.to_owned(),
         prize: None,
      }
 }
}

#[derive(Debug)]
enum Prize {
 gold,
silver,
bronze
}
```

I've tried looking through the documentation and can't see to find any examples. However, this is what I have come up with and struggling to find the right implmentation.

```
impl ToSql for DomainFilter {
    fn to_sql(&self, _ty: &Type, out: &mut BytesMut) -> Result<IsNull, Box<dyn Error + 'static + Send + Sync>> {
        match *self {
            Prize::gold => out.extend_from_slice(b"gold"),
            Prize::silver => out.extend_from_slice(b"silver"),
            Prize::bronze => out.extend_from_slice(b"bronze"),
        };

        Ok(IsNull::No)
    }
    
    fn accepts(ty: &Type) -> bool {
        ty.name() == "prize"
    }

    to_sql_checked!();
}
```

So far this compiles but I'm not sure if the coding above takes into consideration of nullable types: Option<Prize>. 

I can't seem to find a good example of `FromSql` Was wondering if anybody can point out or provide a snippet. I noticed that `from_sql_null` and `from_sql_nullable` are both provided methods, not required. Do I still need to implement these methods because prize is nan Option type. 

Hope to hear from you guys soon 

Cheers

**Comment by sfackler** [comment]
I would recommend using the deriving support for that implementation: https://docs.rs/postgres-types/0.1.1/postgres_types/#derive

**Comment by tomus85** [comment]
Thank you very much, this has solved the issue.
