### ISSUE TITLE
Transform Rust structs to sql and from sql 

### ISSUE THREAD

**Issue by ctaque** [sfackler/rust-postgres#609]
Hi, 
This is not as properly said an issue, but i've been searching for two days a way to transform a struct into sql statement and create a struct or vector of structs from sql statements. I believe there is FromSql and ToSql derive but I'm not sure how to use them.

There have been several attempts at doing this with these crates : https://docs.rs/postgres-mapper/0.1.1/postgres_mapper/ and https://docs.rs/serde_postgres/0.1.3/serde_postgres/

But both have their source code deleted.
I think it could be great to provide an example for how are like me searching for this.

**Comment by sfackler** [comment]
FromSql and ToSql deal with single values in Postgres, not a set of values queried from a table. I don't know if there are any current projects that implement a derive mode to go from a `Row` to a type off the top of my head.

**Comment by djc** [comment]
https://github.com/dutchmartin/sprattus is one, I think I saw another one recently but don't remember.

**Comment by jeff-davis** [comment]
Is there something to do here for rust-postgres, or should we resolve this issue?

**Comment by sfackler** [comment]
I think it makes the most sense to let this develop externally, yeah.
