### ISSUE TITLE
Does `tokio-postgres` dispatch AsyncMessage 'realtime'?

### ISSUE THREAD

**Issue by tuxzz** [sfackler/rust-postgres#610]
I want to ensure all notifications from previous transaction (may from other processes) are received after a transaction created. 
As the [PostgreSQL documention](https://www.postgresql.org/docs/current/libpq-notify.html) said, we can use two blocking API called `PQconsumeInput` and `PQnotifies` to receive all pending notifications. But in `tokio-postgres`, there is only an asynchronous API from `tokio_postgres::Connection`.
Can I achieve my purpose using the asynchronous API? If there are any pending notifications how can I block my program to wait them?

**Comment by sfackler** [comment]
You could send the notifications in a channel and read from that after a transaction, for example.

**Comment by tuxzz** [comment]
> You could send the notifications in a channel and read from that after a transaction, for example.

So the messages in receiving queue are flushed after a transaction created?
I'm looking source code of `tokio_postgres::Connection`. Seems like messages are received from an `mpsc::UnboundedReceiver`. How the messages be synchronized when I create a connection?
I'm a bit curious of the latency between creating transaction and got messages.

**Comment by sfackler** [comment]
Notifications are interleaved directly in the stream of messages from the database. If you e.g. run `transaction.commit().await?`, then the connection will have processed every notification that was sent before the transaction committed.
