### ISSUE TITLE
Mutable Client ref in Transaction

### ISSUE THREAD

**Issue by Ajkcki** [sfackler/rust-postgres#611]
I'm trying to start a transaction
```
let client: Connection<PgConnectionManager<tokio_postgres::NoTls>> = pool.get().await?;
let trans = client.transaction().await?;
```
and the compiler complains 'client' is not mutable. Checking the source code reveals that struct 'Transaction' indeed holds a mutable ref to a 'Client' object,

```
pub struct Transaction<'a> {
    client: &'a mut Client,
    savepoint: Option<Savepoint>,
    done: bool,
}
impl<'a> Transaction<'a> {
    pub(crate) fn new(client: &'a mut Client) -> Transaction<'a> {
        Transaction {
            client,
            savepoint: None,
            done: false,
        }
    }
```

In light of this discussion

https://github.com/sfackler/rust-postgres/issues/380

I'm wonder why Transaction needs a mutable ref to Client, and is there any danger in the following code?

```
let mut client= pool.get().await?;
let trans = client.transaction().await?;
trans.batch_execute("....").await?;
```

**Comment by sfackler** [comment]
Why would there be danger in that code? That's the just the way to use a transaction.

**Comment by Ajkcki** [comment]
Ok, thank you !
