### ISSUE TITLE
A multi-dimensional array as a query parameter

### ISSUE THREAD

**Issue by pimeys** [sfackler/rust-postgres#612]
I'm trying to construct a following query:

```sql
SELECT * FROM foo WHERE (id, id2) = ANY(ARRAY[(1,2),(3,4)]);
```

So what I'd like is to parameterize it:

```sql
SELECT * FROM foo WHERE (id, id2) = ANY($1);
```

And then use something like `vec![vec![1,2],vec![3,4]]` as the parameter. This doesn't really work right now. I found out the `rust-postgres-array` crate, but couldn't figure out is a query like this possible using it.

**Comment by sfackler** [comment]
You would create an [`Array`](https://docs.rs/postgres_array/0.10.0/postgres_array/struct.Array.html) and pass it in as the parameter to the query.
