### ISSUE TITLE
Terminate connection to database

### ISSUE THREAD

**Issue by alex-dukhno** [sfackler/rust-postgres#613]
Hi there!

Thanks for the `rust-postgres` is a cool crate 😄 

I am building PostgreSQL compatible database and using synchronous `Client` in my integration tests.
I am starting the server in separate thread and facing the problem that I can't terminate connection with `Client`.
I think it's good idea to send `terminate` message when dropping `Client` that is not closed. WDYT?

**Comment by sfackler** [comment]
This is normally done by the connection when the client handle drops, but that doesn't currently happen in the synchronous client due to how its constructed. Should be fixable.
