### ISSUE TITLE
How to execute multiple queries concurrently?

### ISSUE THREAD

**Issue by kadfak** [sfackler/rust-postgres#615]
I'm trying to create multiple query futures and then run them all concurrently with `tokio-postgres`, but I couldn't figure out how to resolve query parameters lifetime issues.

Here's the core idea:
```rust
let mut insert_futures = vec![];
for item in &items {
    insert_futures.push(db.execute(
        "INSERT INTO x (a, b) VALUES ($1, $2)",
        &[&item.a, &item.b]
    ));
}
futures::future::join_all(insert_futures).await;
```

The error this code produces:
```
error[E0716]: temporary value dropped while borrowed
  --> src/main.rs:20:14
   |
20 |             &[&item.a, &item.b]
   |              ^^^^^^^^^^^^^^^^^^ creates a temporary which is freed while still in use
21 |         ));
   |           - temporary value is freed at the end of this statement
...
25 | }
   | - borrow might be used here, when `insert_futures` is dropped and runs the `Drop` code for type `std::vec::Vec`
   |
   = note: consider using a `let` binding to create a longer lived value
```

[Playground link](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=0e366bba79eca7bb28405588422e2b2d)

**Comment by sfackler** [comment]
You can use an `async` block around the execute call to keep the temporary array alive. It does require a bit of awkwardness to control what's captured by value vs by reference but it's not too bad: https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=1280b1edc9fd32cfc391e13611eff88c

**Comment by kadfak** [comment]
Problem solved! Thanks!
