### ISSUE TITLE
Line numbers are incorrect for error from Client::batch_execute()

### ISSUE THREAD

**Issue by djc** [sfackler/rust-postgres#621]
For migrations, I'm executing SQL straight from a file through `Client::batch_execute()`. However, the erorrs I get from tokio-postgres aren't great:

```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error { kind: Db, cause: Some(DbError { severity: "ERROR", parsed_severity: Some(Error), code: SqlState("42601"), message: "syntax error at or near \")\"", detail: None, hint: None, position: Some(Original(941)), where_: None, schema: None, table: None, column: None, datatype: None, constraint: None, file: Some("scan.l"), line: Some(1149), routine: Some("scanner_yyerror") }) }', /Users/djc/src/foo/src/lib.rs:78:13
```

If I throw the same SQL content into pgAdmin, I get this:

```
ERROR:  syntax error at or near ")"
LINE 27: );
         ^
SQL state: 42601
Character: 941
```

The error and character are the same, but it would be great if I also got a usable line number out -- I'm not sure how the original line 27 translates to 1149.

(In this case, the issue was a trailing comma before the closing parenthesis of a `CREATE TABLE` statement, but that probably doesn't matter.)

**Comment by sfackler** [comment]
1149 is the line in the `scan.l` file of the Postgres source that triggered the error. The error that we return is exactly what Postgres gives us. You could make a wrapper that converts the position into a line number by looking at the query string, but that's not done in this library currently.
