### ISSUE TITLE
python bindings

### ISSUE THREAD

**Issue by h5rdly** [sfackler/rust-postgres#629]
Hi,

First of all, cheers, this is so much better than using the C++ API directly..

I was wondering whether you would consider adding Python callability to the code.

I'm a few weeks into Rust, and  don't know know the level of complexity of such a task,  but I saw [here](https://blog.nicco.io/2020/01/01/rust-in-python-made-easy/) that functions can be prepended with  `#[no_mangle]`, then wrapped via `ctypes` the same way as C functions.

If this is conceptually something you're ok with, and a lot of this is running around prepending `#[no_mangle]`, I can help :)

Thanks,
Eli

**Comment by sfackler** [comment]
Could you explain a little bit why you aren't able to use any of the existing Python libraries that provide a Postgres client?

**Comment by h5rdly** [comment]
I am, but then I'm bound to Python speeds (psycopg at least is fairly slow). 

I figured (surmised I guess :) ) calling a Rust driver from Python may prove more performant. 

I actaully found [slonik](https://github.com/peopledoc/slonik/), are you guys familiar with this effort?

**Comment by sfackler** [comment]
Nope, haven't heard of that project before.

I think it should definitely be possible to make a C interface for rust-postgres, but I don't personally have the bandwidth/interest to maintain that right now. It's not quite as simple as slapping `#[no_mangle]` on a bunch of functions - it'd need to define an entirely new set of APIs that expose an interface appropriate for a C ABI and wrap the Rust one.

psycopg2 already wraps the native libpq C library IIRC, and I wouldn't expect a drastic performance difference between libpq and rust-postgres. The slowness may just be an inherent cost of bridging between Python and native code, or design decisions made by psycopg2 that impose extra overheads.
