### ISSUE TITLE
Synchronous `Client` and threads

### ISSUE THREAD

**Issue by fredfortier** [sfackler/rust-postgres#638]
I naively instantiating a sync `Client` like this:
```rust
// Has to be mutable to call `client.execute`
let mut client = Client::connect(&get_env_db_conn(), NoTls)?
```

What is the recommended way to use such object across multiple threads? For now, I just create a new instance in each thread. But is this object thread safe? Can I wrap it into `Arc` and `Mutex`, and pass it to another thread? This is confusing to me primarily because mutability requirement.

**Comment by sfackler** [comment]
You could use an Arc and Mutex, or a connection pool like r2d2.

**Comment by fredfortier** [comment]
Are there any examples of using any of those two methods with an instance of `Client`?

**Comment by fredfortier** [comment]
Also, I apologize in advance for my lack of context, but where is the connection pool implemented? I can't seem to find it in the postgres crate.

**Comment by sfackler** [comment]
https://github.com/sfackler/r2d2-postgres

**Comment by fredfortier** [comment]
Looks very much like what I needed. Thanks!
