### ISSUE TITLE
Cannot start a runtime from within a runtime

### ISSUE THREAD

**Issue by glennpierce** [sfackler/rust-postgres#639]
I have recently updated a library of mine that uses rust-postgres from 0.15 to 0.17.5. I have got everything compiling and my tests are working.
The trouble is I have a project that uses my library that uses warp to create a basic webserver api.

Here I have a warp filter that creates a connection using rust-postgres (through my lib)

```
fn with_bmos_conn(details: DBConnectionDetails) -> impl Filter<Extract = (BmosConnection,), Error = std::convert::Infallible> + Clone {

    warp::any().map(move || 
        {
            BmosConnection::new(
                &details.db_host,
                &details.db_port.to_string(),
                &details.db_name,
                &details.db_user,
                &details.db_pass,
            )
        }
    )
}
```

Here I just get the errrors 
`
thread 'main' panicked at 'Cannot start a runtime from within a runtime. This happens because a function (like `block_on`) attempted to block the current thread while the thread is being used to drive asynchronous tasks.'
`

I can understand the error as the new rust-postgres uses tokio now but how can I get around this ?

PS is there a discord for posting help requests like this ? Sorry if help is not for github issues.

Thanks

**Comment by sfackler** [comment]
Warp's an asynchronous library, so you'll probably want to use tokio-postgres instead.

**Comment by glennpierce** [comment]
Thanks I will to port my library. I have stumbled of my first issue I will post on the tokio-postgres issue page.
