### ISSUE TITLE
Typed prepared statement with array of integers params

### ISSUE THREAD

**Issue by apiraino** [sfackler/rust-postgres#643]
Hi,

sorry if I'm asking in the wrong place. I'm probably missing something obvious.

I'm trying to create a typed prepared statement to delete a list of ids that are defined on the table as `id serial`. I cannot figure out the right syntax, example:

```
let example_ids = vec![13, 14, 15];
let st = db_client
    .prepare_typed(
        "DELETE FROM tbl WHERE id in ($1)",
        &[mobc_postgres::tokio_postgres::types::Type::INT4_ARRAY],
    )
    .await?;
db_client.execute(&st, &[&example_ids]).await?;
```

returns the error: `operator does not exist: integer = integer[]`.

I've tried `INT4_RANGE`, too.

 
Possibly related to [this](https://github.com/sfackler/rust-postgres/issues/612)? I've also tried casting  [with Array::from_vec()](https://docs.rs/postgres_array/0.10.0/postgres_array/struct.Array.html#method.from_vec) with a random test such as `postgres_array::Array::from_vec(vec![13, 14, 15], 1);` but I get the same error.

Any hint? Thanks

**Comment by apiraino** [comment]
ahhh think I got it working, [thanks to this suggestion](https://github.com/sfackler/rust-postgres/issues/92#issuecomment-70089809): turn the `IN` clause into a `ANY()`.

```
        let example_ids = vec![13, 14, 15];
        let st = db_client
            .prepare_typed(
                "DELETE FROM tbl WHERE id = any($1)",
                &[mobc_postgres::tokio_postgres::types::Type::INT4_ARRAY],
            )
            .await?;
        db_client.execute(&st, &[&example_ids]).await?;
```

makes sense?

Closing issue but open to suggestions!

**Comment by sfackler** [comment]
Yeah, `ANY()` is the right thing to use there.

**Comment by ctaque** [comment]
Hi, what is the syntax for ``` not in ``` ? 
I tried ``` != ANY($1) ``` and ``` <> ANY($1) ``` but both are returning all the results.

**Comment by apiraino** [comment]
@ctaque the SQL syntax should be `NOT IN (1,2,3,...)`. So perhaps something like this?
```
    let rows = client
        .query("SELECT * from tbl where id NOT IN ($1)", &[&ids])
        .await?;
```
(not tested)

I guess it would require to iterate the list (when not made of integers) to produce something like `NOT IN ('val1','val2',...)`

**Comment by ctaque** [comment]
I guess there is an equivalent of any, because the keyword 'in' is reserved in rust, I would like to have the confirmation of @sfackler

**Comment by sfackler** [comment]
The Postgres documentation claims that `!= ANY` and `<> ANY` should both work just fine: https://www.postgresql.org/docs/9.2/functions-subquery.html#FUNCTIONS-SUBQUERY-ANY-SOME

This syntax is SQL - it has nothing to do with Rust's syntax.

**Comment by ctaque** [comment]
My bad. I ignored the existence of 'any' and 'some' in sql. Thanks for enlighting me !

**Comment by ctaque** [comment]
For those wondering how to do, I did a ```NOT INT``` with a sub query : 

```sql
connection.query(
    "SELECT * FROM table_1 JOIN table_2 ON table_1.foreign_id = table_2.id WHERE foreign_id NOT IN (SELECT id from table_2 where id = ANY($1)",
    &[&vec!(1,2,3)]
);
```
