### ISSUE TITLE
RETURNING id

### ISSUE THREAD

**Issue by glennpierce** [sfackler/rust-postgres#644]
I am trying to port a library from rust-postgres to tokio-postgres where I had a query like

"INSERT INTO table(name, namespace) VALUES ($1,$2) ON CONFLICT(name, namespace) DO NOTHING RETURNING id

this worked in rust-postgres but in the tokio version an empty vector is returned.

ie

let rows = client.query("INSERT INTO table(name, namespace) VALUES ($1,$2) ON CONFLICT(name, namespace) DO NOTHING RETURNING id", &[&name, &namespace]).await?;

row is an empty vector.

Thanks

**Comment by sfackler** [comment]
rust-postgres is a wrapper over tokio-postgres, so I do not believe that is the case.

If you could provide a minimal reproduction of the problem, that would be helpful.

**Comment by glennpierce** [comment]
I believe you are correct. Direct query of the db does the same. So there must be some issue there. Thanks
