### ISSUE TITLE
No notifications coming from connection after 'LISTEN'

### ISSUE THREAD

**Issue by ar3s3ru** [sfackler/rust-postgres#649]
Hello, got a problem that is making my head hurt and don't understand what's wrong...

I'm trying to write a component that:
1. Subscribes to a topic with `LISTEN topic`
1. Listens to messages on the connection
1. Filters `AsyncMessage::Notification` and parses the payload
1. Sends the result of the parsing to a `tokio::sync::broadcast` channel

I'm following the example found here:

https://github.com/sfackler/rust-postgres/blob/4237843a0ef50ab477fa588950f35e9088a4b8e4/tokio-postgres/tests/test/main.rs#L611-L642

I wrote this method that should spawn the connection listener, but the only message that I see printed out is `started listening onto connection`: no messages are arriving on the stream.

Am I missing something? Thanks :bow: 

(P.S. don't mind the mess with `while let`, I really tried every option available to loop on the `AsyncMessage` stream...) 

```rust
pub async fn new(dsn: &str, type_name: &str) -> Result<Self> {
        let (client, mut connection) = tokio_postgres::connect(dsn, tokio_postgres::NoTls)
            .await
            .map_err(|e| Error::Database(e.to_string()))?;

        let (tx, _) = broadcast::channel(DEFAULT_BROADCAST_CHANNEL_SIZE);
        let tx_captured = tx.clone();

        tokio::spawn(async move {
            let mut stream = futures::stream::poll_fn(move |cx| connection.poll_message(cx));

            println!("started listening onto connection");

            while let Some(message) = stream.next().await {
                let message = message
                    .map_err(|e| {
                        eprintln!("failed to get message from db: {}", e);
                        e
                    })
                    .unwrap();

                println!("got some message from db");

                if let AsyncMessage::Notification(not) = message {
                    println!(
                        "received notification from {}: {}",
                        not.channel(),
                        not.payload()
                    );

                    let event: Result<Persisted<Id, Event>> = serde_json::from_str(not.payload())
                        .map_err(|e| Error::InvalidMessage(e.to_string()));

                    tx_captured.send(event).map_err(|e| {
                        eprintln!("failed to send message on channel: {:?}", e);
                        e
                    });
                }
            }
        });

        client
            .batch_execute(&("LISTEN ".to_owned() + type_name + ";"))
            .await
            .map_err(|e| Error::Database(e.to_string()))?;

        Ok(Self { tx })
    }
```

**Comment by sfackler** [comment]
`client` is dropped when the function returns, which closes the connection. You should store it in the `Self` struct to keep it alive.

**Comment by ar3s3ru** [comment]
Thanks for the answer @sfackler , I eventually figured that out a couple of hours after posting the message.

Rather than moving it onto `Self`, I wrapped the `Client` into an `Arc`, cloned it and explicitly called `drop(client_cloned)` from inside the `tokio::spawn` closure.

Worked like a charm.

Might be useful to add this particular detail in the `Connection` documentation though, as I've eventually seen other users having more or less the same issue. Will try to open a PR for that shortly :+1:

**Comment by sfackler** [comment]
It is already in the Connection documentation:

> Connection implements Future, and only resolves when the connection is closed, either because a fatal error has occurred, or because its associated Client has dropped and all outstanding work has completed.

https://docs.rs/tokio-postgres/0.5.5/tokio_postgres/struct.Connection.html
