### ISSUE TITLE
Implementing ToSql for rust variant enum and postgres_types::ToSql is not implemented for `u64`

### ISSUE THREAD

**Issue by glennpierce** [sfackler/rust-postgres#651]
I have a Vector of tuples where each tuple is (String, Variant)

The variant is defined as

pub enum Variant {
    stringValue(String),
    boolValue(bool),
    i32Value(i32),
    u32Value(u32),
    u64Value(u64),
    f32Value(f32),
    f64Value(f64),
    utcValue(DateTime<Utc>),
    dateValue(NaiveDate),
}

I want to update a table where the String in the tuple is the column name and the variant is the value

I was going to loop all the tuples matching on the variant and forming a vector of Box<ToSql>
I can then dynamically construct an UPDATE query for the list of tuples and pass the vector of Box<ToSql> as values.
There is probably a better way to pass dynamic key value pairs to update a table.
Please let me know if there is.

The issues I am having trouble with and one possible bug

First the bug.
When I match on my variant with u64 in I get
  the trait `postgres_types::ToSql` is not implemented for `u64`
  when doing  sql_values.push(Box::new(i));
  

Second is the match of variant is quite ugly. Is the a way to impl ToSql for Variant where tosql is just forwarded to the real value.
I can't use derive ToSql as it is not a C style enum.

Something like this ?

impl ToSql for Variant {
    fn to_sql(&self,
              ty: &Type,
              out: &mut BytesMut)
              -> std::result::Result<IsNull, Box<Error + Sync + Send>> {
            
        match *self {
            Variant::stringValue(v) => v.to_sql(ty, out),
            ...
        };

        Ok(IsNull::No)
    }

    fn accepts(ty: &Type) -> bool {
        true
    }

    to_sql_checked!();
}

But I can't work out why I get 

note: expected fn pointer `fn(&element::Variant, &postgres_types::Type, &mut bytes::bytes_mut::BytesMut) -> std::result::Result<_, _>`
 found fn pointer `fn(&element::Variant, &postgres_types::Type, &mut bytes::bytes::BytesMut) -> std::result::Result<_, _>`
 
 
Thanks for any help.

**Comment by sfackler** [comment]
There is no unsigned 64 bit integer type in Postgres.

**Comment by deuszex** [comment]
ToSql could be implemented for u64 using Numeric. postgresql already uses numeric when counting for bigint overflow.

**Comment by sfackler** [comment]
Numeric is an arbitrarily precision fixed point type, not a 64 bit integer type.
