### ISSUE TITLE
How to use the "postgres-types" crate ?

### ISSUE THREAD

**Issue by apiraino** [sfackler/rust-postgres#658]
Hi, 

sorry for the really dumb question - I can't figure out how to use the [postgres_types](https://docs.rs/postgres-types/0.1.2/postgres_types/) crate.

Like, how do I even have it compile a basic example as shown in the documentation? Which dependencies do I need to pull? Do I need to enable some features?

```
// cargo.toml
[dependencies]
postgres-types = "0.1.2"
postgres = "0.17.5"      -- need this?
tokio-postgres = "0.5.5" -- need this?

// main.rs
use postgres_types::{ToSql, FromSql};
#[derive(Debug, ToSql, FromSql)]
enum Mood {
    Sad,
    Ok,
    Happy,
}
```

(I'm using tokio_postgres through [mobc](https://docs.rs/mobc-postgres/0.5.0/mobc_postgres/)) so I won't use it anyway with tokio_postgres directly but I need to remap some enums to Postgres table fields (not Postgres types)

Thanks for the help!

**Comment by sfackler** [comment]
You need to enable the `derive` feature in your Cargo.toml:

```toml
[dependencies]
postgres-types = { version = "0.1.2", features = ["derive"] }
```

**Comment by apiraino** [comment]
ah ok thanks that did it.

Though, I have not completely clear how [the naming](https://docs.rs/postgres-types/0.1.2/postgres_types/#naming
) works.

I'd like to map an enum into a Postgres integer field, do I have to manually impl `FromSql` and `ToSql` for the `Mood` enum or something similar to the following should work automagically?

```
use postgres_types::{ToSql, FromSql};
#[derive(ToSql, FromSql)]
enum Mood {
    #[postgres(name = "0")]
    Sad,
    #[postgres(name = "1")]
    Ok,
    #[postgres(name = "2")]
    Happy,
}```

```
    client
        .prepare_typed(
            "UPDATE users set mood = $1 where id = $2",
            &[
                tokio_postgres::types::Type::INT4,
                tokio_postgres::types::Type::INT4, // throws Type error ... 
            ],
        )
        .await?
```

**Comment by sfackler** [comment]
https://docs.rs/postgres-types/0.1.2/postgres_types/#naming

**Comment by sfackler** [comment]
The deriving logic maps Rust enums to Postgres enums, not integers. You would need a manual implementation to do that.

**Comment by apiraino** [comment]
Ok, after some digging around it's the solution that makes more sense, I was investigating and figuring out the right tool for this.

I'll see how I can build a prepared statement having a dynamic (`$2`) parameter that accepts a Rust enum item and maps it to the corresponding postgres enum  item :100: 

thanks! :)
