### ISSUE TITLE
Support `FromSQL` for SQL arrays

### ISSUE THREAD

**Issue by ezracelli** [sfackler/rust-postgres#663]
Pretty self explanatory — will take a stab at the MR hopefully this week!

**Comment by sfackler** [comment]
https://docs.rs/postgres/0.17.5/postgres/types/trait.FromSql.html#arrays

The postgres-array crate provides more full support: https://docs.rs/postgres_array/0.10.0/postgres_array/

**Comment by ezracelli** [comment]
Whoops, not sure how I missed that! Thanks @sfackler for the quick reply
