### ISSUE TITLE
MSRV?

### ISSUE THREAD

**Issue by Kixunil** [sfackler/rust-postgres#673]
Is there any MSRV policy? I found out that d1f9d6d8020843dbcd4fa6764b5abf33e56ade33 broke support of Rust 1.41.1 which is present on Debian. Would be nice to fix it - it's due to the `matches` macro.

**Comment by sfackler** [comment]
You can see the version we test against in CI configuration: https://github.com/sfackler/rust-postgres/blob/master/.circleci/config.yml#L25.

The current MSRV is 1.45.0 since that's what tokio 0.3 requires.
