### ISSUE TITLE
Make `row.get()` return a `Result<T>` instead of `T`.

### ISSUE THREAD

**Issue by HTG-YT** [sfackler/rust-postgres#685]
Currently the `row.get()` method returns a `T` or panics if it cannot be done. If I can use a `match {}` on the method, then I can handle the exceptional case (`Err`). Example implementation (in the crate):

```rs
pub fn get<'a, I, T>(&'a self, idx: I) -> Result<T, Error>
where
    I: RowIndex + fmt::Display,
    T: FromSql<'a>, 
{
    match self.get_inner(&idx) {
        Ok(ok) => Ok(ok),
        Err(err) => Err(err),
    }
}
```

Then I would be able to:

```rs
match row.get(1) {
    Ok(ok) => { /* whatever stuff */},
    Err(err) => { /* whatever stuff */ }
}
```

Thank you

**Comment by HTG-YT** [comment]
^^^ tokio-postgres

**Comment by sfackler** [comment]
`Row::try_get` provides that: https://docs.rs/postgres/0.18.1/postgres/row/struct.Row.html#method.try_get

**Comment by HTG-YT** [comment]
thanks
