### ISSUE TITLE
Last Insert ID

### ISSUE THREAD

**Issue by youngtrashbag** [sfackler/rust-postgres#686]
Is there a way to get the last insert ID right after execution of a statement? I looked through the docs a little, and found something about OID (Object Identifier), but could not come to a conclusion, as I am new to rust.

**Comment by sfackler** [comment]
Postgres does return the OID of the last inserted row, but that is not really a commonly used "id" in the modern use of Postgres. A more robust way do to this is an `INSERT ... RETURNING ...` query: https://www.postgresql.org/docs/13/sql-insert.html
