### ISSUE TITLE
Behaviour when calling pgsql function overloads?

### ISSUE THREAD

**Issue by axelc** [sfackler/rust-postgres#687]
Hello, I have a Postgres function with 2 overloads:
sys_user_get_info(bigint) and sys_user_get_info(text).

When trying to call them from rust-postgres, it always seems to call the text overload, even though I'm passing it an i64 parameter:

``` match self
            .get_conn()
            .await?
            .query(
                "SELECT * FROM sys_user_get_info($1)",
                &[{
                    if uid > 0 {
                        &uid
                    } else {
                        &user_name
                    }
                }],
            )
            .await
```

This generates the following error:

_error: Error { kind: ToSql(0), cause: Some(WrongType { postgres: Text, rust: "i64" }) }_

How can I force the call to the bigint overload? Shouldn't the Rust code be able to infer this from the type of the argument passed?

**Comment by sfackler** [comment]
You can type hint in the query itself with `$1::BIGINT`, or use `client.prepare_typed("SELECT * FROM sys_user_get_info($1)", &[Type::BIGINT])`

**Comment by axelc** [comment]
Sounds good, thanks!
