### ISSUE TITLE
Understanding JSONB -> own type

### ISSUE THREAD

**Issue by apiraino** [sfackler/rust-postgres#689]
Hello,

I have a JSONB field in a table. After some time I managed to cast a sql result set to my own types but only by using serde_json, here's a succint example:

```
// CREATE TABLE t (
//   field_name JSONB,
// );

struct MyStruct {
    uuid: uuid::Uuid
}

impl<'a> FromSql<'a> for MyStruct {
    fn from_sql(ty: &Type, raw: &'a [u8]) -> Result<Self, Box<dyn Error + 'static + Sync + Send>> {
        log::debug!("type is {:?}", ty); // prints: "type is json"
        let jd = &mut serde_json::Deserializer::from_slice(raw);
        let resources: Result<MyStruct, _> = serde_path_to_error::deserialize(jd);
        let x = match resources {
            Err(x) => panic!("error at {:?}", x.path().to_string()),
            Ok(y) => y,
        };
        Ok(x)
    }
    ...
}

fn main() {
    // --->> NOTE: with "field_name::jsonb" or "field_name" I can't serialize from sql
    let q = "SELECT field_name::json FROM t limit 1";
    let row = client.query(q, &[]).await.unwrap();
    let data = MyStruct { field_name: row.get(0) };
}
```

As per the **NOTE** If I run a query such as "SELECT field_name FROM t" without explicitely casting to JSON, I was unable to successfully implement the `from_sql`.

Is there something I am missing? In case it matters I think I'm using latest tokio_postgres, postres_types and so on (I am aware of the [postgres-types](https://docs.rs/postgres/0.18.1/postgres/types/trait.FromSql.html) guidelines on implementing `from_sql`).

Thanks!

**Comment by sfackler** [comment]
The JSONB binary format includes an extra header bit. I would recommend using the `Json<T>` type for this: https://docs.rs/tokio-postgres/0.6.0/tokio_postgres/types/struct.Json.html.

**Comment by apiraino** [comment]
@sfackler thanks for the suggestion, I've spent some time to understand and implement it, but I'm afraid I need a bit more context.

Are you suggesting to use `Type::JSON` on my struct, something like:
```
struct DataFromPostgres {
    stuff: tokio_postgres::types::Type::JSON<MyStruct>
}

struct MyStruct {
    uuid: uuid::Uuid
}
```

that syntax, though, is not correct (I get a confusing suggestion to "use fully-qualified syntax: `<postgres_types::Type as Trait>::JSON`") but I cannot figure out to build the correct syntax.

Second question: would this make redundant the implementation of FromSQL and ToSQL?

thanks

**Comment by sfackler** [comment]
`tokio_postgres::types::Json`, not `types::Type::JSON`.

Yes, you would not need to manually implement FromSql or ToSql.

**Comment by apiraino** [comment]
we have worked a bit more on this and removed the FromSql/ToSql. I still have an error when I pull an `uuid` field inside that JSONB field from the DB. I'll try to reproduce in a way that it makes sense:

```
// model
#[derive(Debug, Deserialize, Serialize, Clone)]
pub struct MyStruct {
    pub various_data: uuid::Uuid,
}

let result = Results {
    id: row.get(0),
    ...  
    various_data: row.get::<_, Json<MyStruct>>(7).0
};
```

the error is:
```
thread 'tokio-runtime-worker' panicked at 'error retrieving column 7: error deserializing column 7: invalid length: expected one of [36, 32], found 37 at line 1 column 59', 
    /home/$user/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-postgres-0.5.5/src/row.rs:150:25
```

if `MyStruct.fld` is a string, everything's fine. The data in the DB *should* be fine.

I wonder if I have to have Postgres cast the data in some way but I've also tried to execute `select fld::json from t` and I still have that error.

**Comment by apiraino** [comment]
@sfackler I'll be having a closer look at this. If you spot something I'm missing (or misunderstanding) I'd happy to have a second thought from you :) otherwise I can close this as this is not an issue, rather an exploratory question ticket.

Anyway, thank you so much for your help :+1:

**Comment by sfackler** [comment]
That looks like Serde and Postgres disagree on how a UUID should be encoded. You'd need to look at the raw JSON text to debug probably.

**Comment by apiraino** [comment]
ok @sfackler followed your advice and looked closely to reproduce a minimal example. I think I'm doing something wrong but can't figure out what. Do you spot any difference in these two queries?

table is
```
CREATE TABLE test (id int, fld jsonb null);
INSERT INTO test VALUES (1, '{"uuid":"fcf3883e-eb1e-4453-b48b-e04734eb6b82"}');
INSERT INTO test VALUES (2, '{"items":[{"uuid": "1860965db-35cf-4232-955f-02c0ba3c0397"}]}');
```

This works
```
let q = "SELECT fld::jsonb->'uuid' from test where id=1";
let rs = client.query(q, &[]).await.unwrap();
for row in rs {
    log::debug!("{:?}", row);
    let d = row.get::<_, Json<uuid::Uuid>>(0);
    log::debug!("{:?}", d);
}

// output
[2020-11-12 11:47:03.161687 +01:00] DEBUG Row { columns: [Column { name: "?column?", type: Jsonb }] }
[2020-11-12 11:47:03.161775 +01:00] DEBUG Json(fcf3883e-eb1e-4453-b48b-e04734eb6b82)
```

This doesn't
```
let q = "SELECT fld::jsonb->'items'->0->'uuid' from test where id=2";
let rs = client.query(q, &[]).await.unwrap();
for row in rs {
    log::debug!("{:?}", row);
    let d = row.get::<_, Json<uuid::Uuid>>(0);
    log::debug!("{:?}", d);
}

// output
[2020-11-12 11:44:37.412722 +01:00] DEBUG Row { columns: [Column { name: "?column?", type: Jsonb }] }
thread 'tokio-runtime-worker' panicked at 'error retrieving column 0: error deserializing column 0: invalid length: expected one of [36, 32], found 37 at line 1 column 39', /home/$USER/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-postgres-0.5.5/src/row.rs:150:25
```

The output from `psql` looks identical:
```
db=> SELECT fld::jsonb->'items'->0->'uuid' from test where id=2;
                ?column?                 
-----------------------------------------
 "1860965db-35cf-4232-955f-02c0ba3c0397"
(1 row)

db=> select fld::jsonb->'uuid' from test where id=1;
                ?column?                
----------------------------------------
 "fcf3883e-eb1e-4453-b48b-e04734eb6b82"
(1 row)
```

I'm a bit puzzled :sweat_smile:

**Comment by sfackler** [comment]
`1860965db-35cf-4232-955f-02c0ba3c0397` is not a valid UUID.

**Comment by apiraino** [comment]
ouch I'm so dumb :facepalm: 

Anyway, thank you so much, the road to here did clarify to me a couple of things about Postgres JSONB and tokio-postgres :sweat_smile:

**Comment by CKalt** [comment]
I'm curious. I'm hoping to not require tokio to keep my solution as thin as possible.

Can that be done here?

**Comment by apiraino** [comment]
@CKalt my understanding is that the entire `rust-postgres` crate sits on tokio (even when using the [synchronous Postgres client](https://docs.rs/postgres/0.19.2/postgres/#implementation)), therefore tokio is a hard dependency.
