### ISSUE TITLE
Documentation small error about the location of postgres unix socket

### ISSUE THREAD

**Issue by nguiard** [sfackler/rust-postgres#690]
In this doc page: https://docs.rs/postgres/0.18.1/postgres/config/struct.Config.html
The examples mentioning a unix socket connection use the /var/lib/postgresql as the location where a postgres unix socket would be. However, it seems to me that this location is actually very unlikely.

Apparently, the default location of the socket, if building PG from source, is /tmp. But many distros change this to /var/run/postgresql instead (https://www.postgresql.org/message-id/21044.1326496507@sss.pgh.pa.us). So it seems that the most likely location a new user of this crate would need to input, if he wants to use the unix socket, would be **/var/run/postgresql**. I suggest changing this in the doc page.

**Comment by sfackler** [comment]
Oops, yeah that should be `/var/run/postgresql`! Want to make a PR to fix it up?

**Comment by nguiard** [comment]
Sure, will do that tomorrow!

**Comment by nguiard** [comment]
PR submitted! Closing.
