### ISSUE TITLE
trust authentication without password

### ISSUE THREAD

**Issue by shadiakiki1986** [sfackler/rust-postgres#695]
Logging in to a local postgres database with `psql -d dbname` using trust authentication, and without a password, works for me from the terminal.

With rust-postgres, the following don't seem to work:

```
let mut client = Client::connect("host=localhost dbname=dbname", NoTls)?; // error: no PostgreSQL user name specified in startup packet
let mut client = Client::connect("host=localhost user=ubuntu dbname=dbname", NoTls)?; // error: password missing
let mut client = Client::connect("postgres://localhost/dbname", NoTls)?; // error: no PostgreSQL user name specified in startup packet
let mut client = Client::connect("postgres://ubuntu@localhost/dbname", NoTls)?; // error: password missing
let mut client = Client::connect("postgres://ubuntu:@localhost/dbname", NoTls)?; // error: password authentication failed for user
```

~~How can I log in with trust authentication and without a password?~~

Update: Turns out that it works if I add a password to my user with `alter user ubuntu with password '1234';` and just add the password to the connection string.

```
let mut client = Client::connect("postgres://ubuntu:1234@localhost/dbname", NoTls)?;
```

I'll do that for my use case. Feel free to keep this issue open or close it

**Comment by sfackler** [comment]
Are you sure trust authentication is enabled over TCP and not just unix sockets?

**Comment by shadiakiki1986** [comment]
Well, it works if I set a password, so I'd say yes

**Comment by sfackler** [comment]
Trust authentication doesn't require a password, so I don't see how that's relevant.

**Comment by shadiakiki1986** [comment]
I agree, which is why I thought it was weird to work if I set a password.
Maybe I screwed up somewhere. Sorry about the noise

**Comment by sfackler** [comment]
Psql connects over a unix socket by default, not over TCP. It is not uncommon for Postgres to be configured to use trust authentication over unix sockets, but not over TCP in its pg_hba.conf. I assume that is what is happening.
