### ISSUE TITLE
Allow BPCHAR to be parsed as i8

### ISSUE THREAD

**Issue by ArsileLuci** [sfackler/rust-postgres#700]
We're using `tokio-postgres` with CockroachDB (20.2.1), which follows Postgres protocol.
When raw ENUM (or any user-defined type) fetched from database some weird error occurs.
```
cannot convert between the Rust type `i8` and the Postgres type `bpchar`
```
After small investigations I found that this row in [`tokio-postgres/prepare.rs`](https://github.com/sfackler/rust-postgres/blob/master/tokio-postgres/src/prepare.rs#L129-L181)
```
let type_: i8 = row.try_get(1)?;
```
causes error to fire. In some cases CockroachDB and also Postgres return `BPCHAR` instead of `CHAR` when fetched column has `CHAR` type. I've found [this thread on stackoverflow](https://stackoverflow.com/questions/51421269/why-char-datatype-is-converted-to-bpchar-automatically) where people discuss same behavior in Postgres.

Fix for this is deadly simple we just need to add `BPCHAR` to `simple_from!` for `i8` in [`postgres-types/lib.rs`](https://github.com/sfackler/rust-postgres/blob/master/postgres-types/src/lib.rs#L558) like this
```
simple_from!(i8, char_from_sql, CHAR, BPCHAR);
```

**Comment by sfackler** [comment]
A bpchar is a sequence of characters, not a single character. That would correspond to a str/String in Rust, which already supports conversions with that type: https://github.com/sfackler/rust-postgres/blob/master/postgres-types/src/lib.rs#L538

**Comment by ArsileLuci** [comment]
Ohh, ok. Spent some time googling it. And for sure `BPCHAR` != `CHAR`.
Looks like this comes from CockroachDB.
```
SELECT pg_typeof(typtype) FROM pg_type
```
returns `"char"` for PostgreSQL and `text` for CockroachDB.

Is it still possible to add my solution as `cockroachdb` feature?

**Comment by sfackler** [comment]
If Cockroach returns a string from pg_typeof, then it returns a string. I don't see how allowing an invalid conversion from a Postgres string type to a Rust byte will change that fact.

**Comment by ArsileLuci** [comment]
It still returns 1 byte, so it can be converted to a Rust byte.  And in that case fetching user-defined type won't fail. It could be done as a separate "feature" to support Cockroach. Right now when we try to use user-defined type for example enum as is without explicit cast to string it fails on 
```
let type_: i8 = row.try_get(1)?;
```
Our issue also can be fixed by replacing `i8` with `String` in the line above.

**Comment by sfackler** [comment]
I am not interested in adding a conversion between normally incompatible Postgres/Rust types because one function in CockroachDB returns the wrong type. You can support both behaviors in your own code by simply inspecting the column type and handling the two cases.
