### ISSUE TITLE
PQencryptPasswordConn()

### ISSUE THREAD

**Issue by jeff-davis** [sfackler/rust-postgres#703]
I suggest that we implement `PQencryptPasswordConn()`. Any thoughts/suggestions? I may try to implement it.

**Comment by sfackler** [comment]
It seems like running the entire connection over TLS is a more robust way of avoiding that kind of password exposure, but it seems reasonable to add that functionality in any case.

**Comment by jeff-davis** [comment]
The reasoning behind this function is that the server **never sees** the plaintext password. That eliminates a whole class of administrator errors that could result in the plaintext password being exposed and used for a replay, perhaps on another service. For instance, some log settings will happily log unmodified `CREATE USER foo PASSWORD 'secret'`, and those logs could end up exposed through another set of mistakes.

**Comment by sfackler** [comment]
Ah, that makes sense! Definitely seems reasonable to add then.

**Comment by jeff-davis** [comment]
Thank you for committing: e4e48a06b7
