### ISSUE TITLE
Question: running tests locally?

### ISSUE THREAD

**Issue by jeff-davis** [sfackler/rust-postgres#705]
Is there an easy way to run the tests locally, just like circleci does?

**Comment by sfackler** [comment]
Yeah, you can run `docker-compose -d` to start up the docker image configured for use by the tests.

**Comment by jeff-davis** [comment]
For others who do not know a lot about docker, here's what I did on ubuntu (from within top level directory of `rust-postgres` repo):

```
# in terminal 1
sudo apt install docker.io docker-compose
sudo usermod -aG docker mylocaluser # add yourself to the docker group
docker-compose up

# in terminal 2
cd tokio-postgres
cargo test

# in terminal 1
^C
docker-compose stop
```

I didn't fully validate this so I might have left out a step, but I hope it helps.
