### ISSUE TITLE
Error code is `None` on empty result

### ISSUE THREAD

**Issue by inzanez** [sfackler/rust-postgres#709]
Hi

I'm trying to implement error handling for the errors returned by queries. To test, I submitted a select query that doesn't return anything (`SELECT name from users WHERE id = 123456`, and that id doesn't exist).

I thought I could check on the error using `e.code()` to retrieve the `SqlState`, but apparently I just get `None` returned. I would have expected something like `SqlState::NO_DATA` or `SqlState::NO_DATA_FOUND`, but I guess I missed something here. Any idea why that is not returning detailed information on the error?

Apart from that, is there a way to convert `postgres::Error` into a `postgres::error::DbError`?

**Comment by sfackler** [comment]
There's only a SqlState error if the error is actually produced by the database. I'm assuming you're using `query_one` here, which is just a convenience method that makes a normal query and produces an error if there isn't exactly one value. You can do the same thing yourself if you want more control over things.

**Comment by inzanez** [comment]
@sfackler Oh, I see. Laziness almost never pays off I guess :-)
