### ISSUE TITLE
postgres-types: Implement support for u64

### ISSUE THREAD

**Issue by Mause** [sfackler/rust-postgres#730]
Seems odd to leave this type out when the others are supported?

**Comment by sfackler** [comment]
Which postgres type would that correspond to?

**Comment by Mause** [comment]
That's a good question, I hadn't actually realised postgres didn't have a built-in for it - that explains it's absence.

Would it be possible to use numeric if the database didn't have an appropriate extension loaded? Or make the concrete type configurable?

**Comment by sfackler** [comment]
The numeric type has arbitrary precision, so it would only actually map to u64 some of the time.

**Comment by arl** [comment]
I would need this conversion now to convert a `bigserial` into `u64`.

**Comment by arl** [comment]
oh i see now that that would be `i64`, from https://github.com/sfackler/rust-postgres/blob/86c914c6fc53d1f1902b4f5d52b9116720cec554/postgres-types/src/lib.rs#L404
But am i wrong in thinking that `u64` would be more suited, based on https://www.postgresql.org/docs/14/datatype-numeric.html

**Comment by sfackler** [comment]
Those types are both signed in Postgres.

**Comment by arl** [comment]
From https://www.postgresql.org/docs/14/datatype-numeric.html bigserial
range is from 1 to 9223372036854775807 which makes unsigned in my book.

Le jeu. 13 janv. 2022 à 13:14, Steven Fackler ***@***.***> a
écrit :

**Comment by sfackler** [comment]
9223372036854775807 is `i64::MAX`,` not `u64::MAX`.

**Comment by arl** [comment]
> 9223372036854775807 is `i64::MAX`, not `u64::MAX`.
ok and what about the minimum value of `bigserial` then. 1 is neither `i64::min` nor `u64::min`. The thing is both types are big enough to contain the whole range of valid `bigserial` numbers.  One of them is signed, the other is unsigned. `bigserial` is also unsigned. Anyway, it just made more sense to me that the rust type corresponding to `bigserial` was that with the _closest_ range.

**Comment by sfackler** [comment]
`1` is not the minimum value that can be stored in a `bigserial`. This test passes:

```rust
#[tokio::test]
async fn serial() {
    let client = connect("user=postgres").await;

    client
        .batch_execute(
            "
        CREATE TEMPORARY TABLE t (
            id BIGSERIAL PRIMARY KEY
        )
        ",
        )
        .await
        .unwrap();

    client
        .execute("INSERT INTO t (id) VALUES (-10)", &[])
        .await
        .unwrap();

    let row = client.query_one("SELECT id FROM t", &[]).await.unwrap();
    let id: i64 = row.get(0);

    assert_eq!(id, -10);
}
```

A `bigserial` column is just a `biginteger` column with a special trigger to fill in an incrementing value on insert if one is not provided.
