### ISSUE TITLE
How can I handle DbErrors from a failed tokio_postgres query?

### ISSUE THREAD

**Issue by blazzy** [sfackler/rust-postgres#732]
I'm interested in grabbing the `constraint` property from a `DbError`. The higher level goal is to do optimistic inserts/updates and be notified of which specific constraint was violated if any.

It was challenging for me to get to this data starting with the `tokio_postgres::Error` returned from `query()`:

```rust
Err(err) => {
    let source = err.into_source();
    let constraint = source
        .as_ref()
        .and_then(|e| e.downcast_ref::<tokio_postgres::error::DbError>())
        .and_then(|e| e.constraint());

     println!("{}", constraint.unwrap());
```

The complexity here makes me think I might be doing something wrong.

Another challenge presented, is that the original error is consumed by `into_source`. In the event, that there isn't a `DbError` with a `constraint`, I want to simply return the original error.

It's not clear to me if this is a feature request, or if I'm doing something stupid. I'm far too new to Rust to have constructive opinions, but I was expecting to be able to do something like this:

```rust
let constraint = match err {
   DbError(err) => err.constraint(),
   _ => return Err(err),
}
```

**Comment by sfackler** [comment]
Previous versions had a `fn as_db_error(&self) -> Option<&DbError>` method directly on `Error` to make the check easier which seems reasonable to add back.

IME it's more common to match on the SqlState error which already has a top-level accessor rather than jumping directly to a constraint field.

**Comment by blazzy** [comment]
Oh yeah, it's probably best to start with the SqlState error. I'd definitely want access to that rich context in the DbError too though. Something like `as_db_error` would be really helpful on that front.
