### ISSUE TITLE
Use of transaction and client

### ISSUE THREAD

**Issue by jdrouet** [sfackler/rust-postgres#735]
Hi!
It's more of a question related to the use of transactions and clients (or an improvement, who knows).
I'd like to implement a function which would take a transaction or a client in which I'd execute a query. Is there a way to do that with `tokio-postgres`?
I'm used to use `sqlx` which implements `execute`, `query_one` and so one, through a trait.

Thank you in advance ;)

**Comment by sfackler** [comment]
https://docs.rs/tokio-postgres/0.7.0/tokio_postgres/trait.GenericClient.html
