### ISSUE TITLE
Client `close` method missing `&` in parameters

### ISSUE THREAD

**Issue by iporollo** [sfackler/rust-postgres#736]
In `Client` there is the [method `close`](https://github.com/sfackler/rust-postgres/blob/2e61f7f7f30ee6446f9c61017e74abfcd0ce8cc7/postgres/src/client.rs#L555)

```
    pub fn close(mut self) -> Result<(), Error> {
        self.close_inner()
    }
```

I'm curious if the parameters should instead be `&mut self` ?

**Comment by sfackler** [comment]
The signature is intentional. You can't use the client after it's closed.

**Comment by iporollo** [comment]
Ah that makes sense, thanks!
