### ISSUE TITLE
[Suggestion] Add a clarification to the packages listed in readme.md

### ISSUE THREAD

**Issue by 3NdR1m** [sfackler/rust-postgres#738]
This might sound picky, but what are all these package listed in readme.md? I just opened this repository to browse for links, docs, resource, etc. and these links weren't too helpful. What are they, dependencies? Alternatives? Recommendation? Implementations? I'd suggest to clarify the purpose of these references for visiting users.

Cheers.

**Comment by sfackler** [comment]
They are the libraries defined in this repository, each with a link to its documentation.
