### ISSUE TITLE
Panic when there's an invalid number of parameters

### ISSUE THREAD

**Issue by matthewmueller** [sfackler/rust-postgres#740]
Hey there. I'm running into panics when you pass the wrong number of parameters into a client query. This makes it challenging to wrap the error with metadata and return it back to the client.

For example, with no parameters:

```rust
let res = client.query("SELECT 1", &[&1i64]).await;
```

Results in:

```sh
thread 'main' panicked at 'expected 0 parameters but got 1'
```

It's also a problem with too many parameters:

```rust
let res = client.query("SELECT $1, $2", &[&1i64]).await;
```

```sh
thread 'main' panicked at 'expected 2 parameters but got 1'
```

It'd be sweet if `tokio_postgres::Error` contained this error, rather than panicking. 

Thanks!

**Comment by sfackler** [comment]
You can check for that explicitly if you want by preparing the query and then checking for the expected number of parameters. I don't see any reason not to change the behavior though since the relevant methods are all fallible anyway.

**Comment by matthewmueller** [comment]
Thanks for your tip! This led us to discover [params](https://docs.rs/tokio-postgres/0.7.0/tokio_postgres/struct.Statement.html#method.params) which will work for our use case. Closing!
