### ISSUE TITLE
Mapping Array table

### ISSUE THREAD

**Issue by tomus85** [sfackler/rust-postgres#741]
There is an example of the table 
```sql
CREATE TABLE IF NOT EXISTS Author (
    id          BIGSERIAL NOT NULL PRIMARY KEY,
    "name"      VARCHAR NOT NULL,
    publisher   VARCHAR,
   age      SMALLINT
);

INSERT INTO Author("name", publisher) VALUES ('Author One', 'Ace', 30);
INSERT INTO Author("name") VALUES ('Author two');
```

Converting this to array I simply do this
```sql
SELECT ARRAY(SELECT Author FROM Author)
```
I can see that the results being shown in PostgresSQL. However, I am trying to retrieve the data with `rust-postgres` and not having any luck.
```rust
#[derive(FromSql)]
struct Author {
    id: i64,
    name: String,
    publisher: Option<String>,
    age: Option<i16>
}

fn test_function() {
     let rows = ..... // this is where I perform SELECT ARRAY(SELECT Author FROM Author)

     for row in rows {
        let authors: Vec<Author> = row.get(1); // this is where it crashes. 
     }
}
```

Not sure how to convert SQL `Array` to Rust `Vec`.

Am I missing something

**Comment by sfackler** [comment]
How specifically does it crash?

**Comment by tomus85** [comment]
this is one example with `row.get(1)`
```bash
thread 'test_auth_array' panicked at 'error retrieving column 1: invalid column `1`', /Users/.../.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-postgres-0.6.0/src/row.rs:150:25
stack backtrace:
```

I did `println!("{:?}, row)` to see what I can gather:
```
Row { columns: [Column { name: "array", type: Other(Other { name: "_author", oid: 87478, kind: Array(Other(Other { name: "author", oid: 87479, kind: Composite([Field { name: "id", type_: Int8 }, Field { name: "name", type_: Varchar }, Field { name: "publisher", type_: Varchar }, Field { name: "age", type_: Int2 }]), schema: "public" })), schema: "public" }) }] }
```

Its an array type, also I don't know where `_author` is coming from

**Comment by sfackler** [comment]
Oh, right. Columns are zero indexed, so there is no column 1, just a column 0.

**Comment by tomus85** [comment]
Ah yes you are correct, now its complaining with a different error, this is where I saw the `_author` earlier. 

```panicked at 'error retrieving column 0: error deserializing column 0: cannot convert between the Rust type `alloc::vec::Vec<test_function_state::Author>` and the Postgres type `_author`', /Users/.../.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-postgres-0.6.0/src/row.rs:150:25
```

I've also tried `row.get("_author")` but getting an invalid, this I expect.

**Comment by sfackler** [comment]
It looks like the name of the type in Postgres is `author`, not `Author`. Not sure if that's because the table is actually called `author` or because Postgres is lowercasing the table name for the associated composite type.

**Comment by tomus85** [comment]
thank you very much 👍 
That was the issue. Even though in my SQL `Author` starts with capital `A` but when viewing tables it starts with lowercase `a`. 
It has managed to convert the array to vec....
