### ISSUE TITLE
Support for `WHERE ... IN ($x)`

### ISSUE THREAD

**Issue by inzanez** [sfackler/rust-postgres#745]
Hi

are there any plans to support constructs where a `set` instead of an `array`is passed, which would allow the use of `IN (...)`? I know that most (or even all) of the `IN` queries can be transformed to `ANY` queries. However, the `IN` query may make use of an index where the `ANY` query will not do so.

As this may be quite a drawback if running a `SELECT` matching on a large list of values, `IN` support would be really nice. I would be happy to write a PR to make that work, but maybe some upfront input might help. I am currently struggling of how to best keep the two apart as both `ANY` and `IN` will have to base on `Vec<T>`.

**Comment by sfackler** [comment]
There is no set type in Postgres as far as I'm aware. `IN` takes a comma separated list of expressions, not an array value.

**Comment by inzanez** [comment]
@sfackler Right, that might have been a bit imprecise. So if I'm getting that right, there's no way to use the `IN` operator with parameters. One would have to construct that comma separated list manuallly.

**Comment by sfackler** [comment]
If you wanted to use `IN` with a variable number of parameters, you would need to dynamically construct the `($1, $2, $3)` bit, that's correct.

However, I don't understand what you mean when you say that `ANY` queries will not use indices. For example, these simple queries have identical plans using `IN` vs `ANY`, using a bitmap index scan.

```
postgres=# CREATE TEMPORARY TABLE test (id INTEGER PRIMARY KEY);
CREATE TABLE
postgres=# EXPLAIN SELECT * FROM test WHERE id IN (1, 2);
                               QUERY PLAN
------------------------------------------------------------------------
 Bitmap Heap Scan on test  (cost=4.33..9.67 rows=2 width=4)
   Recheck Cond: (id = ANY ('{1,2}'::integer[]))
   ->  Bitmap Index Scan on test_pkey  (cost=0.00..4.32 rows=2 width=0)
         Index Cond: (id = ANY ('{1,2}'::integer[]))
(4 rows)

postgres=# EXPLAIN SELECT * FROM test WHERE id = ANY('{1, 2}');
                               QUERY PLAN
------------------------------------------------------------------------
 Bitmap Heap Scan on test  (cost=4.33..9.67 rows=2 width=4)
   Recheck Cond: (id = ANY ('{1,2}'::integer[]))
   ->  Bitmap Index Scan on test_pkey  (cost=0.00..4.32 rows=2 width=0)
         Index Cond: (id = ANY ('{1,2}'::integer[]))
(4 rows)
```

**Comment by inzanez** [comment]
Yes, it's a special case and usually won't matter I guess. I will need to do some more testing, but for now this might give a hint:
https://dba.stackexchange.com/questions/125413/index-not-used-with-any-but-used-with-in/125500#125500
