### ISSUE TITLE
Possibility to clear types cache

### ISSUE THREAD

**Issue by pleshevskiy** [sfackler/rust-postgres#753]
At the moment the library works in such a way that if we use custom types (domain, enum, composite) in our queries and if we need to upgrade database, we need to reload the server after that.

After much research into the source code, I realized that everything is hidden in InnerClient.state.types. Once a connection exists, the client polls the database and collects the types in a hashmap. Cool, but it's not assumed that the types can actually be dynamic.

I think there are several ways to implement this:
1) Add a setting where InnerClient doesn't cache types at all. Easiest and for most lightweight systems, utilities, this is the way to go!
2) Add the possibility to clear the types cache in the public api.
3) Add the possibility to customize the lifetime of the cache. This is more complicated, it takes time. But it would be perfect! https://docs.rs/cached/0.23.0/cached/

It would be ideal to implement all of this! We couldn't cache simple things.  In other cases, state with cache and clear the cache on error.

**Comment by sfackler** [comment]
I think option 2 seems like a reasonable approach.

**Comment by pleshevskiy** [comment]
Thank you! This option suits me completely. I can try to implement it and open PR soon if you don't mind
