### ISSUE TITLE
Bug: "EXECUTE" Statement with parameters parsed incorrectly

### ISSUE THREAD

**Issue by ColinTimBarndt** [sfackler/rust-postgres#757]
When I connect to my server, I first run a series of initialization SQL statements, which create databases and define some named prepared statements because I want to use them for my whole connection with Postgre `EXECUTE statement (params...)` statements. The only problems is that if I want to pass user input to the statement (`EXECUTE user_exists($1)`), the `query_one` function panics with `expected 0 parameters but got 1` using the following code:

```rs
// using tokio_postgres
pub async fn user_exists(&self, username: &str) -> Result<bool> {
    if username.len() > 16 {
        return Ok(false);
    }
    let result = self
        .client // Arc<Client>
        .query_one("EXECUTE user_exists($1)", &[&username])
        .await?
        .get("exists");
    Ok(result)
}
```

The prepared statement is defined in my `init.sql` that I execute as soon as the connection is established:
```sql
-- ...
PREPARE user_exists (CHARACTER VARYING(16))
AS
	SELECT EXISTS (
		SELECT 1
		FROM public.logins
		WHERE username LIKE $1
	)
-- ...
```

I am aware that I can define prepared statements using the `prepare` function, but it just returns me a handle to the statement which is counterintuitive because I want to use the prepared statements across my entire Actor Model program (in many different tasks). Sharing it using an `Arc<SomeStruct>` would also be counterintuitive because the prepared statements are stored on the server and not on the client.

It would be great if correct support for the `EXECUTE` statement was added. Otherwise I would recomment to at least leave a note in the documentation that this statement is not supported.

**Comment by sfackler** [comment]
Parameter parsing and handling is performed entirely by the Postgres server. I'm not sure why the argument components of an `EXECUTE` query wouldn't be eligible to be parameters, but it seems like that's the case? This would need to be fixed on the Postgres side as far as I can tell.

**Comment by ColinTimBarndt** [comment]
> Parameter parsing and handling is performed entirely by the Postgres server. I'm not sure why the argument components of an `EXECUTE` query wouldn't be eligible to be parameters, but it seems like that's the case? This would need to be fixed on the Postgres side as far as I can tell.

This seems not to be the case because tokio-postgres itself is issuing the panic:
<details>
<summary>Stack trace</summary>

```txt
thread 'database::test::test' panicked at 'expected 0 parameters but got 1', C:\Users\Admin\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-postgres-0.7.1\src\query.rs:160:5
stack backtrace:
   0: std::panicking::begin_panic_handler
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0\/library\std\src\panicking.rs:493
   1: std::panicking::begin_panic_fmt
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0\/library\std\src\panicking.rs:435
   2: tokio_postgres::query::encode_bind<ToSql*,core::iter::adapters::map::Map<core::slice::iter::Iter<ToSql*>, closure-0>>
             at C:\Users\Admin\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-postgres-0.7.1\src\query.rs:160
   3: tokio_postgres::query::encode::{{closure}}<ToSql*,core::iter::adapters::map::Map<core::slice::iter::Iter<ToSql*>, closure-0>>
             at C:\Users\Admin\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-postgres-0.7.1\src\query.rs:140
   4: tokio_postgres::client::InnerClient::with_buf<closure-0,core::result::Result<bytes::bytes::Bytes, tokio_postgres::error::Error>>
             at C:\Users\Admin\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-postgres-0.7.1\src\client.rs:125
   5: tokio_postgres::query::encode<ToSql*,core::iter::adapters::map::Map<core::slice::iter::Iter<ToSql*>, closure-0>>
             at C:\Users\Admin\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-postgres-0.7.1\src\query.rs:139
   6: tokio_postgres::query::query::{{closure}}<ToSql*,core::iter::adapters::map::Map<core::slice::iter::Iter<ToSql*>, closure-0>>
             at C:\Users\Admin\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-postgres-0.7.1\src\query.rs:49
   7: core::future::from_generator::{{impl}}::poll<generator-0>
             at C:\Users\Admin\.rustup\toolchains\stable-x86_64-pc-windows-msvc\lib\rustlib\src\rust\library\core\src\future\mod.rs:80
   8: tokio_postgres::client::{{impl}}::query_raw::{{closure}}<str,ToSql*,core::iter::adapters::map::Map<core::slice::iter::Iter<ToSql*>, closure-0>>
             at C:\Users\Admin\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-postgres-0.7.1\src\client.rs:355
   9: core::future::from_generator::{{impl}}::poll<generator-0>
             at C:\Users\Admin\.rustup\toolchains\stable-x86_64-pc-windows-msvc\lib\rustlib\src\rust\library\core\src\future\mod.rs:80
  10: tokio_postgres::client::{{impl}}::query_one::{{closure}}<str>
```

</details>

Which happens here:

```rs
assert!(
    statement.params().len() == params.len(),
    "expected {} parameters but got {}",
    statement.params().len(),
    params.len()
);
```
If the error happened on the server side, the crate would have returned an `Err` value as far as I understand it.
I am going to write a test purely on the server side using pgAdmin just to be sure.

**Comment by sfackler** [comment]
The server is the thing that tells the client how many parameters the statement contains.

**Comment by ColinTimBarndt** [comment]
I found out that it is actually impossible to nest prepared statements:

```sql
PREPARE test_param (CHARACTER VARYING(16))
AS
	EXECUTE user_exists($1)
```

While the [documentation] does not clearly state this, a `PREPARE` statement only seems to expect `INSERT`, `DELETE`, `SELECT`, etc statements. An `EXECUTE` statement is treated as a syntax error. Because of this, it would be nice if it was possible to call a custom prepared statement (which was not explicitely defined using `prepare`) with arguments. Would this be possible to safely implement? I can't create a custom instance by calling `Statement::new`.

[documentation]: https://www.postgresql.org/docs/current/sql-prepare.html

**Comment by sfackler** [comment]
I don't know enough about how statements created by `PREPARE` are structured and stored. It may be possible to retrieve enough information from the server to create a `Statement` from them.

**Comment by sfackler** [comment]
However, it would probably be significantly easier overall to adjust your intuition on storing statement handles alongside the client.

**Comment by ColinTimBarndt** [comment]
Yeah, I am rewriting my code for this now. I like the concept of data-driven code though, where I could at least define the structure storing the statement from an sql file with `PREPARE` statements.

By the way, `Statement` does not implement `Debug`. I just noticed this when attempting to derive the trait from my storage structure.

**Comment by ColinTimBarndt** [comment]
I have closed this issue because it is not related to rust-progres itself.
