### ISSUE TITLE
Query to JSON without any de/serialization?

### ISSUE THREAD

**Issue by Zerowalker** [sfackler/rust-postgres#762]
If i query to json via postgresql, what's the correct way get the raw json data?

The usecase is that i grab the json data and then pass it along to the client (browser),
and as postgresql does the json serialization already i don't want to any extra steps to be taken on the data as it's just wasted as it's already in the format i want it to.

using serde_json::Value seems to do some extra steps, but i can't use a String unless i use ::text inside the query, which just seems wrong as that would do an extra conversion by postgresql, even it it might happen to end up with the same results.

As i can't seem to figure it out decided to ask here to hopefully solve this dilemma:)

**Comment by sfackler** [comment]
I would just cast to text in the query.

**Comment by Zerowalker** [comment]
But doesn't that, well cast it?
when you query for json in postgresql, isn't it essentially text you get?
so casting it to text seems like an extra step, as in rust doesn't handle json as text even though it should be able to.

or am i missing something?

**Comment by sfackler** [comment]
I'm not sure I understand. You want to retrieve some data in JSON's standard text encoding. Asking Postgres to produce that for you seems like a straightforward approach.

**Comment by Zerowalker** [comment]
I am probably just not understanding how it works.
To me when i use json in postgresql, i think of it as the json text, so just text that follows the json standard.
So to then say "convert it from json text to text" seems like it's like doing something like "int to int" if you will.
So it does a conversion that's not needed as it's already in the correct state.

Is my understanding of this wrong perhaps?

**Comment by sfackler** [comment]
The binary transmission format for JSONB in particular is not just JSON text. If you want JSON text, you can ask for that by casting to a string type.

**Comment by Zerowalker** [comment]
I am talking about the JSON type, not JSONB, should have specified that perhaps, my bad.

**Comment by sfackler** [comment]
You can make a custom implementation of `FromSql` that pulls the raw response data for JSON values if you want.

**Comment by Zerowalker** [comment]
Oh really?
That would be interesting, will try and see if i can make it.

**Comment by Zerowalker** [comment]
I guess i should close this as i think this is the solution i was looking for.
Thanks:)!
