### ISSUE TITLE
Insert With Returning Clause

### ISSUE THREAD

**Issue by erichCompSci** [sfackler/rust-postgres#771]
It would be nice if there could be at least some limited support for the returns clause in postgresql, as described here:
https://www.postgresqltutorial.com/postgresql-insert/

In particular, I'd like to use it with the tokio async code, but I recognize that it could be used synchronously as well.

This might require new types to encapsulate the different return types.  I might be able to take a crack at this myself, but I was hoping for comment first.

**Comment by sfackler** [comment]
You can just use `client.query(...)`.

**Comment by sfackler** [comment]
I am not saying you can insert and then later query for the new rows, I am saying that `client.query(...)` works with `INSERT ... RETURNING ...` just fine.

```rust
let inserted_ids = client.query(
    "INSERT INTO example (name, email, created_on) VALUES ($1, $2, $3) RETURNING user_id",
    &[&name, &email, &created_on],
).await?;
```

**Comment by erichCompSci** [comment]
This is awesome, thank you.
