### ISSUE TITLE
`date_trunc` behavior change between 0.7.0 and 0.7.1

### ISSUE THREAD

**Issue by kamulos** [sfackler/rust-postgres#775]
A depency upgrade starting from 0.7.0 broke my application. When before `date_trunc` gave me back the days in the UTC time zone, it now uses the systems time zone.

The commit is fbc42ecbe88eb1712a3c3650f295e9d84d09df5a

I have two points:
1. How do I get the old behavior back? I am using `deadpool-postgres` and I can't find any config parameter, that will set me the default time zone for the connection.
2. As this is a significant behavior change this is a bit surprising to come with a semver patch release

**Comment by sfackler** [comment]
You should be able to configure this via the options component of the connection configuration: `options="-c timezone=UTC"`.

Apologies for the break - I had not thought of how it would interact with implicit conversions to un-zoned types.

**Comment by kamulos** [comment]
Thanks, that worked perfectly :slightly_smiling_face:
