### ISSUE TITLE
Streaming very large results

### ISSUE THREAD

**Issue by obourgain** [sfackler/rust-postgres#782]
I have a query that needs to returns millions of rows in a very efficient way. I am not sure how to do that properly, as it seems that both `Transaction::query_portal` and `Client::query_raw` can stream the result set.
Could you explain the difference in behavior between those?

If you are familiar with the Postgres driver in Java (or JDBC in general), I am looking for an equivalent to `ResultSet.setFetchSize(int) `.

Thank you.

**Comment by sfackler** [comment]
The `query_raw` method will stream the resulting rows, but you're "locked in" to receiving all of them from the DB regardless of how many you actually need at the end of it. In contrast, `query_portal` allows you to explicitly ask for just a single "chunk" of the remaining rows of a query. I would guess that `setFetchSize` would work with portals, but I haven't looked at the actual implementation.

**Comment by obourgain** [comment]
I understand, thank you. I will use `query_raw` as it is simpler and seems faster.
