### ISSUE TITLE
How to use postgres from async context?

### ISSUE THREAD

**Issue by hhanh00** [sfackler/rust-postgres#784]
I need to use the synchronous driver for postgres because of one of my dependencies.
But the whole thing is wrapped in a GRPC / tonic server.

Basically, grpc -> 3rd party library -> my code -> postgres.

rust-postgres block_on the runtime that tonic uses. This gives an error
```
'Cannot start a runtime from within a runtime. This happens because a function (like `block_on`) attempted to block the current thread while the thread is being used to drive asynchronous tasks.'
```

A minimal repro would be:
```
use postgres::{Client, NoTls};

#[tokio::main]
async fn main() {
    let _client = Client::connect("host=localhost dbname=template1 user=postgres", NoTls).unwrap();
}

tokio = { version = "1.6.1", features = ["rt-multi-thread", "macros"] }
postgres = "0.19.1"

```

Because of the third party library, I cannot use the async postgres driver and I cannot change the way tonic uses tokio. Anything else is ok.

Do you have any suggestion?

Thanks,
--h

**Comment by sfackler** [comment]
You should not run blocking networking code from an asynchronous task. Use something like spawn_blocking instead:

```rust
use postgres::{Client, NoTls};

#[tokio::main]
async fn main() {
    let _client = tokio::task::spawn_blocking(|| {
        Client::connect("host=localhost dbname=template1 user=postgres", NoTls)
    })
    .await
    .unwrap()
    .unwrap();
}
```

**Comment by hhanh00** [comment]
The blocking network code is not called directly from async code. It is called by the third party library (which is synchronous). I need to expose a grpc server and tonic is async. It is the async (tonic) -> sync (3rd party) -> sync (my code) -> sync (rust-postgres) -> async (tokio-postgres) that is challenging.

**Comment by sfackler** [comment]
What third party library is this? From the error you are seeing, it is running the "sync" code directly on an async runtime thread.

**Comment by hhanh00** [comment]
It's tonic that initiates the async context. The 3rd party library is just regular synchronous code. Eventually, it calls back into client code. For example, this code has the same problem: https://dev.to/steadylearner/how-to-use-grpc-with-rust-tonic-and-postgres-database-with-examples-3dl7

I got it to run by using `block_in_place`. Something like:

```rust
#[tonic::async_trait]
impl Rpc for RPCService {
    async fn test(&self, req: Request<ReqValue>) -> Result<Response<RepId>> {
        let v = req.into_inner().v;
        let id = block_in_place(|| {
            let mut c = Client::connect("postgresql://hanh@localhost/hanh", NoTls).unwrap();
            let row = c.query_one("SELECT id FROM t WHERE i = $1", &[&v]).unwrap();
            let id: i32 = row.get(0);
            id
        });
        Ok(Response::new(RepId { id }))
    }
}

#[tokio::main]
async fn main() {
    let addr = "[::1]:3001".parse().unwrap();
    let service = RPCService {};
    Server::builder().add_service(RpcServer::new(service)).serve(addr).await.unwrap();
}
```
