### ISSUE TITLE
Shorter syntax for query_raw without parameters

### ISSUE THREAD

**Issue by flip111** [sfackler/rust-postgres#796]
https://docs.rs/postgres/0.19.1/postgres/struct.Client.html#method.query_raw

for normal query i could use `&[]` .. for `query_raw` i get `cannot infer type for reference &_`. When i make a separate variable like `let params: Vec<String> = vec![];`. Is there anything that could be done to have short syntax like the normal query function?

**Comment by sfackler** [comment]
You could define a const and use that as a shorthand:

```rust
const NO_PARAMS: &[&ToSql] = &[];
// ...
client.query_raw("SELECT * FROM foo", NO_PARAMS);
```

Alternatively, you could define a method that didn't take params on an extension trait and implement that for Client.

**Comment by flip111** [comment]
Thanks @sfackler , i will leave this issue open in case you decide it's something to add for the documentation or so. Close at your convenience.

**Comment by flip111** [comment]
```
rror[E0277]: the size for values of type `dyn ToSql` cannot be known at compilation time
  --> src/main.rs:99:35
   |
99 |     order by stid asc, date asc", NO_PARAMS)?;
   |                                   ^^^^^^^^^ doesn't have a size known at compile-time
   |
   = help: the trait `Sized` is not implemented for `dyn ToSql`
   = note: required because of the requirements on the impl of `ToSql` for `&dyn ToSql`
   = note: 1 redundant requirements hidden
   = note: required because of the requirements on the impl of `ToSql` for `&&dyn ToSql`
   = note: required because of the requirements on the impl of `BorrowToSql` for `&&dyn ToSql`
```

**Comment by sfackler** [comment]
Oh right, sorry. Here's a working example! https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=eb3de625f705651ee3a6f6d2020b513d
