### ISSUE TITLE
Named derived enum on Rust only works if it's lowercased

### ISSUE THREAD

**Issue by progrestian** [sfackler/rust-postgres#797]
Say I have an SQL enum like so:

`CREATE TYPE ENTRY_FORMAT AS ENUM ('Movie', 'Series', 'Unknown');`

and a Rust enum like so:

```rust
#[derive(Debug, Deserialize, FromSql, Serialize, ToSql)]
#[postgres(name = "ENTRY_FORMAT")]
pub enum Format {
    Movie,
    Series,
    Unknown,
}
```

Doing a simple prepared query (`SELECT * FROM entries WHERE format = $1`) will not work on PostgreSQL 13 with an error that looks like this:

`Err(Error { kind: ToSql(0), cause: Some(WrongType { postgres: Other(Other { name: "entry_format", oid: 25641, kind: Enum(["Movie", "Series", "Unknown"]), schema: "public" }), rust: "tlusr::Format" }) })`

but if I change the name attribute to lowercase like so:

`#[postgres(name = "entry_format")]`

then it will accept the enum flawlessly.
Is this intended? If so, maybe you can add to the docs (or I can make a small PR)?

**Comment by sfackler** [comment]
That is intended and already documented: https://docs.rs/postgres-types/0.2.1/postgres_types/#naming

**Comment by sfackler** [comment]
Postgres always folds non-quoted names to lower-case: https://stackoverflow.com/questions/20878932/are-postgresql-column-names-case-sensitive.

`CREATE TYPE "ENTRY_FORMAT" ...` will give you the upper case name if you want it.

**Comment by progrestian** [comment]
Ah I see, so the weirdness is from postgres's side.  
I'll close the issue then.  

Is adding this to the docs needed?
