### ISSUE TITLE
How is the error handling intended (especially on a connection error)?

### ISSUE THREAD

**Issue by 0xA537FD** [sfackler/rust-postgres#798]
Hey there,
I'd like to know how the error handling in the postgres library is intended to be used, especially in the context of a connection error in the `Client`. What I want to achieve is to log a custom error message when the connection could not be established because the postgres db is offline.

I have a small snippet below on how I connect to the db. Usually I'd expect some kind of enum or something on which I could perform pattern matching but with the postgres error I honestly have no idea how it should be done.

```rust
let mut db_client = match Client::connect("user:user@localhost:5432/db", NoTls) {
    Ok(c) => c,
    Err(e) => {
        // how should i match the specific error in here?
    }
};
```

**Comment by sfackler** [comment]
How would you determine if the DB is offline? A connection refusal? Read or write timeout? TLS handshake failure? Unexpected EOF? Any IO error?

**Comment by 0xA537FD** [comment]
In this case I'd like to catch a connection refusal and log to the user that the db might be offline. The error which I get looks like this:

```
Error { kind: Connect, cause: Some(Os { code: 111, kind: ConnectionRefused, message: "Connection refuse
d" }) }
```

Since I can't match the `kind` and don't know where to find the `Os` struct that is assigned to `cause` and whether it is even public etc., I don't know how to check if I received a connection refusal.

**Comment by sfackler** [comment]
You can call `error.source()` and try to downcast that to a `std::io::Error`.

**Comment by 0xA537FD** [comment]
Thank You!

For anyone else who might want to achieve this. What I've done looks something like this:

```rust
use std::io;

let mut db_client = match Client::connect("user:user@localhost:5432/db", NoTls) {
    Ok(c) => c,
    Err(e) => {
        if let Some(e) = e.source() {
			if let Some(e) = e.downcast_ref::<io::Error>() {
				if let io::ErrorKind::ConnectionRefused = e.kind() {
					panic!("Failed to connect to the db");
				}
			}
		}
    }
};
```
