### ISSUE TITLE
Connection is stuck in tokio_postgres::connect, despite timeout

### ISSUE THREAD

**Issue by NotSqrt** [sfackler/rust-postgres#801]
Hello,

I'm having troubles with a connection to a database on localhost.
My setup is not very simple : a PyO3 library, that starts a tokio runtime at the first import from python, and then a connection is opened when calling some functions from python.
When working from a basic python process, it works correctly. When working inside a [celery](https://docs.celeryproject.org/) worker (that uses forking), it fails.

I've confirmed that the `connect_with_timeout` function is called with a usable timeout, but the `TcpStream::connect` call never ends despite the `time::timeout` wrapper.

With wireshark, I have confirmed that the handshake of the TCP connection is done, but then no data is exchanged, and from the point of view of postgres, no connection is attempted.

The `tracing` crate with the `RUSTFLAGS="--cfg tokio_unstable"` compilation flag does not give more details.

I'm using latest rust, tokio, tokio-postgres versions, on ubuntu.

Do you have any tips on where to go from here to continue the debugging ?
Does that remind you of a similar problem ?

Thanks a lot !

**Comment by sfackler** [comment]
I am not familiar with how celary works, but I would not be surprised if forking disrupted the proper operation of a Tokio runtime in some way.

**Comment by NotSqrt** [comment]
Indeed !

I moved the tokio runtime initialisation at first usage instead of first import from python, and the issue is gone. It certainly was due to celery forking a process where a tokio runtime was already initialized.

Problem solved !
