### ISSUE TITLE
windows connection error UTF-8

### ISSUE THREAD

**Issue by Stargateur** [sfackler/rust-postgres#803]
I setup a postgresql server v13 on my window (mostly to see if it was possible) all default expect for ssl configuration (that work finally) but I end up with a hard error:

```none
Jul 11 01:49:50.720 TRACE mio::poll: registering event source with poller: token=Token(2), interests=READABLE | WRITABLE
Jul 11 01:49:50.780 TRACE tokio_util::codec::framed_impl: flushing framed transport
Jul 11 01:49:50.780 TRACE tokio_util::codec::framed_impl: writing; remaining=44
Jul 11 01:49:50.781 TRACE tokio_util::codec::framed_impl: framed transport flushed
Jul 11 01:49:50.782 TRACE tokio_util::codec::framed_impl: attempting to decode a frame
Jul 11 01:49:50.782 TRACE tokio_util::codec::framed_impl: frame decoded from buffer
Jul 11 01:49:50.783 TRACE tokio_util::codec::framed_impl: flushing framed transport
Jul 11 01:49:50.784 TRACE tokio_util::codec::framed_impl: writing; remaining=81
Jul 11 01:49:50.784 TRACE tokio_util::codec::framed_impl: framed transport flushed
Jul 11 01:49:50.784 TRACE tokio_util::codec::framed_impl: attempting to decode a frame
Jul 11 01:49:50.784 TRACE tokio_util::codec::framed_impl: attempting to decode a frame
Jul 11 01:49:50.785 TRACE tokio_util::codec::framed_impl: frame decoded from buffer
Jul 11 01:49:51.027 TRACE tokio_util::codec::framed_impl: flushing framed transport
Jul 11 01:49:51.027 TRACE tokio_util::codec::framed_impl: writing; remaining=181
Jul 11 01:49:51.027 TRACE tokio_util::codec::framed_impl: framed transport flushed
Jul 11 01:49:51.028 TRACE tokio_util::codec::framed_impl: attempting to decode a frame
Jul 11 01:49:51.038 TRACE tokio_util::codec::framed_impl: attempting to decode a frame
Jul 11 01:49:51.039 TRACE tokio_util::codec::framed_impl: frame decoded from buffer
Jul 11 01:49:51.039 TRACE mio::poll: deregistering event source from poller
Jul 11 01:49:51.039 DEBUG optomata::internal_server_error: Pool { source: Backend(Error { kind: Parse, cause: Some(Custom { kind: InvalidInput, error: Utf8Error { valid_up_to: 34, error_len: Some(1) } }) }) }
Jul 11 01:49:51.040 ERROR optomata::internal_server_error: Pool: An error occured while creating a new object: error parsing response from server: invalid utf-8 sequence of 1 bytes from index 34
```

I use deadpool but that unrelated, I'm unaware of a PostgreSQL option for internal protocol encoding. The same code work for a linux server.

HS: don't do like me it's a nightmare

I did run the test of tokio-postgresql:

```none
---- custom_array stdout ----
thread 'custom_array' panicked at 'called `Result::unwrap()` on an `Err` value: Error { kind: Db, cause: Some(DbError { severity: "ERREUR", parsed_severity: Some(Error), code: SqlState(E42704), message: "le type « hstore[] » n'existe pas", detail: None, hint: None, position: Some(Original(12)), where_: None, schema: None, table: None, column: None, datatype: None, constraint: None, file: Some("d:\\pginstaller_13.auto\\postgres.windows-x64\\src\\backend\\parser\\parse_type.c"), line: Some(274), routine: Some("typenameType") }) }', tokio-postgres\tests\test\main.rs:193:62
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

---- md5_password_ok stdout ----
thread 'md5_password_ok' panicked at 'called `Result::unwrap()` on an `Err` value: Error { kind: Parse, cause: Some(Custom { kind: InvalidInput, error: Utf8Error { valid_up_to: 4, error_len: Some(1) } }) }', tokio-postgres\tests\test\main.rs:32:53

---- notices stdout ----
thread 'notices' panicked at 'assertion failed: `(left == right)`
  left: `"l'identifiant « xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx » sera tronqué en « xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx »"`,
 right: `"identifier \"xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx\" will be truncated to \"xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx\""`', tokio-postgres\tests\test\main.rs:604:5

---- md5_password_wrong stdout ----
thread 'md5_password_wrong' panicked at 'error parsing response from server: invalid utf-8 sequence of 1 bytes from index 4', tokio-postgres\tests\test\main.rs:73:19

---- pipelined_prepare stdout ----
thread 'pipelined_prepare' panicked at 'called `Result::unwrap()` on an `Err` value: Error { kind: Db, cause: Some(DbError { severity: "ERREUR", parsed_severity: Some(Error), code: SqlState(E42704), message: "le type « hstore[] » n'existe pas", detail: None, hint: None, position: Some(Original(12)), where_: None, schema: None, table: None, column: None, datatype: None, constraint: None, file: Some("d:\\pginstaller_13.auto\\postgres.windows-x64\\src\\backend\\parser\\parse_type.c"), line: Some(274), routine: Some("typenameType") }) }', tokio-postgres\tests\test\main.rs:111:66

---- plain_password_ok stdout ----
thread 'plain_password_ok' panicked at 'called `Result::unwrap()` on an `Err` value: Error { kind: Parse, cause: Some(Custom { kind: InvalidInput, error: Utf8Error { valid_up_to: 4, error_len: Some(1) } }) }', tokio-postgres\tests\test\main.rs:32:53

---- plain_password_wrong stdout ----
thread 'plain_password_wrong' panicked at 'error parsing response from server: invalid utf-8 sequence of 1 bytes from index 4', tokio-postgres\tests\test\main.rs:51:19

---- scram_password_wrong stdout ----
thread 'scram_password_wrong' panicked at 'error parsing response from server: invalid utf-8 sequence of 1 bytes from index 4', tokio-postgres\tests\test\main.rs:95:19

---- scram_password_ok stdout ----
thread 'scram_password_ok' panicked at 'called `Result::unwrap()` on an `Err` value: Error { kind: Parse, cause: Some(Custom { kind: InvalidInput, error: Utf8Error { valid_up_to: 4, error_len: Some(1) } }) }', tokio-postgres\tests\test\main.rs:32:53

---- types::test_hstore_params stdout ----
thread 'types::test_hstore_params' panicked at 'called `Result::unwrap()` on an `Err` value: Error { kind: Db, cause: Some(DbError { severity: "ERREUR", parsed_severity: Some(Error), code: SqlState(E42704), message: "le type « hstore » n'existe pas", detail: None, hint: None, position: Some(Original(16)), where_: None, schema: None, table: None, column: None, datatype: None, constraint: None, file: Some("d:\\pginstaller_13.auto\\postgres.windows-x64\\src\\backend\\parser\\parse_type.c"), line: Some(274), routine: Some("typenameType") }) }', tokio-postgres\tests\test\types\mod.rs:46:14

---- types::test_citext_params stdout ----
thread 'types::test_citext_params' panicked at 'called `Result::unwrap()` on an `Err` value: Error { kind: Db, cause: Some(DbError { severity: "ERREUR", parsed_severity: Some(Error), code: SqlState(E42704), message: "le type « citext » n'existe pas", detail: None, hint: None, position: Some(Original(87)), where_: None, schema: None, table: None, column: None, datatype: None, constraint: None, file: Some("d:\\pginstaller_13.auto\\postgres.windows-x64\\src\\backend\\parser\\parse_type.c"), line: Some(274), routine: Some("typenameType") }) }', tokio-postgres\tests\test\types\mod.rs:276:10
```

```sql
SHOW SERVER_ENCODING;
```

```none
result to:
 server_encoding
-----------------
 UTF8
(1 ligne)
```

I have no idea if support windows is a goal or not.

**Comment by sfackler** [comment]
Can you use something like Wireshark to capture the communications with the postgres server?

**Comment by Stargateur** [comment]
[output.pcapng.gz](https://github.com/sfackler/rust-postgres/files/6796159/output.pcapng.gz)

I tried notice I don't know much about how to use wireshark, I filter based on localloop and port 5432, there is no sensitive information, well in fact there was, I forget to update the password, the old one was a generate password from a old server deleted... and so using the good password there is not anymore the error. So I guess the bug is somewhere for wrong password code.

wrong password was = "Mo&NTSgsOR;0[2$,lKXH" (not used anymore so safe)

**Comment by sfackler** [comment]
It looks like the connection was made with TLS, so I unfortunately can't see any of the interesting parts. Could you capture the same thing but with TLS disabled?

**Comment by Stargateur** [comment]
Oh, yes, of course, so finally my password wasn't compromise.

here, the real password is.... "password", and I put a wrong password "passwor" same error
[output.pcapng.gz](https://github.com/sfackler/rust-postgres/files/6797262/output.pcapng.gz)

**Comment by sfackler** [comment]
It looks like the issue is with Postgres's French locale. The error message is not valid UTF-8:

Raw escaped bytes:
```
\x4d\x61\x75\x74\x68\x65\x6e\x74\x69\x66\x69\x63\x61\x74\x69\x6f
\x6e\x20\x70\x61\x72\x20\x6d\x6f\x74\x20\x64\x65\x20\x70\x61\x73
\x73\x65\x20\xe9\x63\x68\x6f\x75\xe9\x65\x20\x70\x6f\x75\x72\x20
\x6c\x27\x75\x74\x69\x6c\x69\x73\x61\x74\x65\x75\x72\x20\x20\xab
\x20\x6f\x70\x74\x6f\x6d\x61\x74\x61\x20\xbb\x00
```

`String::from_utf8_lossy` decode:

```
Mauthentification par mot de passe �chou�e pour l'utilisateur  � optomata �
```

**Comment by Stargateur** [comment]
probably WTF-16 of windows, should this be considered a bug to report https://www.postgresql.org/docs/13/bug-reporting.html#id-1.3.8.7 ? In my option yes, postgresql should return a utf8 string in its internal protocol even if windows use WTF-16.

**Comment by sfackler** [comment]
Yeah, this definitely seems like a bug in Postgres. Error messages should respect client_encoding, or if not their encoding should be specified in the [documentation](https://www.postgresql.org/docs/13/protocol-error-fields.html).

**Comment by rjuju** [comment]
Hi,

As I just answered on the postgres mailing lists (https://www.postgresql.org/message-id/flat/CAO16vDNM5_eUZG3unbumx2AJt11VZxuQxn9cSZ9VhSCpD1TMgw%40mail.gmail.com) , this is in my understanding sadly working as designed.  The client encoding can't be set during startup (and authentication is part of it), see https://github.com/postgres/postgres/blob/master/src/backend/utils/mb/mbutils.c#L85-L88 for more details about it:

> /*
>  * During backend startup we can't set client encoding because we (a)
>  * can't look up the conversion functions, and (b) may not know the database
>  * encoding yet either.  So SetClientEncoding() just accepts anything and
>  * remembers it for InitializeClientEncoding() to apply later.
>  */

So rust-postgres should be prepared to receive non UTF-8 messages until authentication succeeded.

**Comment by sfackler** [comment]
Hmm, that's unfortunate. I guess we'll have to add some logic to our handling of ErrorResponses to do a lossy UTF-8 decode as necessary.

**Comment by rjuju** [comment]
Indeed.  I'm also wondering how much relying on UTF-8 only encoding can be problematic in some parts of the world.  I think that at least Japan is still using a lot of those encodings, and probably Taiwan with big5 encoding.

**Comment by Stargateur** [comment]
> such messages are currently sent using the language and encoding derived from the postmaster's environment. In simple cases that'll be the same as the client's environment and everything works.

I have strong opinion about all should default to UTF-8 in 2021, the specification of the protocol should specified a static encoding at least until the client can choice one. The current behavior to "use what OS use" that impact the protocol is not ideal cause the client need to handle every possible case like handle big5 encoding (never hear of it before but anyway). Asking a client to handle every text encoding is annoying.

But I see no reason to not have a flexible call to `from_utf8_lossy` in the error handling in Rust at least for now even if this allocate a string I don't see this as a big problem for an error return.

**Comment by rjuju** [comment]
> I  have strong opinion about all should default to UTF-8 in 2021

In an ideal world I would agree, but I think that it would break on a lot of environments as there are a lot of UTF-8 characters that are not supported in other encodings.  And I saw how creative some people are naming roles, databases and other objects :(

> But I see no reason to not have a flexible call to from_utf8_lossy in the error handling in Rust at least for now even if this allocate a string I don't see this as a big problem for an error return.

+1

**Comment by upachler** [comment]
Hi there,

@sfackler: Looks like I have a fix. 

I'm on a Windows machine (german locale), with a local PostgreSQL database and a rust app I'm currently developing, using sqlx. Upon connection, I'm getting pretty much the same error message as above. My hunch is that everyone with connection issues in a non-us local having 'funky' characters in their error message will get this issue. For me, it couldn't find the database and used non-ascii quote chars to enclose the database name - but this could happen in any error message, frankly.

I debugged this a little into the postgres-protocol crate (my toko-postgres is using the newest version 0.6.6). 

@sfackler you were talking about upgrading the error handling to be able to handle this better, and this is what I've done. So when parsing an `ErrorField` I now user `String::from_utf8_lossy()` (which returns `Cow<'a,str>`) instead of `get_str()`. Also, `ErrorField`'s `value` field is now `Cow<'a,str>` instead of `&str`. With this in place, I see proper error messages now (and I could finally find out what the connection problem in my project was :)

Please let me know if the fix is acceptable, or if I should change anything. Currently the fix sits in my fork here:
https://github.com/upachler/rust-postgres/tree/bugfix/803-windows-connection-error-utf-8 

Thanks,
Uwe

**Comment by xuyang2** [comment]
> It looks like the issue is with Postgres's French locale. The error message is not valid UTF-8:
> 
> Raw escaped bytes:
> 
> ```
> \x61\x75\x74\x68\x65\x6e\x74\x69\x66\x69\x63\x61\x74\x69\x6f
> \x6e\x20\x70\x61\x72\x20\x6d\x6f\x74\x20\x64\x65\x20\x70\x61\x73
> \x73\x65\x20\xe9\x63\x68\x6f\x75\xe9\x65\x20\x70\x6f\x75\x72\x20
> \x6c\x27\x75\x74\x69\x6c\x69\x73\x61\x74\x65\x75\x72\x20\x20\xab
> \x20\x6f\x70\x74\x6f\x6d\x61\x74\x61\x20\xbb\x00
> ```
> 
> `String::from_utf8_lossy` decode:
> 
> ```
> authentification par mot de passe �chou�e pour l'utilisateur  � optomata �
> ```
> 
> Note the `�`s, indicating an invalid UTF-8 byte sequence.

```rust
use encoding_rs;

fn main() {
    let bytes = b"\x61\x75\x74\x68\x65\x6e\x74\x69\x66\x69\x63\x61\x74\x69\x6f\x6e\x20\x70\x61\x72\x20\x6d\x6f\x74\x20\x64\x65\x20\x70\x61\x73\x73\x65\x20\xe9\x63\x68\x6f\x75\xe9\x65\x20\x70\x6f\x75\x72\x20\x6c\x27\x75\x74\x69\x6c\x69\x73\x61\x74\x65\x75\x72\x20\x20\xab\x20\x6f\x70\x74\x6f\x6d\x61\x74\x61\x20\xbb\x00";
    let (cow, encoding_used, had_errors) = encoding_rs::WINDOWS_1250.decode(bytes);
    println!("got: {:?}", &cow[..]);
    println!("encoding_used: {:?}", encoding_used);
    println!("had_errors: {:?}", had_errors);
}
```

output:
```console
got: "authentification par mot de passe échouée pour l'utilisateur  « optomata »\0"
encoding_used: Encoding { windows-1250 }
had_errors: false
```

**Comment by sfackler** [comment]
@upachler I ended up taking a slightly modified different route to avoid creating the Cow in postgres-protocol.

**Comment by upachler** [comment]
I'm sorry, but I just checked this with my project, and it still doesn't seem to work. I checked out https://github.com/sfackler/rust-postgres.git, to which it was merged.

I once again get the error message:
```
thread 'main' panicked at C:\Users\Uwe Pachler\.cargo\git\checkouts\rust-postgres-0028e9b4492c1e5d\647a925\postgres-protocol\src\message\backend.rs:657:36:
error field value contained non-UTF8 bytes: Utf8Error { valid_up_to: 10, error_len: Some(1) }
``` 

with the solution I suggested I get this (for the same deliberate misconfiguration, see the tolerated ill-encoded quotation marks around the database name):
```
thread 'main' panicked at verishda-server\src/bin/standalone.rs:39:56:
could not connect to database postgres://verishda:verishda@localhost:5432/verishdax: db error: FATAL: Datenbank �verishdax� existiert nicht
```

**Comment by sfackler** [comment]
Did you also pull tokio-postgres from the git repo?

**Comment by upachler** [comment]
Hi @sfackler,
Alright, with also patching tokio-postgres, this looks fixed to me now.
Thanks!
