### ISSUE TITLE
Implement `ToSql` and `FromSql` for fixed size Rust arrays `[T; N]`

### ISSUE THREAD

**Issue by LukasKalbertodt** [sfackler/rust-postgres#805]
Thanks for your work on this library!

I was wondering if there is a specific reason why `ToSql` and `FromSql` is not implemented for fixed size arrays? For example:

```sql
create table videos {
    resolution integer[2]
}
```

With this fixed size array, I would expect to be able to retrieve it like `row.get::<_, [i32; 2]>(0)`. Same for having composite types and using `derive(ToSql)` on a `struct`. 

Right now, postgres arrays can only be converted from/to slices and `Vec<T>`. Maybe support for fixed size Rust arrays was not added because until recently you couldn't implement a trait for arrays of any length? With const generics, this has changed.

I tried to find a related issue here, but couldn't. If there is no reason for the lack of this impl, I can create a PR.

**Comment by sfackler** [comment]
The only reason those don't exist is due to the historic lack of const generics. Now that they do exist we should be able to add the impls, probably flagged off to only exist when building on a modern compiler to avoid bumping the MSRV too aggressively.

**Comment by LukasKalbertodt** [comment]
Sweet! I could take a look at adding those impls as you described. Or do you want to work on that?

**Comment by sfackler** [comment]
Go for it!

**Comment by LukasKalbertodt** [comment]
I started working on this and found out that while implementing `ToSql` is straight-forward, `FromSql` is not. 

That's because there is currently not a great way to construct arrays. The easy solution would be to construct a `Vec` and then use `TryFrom` to convert it to an array. But that entails a useless allocation. The alternative is to write `unsafe` code by having an array of `MaybeUninit` and fill it element by element. I've written this exact code for `std` before, so I think I will get it right, but I saw that this whole repository basically uses no `unsafe` at all. And I assume you want to keep it that way, right? (I would)

So how should we proceed? (a) give up on arrays completely for now, (b) only add `ToSql` impl, (c) implement `FromSql` via `Vec` and hope we can improve performance later, (d) implement `FromSql` using `unsafe` code. Option (c) might not be that bad considering that users of this library have to use `Vec` in those cases anyway.

**Comment by sfackler** [comment]
Yeah, it seems fine to use a Vec for now. IIRC there are some proposals to add an "array builder" type to std that would allow us to safely construct it directly. Alternatively, if such a thing already exists as a (good) third party library we can just use that.
