### ISSUE TITLE
INT being cast to BIGINT in SQL request

### ISSUE THREAD

**Issue by trungda** [sfackler/rust-postgres#818]
Hi team,
Thanks a lot for this awesome crate. I have noticed something interesting/strange about how the driver is communicating with `Cockroachdb` (I haven't tested this behavior with Postgres). Below is my set up:
1. I have a simple local cockroach cluster
2. A simple Cockroachdb table:
```
CREATE TABLE users (
	id BIGINT NOT NULL,
	name STRING,
	age INT,
	CONSTRAINT "primary" PRIMARY KEY (id ASC)
);
```
3. The following code to reproduce.
```
use tokio_postgres::{NoTls, Error};

#[tokio::main] // By default, tokio_postgres uses the tokio crate as its runtime.
async fn main() -> Result<(), Error> {
    // Connect to the database.
    let (client, connection) =
        tokio_postgres::connect("postgresql://alice@localhost:26257/test", NoTls).await?;

    tokio::spawn(async move {
        if let Err(e) = connection.await {
            eprintln!("connection error: {}", e);
        }
    });

    // insert a new row with (id, age) = (1, 10)
    client
        .query("INSERT INTO users (\"id\", \"age\") VALUES (1, 10);", &[])
        .await?;

    // try to set age = age + 10 for id = 1
    let new_age = 10 as i32;
    let row = client.query("UPDATE users SET \"age\" = \"age\" + $1 WHERE \"id\" = 1;", &[&new_age]).await?;

    println!("{:?}", row);
    Ok(())
}
```

When running the code, it throws this error:
```
Error: Error { kind: ToSql(0), cause: Some(WrongType { postgres: Int8, rust: "i32" }) }
```
When I use `CAST($1::INT4)` in the query, it works. 

It looks like *something* is treating the first parameter as a `BIGINT` even though it should have been an `INT`, but I am not sure what that something is, is it `tokio-postgres` or `cockroach` itself? Is it even an expected behavior? Thanks.

**Comment by sfackler** [comment]
We just give the raw query string to the backend and it tells us which parameter types it expects. Maybe cockroach treats all integer parameters as bigints or something?

**Comment by trungda** [comment]
I see. And then, you use the type info from cockroach to serialize the arguments before sending the encoded stream to cockroach for execution?
