### ISSUE TITLE
query_raw and portal_raw seem not named right

### ISSUE THREAD

**Issue by Stargateur** [sfackler/rust-postgres#820]
`query_raw` and `portal_raw` basically just don't collect all data required into a vector, I feel `raw` is a little miss leading, it's hint "this should not be used", unless I miss something I don't see any reason to not use them when possible. Is there a performance penalty ? What is the preferred way ?

**Comment by sfackler** [comment]
It is not hinting that they should not be used. There is no performance penalty - the `query` and `portal` methods just call into `query_raw` and `portal_raw` internally.

**Comment by sfackler** [comment]
The variants returning vecs are intended to be the ones people should be using most of the time, which is why they have the shortest names.
