### ISSUE TITLE
doc links broken?

### ISSUE THREAD

**Issue by zoombinis** [sfackler/rust-postgres#823]
For the longest time I was wondering how anyone knew how to use this API, then I realized the docs were broken!

https://docs.rs/tokio-postgres/0.7.2/tokio_postgres/struct.Client.html#method.query_raw

That link won't let you read query_raw or any examples. I eventually found the examples in the code itself here:

https://github.com/sfackler/rust-postgres/blob/master/postgres/src/client.rs

Is this a bug with rust docs, or a bug with rust-postgres? I am not sure...

**Comment by zoombinis** [comment]
also, sorry to shoehorn this in here, but there's I think a small typo in the docs. There needs to be an `await` [here](https://github.com/sfackler/rust-postgres/blob/master/postgres/src/client.rs#L231) since it's a future but it's currently missing:

>66 | |   )?;
   | |____^ the `?` operator cannot be applied to type `impl futures::Future`
   |
   = help: the trait `Try` is not implemented for `impl futures::Future`
   = note: required by `branch`
help: consider `await`ing on the `Future`
   |
66 |   ).await?;
   |    ^^^^^^

**Comment by sfackler** [comment]
This is what I see when I go to that link:

![Capture](https://user-images.githubusercontent.com/1455697/132583984-a114bbd5-a6ca-490c-bf8d-b6bb3b6a4bd6.PNG)

The second thing you linked is for the blocking non-async client, so it does not return a future.

**Comment by zoombinis** [comment]
I'm stumped... on both Brave and Firefox on Ubuntu 18.04 this is all I see:
![delete](https://user-images.githubusercontent.com/72039888/132584594-331b1aa7-0ad5-451a-8729-5797f72efec6.png)

**Comment by sfackler** [comment]
Click the `+` button next to `impl Client`.

**Comment by zoombinis** [comment]
Thanks, never in a million years would I have figured that out!
