### ISSUE TITLE
ToSql and FromSql on domain types ?

### ISSUE THREAD

**Issue by damien-urruty-sonarsource** [sfackler/rust-postgres#837]
First thanks for this brilliant set of libs!

I am working with tokio-postgres for a couple weeks now, and I have a question regarding ToSql and FromSql.

I have some domain types in my code, and I would prefer they stay as self-contained as possible, decoupled from the rest of the app. It appears to me that deriving ToSql and FromSql for them introduces coupling, as now if I want to change the way I store the entity (e.g. table structure), the domain model has to change, or the other way round. I know that I could rename fields with the macro, but coupling would still be present between the structure of the domain type and the table in the database. If I take an example, today I use a composite type in a table column, if tomorrow I want to extract it into another table (which is purely a database concern), the model will have to change.

Are people just using the ToSql and FromSql macros directly on domain types and not bother too much about coupling, or do they have separate domain and database types, annotating only the latter ? This implies some conversion has to take place.

To avoid that effect, I tried to implement ToSql and FromSql myself in the database module (e.g. for my structs) because I feel it's a database concern to serialize from/to domain value. It appears to be pretty complicated, and I have the impression that there is not much facility to help in the lib. I wanted to know if that's really the way to go or if I am reinventing the wheel here.

Thanks!

**Comment by sfackler** [comment]
You can use macros to derive ToSql and FromSql for newtype wrappers: https://docs.rs/postgres-types/0.2.2/postgres_types/#derive

**Comment by damien-urruty-sonarsource** [comment]
Is there any example how to achieve that ? Should I define a newtype wrapper for each of my postgres composite or enum types ? Will it work for a newtype wrapping several rust types (composite) ?

**Comment by damien-urruty-sonarsource** [comment]
I tried something like:

```
#[derive(ToSql, Debug)]
struct MyCompositeType(String, u8, bool);
```

But i get this error:

> #[derive(ToSql)] may only be applied to structs, single field tuple structs, and enums

**Comment by sfackler** [comment]
You need to use a struct with named fields.

**Comment by damien-urruty-sonarsource** [comment]
Maybe to clarify, what I call domain types is *not* the postgres notion, it's about entities used in my application to represent the business (just discovered that domain types were a thing in Postgres). Basically I have structs representing my domain types (say for example a Product, that has a name, a price, a category (represented by an enum type)).

So what you suggest is to keep those domain structs separate from the structs used for persistence, on which I could derive ToSql and FromSql ? So I would have a conversion step to map my domain types to persistence types ?

**Comment by sfackler** [comment]
Oh. This library does not define an ORM interface. Every type implementing ToSql or FromSql corresponds to a single specific Postgres types.

**Comment by antondc** [comment]
@damien-urruty-sonarsource a bit late here, but this may be achieved implementing `Display` for your enum in the domain layer, and then implementing `ToSql` in the infrastructure layer.

For example, for an enum `MyEnum`, which in DB corresponds to `myenum`:

```rust
// Entity, domain layer
use std::fmt::{Display, Formatter, Result};

pub enum MyEnum {
  VariantA,
  VariantB,
}

impl Display for MyEnum {
  fn fmt(&self, f: &mut Formatter) -> Result {
    match self {
      MyEnum::VariantA => write!(f, "variant_a"),
      MyEnum::VariantB => write!(f, "variant_b"),
    }
  }
}
```

```rust
// Some Postgres repository implementation, infrastructure layer:
use crate::domain::user::Role;
use bytes::BytesMut; // bytes library used by rust-postgres, but not exported
use std::{error::Error, result::Result};
use tokio_postgres::types::{to_sql_checked, IsNull, ToSql, Type};

impl ToSql for Role {
  fn to_sql(&self, ty: &Type, out: &mut BytesMut) -> Result<IsNull, Box<dyn Error + Sync + Send>> {
    format!("{}", self).to_sql(ty, out).unwrap();

    Ok(IsNull::No)
  }

  fn accepts(sql_type: &Type) -> bool {
    sql_type.name() == "myenum"
  }

  to_sql_checked! {}
}
```
