### ISSUE TITLE
How do I annotate the typename for a type which doesnt derive FromSql/ToSql?

### ISSUE THREAD

**Issue by nifker** [sfackler/rust-postgres#838]
When I manually implement FromSql/ToSql for Foo I cant use '#[postgres(name = "foo")]' in front of the struct definition and thus get a conversion error because of the name capitalization.
Any way I can also manually set the Postgres name for the struct?

**Comment by sfackler** [comment]
If you are manually implementing FromSql/ToSql, then you are writing the code that checks the type name and you can do whatever you want with respect to capitalization.

**Comment by nifker** [comment]
Alright I see. I did my comparison in the accepts function wrong. Thank you!

**Comment by nifker** [comment]
@sfackler as a sidenote: wouldnt it be useful if postgres reexports 'bytes' as it is used to implement ToSql/FromSql?
