### ISSUE TITLE
Connection hanging with `tokio-postgres` after a `SELECT` with a large `LIMIT`

### ISSUE THREAD

**Issue by JamesHinshelwood** [sfackler/rust-postgres#840]
I have a program which picks a batch of rows out from the DB and tries to run an `UPDATE` on each one. I query from the DB using the `query_raw` method which returns a `RowStream`. The query used here is `SELECT * FROM users LIMIT 500`.

The first `SELECT` succeeds, but when I come to run `.execute` to update a row, the method never returns and my program hangs.

This does not occur if I use the non-streaming `query` method for my select. It also does not occur if I instead only query 20 users at a time (i.e. `SELECT * FROM users LIMIT 20`).

I have produced a fairly minimal (~50 line) program which reproduces the issue here: https://github.com/JamesHinshelwood/limit-hang-mcve
The `README.md` of that repository also includes `TRACE` logs for an execution of the program where the hang occurs.

Please let me know if anything is unclear or if there is anything else I can do to help.

**Comment by sfackler** [comment]
The Postgres connection can only handle one request at a time. When the number of rows returned is low enough, the server is able to send them all down the the client at once, freeing it up to process your updates. However, when the limit is increased, you deadlock as the server is waiting for you to read the remaining rows of the select and you are waiting on the server to process the update.

To fix this, you can either load all of the rows up front like `conn.query` does, or if there are too many rows to comfortably fit in memory, use a transaction and create a portal which will let you page through the full rows of the response in chunks.

**Comment by Stargateur** [comment]
I agree with sfackler in networking you must always read before any write, another solution would be to spawn the update in other task to keep reading the result. You would need to accumulate the task in the vec to await them all at the end. I think use a portal is way better.
