### ISSUE TITLE
[Question] Owned query parameters

### ISSUE THREAD

**Issue by elpiel** [sfackler/rust-postgres#843]
It's not that often that I get into this problem, however, if you're making a query you always have to pass `&dyn ToSql + Sync`.
This is not sufficient in some cases, e.g. if you're pushing your parameters into a vec in one function scope to build the parameters list and in another (the caller) you try to use the parameters and pass them to `client.query`

Is there a way we can make query or similar function work with `Box<dyn ToSql>`. I've tried implementing it for `tokio-postgres` but I quickly bumped into some issues with the implementation.

It's also not possible to use something like `Vec<Box<dyn ToSql + Sync + Send>` if you want to send the value to the `fn query` since query is expecting a `ToSql + Sync`

**Comment by sfackler** [comment]
You can use `query_raw` for this: https://docs.rs/tokio-postgres/latest/tokio_postgres/struct.Client.html#method.query_raw

**Comment by elpiel** [comment]
> You can use `query_raw` for this: https://docs.rs/tokio-postgres/latest/tokio_postgres/struct.Client.html#method.query_raw

I managed to take a look at the issue again, however, this approach does not work because `Box<dyn ToSql + Sync>` does not implement `BorrowToSql`

![Screenshot from 2021-12-16 10-00-38](https://user-images.githubusercontent.com/8925621/146331571-b093a103-8fbd-48a4-8047-f0aa40743a28.png)

**Comment by sfackler** [comment]
You can transform the iterator to convert the `Box<dyn ToSql>` to `&dyn ToSql`, but that PR seems like a reasonable thing to add as well!

**Comment by elpiel** [comment]
I was actually getting an error with the iterator too, IIRC because of a `Send/Sync` issue.

PS: I still have no idea how the `slice_iter` magic works
