### ISSUE TITLE
[Question] Does the usage of `postgres-types` protect against sql Injection?

### ISSUE THREAD

**Issue by RonaldColyar** [sfackler/rust-postgres#844]
Just wondering what type of protection this library collection provides against injection attacks.

**Comment by sfackler** [comment]
If user provided values are only added to the query as parameters you will be protected against injection attacks.

**Comment by RonaldColyar** [comment]
Thanks so much!! Wonder if you have a discord channel for these amazing libraries? It would be cool to contribute and chat.

**Comment by sfackler** [comment]
I do not have a Discord channel. The closest would probably be the tokio discord.

**Comment by RonaldColyar** [comment]
You should make one it would be amazing to have a contributor-based chat for your work. This is art!!
