### ISSUE TITLE
[Question] Can you gather serial id's from insert calls?

### ISSUE THREAD

**Issue by RonaldColyar** [sfackler/rust-postgres#848]
Have a system that I am working on, I will need to insert a row and gather the id back from the insertion. Haven't seen an example regarding it just yet.

Mock query:

```SQL
INSERT INTO employee (lastname,firstname) VALUES ('Jain', 'Manish') RETURNING id;

```

**Comment by MirrorBytes** [comment]
So when looking at the rows I'm only seeing the columns with the name and type of the column.

Using the following:

```rust
let rows: Vec<Row> = pg_client.query("INSERT INTO \"Device\"(\"name\") VALUES($1) RETURNING id", &[&name]).await?;

println!("{:?}", rows.get(0));
```

returns:

```rust
Some(Row { columns: [Column { name: "id", type: Int4 }] })
```

Is there a way to return the actually value of the row? Is there something I'm missing?

**Comment by SquireOfSoftware** [comment]
Dumb question, what is the difference between `query` and `execute`? Should one be preferred over the other? Or is it all just preference?

I had the impression that `inserts` ought to be done by `execute` where as `read only` operations to be done by `query`...I might have misread the docs though...

**Comment by sfackler** [comment]
The only difference is what the method returns.
