### ISSUE TITLE
How can one wrap ToSql/FromSql with a database function?

### ISSUE THREAD

**Issue by Fuuzetsu** [sfackler/rust-postgres#850]
I'm using AWS Redshift and I'm trying to put JSON in the `super` data type. The way one would normally insert data using this is to call https://docs.aws.amazon.com/redshift/latest/dg/JSON_PARSE.html function on a JSON string.

My issue is that I can't figure out how to do this programmatically in ToSQL (and FromSQL) base on some newtype. Given a prepared statement like `INSERT INTO foo (field1, json_field) VALUES ($1, $2)`, I would like to invoke it with `('field1_text', PARSE_JSON('{"data": 1}')`

Is this possible? Do I have to instead prepare a query like `INSERT INTO foo (field1, json_field) VALUES ($1, PARSE_JSON($2))`? Unsure if this is even a thing.

For decoding, similar thing needs to happen but this time using https://docs.aws.amazon.com/redshift/latest/dg/JSON_SERIALIZE.html.

**Comment by sfackler** [comment]
`VALUES ($1, PARSE_JSON($2))` would be the way to do it in Postgres (though there may be some Redshift-specific issues there).

**Comment by Fuuzetsu** [comment]
> `VALUES ($1, PARSE_JSON($2))` would be the way to do it in Postgres (though there may be some Redshift-specific issues there).

I see, thank you. That sucks a little bit because I'm generating the `$i` params but I guess it just means the generator needs improving. Thank you!
