### ISSUE TITLE
BinaryCopyOutRow type conversion

### ISSUE THREAD

**Issue by zoain-it** [sfackler/rust-postgres#851]
How do I convert an arbitrary type of BinaryCopyOutRow to a string value

**Comment by sfackler** [comment]
That isn't a thing you can do easily. If you want all of the values as strings, I would recommend just using the CSV copy format.

**Comment by zoain-it** [comment]
Ok, I understand. I'm going to try to convert each type manually, but I didn't find the XML equivalent of Rust Type
