### ISSUE TITLE
copy_out, returns None in advance

### ISSUE THREAD

**Issue by cc-morning** [sfackler/rust-postgres#852]
`copy_out` `COPY TO STDOUT BINARY`, the stream returns early.
Total data 300 million, returned at more than 4 million

**Comment by cc-morning** [comment]
This seems to happen only with specific data, but I haven't located the relevant data for the impact. Here is my current code, where I try to locate the affected data and then provide a reproducible example:

```rust
let columns = match &self.columns {
    Some(columns) => columns.clone(),
    None => get_columns_by_table(&client, &self.table).await?,
};
let types = get_types_by_table(&client, &self.table).await?;

let sql = {
    let mut sql = format!("COPY \"{}\" (", self.table);
    for (index, column) in columns.iter().enumerate() {
        sql.push('"');
        sql.push_str(column);
        sql.push('"');
        if index < (columns.len() - 1) {
            sql.push_str(", ");
        }
    }
    sql.push_str(") TO STDOUT BINARY");
    sql
};
info!("sql : {}", sql);

let read_stream = {
    let stream = client.copy_out(&sql).await.unwrap();
    BinaryCopyOutStream::new(stream, &types)
};

pin_mut!(read_stream);
// use stream
```

**Comment by sfackler** [comment]
Are there any logs in the database?

**Comment by cc-morning** [comment]
I found this code in binary_copy and I'm not sure if it could be causing the early return

```rust
check_remaining(&chunk, 2)?;
let mut len = chunk.get_i16();
if len == -1 {
    return Poll::Ready(None);
}
```

**Comment by cc-morning** [comment]
> Are there any logs in the database?

Only tomorrow I can give you an answer, I have left the company intranet environment

**Comment by sfackler** [comment]
A -1 length is how the server tells the client that it is done sending data: https://www.postgresql.org/docs/14/sql-copy.html
