### ISSUE TITLE
Holding a connection in a struct

### ISSUE THREAD

**Issue by cholcombe973** [sfackler/rust-postgres#854]
I'm new to the tokio_postgres crate. Previously I've used the postgres crate a bunch. I normally store the connection to the database in a struct and then call back to a bunch of times. As an example with the async tokio runtime:
```
pub struct Db {
    client: Client,
}

impl Db {
    pub async fn new(password: &str) -> Result<Self> {
        let (client, connection) = tokio_postgres::connect(
            &format!(
                "host=localhost user=postgres port=4321 password={}",
                password
            ),
            NoTls,
        )
        .await?;
        tokio::spawn(async move {
            if let Err(e) = connection.await {
                eprintln!("connection error: {}", e);
            }
        });
        Ok(Self { client })
    }
}
```
Is something like this valid? When the later functions go and call to `self.connection` they are getting a connection closed error before they can run the statement. I tried using the regular postgres crate and I ran into an issue where tokio was complaining of a double runtime creation. I think internally the postgres crate uses tokio which creates a problem if you're using tokio also in `main`. Should I just spawn a new connection in every function?

**Comment by sfackler** [comment]
That seems like the standard way to use a client. Can you post a self contained example of a program that fails?

**Comment by cholcombe973** [comment]
I produced a minimal example and it works fine so it must be something wrong with my code then.

**Comment by sfackler** [comment]
One potential pitfall to look for is accidentally starting the connection in one Tokio runtime, allowing that to shut down, and then trying to use the client in another (e.g. by having multiple functions annotated with `#[tokio::main]`).

**Comment by cholcombe973** [comment]
The problem seemed to occur only when I was doing unit tests with #[tokio::test]. During a normal run everything works correctly. Maybe the multiple block_on calls I had in the test we're doing something I didn't know.

**Comment by sfackler** [comment]
With `#[tokio::test]`, each test has its own independent runtime and sharing resources between tests can also be a source of these kinds of problems.
