### ISSUE TITLE
DBError unaware of column and table for `SqlState::UNDEFINED_COLUMN`

### ISSUE THREAD

**Issue by WarriorOfWire** [sfackler/rust-postgres#860]
```Postgres(Error { kind: Db, cause: Some(DbError { severity: "ERROR", parsed_severity: Some(Error), code: SqlState(E42703), message: "column \"available_messages\" of relation \"mm\" does not exist", detail: None, hint: None, position: None, where_: None, schema: None, table: None, column: None, datatype: None, constraint: None, file: Some("copy.c"), line: Some(739), routine: Some("CopyGetAttnums") }) })```

I expected to be able to get at the table name and column name when I went to insert some data into my table. Here's the code I'm using to parse the result:

```
let res = transaction.copy_in("copy to_table (present1, present2, missing, present3) from stdin wth binary");
match res.await {
    Ok(rows) => log::info!("committed ${rows}", rows = rows),
    Err(e) => {
        log::error!("{:?}", e);
        match e {
            SinkError::Postgres(postgres_error) => {
                match postgres_error.as_db_error() {
                    Some(dberror) => {
                        match dberror.code() {
                            &SqlState::UNDEFINED_COLUMN => {
                                log::info!("missing column: {table}.{column}", table = dberror.table().unwrap_or_default(), column = dberror.column().unwrap_or_default())
                            }
```

I was expecting to be able to use the `column()` and `table()` properties of DBError to drive some recovery and schema migration. It seems from the message (and intuitively) that the `UNDEFINED_COLUMN` error code is intrinsically linked to a table and a column.

Here's the doc I was reading:
https://github.com/sfackler/rust-postgres/blob/master/tokio-postgres/src/error/mod.rs#L267-L272

Missing column, missing table, mismatched column type are the 3 most crucial DBErrors where I need table & column metadata. I run great big batches across thousands of tables in 1 transaction (to help be kind to vacuum & transaction id wraparound - it was a big help) and once in a while there's a column addition that needs to go through. I can write regexes to parse out the needful information from the error messages but would prefer to do it a more correct way if it's valuable to add here!

Versions:
```
tokio-postgres = {version = "0.7.5"}

                                                   version
--------------------------------------------------------------------------------------------------------------
 PostgreSQL 14.1 on x86_64-pc-linux-musl, compiled by gcc (Alpine 10.3.1_git20211027) 10.3.1 20211027, 64-bit
```

Workaround I'm using at the moment:
```
static ref UNDEFINED_COLUMN: Regex = Regex::new(r#"column "(?P<column>.+)" of relation "(?P<table>.+)" does not exist"#).unwrap();

[...]

match postgres_error.as_db_error() {
    Some(dberror) => {
        match dberror.code() {
            &SqlState::UNDEFINED_COLUMN => {
                let pair = UNDEFINED_COLUMN.captures(dberror.message()).unwrap();
                let table = pair.name("table").unwrap().as_str();
                let column = pair.name("column").unwrap().as_str();
                log::info!("missing column: {table}.{column}", table = table, column = column)
            }
```

**Comment by sfackler** [comment]
You'd have to file an issue upstream with Postgres - this library just exposes the fields that are provided to it.

**Comment by WarriorOfWire** [comment]
Yes indeed, I dug through this code and came back here to close this issue; thanks for your reply! I see how you're parsing the response, and it's clear that it would need to come in the Postgres response body. I'll make liberal use of Regex in the meantime 😅 

This library is really nice; thank you for providing it!
