### ISSUE TITLE
How to use `derive(ToSql)` with `copy_in()`?

### ISSUE THREAD

**Issue by WarriorOfWire** [sfackler/rust-postgres#862]
```
#[derive(postgres_types::ToSql, postgres_types::FromSql)]
#[postgres(name = "statistic_set")]
pub struct StatisticSet {
    pub minimum: f64,
    pub maximum: f64,
    pub samplesum: f64,
    pub samplecount: i64,
}
```

Trying to use the type like this:
```
let transaction = self.client.transaction().await?;

let sink = transaction.copy_in("copy some_table (ss) from stdin with binary").await?;
let writer = BinaryCopyInWriter::new(sink, &vec![ 
    // what type am i supposed to put here? Type::RECORD is not what is expected, and the error message does not tell me that it's supposed to be
    Type::RECORD
]);
pin_mut!(writer);

writer
    .as_mut()
    .write(&[&StatisticSet { minimum: 1.0, maximum: 2.0, samplesum: 4.0, samplecount: 3 }])
    .await?;
writer.finish().await?; // WrongType { postgres: Record, rust: "postgres_things::StatisticSet" }
return Ok(1);
```

![image](https://user-images.githubusercontent.com/3454741/149836027-5c55526e-cb80-4cfe-89d8-7338eacc729f.png)
finally dug up one issue here. By setting `#[postgres(name = "record")]` (mind the caps) I can get past the name check, but then a Kind check fails. I haaven't yet dug up exactly what kind I should be expecting. This seems surprising; is it by design? I have not been able to get past the `.to_sql_checked(type_, this.buf)` gate in `write_raw` with a simple `derive(ToSql)` struct.

**Comment by sfackler** [comment]
You can prepare a statement using StatisticSet to load its type from the database:

```rust
let stmt = client.prepare("SELECT $1::statistic_set").await?;
let statistic_set_type = stmt.params()[0].clone();

let writer = BinaryCopyInWriter::new(sink, &[statistic_set_type]);
```

**Comment by WarriorOfWire** [comment]
Wow, thank you for this very prompt reply! Loading the type from a parameter type list is really nice, I wish I had thought of it ❤️

Replacing `Type::RECORD` with the DB type gets me further, and even has the right oid:
```
WrongType { postgres: Other(Other { name: "statistic_set", oid: 17557, kind: Composite([Field { name: "minimum", type_: Float8 }, Field { name: "maximum", type_: Float8 }, Field { name: "samplesum", type_: Float8 }, Field { name: "samplecount", type_: Int8 }]), schema: "public" }), rust: "postgres_things::StatisticSet" }
```

Now I'm staring at the struct and the error message and so far I'm having a hard time telling what's wrong with this.

**Comment by WarriorOfWire** [comment]
Oop, I had left `#[postgres(name = "record")]` like a goof. This issue is resolved with `#[postgres(name = "statistic_set")]`; the type works exactly as it should when you (1) set the type name correctly and (2) use the type definition from the database.

Thank you again for your patience and support!
