### ISSUE TITLE
Tiny QOL change: `get<I,T>` should be `get<T,I>`

### ISSUE THREAD

**Issue by njaard** [sfackler/rust-postgres#864]
On the rare occasion I need to use the turbofish on the `Row::get` function, I need to tell Rust what my _output_ type will be, as the input type is most likely to be inferred.

so `get::<_,String>(0)` is easy enough to do, but `get::<String>(0)` is more intuitive (directly guessable for first time users) and a little bit prettier.

**Comment by sfackler** [comment]
You'd still have to write `get::<String, _>(0)` though.

**Comment by njaard** [comment]
Derp
