### ISSUE TITLE
Boolean coercion

### ISSUE THREAD

**Issue by roy-ganz** [sfackler/rust-postgres#866]
Hi, I have some coercion troubles with boolean values in the binary protocol.
 
I try to call - using `tokio_postgres` -
```
conn.prepare_typed("SELECT t.id, t.completed FROM Todo t \
                    WHERE t.completed = $1", 
                   &[Type::VARCHAR]).await?; // Fails at runtime
```
This does not work, because the column `t.completed` has a boolean type and I try to give a string.
 However according to [Postgres documentation](https://www.postgresql.org/docs/9.5/datatype-boolean.html) strings, such as 'yes' are allowed for boolean columns.
In the [Postgres source code](https://github.com/postgres/postgres/blob/master/src/backend/parser/parse_coerce.c#L1170) there is actually a coercing function. However it doesn't work out with the statement above.

Maybe an alternative solution would be the text protocol instead the binary protocol. Postgres itself supports that, but from the Rust API I don't see how to use it.

The situation with boolean values is just an example. The same applies to dates, times and other datatypes that have a string representation. I guess once I know how to deals with bools, the rest should be easy peasy.

Thanks for your time.

PS: I've asked this on [users.rust-lang.org](https://users.rust-lang.org/t/boolean-coercion-in-postgres-protocol/71176), but got no answer. I'm interested in this, because I'm writing the Postgres backend for my [Toql](https://github.com/roy-ganz/toql) ORM.

**Comment by sfackler** [comment]
This is more of a question for the Postgres developers, than me - this library just passes those values along to the library directly.

My guess would be that the function you found is specifically for implicit casts while this is treated as an explicit cast, but I can't say for sure.

**Comment by roy-ganz** [comment]
Thanks for your quick response. 
In that case I check at Postgres directly. I close the issue for now. 
Happy weeekend.
