### ISSUE TITLE
params doesn't work for e.g. columns

### ISSUE THREAD

**Issue by idl0r** [sfackler/rust-postgres#868]
Hi,

I was just trying something like
```
result = client.query("SELECT * FROM cmdb WHERE $1ILIKE $2", &[&args.column.unwrap(), &args.pattern],);
```
```
 DEBUG tokio_postgres::prepare > preparing query s0: SELECT * FROM cmdb WHERE $1 ILIKE $2
```

However, that doesn't seem to work.
It only works either this (static/hardcoded) way:
```
result = client.query("SELECT * FROM cmdb WHERE name ILIKE $1", &[&args.pattern]);
```

or this way:
```
           result = client.query(
                &std::format!("SELECT * FROM cmdb WHERE {} ILIKE $1", args.column.unwrap()),
                &[&args.pattern],
            );
```

Any ideas what might be wrong here?
args.column.unwrap() is "name" in this case.
I also tried &"name".to_string() instead but that also doesn't work.
Shouldn't it be possible to basically use those params everywhere in the query/statement?

**Comment by sfackler** [comment]
Postgres does not support parameters in that position.

**Comment by idl0r** [comment]
Oh, ok, I wasn't aware of it. I thought that's handled by rust-postgres. Closing then. Thanks!
