### ISSUE TITLE
Name of prepared statements

### ISSUE THREAD

**Issue by dbischof90** [sfackler/rust-postgres#878]
Hi! Getting to know prepared statements a bit better after some time absent.
I'd like to access the prepared statement (PS) on the server side too, check the execution plan, analyze it, etc. but for that I need its name. I can check and find it by trial and error but if there's many, that becomes more and more tricky. Ideally I'd expose the name of the PS via debug logger in my application and I see in https://docs.rs/tokio-postgres/latest/src/tokio_postgres/statement.rs.html#52 that the name is exposed, however only as `pub(crate)`. Is there a reason for not moving that to `pub`?

**Comment by sfackler** [comment]
The name of the statement isn't considered part of the public API. You can look at the pg_prepared_statements table to find all of the live prepared statements in the session though: https://www.postgresql.org/docs/current/view-pg-prepared-statements.html
