### ISSUE TITLE
Is it possible to just check if a value is null regardless of type?

### ISSUE THREAD

**Issue by nerdrew** [sfackler/rust-postgres#879]
I want to do a `LEFT JOIN` and then skip processing if the join didn't return anything. I'm basically looking for `is_empty()` to take some sort of range rather than check the whole row. Is this supported currently?

**Comment by sfackler** [comment]
You could make a type with a FromSql implementation that accepts all types and just sets its value identifying if the value is null or not.

**Comment by nerdrew** [comment]
That was a good suggestion. As always, this crate is a pleasure to work with. Thanks!

Here's what I did:

```rust
#[derive(Debug)]
struct NullChecker(bool);

impl tokio_postgres::types::FromSql<'_> for NullChecker {
    fn from_sql(_ty: &tokio_postgres::types::Type, _raw: &[u8]) -> Result<Self, Box<dyn std::error::Error + Send + Sync + 'static>> {
        Ok(Self(false))
    }

    fn from_sql_null(_ty: &tokio_postgres::types::Type) -> Result<Self, Box<dyn std::error::Error + Send + Sync + 'static>> {
        Ok(Self(true))
    }

    fn accepts(_ty: &tokio_postgres::types::Type) -> bool {
        true
    }
}
```
