### ISSUE TITLE
Parameter binding failure when a value is casted to another type (f32::int)

### ISSUE THREAD

**Issue by Weakky** [sfackler/rust-postgres#880]
## Description

Hey,

I'm trying to execute the following query:

```rust
client.query(r#"SELECT $1::int;"#, &[&1.5_f32]).await?;
```

But it fails with the following error:

```
Error: error serializing parameter 0: cannot convert between the Rust type `f32` and the Postgres type `int4`

Caused by:
    cannot convert between the Rust type `f32` and the Postgres type `int4`
```

This error happens in the `query::encode_bind` function while attempting to bind the parameters to the actual query (or at least that's what I think it does).

I'm failing to understand why such conversions need to happen in the library runtime and why this query is erroring out.

My best guess at the moment is that there's a bug in the parameter binding logic since it tries to convert an `f32` to an `int4` although it should really just convert that `f32` to a `REAL` (if I'm following the code correctly) 🤔 ?.

Put differently, `Statement::params()` returns `[Int4]` which looks surprising to me.

Is this expected?

Cheers for the awesome work!

**Comment by Weakky** [comment]
Disclaimer: This might all be obvious stuff, I'm a complete rookie when it comes to database drivers, please take these questions as naive open questions and not as complaints 🙏.

I went on to dig a bit more. I've found out that `Statement` was initialized from a `&str` by sending a PG query and reading the `ParameterDescription and `RowDescription` PG messages. This is where the `Int4` PG type comes from.

I've been told this is the standard way of sending prepared statements for pg clients because it might be impossible to infer the proper types _just_ from the runtime parameters types. eg: json vs jsonb. That makes a ton of sense.

However, I'm surprised rust-type parameters are not taken into account? Doesn't that prevent a ton of prepared queries with a parameter cast to work?

Even simpler queries such as `SELECT $1` can't work reliably. Anything else than a string as a query parameter will fail because PG will fallback to inferring `Text` as a query parameter.

**Comment by sfackler** [comment]
In most queries, the parameter type can be inferred from usage - e.g. `SELECT foo FROM bar WHERE id = $1`, `$1` will have the type of the `id` column. You can use prepare_typed if you want to explicitly provide types for all of your query parameters: https://docs.rs/postgres/latest/postgres/struct.Client.html#method.prepare_typed

**Comment by Weakky** [comment]
Thanks for the answer. Can you think of drawbacks for explicitly providing the types vs letting PG infer the types ? Other than verbosity, which we don't really care about in our case.

**Comment by sfackler** [comment]
The verbosity is the only real drawback I'm aware of.

**Comment by sfackler** [comment]
You would use whatever the appropriate underlying type is - a `TEXT` parameter that happens to be null is different from a `BIGINT` parameter that happens to be null.

**Comment by sfackler** [comment]
All query parameters are assigned a type.

**Comment by Weakky** [comment]
Awesome! Thank you for bearing with all my questions. I'm closing this issue now 🙏
