### ISSUE TITLE
Automatic type conversion is supported in copy_in

### ISSUE THREAD

**Issue by cc-morning** [sfackler/rust-postgres#881]
The current copy_in implementation requires passing in the corresponding rust type even if the type is specified, and does not support automatic detection of conversions.

For example, I have no way to handle csv data with different structures in a uniform way, always because the lifecycle can become very cumbersome.

```rust
// Query the corresponding type in the database
// varchar, int2, int2, timestamp
let types = get_types_by_table(&client, "test").await?;
let sink = client.copy_in("COPY \"people\" (\"name\", \"sex\", \"age\", \"birthday\") FROM STDIN BINARY").await?;
let writer = BinaryCopyInWriter::new(sink, &types);

let row = vec![ "test","0","23","1999-06-14 08:00:00" ];
if let Err(e) = writer.as_mut().write_raw(row).await {
    error!("{:#?}", e);
}
```
error out
```bash
WrongType {
    postgres: Int2,
    rust: "alloc::string::String",
}
```

**Comment by sfackler** [comment]
If you have a CSV, I would recommend using the CSV copy format directly. https://www.postgresql.org/docs/current/sql-copy.html

**Comment by cc-morning** [comment]
> If you have a CSV, I would recommend using the CSV copy format directly. https://www.postgresql.org/docs/current/sql-copy.html

It means that copy_in supports FROM STDIN CSV, right?

**Comment by sfackler** [comment]
yes

**Comment by cc-morning** [comment]
> 是的

So how do I use csv in copy_in? The code continues as is and seems to treat a record as a field

**Comment by cc-morning** [comment]
It seems to be ok to write directly using sink
