### ISSUE TITLE
Connection often closed between queries

### ISSUE THREAD

**Issue by jo-so** [sfackler/rust-postgres#884]
I'm using `tokio-postgres` and the connection pool manager [bb8](https://lib.rs/crates/bb8-postgres). In my application I often get a closed connection `Error { kind: Closed, cause: None }` between two queries and in the postgresql.log I see these messages:

```
website_connect@website LOG:  could not receive data from client: Connection reset by peer
website_connect@website LOG:  could not send data to client: Broken pipe
website_connect@website LOG:  could not send data to client: Broken pipe
website_connect@website LOG:  could not receive data from client: Connection reset by peer
website_connect@website FATAL:  connection to client lost
website_connect@website FATAL:  connection to client lost
website_connect@website LOG:  could not send data to client: Broken pipe
website_connect@website FATAL:  connection to client lost
website_connect@website LOG:  could not send data to client: Broken pipe
website_connect@website FATAL:  connection to client lost
website_connect@website LOG:  could not send data to client: Broken pipe
website_connect@website FATAL:  connection to client lost
```

I'm using `tokio-postgres v0.7.5`, `postgres-protocol v0.6.3`, PostgreSQL 14.2 via Unix sockets.

Do you have any suggestion how I could further investigate this problem?

**Comment by jo-so** [comment]
I could reproduce this with a TCP connection, and I've captured the connection with Wireshark: [psql-rust.pcapng.gz](https://github.com/sfackler/rust-postgres/files/8489042/psql-rust.pcapng.gz). In `tcp.stream == 12` you can see an RST of the connection, which leads to a duplicate key in package 628. Hence, the lost of the connection happened after the `INSERT` was sent to the server and before tokio-postgres fetch the response.

**Comment by sfackler** [comment]
Can you provide a self contained example that produces this issue?

**Comment by jo-so** [comment]
Unfortunately not. It's part of a greater application, and it's not easy to isolate only one failing part.

It was much easier to switch the pool manager to [deadpool-postgres](https://lib.rs/crates/deadpool-postgres), and it happens there, too. But without a connection manager, I've seen no closed connections. In the log I found these messages:

```
 TRACE mio::poll                      > registering event source with poller: token=Token(1), interests=READABLE | WRITABLE
 WARN  deadpool.postgres              > Connection error: error communicating with the server: IO driver has terminated
 INFO  deadpool.postgres              > Connection could not be recycled: Connection closed
```

**Comment by sfackler** [comment]
It sounds like the Tokio runtime the pool is using is being shut down mid operation.

**Comment by jo-so** [comment]
Do you have any idea how to fix it (or work around this)? Can I somehow further investigate the issue?

**Comment by sfackler** [comment]
In what runtime are you constructing the pool, and how is the runtime stored vs the pool? A way this can happen is to e.g. have a pool in a static that is used my multiple `#[tokio::test]`s, each of which will use its own runtime that is destroyed as soon as the test completes.

**Comment by jo-so** [comment]
That was a very good hint! I've only seen these disconnects in the test suite and thought I was lucky not to have them in production yet. But they are caused by the tests themselves. I create the connection pool in an AsyncOnce on first access, i.e. in the runtime of the first test case, which is later invalidated.

I was using tokio, but now I switched to async_std because they have a global runtime and all my errors disappeared with it.

So it is not a bug. It was my bad usage of pooling.
