### ISSUE TITLE
Master can no longer be compiled under 2018 edition

### ISSUE THREAD

**Issue by funbringer** [sfackler/rust-postgres#885]
Here's what's happening:

```shell
$ cargo generate-lockfile 
    Updating crates.io index
$ cargo fetch
# 1.53 is used in CI
$ cargo +1.53 test --all
error: failed to download `geo-types v0.7.4`

Caused by:
  unable to get packages from source

Caused by:
  failed to parse manifest at `/home/.../.cargo/registry/src/github.com-1ecc6299db9ec823/geo-types-0.7.4/Cargo.toml`

Caused by:
  feature `edition2021` is required

  this Cargo does not support nightly features, but if you
  switch to nightly channel you can add
  `cargo-features = ["edition2021"]` to enable this feature
```

Apparently, geo-types 0.7.3 -> 0.7.4 [changed edition to 2021](https://github.com/georust/geo/blob/863477f72c2aec5884ac0d99b9d11c54020849f5/geo-types/Cargo.toml#L10).

**Comment by sfackler** [comment]
It seems like you would need to file this on the geo-types repo?

**Comment by funbringer** [comment]
Maybe you're right. The last build happened 24 days ago, so I just wanted to let you know.

**Comment by funbringer** [comment]
I'm kind of disappointed with how this went, but there's nothing I can personally do. Thanks anyway.
