### ISSUE TITLE
Vec<T> for null

### ISSUE THREAD

**Issue by EvanCarroll** [sfackler/rust-postgres#895]
It would be good if FromSql<Vec<T>> was implemented for NULL. Currently it only seems to be implemented for Option<Vec<T>>, but I think the semantics are fine for a NULL to be represented by an empty vector too?

> thread 'tokio-runtime-worker' panicked at 'error retrieving column features: error deserializing column 29: a Postgres value was `NULL`', /home/ecarroll/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-postgres-0.7.5/src/row.rs:151:25note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

In this case I'm trying to get `feature` records from the database into a Vec<Feature>. However, some properties do not have any features. For them, I wanted it to be represented by an empty array...

```rust
struct Property {
  features: Vec<Feature>
}
```

**Comment by sfackler** [comment]
A null array is a distinct value from an empty array. I don't think this conversion would be appropriate.

**Comment by EvanCarroll** [comment]
While technically true, you can't get a meaningful empty vector out of rust-postgres that I can see. What would generate an empty (zero-length) vector?

```rust
#[derive(FromSql)]
struct Foo {
  id: i64,
  name: String,
  bars: Vec<Bar>
}
#[derive(FromSql)]
struct Bar {
  id: i64,
  name: String,
}
```

```sql
CREATE TABLE foo(a_id, b_id, foo_name) AS SELECT 1, 2;
CREATE TABLE bar(b_id, bar_name) AS SELECT 7, 8;
```

```sql
SELECT a, b
FROM foo
JOIN bar
  USING (b)
```

In this case, if there are no `bar` for `foo` you can represent this as `foo.bars = None`, or `foo.bars = Vec::new()`. It would be desirable from the Rust perspective (because Rust supports zero-length vectors) to not have to wrap a vector in an option; there is [`vec.is_empty()`](https://doc.rust-lang.org/std/vec/struct.Vec.html#method.is_empty) which will effectively represent the null option.

Sure, for consistency **anything** wrapped in an `Option<>` should have null represented by None. But there are other ways with other types like Vec.

**Comment by sfackler** [comment]
> What would generate an empty (zero-length) vector?

An empty array in Postgres would generate an empty vector.

**Comment by EvanCarroll** [comment]
Sure, which is only possible if you type a column on a table to a composite type, rather than having the NULL as a result of a join. Something I've never seen, but I guess it's possible. Fair enough.

```sql
CREATE TABLE bar(bar_id, bar_name) AS SELECT 7, 'my bar';
CREATE TABLE foo(foo_id, bar_id, foo_name, bars) AS SELECT 1, 2, 'my foo', ARRAY[]::bar[];
```

I guess I forgot that use case and just assumed that all FromSql NULL to Vec<T> were a result of an INNER JOIN with no corresponding rows.
