### ISSUE TITLE
Queries against a schema are send to another

### ISSUE THREAD

**Issue by mamcx** [sfackler/rust-postgres#896]
After I move to async, I get sometimes the behavior of certain data sent to another schema, and that is terrible because this is for a multi-tenant setup.

I run all inside actix, and execute in each request:

```sql
SET search_path = NAME_SCHEMA, public, pg_catalog
```

This works most of the time but is unclear to me how or when this fails. It could have been related to the error "current transaction is aborted, commands ignored until end of transaction block" but I'm unsure.

I wonder if this could be related to the use of connection pools:

```rust
    #[tracing::instrument(name = "PG OPEN")]
    pub async fn open(conn: PgCon) -> Result<Self, Error> {
        //dbg!(&conn);

        let conn2 = conn.clone();
        let mut cfg = Config::new();
        cfg.dbname = Some(conn.db);
        cfg.user = Some(conn.user);
        cfg.host = Some(conn.host);
        cfg.password = conn.pwd;
        cfg.port = Some(conn.port);
        cfg.application_name = conn.app;

        cfg.manager = Some(ManagerConfig {
            recycling_method: RecyclingMethod::Fast,
        });

        let pool = cfg.create_pool(Some(Runtime::Tokio1), NoTls)?;

        Ok(Self { pool, conn: conn2 })
    }
```

So:

How to be certain the schema scoping is valid in each request?

**Comment by sfackler** [comment]
None of the types in that code are defined by this library. If you have a question about a connection pool, you should probably ask that on the repository for that library.

**Comment by mamcx** [comment]
Yeah, sorry. I update the sample.

**Comment by mamcx** [comment]
Ok, I post this in [deadpool](https://github.com/bikeshedder/deadpool/issues/204), thanks.

**Comment by bikeshedder** [comment]
I wonder if this could be caused by the way `tokio-postgres` implements pipelining. The only way I can imagine this happening is a connection still executing queries while it's being reused by another worker. I tried coming up with an explanation here:

- bikeshedder/deadpool#204
