### ISSUE TITLE
Error "current transaction is aborted, commands ignored until end of transaction block", or: equivalent to AutoCommit in web request 

### ISSUE THREAD

**Issue by mamcx** [sfackler/rust-postgres#897]
I'm getting `current transaction is aborted, commands ignored until end of transaction block`. I know what is this, but I always wrap all my transactions:

```rust
{
    db.begin_tran().await?;
    let doit = || async {
        {
            ...
            ...
        }
    };
    let result = doit().await;
    match result {
        Ok(ok) => {
            db.commit_tran().await?;
            Ok(ok)
        }
        Err(e) => {
            db.rollback_tran().await?;
            Err(e)
        }
    }
```

This run in a webserver with Actix. Is the same codebase ported to async and is the first time I get this kind of issue.

So I don't understand how I can have an unfinished transaction that is alive in the next request.

Also: Is possible to have the equivalent of AutoCommit?

**Comment by sfackler** [comment]
`begin_tran`, `commit_tran`, and `rollback_tran` are not methods defined by tokio-postgres. What is the actual code you're running?

**Comment by mamcx** [comment]
Yeah, sorry. I update the sample.
