### ISSUE TITLE
Error - Kind: Closed, Cause: None

### ISSUE THREAD

**Issue by Ep0chalypse** [sfackler/rust-postgres#905]
Hi, I'm using the postgres crate in a simple project and seemingly randomly the application will crash when attempting a sql insert. The error is not very helpful and I have no idea what is causing it.

The error is:
`Error { kind: Closed, cause: None }`

My enviroment is:
- postgres crate: 0.19.3
- rustc:                1.61.0
- os:                    Raspbian 11 armv6l

I'm connecting to postgres like:
```
Client::configure()
            .host(host.as_str())
            .user(user.as_str())
            .password(pass.as_str())
            .dbname(dbname.as_str())
            .connect(NoTls)
```

And I'm inserting with the following code:
```
client.execute(
            "
                INSERT INTO temperatures (recorded_at, temp_c, temp_f, humidity) 
                VALUES ($1, $2, $3, $4)",
            &[
                &reading.recorded_at,
                &reading.temp_c,
                &reading.temp_f,
                &reading.humidity,
            ],
        )
```

**Comment by sfackler** [comment]
The Postgres server is closing the connection to the client.

**Comment by Ep0chalypse** [comment]
> The Postgres server is closing the connection to the client.

Thanks for the quick reply.

I'm new to rust and I'm unsure of the proper way to catch this error and attempt a reconnect. Making matters worse is that this error seemingly happens randomly... sometimes after a week or 2 running so I can't write some code and test it to see if it fixed the issue.

Is the [is_closed()](https://docs.rs/postgres/0.19.3/postgres/error/struct.Error.html#method.is_closed) function intended to handle this error? Would code like this be ideal? Or is there a better approach?
```
 match client.execute(sql, params) {
            Ok(rows) => {...}
            Err(e) => {
                  if e.is_closed() {
                    client = Client::configure()
                                 .host(host.as_str())
                                 .user(user.as_str())
                                 .password(pass.as_str())
                                 .dbname(dbname.as_str())
                                  .connect(NoTls)
                }
           }

```

**Comment by sfackler** [comment]
I would recommend using a connection pool to handle reconnection for you. https://github.com/sfackler/r2d2-postgres is one example.

**Comment by Ep0chalypse** [comment]
Ok, I was trying to keep this project as minimal as possible and debated on a connection pool but it seemed overkill for this project. I'll have to reconsider it.

**Comment by Ep0chalypse** [comment]
I'll likely end up using https://github.com/sfackler/r2d2-postgres. If I don't and come up with a suitable sollution I'll post the code I end up using here. For now consider this closed.

Thanks!
