### ISSUE TITLE
time: 0.3.10 now requires Rust 1.57

### ISSUE THREAD

**Issue by elpiel** [sfackler/rust-postgres#909]
It seems that the new bump in minor version of time to 0.3.10 has moved to edition = 2021 and introduced a MRVS of 1.57:

https://github.com/time-rs/time/blob/v0.3.10/Cargo.toml#L10

Here's a failing action for a PR that showing this problem:

https://github.com/sfackler/rust-postgres/runs/6983516543?check_suite_focus=true

**Comment by sfackler** [comment]
Should be fine to just bump the version in CI to 1.57 in #908.

**Comment by elpiel** [comment]
Perfect, I'll do.
