### ISSUE TITLE
tokio-postgres not recognizing uuid param in WHERE clause

### ISSUE THREAD

**Issue by ghost** [sfackler/rust-postgres#914]
Hi, I am using a UUID id field in the WHERE clause of a left join query.

However tokio-postgres does not recognize the field I think due to it's type being a Uuid. How can I provide the type of the parameter to the query. I'm not sure how to use prepare_typed.

let stmt = "SELECT u.id, u.username, u.profile_photo
                   FROM users u
                   LEFT OUTER JOIN favorites f
                   ON u.id = f.favorite_user_id
                   WHERE f.user_id = $1
                   ORDER BY u.username ASC";
  let result: &Vec<Row> = &client
    .query(stmt, &[&member_user_id])
    .await
    .unwrap();

let favorites: Vec<Favorites> = result
    .into_iter()
    .map(|row: &Row| Favorites::from(row))
    .collect();

Ok(HttpResponse::Ok().json(favorites))

**Comment by sfackler** [comment]
What does "does not recognize the field" mean? What error are you seeing?

**Comment by sfackler** [comment]
There should not be any difference in using a UUID parameter versus an integer parameter.

**Comment by sfackler** [comment]
That doesn't contain the table structure, or the set of data that's present in the database.
