### ISSUE TITLE
Buffered `tokio_postgres::RowStream` 

### ISSUE THREAD

**Issue by BratSinot** [sfackler/rust-postgres#916]
Greetings!

Any way to use `tokio_postgres::RowStream` with https://docs.rs/futures-util/latest/futures_util/stream/trait.StreamExt.html#method.buffered?

**Comment by sfackler** [comment]
Yes, `RowStream` implements `Stream`.

**Comment by BratSinot** [comment]
> https://docs.rs/futures-util/latest/futures_util/stream/trait.StreamExt.html#method.buffered

Yeah, but `Item = Result<Row, Error`, and `buffered` want `Future`.

**Comment by sfackler** [comment]
Right, so you can't call buffered directly on a RowStream. What is the thing you're trying to do?
