### ISSUE TITLE
Are there plans to support `in` query with a collection argument

### ISSUE THREAD

**Issue by Valve** [sfackler/rust-postgres#92]
To be able to do something like:
```rust
 let stmt = pg_conn.prepare("select * from people where id in $1").unwrap();
  for row in stmt.query(people_ids).unwrap() {
  }
```

**Comment by johto** [comment]
Just do `SELECT * FROM people WHERE id = ANY($1)` and pass in an array.  That's what IN() does behind the scenes anyway.

**Comment by Valve** [comment]
passing an array gives me:
`
error: the trait `postgres::types::ToSql` is not implemented for the type `&[i32]`
`

**Comment by johto** [comment]
Sorry, I meant "do whatever is necessary to get your driver to pass an array in as the parameter".  I'm not sure how to do that in rust-postgres, though, sorry.

**Comment by zr40** [comment]
I don't have a rustc nearby, but I suspect you want to do something like:
```rust
for row in stmt.query(&[people_ids]).unwrap() {
```
(give or take some `&`s)

**Comment by sfackler** [comment]
If we were going to support `ToSql` implementations for `&[T]` for this use case, I think it'd need to be a blanket implementation for all `T: ToSql`. I believe this would currently conflict with the `ToSql` implementation for `&[u8]` which maps to `bytea`. If Rust gains some form of implementation specialization we can make this work.

**Comment by Valve** [comment]
Thanks, very handy
