### ISSUE TITLE
Possible buffer corruption in `tokio_postgres::Client`?

### ISSUE THREAD

**Issue by trungda** [sfackler/rust-postgres#920]
Hi, 
Thanks for the great crate, we have been using this crate and other wrappers (e.g., deadpool) in production for a while now. I'll try my best to explain what I am seeing. This is a very strange behavior and I've spent days debugging. 

Below roughly is a simplified version of our code in production.

```
use serde_json::Value;
use tokio_postgres::Client;

async fn foo() -> Result<(), Error> {
    let client = Rc::new(connect_to_a_db(config, database).await?); // connect_to_a_db returns a `tokio_postgres::Client`.

    let table = "table_foo";
    let (l1, l2) = create_records();
    future::try_join(
        handle_l1(table, l1, client.clone()),
        handle_l2(table, l2, client),
    )
    .await?;
}

async handle_l1(table: &str, l1: Vec<Value>, client: Rc<Client>) {
    // Build query and params from `Value`;
    let query = ...;
    let params = ...;
    client
        .execute_raw(query.as_str(), params.iter())
        .await
        .map(|_| ())
}

async handle_l2(table: &str, l2: Vec<Value>, client: Rc<Client>) {
    // Build query and params from `Value`;
    let query = ...;
    let params = ...;
    client
        .execute_raw(query.as_str(), params.iter())
        .await
        .map(|_| ())
}
```

If we just have either `handle_l1` or `handle_l2` in the `future::try_join`, everything works as expected. However, when joining two futures together, we are seeing malformed queried being sent to the database. The debug log printed out inside `query::execute` looks perfectly fine but somehow, the parameters seen by the database are corrupted. 
I know this is still kind of vague and it's not really a repro but maybe you could help us look at the way we use `Client` and confirm if it's safe to use a `Rc<Client>` in a `futures::try_join` like what we are using here. Thanks.

**Comment by sfackler** [comment]
How are the parameters being corrupted? Is it sending the wrong length, the wrong values, etc.

At least from what you've shown there it seems like it should work fine.

**Comment by trungda** [comment]
The symptom is that the parameters in handle_l2 are populated with values from handle_l1. The issue went away if we instantiated 2 clients for handle_l1 and handle_l2. But when we share one client instance (gated by Rc), the issue seems to happen. 
Note that this is a hot codepath.

**Comment by trungda** [comment]
Yes. I can imagine this is hard to repro. Specifically, in our code, we use `UPSERT` and `DELETE` in `query1` and `query2`. I'll try to repro and report back.

**Comment by sfackler** [comment]
If the problem is in this library, the queries used shouldn't matter - the client just treats them as arbitrary strings.

**Comment by trungda** [comment]
It's quite hard to repro locally actually. Our code executes this path in multiple threads and within each thread, the code is in has a high hit rate too. I will keep trying.

**Comment by trungda** [comment]
Hi @sfackler , I have run your script in my environment and watched the running statements while running the script.
Below is my script
```
use futures::future;
use tokio_postgres::{Error, NoTls};

#[tokio::main] // By default, tokio_postgres uses the tokio crate as its runtime.
async fn main() -> Result<(), Error> {
    // Connect to the database.
    let (client, connection) =
        tokio_postgres::connect("postgresql://root@localhost:26257", NoTls).await?;

    tokio::spawn(async move {
        if let Err(e) = connection.await {
            eprintln!("connection error: {}", e);
        }
    });

    // let row = client
    //     .query("SELECT status FROM crdb_internal.jobs LIMIT 1;", &[])
    //     .await?;
    // let row1 = row[0].try_get::<&str, Option<String>>("status")?;
    // println!("{:?}", row1);

    client
        .batch_execute(
            "
    CREATE TABLE IF NOT EXISTS t (
        id INT,
        name TEXT
    );

    INSERT INTO t (id, name) VALUES (3, 'joe'), (4, 'bob');
    ",
        )
        .await
        .unwrap();

    for i in 0u64.. {
        let query1 = async {
            let row = client
                .query_one("SELECT name FROM t WHERE id = $1 LIMIT 1", &[&3i64])
                .await
                .unwrap();

            assert_eq!(row.get::<_, String>(0), "joe");
        };

        let query2 = async {
            let row = client
                .query_one("SELECT name FROM t WHERE $1 AND id = $2 LIMIT 1", &[&true, &4i64])
                .await
                .unwrap();

            assert_eq!(row.get::<_, String>(0), "bob");
        };

        future::join(query1, query2).await;

        if i % 1000 == 0 {
            println!("completed run {i}");
        }
    }

    Ok(())
}
```

And below is a screenshot that captures me running `select query from [show statements];`. 
<img width="706" alt="Screen Shot 2022-07-14 at 11 34 06 PM" src="https://user-images.githubusercontent.com/2529107/179165694-f24d1f10-28b6-4167-bd6c-70a9ebfba21d.png">

As you can see from the screenshot that `SELECT name FROM t WHERE 3 AND (id = $2) LIMIT 1` is definitely not populated properly. It should have always been 
`SELECT name FROM t WHERE true AND (id = 4) LIMIT 1;`

Am I missing something?

**Comment by sfackler** [comment]
But does the assertion on what row is returned fail?

**Comment by trungda** [comment]
So that's another piece of magic. I think the malformed queries are not sent by the application code. Something else constructs and executes the wrong queries. I might be crazy.

**Comment by sfackler** [comment]
Or alternatively the bug is on in whatever implements the `[show statements]` logic.

**Comment by trungda** [comment]
Yeah that could be another mystery. However, when I switch to using 2 different clients, one for the first query and one for the second query, such malformed queries are not observed anymore. 
An example of that:
<img width="693" alt="Screen Shot 2022-07-15 at 9 14 22 AM" src="https://user-images.githubusercontent.com/2529107/179264309-a3e74b69-4d37-404e-b907-9495ca6103aa.png">

**Comment by trungda** [comment]
I see. Let me look into it.

**Comment by georgeli-roblox** [comment]
We can also turn on  slow query log to log the statements being executed.  if we think [show statements] has issues. Also it seems the problem select is using bind variable `id = $2`  instead of `id = <some value>`?   if we have a list of IDs,  `id in (.....)`,  it seems to show some arbitrary column values from the other concurrent upsert rows.
