### ISSUE TITLE
Joining UPSERTs with query_one and owned parameters

### ISSUE THREAD

**Issue by elpiel** [sfackler/rust-postgres#927]
Hello,
I'm doing multiple UPSERT queries with RETURNING statement that I want to join in single future. This can be achieve only with `query_raw` since `query_one` takes a `&[...]` and the parameters don't live long enough, while we can use:
`vec![Box::new(param1) as Box<dyn ToSql + Sync + Send>,]` with `query_raw`.

However, this has some drawbacks, mainly I have to manually:

- handle `RowStream` the same way `query_one` does
- create own error and duplicate the `Error::RowCount` error and wrap the `tokio_postgres::Error`

A solution to fix this would need to either:
- Add additional methods (or a trait maybe) for `IntoIterator` parameters of `query_one` and `query_opt`
- Change the API and introduce a breaking change - not really sure how to introduce this changed API though

While it's good that it takes reference to the parameters, this has caused me multiple problems in the past too.
It would be very beneficial, in my opinion, to have such an improvement for owned types as I still think it's a rough edge that needs some polishing.

What do you think about that?

**Comment by sfackler** [comment]
You can use an `async { ... }` block to close over the `query_one` and the parameters slice.

```rust
let future1 = async {
    let params = vec![...];
    client.query_one(query_string, &params).await
}
```

**Comment by elpiel** [comment]
I'm generating the futures from an iterator:

```
let spenders_futures = delta_balances
        .spenders
        .into_iter()
        .map(|(spender, amount)| async {
            let params = vec![
                Box::new(channel_id) as Box<dyn ToSql + Sync>,
                Box::new(Side::Spender),
                Box::new(spender),
                Box::new(amount),
                Box::new(updated),
                Box::new(now),
            ];

            client
                .query_one(
                    &statement,
                    params.as_slice(),
                )
        });
```

This still causes issues:

```
mismatched types
expected reference `&[&dyn ToSql + Sync]`
   found reference `&[Box<dyn ToSql + Sync>]
```

**Comment by sfackler** [comment]
You shouldn't need the vec: 

```rust
async {
    client.query_one(
        &statement,
        &[
            &channel_id,
            &Side::Spender,
            // ...
        ]
    ).await
}
```

**Comment by elpiel** [comment]
It's still causing problems and it suggests to use `async move` (because of the borrowed `&statement` and other borrowed values) but when I use it, then `Client` is also borrowed and it can't be cloned.

**Comment by sfackler** [comment]
Ah yeah you sometimes need to use `async move` and manually take references as necessary. That looks like what I'd do though.

**Comment by elpiel** [comment]
Ok, thanks for the help, as always :yum:
