### ISSUE TITLE
Support SQL name parameters, same as pg-promise

### ISSUE THREAD

**Issue by nyurik** [sfackler/rust-postgres#929]
The massively popular [pg-promise](https://www.npmjs.com/package/pg-promise) JavaScript library has a feature that I believe makes querying somewhat safer and more convenient - ability to [parameterize SQL names](https://github.com/vitaly-t/pg-promise#sql-names).

`pg-promise` uses `$1:name` to indicate that the parameter should be escaped and inlined before it reaches the server.  It also has a shortcut syntax `$1~`.  Examples from the docs. 

```js
await db.query('INSERT INTO $1~($2~) VALUES(...)', ['Table Name', 'Column Name']);
//=> INSERT INTO "Table Name"("Column Name") VALUES(...)
await db.query('INSERT INTO $1:name($2:name) VALUES(...)', ['Table Name', 'Column Name']);
//=> INSERT INTO "Table Name"("Column Name") VALUES(...)
await db.query('SELECT $1:name FROM $2:name', ['*', 'table']);
//=> SELECT * FROM "table"
await db.query('SELECT ${columns:name} FROM ${table:name}', {
    columns: ['column1', 'column2'],
    table: 'table'
});
//=> SELECT "column1","column2" FROM "table"
```

Could we have a similar functionality in `rust-postgres`?  There are many cases when the SQL table or a function name is given as a user-supplied parameter, and the current implementers must remember to properly escape it, i.e.

```rust
let escaped_schema = escape_identifier(&schema);
let escaped_function = escape_identifier(&function);
let raw_query = format!("SELECT {escaped_schema}.{escaped_function}(...);");
```

I am not certain that `rust-postgres` should handle edge cases like `*`. Note that pg-promise also has `:alias` that would simplify the above example -- having a dot in a single parameter could convert `public.myfunc` to `"public"."myfunc"`.

### See also
* #925

**Comment by sfackler** [comment]
I don't feel that this library should perform any client-side processing of the query string.

**Comment by nyurik** [comment]
@sfackler this is a fair point, yet this is a very common use case judging by the fact that another popular lib has implemented it, and there are stackoverflow questions like [1](https://stackoverflow.com/questions/57539838/rust-postgres-execute-how-to-pass-table-name-as-a-variable).  Do you think it makes sense for all such use cases to implement it by hand, or perhaps another crate?
