### ISSUE TITLE
Row mapping support

### ISSUE THREAD

**Issue by exe-dealer** [sfackler/rust-postgres#93]
It would be nice to implement [::serialize::Decoder](http://doc.rust-lang.org/nightly/serialize/trait.Decoder.html) for e.g. RowDecoder and make possible to map row to struct

```rust

#[derive(Decodable)]
struct Person {
    id: i32,
    name: String,
    time_created: Timespec,
    data: Option<Vec<u8>>
}

let persons: Vec<Person> = conn.query("SELECT id, name, time_created, data FROM person").unwrap();

```

**Comment by sfackler** [comment]
I unfortunately don't think the Decodable API is compatible with the way the Row API works. A separate trait with a syntax extension to derive it would be pretty straightforward, though it seems like something that would make sense as as separate project than the driver itself.

**Comment by exe-dealer** [comment]
Decodable API is compatible enough to decode vector of strings https://github.com/exe-dealer/pgblackboard/blob/fda7f4b551e4e541b566932081c2e6e1063469f2/src/postgres/decoder.rs

Implementation of Decoder over bare Stream can eliminate unnecessary per cell memory allocations for int-like values. (Though I guess it can ruin pretty message abstractions). Since stream is accessable only on driver level it is impossible to implement memory efficent decoder in separate project. I still think decodable rows are appropriate in driver, and if driver user wants generic row it can decode it to existing Row struct.

**Comment by sfackler** [comment]
I wouldn't be opposed to a PR with a reasonable Decoder implementation.
