### ISSUE TITLE
retrieving postgres `date` type without chrono

### ISSUE THREAD

**Issue by djanatyn** [sfackler/rust-postgres#947]
Today while pair-programming, we had a postgres database with a `date` column. We were trying to use [`postgres::row::Row#get`](https://docs.rs/postgres/0.19.4/postgres/row/struct.Row.html#method.get) with `postgres::types::Date`:
```rust
/// A wrapper that can be used to represent infinity with `Type::Date` types.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Date<T> {
    /// Represents `infinity`, a date that is later than all other dates.
    PosInfinity,
    /// Represents `-infinity`, a date that is earlier than all other dates.
    NegInfinity,
    /// The wrapped date.
    Value(T),
}
```

At first we were confused by what `T` should be, and tried `i32`:
```rust
let a: postgres::types::Date<i32> = row.get("date");
```

That didn't end up working (sorry, don't have the error message), so we switched to using the `with-chrono-0_4` feature, and returned `chrono::NaiveDate` instead:
```rust
let date: chrono::NaiveDate = row.get("date");
```

I was wondering:
* Is it possible to use `postgres::types::Date` with the postgres `date` type in this context? I couldn't find any examples of usage, or any associated tests.
* If you can use `postgres::types::Date`, what is the meaning of the `<T>` parameter? For a regular postgres `date` column, what should `T` be?

Thank you for your time!

**Comment by sfackler** [comment]
`postgres::types::Date<chrono::NaiveDate>`.

The date enum handles the infinity values that Postgres supports but Rust date types typically do not. If you aren't using infinite date values in your database you should just use `chrono::NaiveDate` directly.

**Comment by djanatyn** [comment]
Thank you, that explains it!
