### ISSUE TITLE
Ask: What happened when queried value are null?

### ISSUE THREAD

**Issue by kokizzu** [sfackler/rust-postgres#96]
For example in your example:
```
let stmt = try!(conn.prepare("SELECT bar, baz FROM foo"));
for row in try!(stmt.query(&[])) {
    let bar: i32 = row.get(0);
    let baz: String = row.get("baz");
    println!("bar: {}, baz: {}", bar, baz);
}
```
What will be happened when `bar` or `baz` is `NULL` value?

**Comment by sfackler** [comment]
In the case of that example, `get` will panic. For values that are expected to be possibly `NULL`, you would want to retrieve `Option` types, which will map `NULL` to `None:
```rust
let bar: Option<i32> = row.get(0);
```
There's also a `try_get` method in addition to `get`, which returns a `Result`. In the case that the value was `NULL` and the output type isn't an `Option`, it will return an `Error::WasNull` error.

**Comment by viper6277** [comment]
Hey, Rust Newbie here.... Having exactly this problem.... and the docs : 

https://docs.rs/postgres/0.17.0/postgres/binary_copy/struct.BinaryCopyOutRow.html#method.try_get

do little to help me understand...

would be great if we could have a nice example of this method...something like....

```rust
for row in &db_conn.query("
       SELECT company.id,
                     company.name,
                     company.spending
         FROM company
        LIMIT 100;", &[]).unwrap() {
                
        let cd = CompanyDetail {
            id: row.get(0),
            name: row.get(1),
            spending: row.try_get(2)   // Naturally this does not work
        };
        println!("Company {} Spending", CompanyDetail.name, CompanyDetail.spending);
    }

```

Thanks guys...

**Comment by viper6277** [comment]
So after doing more research, reading...and grappling with Rust compile time errors .... which I have taken the stance that it really is trying to help me... I ended up working out a solution to my problem...here is the update... 

```Rust
for row in &db_conn.query("
       SELECT company.id,
                     company.name,
                     company.spending
         FROM company
        LIMIT 100;", &[]).unwrap() {

   //
   let spending_field:Result<i32, postgres::Error> = row.try_get(2);

   let mut struct_field:i32;
   
   match &spending_field {
      Ok(v) => struct_field = *v,
      Err(e) => struct_field = 0
    }
                
     let cd = CompanyDetail {
            id: row.get(0),
            name: row.get(1),
            spending: struct_field 
        };
     println!("Company {} Spending", CompanyDetail.name, CompanyDetail.spending);

    }
```
Not sure if it's the most optimal solution... but for now it solved my problem... if anyone has a better way ...please post up your thoughts...

thanks again... 

Eddie
