### ISSUE TITLE
non-C-like enums are not supported for enum postgres derive

### ISSUE THREAD

**Issue by spartucus** [sfackler/rust-postgres#964]
Env:
* rustc 1.65.0 (897e37553 2022-11-02)
* postgres: 0.19.4
* postgres-types: 0.2.4
* postgres-ssl: 0.5.0

I defined such enum:
```rust=
#[derive(FromSql, ToSql)]
pub enum Foo {
    Bar,
    Bzz(i8),
    Qzz(i8),
}
```

It prints error log:
```
error: non-C-like enums are not supported
  --> hi/src/main.rs:17:5
   |
17 |     Bzz(i8),
   |     ^^^^^^^^^^^^^^

```

**Comment by sfackler** [comment]
What Postgres type would they correspond to?

**Comment by spartucus** [comment]
I'm a bit confused about that too, i don't know how to convert these enum types into SQL types. Any suggestions?

**Comment by sfackler** [comment]
I don't believe there is a Postgres type that would correspond to them, which is why the derive doesn't support them.

**Comment by spartucus** [comment]
Yes, agree.
