### ISSUE TITLE
Vec<String> to UuidArray unwrapping advice

### ISSUE THREAD

**Issue by SquireOfSoftware** [sfackler/rust-postgres#974]
I am having this error pop up on me and I am confident that I am doing something wrong:

```
'called `Result::unwrap()` on an `Err` value: Error { kind: ToSql(0), cause: Some(WrongType { postgres: UuidArray, rust: "alloc::vec::Vec<alloc::string::String>" }) }',
```

So my postgres table looks like this:

```
CREATE TABLE IF NOT EXISTS orders (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    ...
)
```

And my rust function looks like this:

```
pub async fn get_orders_from(ids: Vec<String>, db: &Object) -> Result<Vec<Order>, Error> {
    let raw_result = db.query("select * from orders where id = any ($1)", &[&ids])
        .await;

    dbg!(&raw_result); // added this in to help debug the problem

    let result = raw_result.unwrap();
```

Toml dependencies are:

```
tokio-postgres = {version = "0.7.7", features=["with-uuid-1", "with-chrono-0_4"]}
uuid = "1.2.2"
```

My question is this: when working with `uuid` fields on postgres, do I need to convert the parameters that I am feeding into the `tokio_postgres` crate into the appropriate types on the database? as I am assuming that this is where the error is firing off.

EDIT: I forgot to mention that I did stumble on to this post here: https://github.com/sfackler/rust-postgres/issues/407, however I wasn't sure if the error that I was receiving were referring to the data extraction step or at the data querying step. And as such I assumed that this issue was referring to data extraction rather than data querying.

**Comment by sfackler** [comment]
Yes, you need to use `Vec<Uuid>`, not `Vec<String>`.

**Comment by SquireOfSoftware** [comment]
Awesome, thanks @sfackler, also happy new year!

FYI, for future people, my hacky solution is:

```
pub async fn get_orders_from(ids: Vec<String>, db: &Object) -> Result<Vec<Order>, Error> {
    let uuid_list: Vec<Uuid> = ids.iter()
        .map(|id| Uuid::from_str(id).unwrap())
        .collect();

    let raw_result = db.query("select * from orders where id = any ($1)", &[&&uuid_list[..]])
        .await;

    dbg!(&raw_result); // added this in to help debug the problem

    let result = raw_result.unwrap();
```

Pretty sure I am making a lot of rust developers and my future-self cry, but it works for now with my working knowledge of rust.
