### ISSUE TITLE
Should this not throw errors if I am trying to insert and it's not actually inserting?

### ISSUE THREAD

**Issue by JohnAllen** [sfackler/rust-postgres#992]
This is just a high level question so I can better understand how this works. Basically I have some code that is not throwing any errors that is supposed to be inserting rows into Postgres. Yet it isn't, or if it is I can't find them. I would have guessed that this should throw some error somewhere or do something if it is not working, but I could be wrong.

**Comment by sfackler** [comment]
It depends on what you mean specifically by throwing in this context. The library will not panic on errors but instead return a `Result::Err` from the method. Without seeing your code I can't say for sure, but I could see a couple of possibilities as to what's going on:

1. The insert is failing (IO error, invalid SQL syntax, etc) but the calling method isn't handling the `Result` returned from `client.execute`.
2. The insert query is successfully executed but inserts 0 rows. On success, `client.execute` will return the number of rows inserted as reported by the database that you can check.
3. The rows are successfully inserted but not made visible to the later queries that try to read them (they're in an uncommitted transaction, etc).
