### ISSUE TITLE
Consider expose `Bytes` type trhough postgres-protocol?

### ISSUE THREAD

**Issue by fakeshadow** [sfackler/rust-postgres#996]
For type like [DataRowBody](https://github.com/sfackler/rust-postgres/blob/4bae134f501db5c08b8dd43a44474e515bbb39d3/postgres-protocol/src/message/backend.rs#L528) that is backed by Bytes internally it would be beneficial to expose it directly for zero copy downcasting/slicing without concerning of explicit reference and lifetime.

For example:
```rust
pub struct DataRowBody {
    storage: Bytes,
}

impl DataRowBody {
    fn storage(&self) -> &(impl AsRef<[u8]> + Clone) {
        &self.storage
    }
}

// slice bytes with cheap clone
fn slice(row: DataRowBody) -> Bytes {
    let bytes = (row.storage() as &dyn Any).downcast_ref::<Bytes>().unwrap();
    bytes.slice(1..5)
}

// cheap clone to onwership.
fn cheap_clone(row: DataRowBody) -> impl AsRef<[u8]> + 'static {
    row.storage().clone()
}

```

**Comment by sfackler** [comment]
Seems reasonable, but I think the simpler option would be to just add a `pub fn storage_bytes(&self) -> &Bytes` method.
