### ISSUE TITLE
Recommended connection pool for tokio-postgres

### ISSUE THREAD

**Issue by pascaldanek** [sfackler/rust-postgres#997]
Do you recommend any specific connection pool to be used with tokio postgres ?

**Comment by sfackler** [comment]
I don't have any strong opinions there. I believe deadpool is one example but can't vouch for it one way or the other.

**Comment by Snamnik** [comment]
I'm also looking for a connection pool to be used with tokio postgres. Is deadpool the best option or is ther any other options?
