### ISSUE TITLE
Should query panic when the number of parameters doesn't match?

### ISSUE THREAD

**Issue by SvizelPritula** [sfackler/rust-postgres#998]
The `query` method and its siblings will panic when the number of parameters in the statement doesn't match the number of parameters passed into the method. This seems like a very strange design decission. The method already returns a generic opaque error type, so it should be simple to add a variant to it for this type of error. It's also inconsistent, since a completely malformed query will just return a "soft" error. It a valid query with an incorrent number of parameters worse that a completely invalid query? Furthermore, panics are usually reserved for programmer errors. Since the query gets parsed by the server, a misbehaving server could crash client code.

**Comment by sfackler** [comment]
Are you connecting to misbehaving servers? If you are particularly concerned about that you can always check the number of parameters in the prepared statement before executing it. I don't feel particularly strongly about this case panicking vs returning an error though.

**Comment by SvizelPritula** [comment]
That's true, but `Row::get` actually brings convenience, since it returns `T` instead of `Result<T>`. It also has an alternative for handling errors. The `query` methods and likes already return a `Result`, so panicking brings no convenience. The `Error` type is also opaque, so it wouldn't force users to handle new error types. It seems weird that of all the ways a server could misbehave, such as sending wrong types messages, sending malformed messages or failing to parse valid queries, just one results in a panic instead of an Error. Sure, it's an uncommon error, and anyone who wants that extra robustness can use `prepare` and manually check the parameter count of the returned statement, but I think that's something this library can easily do for free.

I'd be happy to submit a PR if desired. I'm just slightly unsure whether this change would be considered breaking by SemVer's rules, although I can't think of any program it could break.

**Comment by sfackler** [comment]
Sure, I'd take a PR making the change.

**Comment by fakeshadow** [comment]
not strongly related but this was the main source of panic when holding the client's buffer lock. with it gone could it be acceptable to make `parking_lot` an optional dep and default to std's mutex as there is no other obvious cases of triggering poison.
